- Wire-iOS Tests/GroupDetailsParticipantCellTests.swift
- Wire-iOS Tests/Mocks/MockUser.h
- Wire-iOS Tests/Mocks/MockUser.m
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsParticipantCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ServicesSectionController.swift
When team user is added to non-team group he would see all participants as guests.
Guest icon logic was not taking the conversation into account.
Use the `isGuest(_ in: ZMConversation)` function to determine if a group participant is a guest.
> Fix guest icon being shown for users in non-team group

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Developer/DebugAlert.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift
Users without Mail.app installed cannot send logs.
I've added the possibility to send logs to us by using `UIActivityViewController`. Since this action is detached from sending emails, I've added an alert to remind the user to send the email after completing actions with the activity controller.
> ZIOS-9292: Allow users to share logs via UIActivityViewController if unable to send mails

- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/RenameGroupSectionController.swift
* Disable renaming conversation and hide icon for past members.
> Disable renaming conversation and hide icon for past members

- Wire-iOS/Sources/Developer/DeveloperOptionsController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift
All navigation titles in Settings view controllers are now uppercase. The only leftover is the default Edit/Done button in Devices list provided by `UITableView`.
> All titles in settings navigation controllers are now uppercase

- avs-versions
Please update to latest AVS 4.2. branch. No API changes. All initial tests are positive. Release notes are here: https://github.com/wearezeta/avs/blob/release-4.2/ChangeLog.txt
> Bump AVS to 4.2.

- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
After connecting to a user on the user details screen the participants list wouldn't reflect the updated connection state.
We weren't observing connection state changes in the participants list.
Observe connection state changes and reload the list of participants in case it changes.
> Reload the participant list when the connection state changes

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- In the dark mode the status bar was dark.
> Group details: Use the correct status bar style

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
* Check if user is guest in conversation instead of whether she has a team.
> Only show guest options if user is not guest in team

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileTitleView.swift
NavigationBar title is not animating correctly when transitioning to the profile details screen.
On iOS 10 and earlier the navigation bar title view doesn't handle auto layout views.
Size view manually on iOS 10 and earlier
> Fix navigation bar layout during the transistion on iOS 10.x

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Guest option was shown to non-team users
We were only checking that the user is not guest in the conversation.
We also need to check that the user is in team.
> Only show guest option for team users

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Client crashes if:
1. User A is a team user.
2. User A is added by non-team user to the group conversation.
3. User A tries to change the guest only settings.
If the conversation is not created in team it's not possible to set the team-only flag.
Hide the options section in this case.
> Do not show the options in non-team conversation

- Wire-iOS Tests/GroupDetailsParticipantCellTests.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsParticipantCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/SectionCollectionViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ServicesSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Contacts/ContactsSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/SearchSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Suggestions/DirectorySectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
The new unified user cell had some layout issues:
- When opening the search UI and scrolling down the list the first cell which becomes visible would appear with a broken animation.
- The cell which appear with an broken animation would also show wrong icons all stacked on top each other.
The cell with a broken layout is created inside the an animation block when we resize the view as a response to hiding the keyboard. This causes a newly created cell also to animate from its initial zero frame.
The falsely shown icons is also a side effect of creating the cell inside an animation and it has something do with how stack views handle hidden views.
A workaround for for animating cell is invoke another layout before it's displayed. The stack view bug can be workaround by initially hiding all …
> Layout fixes for unified user cell

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
Tap areas for the button in the conversation navigation bar is very small
The navigation bar had `IconButton` buttons which usually have a hit area which extends outside the size frame of the button itself. This doesn't work when put inside a navigation bar because they will be wrapped inside a container view.
Use regular `UIBarButtonItem` which by default get very good hit area.
I removed the call to `self.updateLeftNavigationBarItems ` in `viewWillLayoutSubviews` because it was introducing animation issues when the guest bar was updated. The call was added to make sure the iPad has the correct visible button when transitioning between size classes. I was testing this and it still worked fine since we also update the buttons  on `willTransition(to: UITraitCollection)` and …
> Increase tap areas in conversation navigation bar

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileTitleView.swift
Make automation identifiers more specific for the case when multiple screens are visible side by side.
> More specific automation identifiers

- Wire-iOS Tests/ConversationOptionsViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/Conversation+OptionsConfiguration.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewModel.swift
* Only try to fetch link when opening guest options for `.code` access modes. There was an issue for legacy conversations which have not yet been promoted to `[.invite, .code]` access modes, as we tried to fetch the conversation link when opening the guest options menu the users was shown an error.
> Only try to fetch link when opening guest options for .code access modes

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Analytics/CallQualityScoreProvider.swift
- Wire-iOS/Sources/Analytics/CallQualitySurveyReview.swift
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
This fixes several issues regarding analytics and automation for the call quality survey:
- Do not display during automation tests (ZIOS-9729)
- Fix a faulty check that prevented the survey to be displayed on external clients
- Send an analytics event for all cases, even when the user did not see/answer the survey
> Fix call quality survey analytics and automation

- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/TopPeopleLine/TopPeopleSectionController.swift
Top people section was not displayed in the search UI
Method call calculate the top people was missing
Add missing method call.
> Refresh top people when opening the search UI

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/Helpers/UIPasteboard+Compatibility.h
- Wire-iOS/Sources/Helpers/UIPasteboard+Compatibility.m
- Wire-iOS/Sources/UserInterface/Components/MediaAsset.h
- Wire-iOS/Sources/UserInterface/Components/MediaAsset.m
- WireExtensionComponents/Views/TextView.m
As reported here: https://github.com/wireapp/wire-ios/issues/1485, there are some cases where the images are not copied correctly from the clipboard.
The main cause is that the images copied from Universal Clipboard are not properly recognized as images: while debugging, `[self containsPasteboardTypes:UIPasteboardTypeListImage]` returns `false` while `self.hasImages` returns `true`. While copying images from other sources like the local clipboard. This method is available only from iOS 10.
Furthermore, calling `pasteboard.image` from `canPerformAction:withSender:` is causing the system to display immediately the "Pasting from <Device>" popup in case of pasting from Universal Clipboard (and it's useless since APIs provide the `hasImages` method).
I've implemented three new methods in the …
> ZIOS-9738: Cannot copy images from the clipboard

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- The new API should be triggering the check if the users are already expired from the backend.
> Notify sync engine about opening and closing the conversation

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/SimpleTextField.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
Group creation flow was partially displayed in dark mode 
Only the cells in the `add participants` - step supports dark mode
Make the entire group creation flow support dark mode.
> Support dark mode in the group creation flow

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter+ConversationImages.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
In the current implementation, previewing an image message with 3D Touch displays an image controller with the navigation bar and an action buttons row. These buttons could not be tapped and the user could not quickly interact with the image (like/share/... from the preview).
This PR introduces system preview action items on the image controller. This allows the user to swipe up when previewing and quickly interact with the image from there.
> [ZIOS-9417] Implement 3D Touch actions for image preview

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationEmailFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/EmailSignInViewController.m
UX for registration flow on iPad was affected by two problems, in the case of registration with already registered user credentials:
- server registration was performed after accepting ToS, so in the case of an already registered user,  ToS screen was unnecessarily shown
- after switching to the login screen, the arrow icon was hidden, forcing in this way the user to re-insert the password.
- I've moved the registration phase before accepting the terms of use (you need to accept them anyway in order to receive the activation email)
- I'm checking the accessory view of the password field in the login view in case of a `LoginCredentials` object with the `password` field filled.
This should solve both ZIOS-9722 and ZIOS-9744, since the alert about credentials is shown correctly.
> ZIOS-9722, ZIOS-9744: Improved registration flow on iPad

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsInvitePeopleView.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
* Don't show open conversation option for wireless users.
* Show device tab for wireless users.
* Fix participants cell invite section title font.
> Don't show open conversation option for wireless users

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
When using a small screen device (ex: iPhone 4s), the audio recording long press gesture was not recognized.
The long press gesture was not detected by the button the because on small screens it is located next to the expand row button, which has a longer padding. The expand button would intercept touches from the record button, even when the finger is visually above the record button.
This was fixed by reducing the padding around the expand button. Both buttons now have an equal hit size.
> ZIOS-9491: Fix audio record button reachability on small screens

- Wire-iOS/Sources/Analytics/Analytics.m
- Wire-iOS/Sources/Analytics/AnalyticsProviderFactory.swift
In theory we should be able to see the Mixpanel client ID in the console in order to verify actions on the client create events in Mixpanel. Right now this is not happening, we need some more logs to investigate it.
> Added more logs to investigate analytics mixpanel issue

- Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
Video playback is silent if the silence switcher is on.
We must tell AVS that we are about to play a video so that they can configure the audio session for playback. We do listening to "rate" notifications from the `AVPlayer`. This appears not to be working on iOS 11 anymore
Switch back to KVO observing of the playback rate and remove the kvo observer early to avoid crashes on iOS 10.
see: https://github.com/wireapp/wire-ios/pull/1529
> Fix observing of playback rate

- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.h
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/AlertResultConfiguration.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+Block.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+CancelRequest.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/UIAlertController+ConversationDegraded.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
* Present conversation degraded overlay as regular alert on iPad.
* Fix crash for action sheet shown for connections (the wrong method was called)
* Update `ConversationActionController` to work with iPad popovers.
* Fix action execution after selection on iPad (leave / archive etc.).
* Fix "show devices" view controller presentation after a conversation degraded (it was impossible to dismiss the presented devices list controller in some cases).
> Fix crash for action sheet shown for connections, update for iPad popovers

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
App crashes sometimes with calling cellForRow after scrollToRow is called.
UITableView.cellForRow returns nil if cell is not visible or index path is out of range. Delay for 0.1 sec does not promise that the cell is visible after scrolling without animation.
Unwrap cell before calling completion closure.
Call scrollToRow inside a UIView.animate's closure with duration = 0.0
Call completion closure in UIView.animate's completion closure, instead of hard code delay.
> ZIOS-9751 fix/crash when calling cellForRow

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationPreviewViewController.swift
When previewing a conversation in the list UI, the top of the 3D touch view cuts off the conversation.
This is fixed by removing unwanted constraint insets at the top of the conversation view.
> ZIOS-9650: Fix 3D Touch preview margins

- Wire-iOS Tests/MarkdownTextViewTests.swift
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
When the user would change the color theme of the app, the color of the text in the message text field would not change, and the text stayed invisible.
This regression was caused by the introduction of the markdown view. This view uses its own style object to create the attributed text, and Classy didn't update that object when the theme changed.
This PR introduces a method that correctly updates the color of the text field when needed.
> ZIOS-9775: Update the color of the input field when theme changes

- Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
Only show the survey in internal builds until the review has completed.
> Disable call survey in public builds

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCell/ParticipantsCellViewModel.swift
"Du hat..." is not correct in German, since the verb is conjugating for the subordinate. I would update the Crowdin after this one would be merged.
> Correct german grammar: you started the conversation

- Wire-iOS/Sources/AppStateController.swift
This PR replaces: https://github.com/wireapp/wire-ios/pull/1889
There was an issue where the app would transition to the landing page if the application did become inactive/active while being in the unauthenticated state.
The `authenticatedError` would get cleared on all state changes except when transitioning to the `unauthenticated(error: nil)`. 
The intent of: https://github.com/wireapp/wire-ios/blob/a2a4e34347d5a4da53e137f938790377c41dd1a9/Wire-iOS/Sources/AppStateController.swift#L94 was however to only clear the error when transitioning out of the `unauthenticated`. That behaviour changed when the `==` operator for the AppState started taking associated values into account.
Restore intended behaviour by comparing using a switch statement.
> Fix transition to landing page on during login

- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
When iPad changes from split mode to full screen mode, the conversation screen is incorrect, a black rectangle may be shown between conversation list and conversation screen.
The rightViewOffsetConstraint and leftViewOffsetConstraint's constant is not updated after rotation or size class update. Incorrect constraint value is applied.
Reset openPercentage after size change, which also update rightViewOffsetConstraint.constant.
> Fix: [iPad]Portrait split mode - conversation list view not dismiss after another app added to screen

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/UIApplication+Permissions.h
- Wire-iOS/Sources/Helpers/UIApplication+Permissions.m
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/SavableImage.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Helpers/UIAlertController+Wire.m
Permission/failure errors were not checked when saving images to the photo library from a conversation. The save animation would always run, even when the image was not actually saved to the library.
Before saving the image, we request permission if needed, and show an alert if saving the image fails. If permission was denied, we offer a button in the alert for the user to open the settings and change the authorization.
> ZIOS-4187: Show alert when permission is required to save image

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
Changed title of the first step in ConversationCreationController to "Group name". I duplicated the string because the title of the view and the placeholder of the textfield may not coincide in the future, since they're placed in two different controls.
> ZIOS-9758: Changed title of the first step in ConversationCreationController

- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
When user taps cancel of "unlock with touch ID" system dialog, then put the app into background, the next time the user switches back to Wire app, the "unlock with touch ID" system dialog does not appear without tapping the "Unlock" button.
The flag localAuthenticationCancelled is not reset to its initial value when the app goes to background.  It prevents calling requireLocalAuthenticationIfNeeded when the app becomes active.
set the flag localAuthenticationCancelled to false when the app goes to background.
> Show "unlock with touch ID" system dialog when user tapped cancel button, put the app to background, then open the app again

- Wire-iOS/Sources/UserInterface/Conversation/PlaceholderConversationViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Implemented `PlaceholderConversationViewController`, which was actually empty. It contains the grey placeholder of the new shield, displayed when there are no conversations to show.
> ZIOS-9782: Replace the empty conversation placeholder

- Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift
- Wire-iOS/Sources/Managers/MediaPlaybackManager.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
- WireExtensionComponents/Utilities/KeyValueObserver.m
When making an audio call as an audio message is playing, the app crashes.
This happens because the observer for `title` is removed twice.
The workaround that caused this issue was added because the observer was removed from inside the `deinit` of the object. As this causes the object to be removed from the `KeyValueObserver` before we can remove it, we needed to explicitly call `removeObserver`.
We fix this by tearing down the observer outside of `deinit`.
> ZIOS-9797: Fix audio player crash when making an outgoing call

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
- The case when user is not connected was not handled.
- No tests affected.
> Profile: do not show shield for unconnected users

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Restore title of first screen in group creation flow per design feedback
> Restore “Create group” title for ZIOS-9758

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/PlaceholderConversationView.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Placeholder view on iPad was not visible in certain orientations, because it was considered as the right view controller. Furthermore, it was keeping the same size of a normal conversation view, allowing the user to swipe and close the sidebar with the placeholder view on the right.
Replaced the `rightView` property with a custom `PlaceholderConversationView` and fixed the display logic.
> ZIOS-9782: Fixed placeholder view behavior on iPad

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
AVS was noticing that they were sometimes failing to change audio category after an audio recording.
Were were notifying AVS too early that we've stopped recording which caused any update to the audio category to fail
Notify AVS when the `AVAudioRecorder` delegate tells us that it has stopped.
> Fix notifying that audio recording has stopped before recorder is shutdown

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
After registering with a phone number, opening the profile view controller caused a crash.
The `emailAddress` field of the user was force unwrapped to check if it's empty, but there was no value.
This is fixed by checking if the field if either `nil` or empty, without implicit or forced unwrapping.
> ZIOS-9811: Fix crash when opening settings for users without email

- Wire-iOS/Resources/Sounds/audio-notifications/MediaManagerConfig.plist
When removing someone from a group and music was playing, the music was paused for a few seconds.
The alert sound played before confirming the removal of the participant required the music to be paused. 
This was fixed by allowing the alert sound to be mixed with other currently playing sounds.
> ZIOS-8802: Fix music pausing when removing someone from a group

- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
list ui turns black during the transition to conversation view
The leftView was set to hidden immediately in the line:
self.leftView.hidden = self.openPercentage == 0;
Do not call updateLeftViewVisibility every time in updateForSize, which is called by viewWillLayoutSubviews.
for iPad, call updateLeftViewVisibility after orientation changes, to hide the left view when rotates to portrait mode, and shows the left view when rotates to landscape mode.
> Fix - List UI turns black during transition to conversation view

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
App crashes when showing video editor on iPad.
"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'On iPad, Wire.StatusBarVideoEditorController must be presented via UIPopoverController'"
Present videoEditor in popover style on iPad. 
###Note 
This PR fixed a run time warning for dismiss spinner in non-main thread.
> Fix crash: when presenting video editor on iPad

- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileFooterView.m
In the profile details view controller, there was no spacing between the icon and the title on the bottom left footer button.
The title edge insets were used to set the margin but were not taken into account by the button. Changed to use the dedicated `-[IconButton  setTitleImageSpacing:]` with a 16pt spacing.
> ZIOS-9806: Fix spacing

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
The cancel button on the landing screen was too big and mispositioned; which caused a visual glitch in the transition from the self profile view controller.
The cancel button was sized and positioned manually. The close button in the self profile is managed by a navigation bar, and thus has a different position on every device (adapted by the `UINavigationBar` depending on the size of the screen).
Because the two buttons do not have the same size, and a slightly different position, this caused the animation between the two to be "off".
We now use a standard navigation bar to size and position the cancel button on the landing page.
> ZIOS-9808: Fix visual issues on landing page

- Wire-iOS/Sources/UserInterface/Settings/BackupViewController.swift
Store the back up on simulator to the `tmp` folder to allow automation to fetch it.
> Back up to tmp on simulator

- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
The sketch hint was not using the correct placeholder color.
> ZIOS-7590: Use light gray placeholder color for sketch hint

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Swap the copy in titles/subtitles to clarify when to create a personal account or team:
> **For personal use**
> create an account
> **For organizations**
> create a team
Per discussion with @teller & @Yorgos-V.
> Flip create account/create team copy

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NoHistoryViewController.swift
- WireExtensionComponents/Views/Loading/UIViewController+LoadingView.h
- WireExtensionComponents/Views/Loading/UIViewController+LoadingView.m
When user restores the backup due to the timing issue when the check mark is removed the view controller is not dismissed yet.
The proposed solution is to keep the check mark and just dismiss the whole controller.
> Restore: Do not remove the checkmark after the animation

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ParticipantsDeviceHeaderView.m
In device fingerprint screen, no link for the text "Why verify conversations?" for Chinese simplified, Italian and some other languages.
In some of the translations, "profile.devices.fingerprint_message.link" is not a substring of "profile.devices.fingerprint_message". Part of "profile.devices.fingerprint_message" is not mark as a link in these languages.
Rewrite the logic to combine two strings, instead of finding "profile.devices.fingerprint_message.link" in "profile.devices.fingerprint_message".
"general.space_between_words" is added for localize space for languages which do not have spaces.
> Fix: When app language set to Chinese simplified or Italian, "Why verify  conversations?" is not clickable 

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationNewDeviceCell.swift
In ConversationNewDeviceCell, the string "You started using this device" has space in Chinese.
The string concatenation did not consider the writing systems which don't use spaces.
Use localized space instead of simple space string.
> Fix: remove space in the string of ConversationNewDeviceCell for languages do not have space

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
"Bill calling" is translated to "Bill anruf" in German. The correct translation should be "Bill Anruf"
"Anruf" is lowercase in the code.
Keep the original Uppercased localization. Handle the casing in Crowdin.
> Fix: Change 'anruf' to 'Anruf'

- Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
Call quality survey overlay was shown when `UseAnalytics` flag was set to zero.
I'm now checking if `UseAnalytics` is active before showing the survey overlay.
> ZIOS-9795: Disable call quality overlay if UseAnalytics is set to 0

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationViewController.m
This portion of code used to show the "You logged in on the new device" screen, which was moved in the flow.
> Notify UI that sign in is successful

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift
On iOS 9/10, app crashes when the user changes audio effect, dismiss audio record keyboard or rerecord the audio.
AudioPlayerController was deallocated while key value observers were still registered with it.
Before AudioPlayerController is freed, remove the observer.
> remove observer before audioPlayerController is freed

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NoHistoryViewController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/UIAlertController+ImportWarning.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/UIAlertController+Restore.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/UIAlertController+RestorePassword.swift
* Extract alerts from view controller, update copy.
> Update restore history copy

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift
App crashes when fast tapping audio effect keyboard. 
It crashes at the line  -[AVAudioRecorder finishedRecording], possible reason is AVAudioPlayer.delegate is unowned(unsafe), not a weak type. It always assume delegate is non nil.
Manually set AVAudioPlayer.delegate to nil when tearDown.
> Fix: App crashes when fast changing audio filter to first(none) effect

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
Audio record time is not reset immediately after re-recording the audio message.
The time label should be reset to 0 after the state change to .ready 
reset time label when the state change to ready.
> Fix: Timer is not reset immediately after re-recording the audio message

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
The problem happens when user received the timed message and this message is visible with the running timer in the current open conversation. If then user selects then to log out the app would crash.
The crash is happening because the countdown timer continues to run. When it updates and the data model is already torn down, there is no way to query the message state, so it causes the crash.
Generally the cell must get `didEndDisplayingInTableView` callback when it's removed from the screen, but it is most likely not happening since the whole table view gets deallocated.
The fix makes the display timer stop when the cell gets removed from the window.
> Do not crash when logging out

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
When lightly pressing on a conversation content cell, the contents appear flipped inside the 3D Touch preview.
The previewing was registered with the content table view. This view has an affine transform that flips the contents. When the peek is created, the transforms are removed from the snapshot and thus the contents appeared flipped.
Previewing is now registered with the parent view of the table, which has no transform.
> ZIOS-9875: Fix reversed content cell in 3D Touch peek

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
* Fix username label being cut off in conversation header view.
> Fix username label being cut off in conversation header view

- Wire-iOS/Wire-Info.plist
The UTI types are building a graph-like hierarchy. Initially the backup used to be a ZIP archive, therefore it was inherited from ZIP file UTI. Now as we changed the files to be encrypted the inheritance from ZIP does not make sense any more.
[Apple System-Defined UTI Types](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html)
> Backup: Changed parent UTI type from ZIP to public.data

- Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
When *Chrome* was set as the default browser, tapping on a detected email or phone number would open chrome, instead of performing native actions (opening *Mail* or asking to call that number).
Detected email addresses and phone numbers have the URL schemes `mailto` and `tel` respectively. When opening a link, we check if the URL scheme is `x-apple-data-detectors`, and if so, allow the operating system to handle it, otherwise we open the link ourselves, adhering to the user's default browser setting.
Create a list of URL schemes for links that need to be opened by the operating system, against which we compare the schemes of tapped links.
> make sure data detected urls are handled by os

- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
Right now in a full screen camera we are using a native camera. But in this case we couldn't have a preview with sketch and emoji.
When shot a photo with full screen camera, follow camera keyboard's workflow.
> feature: ZIOS-7694  [UX] [Improvement] Not possible to sketch/add emoji on a photo taken from a full screen camera in camera keyboard

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
The image does not zoom in for the first double tap. 
For uncertain reason, viewWillLayoutSubview is called for the first call trigger of double tap gesture. The zoom level is reseted
Do not call updateZoom when viewWillLayoutSubview
It also fixes "rotate screen and zoom resets issue".
> fix: ZIOS-9783  First double tap doesn't zoom picture in when it's opened full screen

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
Force-touch image preview and full-screen image view's image zoom level is invalid after https://github.com/wireapp/wire-ios/pull/2022.
Zoom ratio is not recalculated force-touch image preview and full-screen image view
Undo the changes in https://github.com/wireapp/wire-ios/pull/2022. The ticket will be restarted.
> undo viewWillLayoutSubviews

- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
App crashes when calling ZMBareUser.nameIncludingAvailability (the ZMBareUser is a service user)
name property is nil
unwrap before creating attributed string
> fix: unwrap name of ZMBareUser before creating Attributed string

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Audio recordings started before incoming or outgoing calls were deleted due to an unhandled case.
This is because the keyboard got dismissed on `viewWillDisappear()`, but the continuation of the flow (adding effects on the registration and sending it) was not handled.
I'm now handling the cases where the keyboard should reappear after the call termination by monitoring changes on `WireCallCenterCallStateObserver` inside `ConversationInputBarViewController+Audio.swift`.
> ZIOS-9889: Audio message is discarded after Wire call

- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
We were able to add services to non-team conversations
The check was checking if you can add guests instead.
Same as #2033, but using correct base branch
> Fix the check for adding bot to conversation

- Wire-iOS Share Extension/ja.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/InfoPlist.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.stringsdict
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Updated localization

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
* Fix verified shield being visible without own devices being verified.
> Fix verified shield being visible without own devices being verified

- Wire-iOS/Sources/UserInterface/Conversation/Content/Previews/LocationPreviewController.swift
When swiping up on a location preview on iPhone X, the preview looses its rounded edges and becomes smaller.
This is caused by a bug with Auto Layout on iPhone X. The safe area margins are changed when moving the preview up, which causes the frame of the map to change.
Constraining the map to the edges of the view fixes the issue.
> ZIOS-9899: Fix 3D Touch location preview glitch on iPhone X

- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
The app crashes when trying to accept the non-callkit call.
The tracking meta generation method `ephemeralTrackingAttributes` was implemented on the same class in extensions in UI and in SE. The problem was that the return type of the method was different, so in the run time the expected return was not matching with the real one.
Remove the implementation of the method from the UI and make the SE method public so there is no possibility of the return type mismatch.
> Fix crash when calling without CallKit

- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileView.swift
* Fix self user image size in settings on iPad in small horizontal trait.
> Fix self user image size in settings on iPad in small horizontal trait

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
Revise backup description to include strong password recommendation.
@mikeger @daehn I also updated the current German translation in Crowdin to reflect the revised version of the string, but merging this may mark the modified string as untranslated, so I'll push an extra commit with the revised translation to save time.
> Recommend strong password for backup file

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Controllers/AccessibilityWrapperController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/ProfilePictureStepViewController.m
It was requested to add the intermediate view that would wrap some controllers in order to calculate the elements positions:
- Camera picker in the registration.
- Documents picker.
@mykola-mokhnach name is "accessibilityWrapper".
> Added accessibility element that wraps the iOS controllers

- avs-versions
With the new message recording API we are asking AVS to prepare the audio session for the recording, AVS then is setting the session category and waiting for the confirmation from the operating system. Unfortunately on the Simulator the confirmation never arrives, so AVS is never telling us that it is ready to start the recording.
AVS fixed the issue from their side in the way that on the simulator they are immediately calling the callback without waiting for the iOS confirmation.
> Bump AVS to 4.3.16

- Wire-iOS/Sources/AppStateController.swift
Fixing https://github.com/wireapp/wire-ios/pull/2058 had a side effect which caused a freshly installed client to always launch into the login screen.
Even when launching without any accounts SessionManager will call the `sessionManagerDidFailToLogin` delegate method with an error which we were previously losing due to the bug which was fixed.
Only save the error if we have a selected account by unwrapping the optional.
> Only save authentication errors if we have a selected account

- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
On iOS, these issues are found in Self profile screen:
1. container view is covered by the navigation bar
2. table view top inset is negative 
3. accountSelectorControllerView is not center aligned
The layout system of iOS9 is different from iOS11
Add iOS9 specific constraints for Self profile screen.
> Fix: Self profile screen UI issue on iOS9 

- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
This PR is a fix for https://github.com/wireapp/wire-ios/pull/2064.
app crash when opening Profile screen
accountSelectorController.view.superview is nil on iOS > 9
unwrap superview and apply the fix only for iOS9
> fix: ZIOS-9967 app crash when opening Profile screen

- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
The image in Sketch is covered by the color picker.
The canva's top is pinned to the container's top. If the image do not have an inset on top, the color picker covers the canvas
The canvas's top should be pinned to colorPicker's bottom instead of the container.
> fix: Image in Sketch is covered by the color picker

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
App crashes when force touch a small image(e.g. 70x70px) in conversation view
When ConversationImagesViewController is going to layout its subviews, InputBarButtonsView crashes for the case only one button is shown in first row.
Actually, InputBarButtonsView's layoutSubview method will be called several times before it is shown. Choose the first button (expandRowButton) as reference button for the intermediate state layout, which the InputBarButtonsView's width only allow one button per row.
> Fix: App crashes when force touch a small image in conversation view

- Wire-iOS Tests/CallInfoViewControllerTests.swift
- Wire-iOS Tests/CallParticipantsViewTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewControllerAccessoryType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController.swift
Show list of participants in group calls.
- `CallParticipantsViewModel ` has been replaced by the typealias `CallParticipantList`
- Show no avatar for outgoing group calls / video calls
> Show participant list in group calls

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
This PR is a follow-up of https://github.com/wireapp/wire-ios/pull/2060
App crashes when force touch a small image(30x30px) in conversation view
When ConversationImagesViewController is going to layout its subviews, InputBarButtonsView crashes for the case only zero buttons is shown in the first row.
Prevent access minus item index in the intermediate layout state.
> crash fixed

- Wire-iOS/Sources/AppStateController.swift
This PR is a follow-up of https://github.com/wireapp/wire-ios/pull/2074
Launch screen not shown after new installation
Caused by https://github.com/wireapp/wire-ios/pull/2074, when the app first launch, selectedAccount, account & loadingAccount are nil.
Add a nil check for account object.
> Fix: Launch screen not shown after new installation

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController+Constraints.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController+Private.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController.m
- Wire-iOS/WireBridgingHeader.h
Unable to finish the registration on iPad due to "I Agree" button is untappable.
"I Agree" button is placed outside its container view.
Rewrite the constraints for iPad.
> Fix/zios 9982 [iPad] Cannot finish registeration due to untappable "I Agree" button

- Wire-iOS.xcodeproj/project.pbxproj
Add build script to test target removing old snapshot results. This wasn't an issue on CI but when running tests locally the SnapshotResults folder included all failed snapshots and not only the ones from the last test session.
> Add build script to test target removing old snapshot results

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
When the user force touch a small image, the full-screen image viewer do not show all toolbar's buttons.
Unnecessary constraints are created when the InputBarButtonsView is in the intermediate state.
Do not create the constraints during the intermediate state by checking the width is valid or not.
> Fix/zios 9977 after force touch a small image, the image toolbar shows only one button and unable to touch

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
When the user wants to edit his/her devices' list, two "DONE" buttons are shown in the navigation bar
The left navigation bar button item is not hidden when toggling edit mode in that screen
Hide/show the left navigation bar button item when toggling edit mode.
> fix: ZIOS-7326  Two Done buttons on the device list dialogue

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/SelfVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
The self video preview should show a mute icon when not in floating mode but displayed in the regular video grid as well. To do that we now also keep a reference to this instance.
> Update mute status of self video when not floating as well

- Wire-iOS Tests/CallInfoConfigurationTests.swift
- Wire-iOS Tests/CallInfoTestFixture.swift
- Wire-iOS Tests/Mocks/MockCallInfoViewControllerInput.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallAction.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/CallInfoConfiguration+Debug.swift
Show an alert when a conversation degrades when making a call or receiving an incoming call.
> Handle call degradation

- Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
- Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.m
App would get into an infinite loop when asking the `NotificationWindowRootViewController` if it `shouldAutorotate` and crash when long pressing on a message.
Long pressing on message shows a context menu, which is displayed in a an window above all other windows. When this is window is displayed the `NotificationWindowRootViewController` would get asked if it `shouldAutorotate` which in turn looks for the top most controller in the front most window. This would after change from yesterday always pick an internal class from apple which displays the context menu.
Ignore all window not created by us when looking for the top most view controller.
> Ignore all system windows when looking for the top most view controller

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
The button to initiate the the group call should be visible:
- For team users.
- If the conversation has 4 or less participants.
> Only allow GVC to team users in convo with <= 4 participants

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/UserImageViewContainer.swift
Username and calling duration labels were not visible during a call with a contact that has a profile picture.
This was caused by the internal `UIImageView` stretching priority settings, automatically set to 750 instead of the expected value (249).
I'm applying the new stretching priority to both views, the `userImageView` container and the inner `imageView`.
> ZIOS-9994: Username not visible in calling overlay during calls with users with a profile picture

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
When hanging up a call the call UI would switch to the incoming call layout for the action buttons.
When leaving a call SE will treat it as having the state `.incoming(video: false, shouldRing: false, degraded: false)`.
Display incoming calls with `shouldRing = false` as terminating
> Fix terminating state when hanging up

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
It was possible to open the camera during a call.
I've implemented the same alert used to block interactions with audio messages during a call.
> ZIOS-9944: Block video actions during a call

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/EmailVerificationStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+Newsletter.swift
Show an alert dialog over email verification screen when the user create a personal or team account with email address.
Screenshot of alert dialog over personal account email verification screen:
Screenshot of alert dialog over team account email verification screen:
> Feature: Alert dialog for newsletter scription when the user creating a account with email

- avs-versions
> bump AVS to 4.3.40

- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
- This controller is displayed when the call is minimized.
- Should show the title: 
- If the call is ongoing it should show "Tap to return to call" + timer.
- If the call is in the different state display the call state.
> Top overlay: display return to call only if call ongoing

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
- avs-versions
When the the remote participant turns his camera off the video feed goes blank.
When the remote participant turns his camera off your own video preview should move into the grid, this failed because we performed the operations in the wrong order.
If the self preview is currently floating we need to perform the following:
1. Remove video from floating video container
2. Add video to grid
When the preview is moving from the grid to the floating container the order is reversed.
> Fix remote participant turning camera off

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+Newsletter.swift
Prevent keyboard hides alert in name input screen.
> Dismiss keyboard when newsletter alert appears 

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallAccessoryViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
All the UI elements didn't update their color theme correctly when toggling between audio and video in a call.
- Trigger update of status bar when call configuration changes
- Fix call participant list not updating it's color variant correctly.
> Fix theming when switching between audio and video

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
Call UI would be displayed under the status bar on iOS 10 and earlier.
On iOS 10 we were falling back to `layoutMarginsGuide`  since `safeAreaLayoutGuide` isn't available but it doesn't take the status bar into account.
Use `topLayoutGuide` instead.
> Fix anchoring to status bar on iOS 10 in call UI

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/ThumbnailCornerPinningBehavior.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
- Wire-iOS/Sources/UserInterface/Helpers/CGSize+AspectRatio.swift
* Fix floating self preview margins.
* Use a larger preview view in regular width trait collections and update on changes.
* Update thumbnail content size before recalculating pinning behaviour anchor points.
* Fix floating self video preview on iPad, this was mostly caused by the preview size calculation on rotation. We now flip the thumbnail aspect ratio when needed.
> Fix floating self video preview on iPad

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+Internal.h
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
This PR introduces the new design of the status bar on iPad, according to the spec.
To achieve the black status bar on iPad only, we pin the main split view controller to the bottom of the status bar when the size class is regular, and to the top of the client view controller when the size class is compact.
We also update the status according to the size class when the trait collection of the root client view controller changes.
The iPhone UI is not affected by this PR.
> ZIOS-9499: Fix status bar visual issue on iPad

- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
Action buttons are not responding to touches in a video call
Buttons have blur effect while in video call which steals the touches
Disable user interaction for the blur view.
> Fix unresponsive action button in a video call

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Handles.swift
loading view does not dismiss as expected after setMarketingConsent is completed.
Remove it for now. Will investigate it before next release.
> fix: Remove the loading view of ConversationListViewController when setMarketingConsent is called

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
* Hide call icons in conversation with already ongoing call.
> Hide call icons in conversation with already ongoing call

- Wire-iOS Tests/CallInfoConfigurationTests.swift
- Wire-iOS Tests/CallInfoTestFixture.swift
- Wire-iOS Tests/Mocks/MockConversation.h
- Wire-iOS Tests/Mocks/MockConversation.m
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallAction.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
Design want the video button to be disabled in large group but still show an alert when it's tapped informing the user why video calling is not possible.
Since a disabled button is not responding to touches we place a ghost button on top of the video button which is only enabled when the video button is disabled.
> Disable video for calls in large groups

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
The minimized call bar stopped appearing.
The changes with the iOS status bar style are clashed with the changes from the call bar minimization:
the new constraints logic was not taking the top overlay container in account.
Take the top overlay in account when creating the constraints.
> Fix the constraints for the top bar

- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsView.swift
* Always reload using diff calculation system.
> Always reload using diff calculation system

- Wire-iOS Tests/CallInfoConfigurationTests.swift
- Wire-iOS Tests/CallInfoTestFixture.swift
- Wire-iOS Tests/Mocks/MockUser.m
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
Introduce a restriction that non team users can only video call if someone initiates the video call.
> Limit video group calling for non-team users

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
When client list screen is shown during login, the loading spinner dismiss before client list screen is dismissed and the user may remove another device which is not necessary.
Loading view is dismissed when finishedDeleting is called, but client list screen is not yet dismissed.
Hide loading view when viewDidDisappear instead of finishedDeleting.
> Fix: Client list screen - loading spinner dismiss before client list screen is dismissed

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/AppRootViewController.swift
Copy was outdated for warning when switching accounts.
> Update copy for account switch warning

- Wire-iOS Tests/CallInfoConfigurationTests.swift
- Wire-iOS Tests/CallInfoTestFixture.swift
- Wire-iOS Tests/Mocks/MockCallInfoViewControllerInput.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/CallInfoConfiguration+Debug.swift
- Wire-iOS/Sources/UserInterface/Calling/Permissions/CallPermissionsConfiguration.swift
I was trying to reduce the number of UI reloads we do when the call changes and then realized that when checking if two instances of `CallInfoConfiguration` are equal it always gets reported as `true`. 
This issue was due to the fact that all of the properties of `CallInfoConfiguration` are computed and based on the stored `VoiceChannel` reference type, so when comparing two different instances they will internally access the same voice channel and return the same results for all variables. As this was not what we had in mind and want a immutable struct to be passed down as configuration I now changed this and all properties are now stored and only once computed in init.
Besides that 9d050cc fixes an issue with the timing of the mute overlay animation in the self preview which is now in …
> Convert CallInfoConfiguration to stored properties

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
If user during the call minimizes the call overlay and navigate to the settings, the settings navigation bar is shifted down.
The additional inset was added for the case of iPhone X device.
This inset is now automatically inserted with the constraints, so the setting is removed as unnecessary.
> Settings: Removed unnecessary top bar inset

- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
When marketing consent setting is toggled, loading view appears behind the setting popover.
The loading view was shown on rootViewController.
Show the loading view was shown on SelfProfileViewController.
> Fix: iPad - when marketing consent setting is toggled, loading view appears behind the setting popover

- Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
* Hide custom calling UI for incoming calls when callkit is enabled.
> Hide custom calling UI for incoming calls when callkit is enabled

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
The `VideoConfiguration` is re-calculated fairly frequently but most the time it doesn't result in any necessary update for the views. This PR makes the `VideoConfiguration` immutable and only update the views if the configuration actually changed.
> Make VideoConfiguration immutable

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/UIImagePickerController+iPadPopover.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+CameraPicker.swift
- Wire-iOS/Sources/UserInterface/Helpers/IPadPopoverConstants.swift
Photo picker's size resize to 320px width after the user had selected the album
Set preferredContentSize to standard size (320x568) for photo picker popover on iPad.
> Fix: iPad - photo picker popover size is not consistent

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
* Dismiss overlay when it is visible on tap over floating preview.
> Dismiss overlay when it is visible on tap over floating preview

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/BrowserOpening.swift
- Wire-iOS/Wire-Info.plist
As suggested in [the operational-security article](https://operational-security.com/wire-secure-messenger-year-later/), Wire would be better if it would support more of the independent browsers.
Added the support for Brave and SnowHaze browsers. The integration is very similar to other (Chrome, Firefox, ...) browsers.
Both browsers are open-source: https://github.com/snowhaze/ and https://github.com/brave/
> Support opening links in SnowHaze and Brave

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationPhoneFlowViewController.m
Newsletter popup shows after entering the incorrect code from SMS. It hides the code error alert.
Newsletter popup was shown whatever verification was succeeded or failed
Show marketing consent dialog after the code is verified successfully.
> fix: Newsletter popup shows after entering incorrect code from sms

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
On iPad, the calling overlay was not going under the status bar.
Some simultaneous changes in the bar constraints code by me and @alexaubry caused the incorrect behavior when the call bar was pinned to the bottom of the status bar.
Refactor the code to move the logic to one method.
> Display the call overlay correctly on iPad

- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+SizeClass.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientUnregisterFlowViewController.swift
This PR is a reworking of https://github.com/wireapp/wire-ios/pull/2182
After removing a device in the settings screen, the spinner does not dismiss.
In https://github.com/wireapp/wire-ios/pull/2182, I try to fix the issue by dismissing the spinner when view did disappear, which would not be triggered in the settings screen,.
Restore to the original pattern. Create a delegate method finishedDeleting and ClientUnregisterFlowViewController dismisses ClientListViewController when finishes device deletion. Show spinner on ClientUnregisterFlowViewController after that.
On ClientListViewController, show the spinner on the navigation controller to cover the navigation bar buttons.
> Fix: Client list screen - loading spinner dismiss before client list screen is dismissed (rework)

- Wire-iOS/Sources/UserInterface/Camera/CameraController.m
- Wire-iOS/Sources/UserInterface/Components/DeviceOrientationObserver.m
When user takes the picture in the camera keyboard in landscape, the picture appears rotated on the confirmation screen.
During the migration to the Xcode 9.3, we changed the orientation observer code so that it was not setting the outer accessible variable that indicates the orientation to the correct value.
> Fixed landscape picture taking in the camera keyboard

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
This PR is a follow up of https://github.com/wireapp/wire-ios/pull/2206.
In setting screen, loadingView is not dismissed if the user has only one device
showLoadingView is set to true before the view controller has a navigation controller. The overridden showLoadingView does not handle this case
Dismiss showLoadingView in both navigation controller and ClientListViewController in this case.
> Fix: loadingView is not dismissed if the user has only one device

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
iOS app is crashing when selecting the fullscreen camera from the camera keyboard.
We try to set the preferred camera in the code, but UIImagePickerController is configured for showing the camera roll. 
Correctly set the source type for the camera.
> Select correct sourceType

- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Handles.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationEmailFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationPhoneFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+Newsletter.swift
After https://github.com/wireapp/wire-ios/pull/2205 is merged, In-app browser is blank when open marketing consent dialog's privacy web page.
SFSafariViewController cannot render correctly if it is not presented with the same window as the current view controller.
Present BrowserViewController from the same view controller instead of notificationsWindow.rootViewController.
After testing, I found that BrowserViewController does not call completion closure. Rewrite BrowserViewController in a simpler way to fix it.
> Fix: in-app browser is blank when open marketing consent dialog's privacy web page

- Wire-iOS/Sources/UserInterface/Helpers/UINavigationController+Additions.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+Newsletter.swift
There is no Newsletter popup after team owner verified his email address.
Related to https://github.com/wireapp/wire-ios/pull/2216.
After the fix for new BrowserViewController, we show the UIAlertContoller from the current viewController, which may be not yet in the view hierarchy and the alert may not appear.
Show the alert from the navigation controller after navigationController.pushViewController or navigationController.setViewControllers.
> Fix: There is no Newsletter popup after team owner verified his email address

- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionsView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
* Don't display the audio keyboard again when there is still an ongoing call.
> Don't re-display audio keyboard when there is still an ongoing call

- Wire-iOS/Sources/Helpers/syncengine/Message+UI.h
- Wire-iOS/Sources/Helpers/syncengine/Message+UI.m
- Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Calling.swift
- When user forbid the video permissions, but allow the audio permissions, we still want to allow the call to be started.
- Removed unused method: `isPresentableAsNotification`.
> Allow calling when video permissions are not granted

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
When the user enters re-authentication from the profile screen, the cancel button is not shown and he can not go back.
RegistrationRootViewController's firstAuthenticatedAccount property returns nil, which should return the account authenticated.
Replace RegistrationRootViewController.firstAuthenticatedAccount with [[SessionManager shared] firstAuthenticatedAccount].
> Fix: Back button is not shown in the re-authentication screen 

- WireExtensionComponents/Views/RoundedView/ContinuousMaskLayer.swift
This fixes the implicit animation of the avatar performed when swiping in the conversation view.
The rounded mask layer was starting a basic animation. This is not required, since the size of the avatar element does not change; so that behavior was removed.
> ZIOS-10088: Fix implicit avatar animation

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
In case user haven't granted the video permissions yet, the initial call to `disableVideoIfNeeded()` is happening before user have decided to reject the permissions, therefore it has no effect (isVideoDisabledForever is yet false).
Solution is to call the method once again when the call is answered.
> Disable video when no permissions granted: case when first answering the call

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
* It was not possible to toggle video on / off when receiving an incoming call without CallKit.
* In case of an incoming video call the initiating side can not toggle video on and off, meaning in this state we should consider the call to be a video call.
> Include incoming video call state in isAnyParticipantSendingVideo calculation

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientUnregisterFlowViewController.swift
This PR is a follow-up of https://github.com/wireapp/wire-ios/pull/2228.
Apply dark variant for the ClientListViewController when it is shown in login workflow.
> fix variant for login workflow

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/GridView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/SelfVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
* Layout video streams horizontally next to each other when on iPad in landscape.
> Layout video streams horizontally next to each other when on iPad in landscape

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
We moved to open all links in Safari View Controller, but in case of opening the manage team link we've been pushing the controller on the navigation stack, which seems to be not supported in the safari controller.
Changed to present the controller as modal.
> Manage conversation link: fix opening in SafariVC

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
* Fix audio call overlay being visible during second call.
> Fix audio call overlay being visible during second call

- WireExtensionComponents/Views/RoundedView/ContinuousMaskLayer.swift
The app was crashing in the calling UI with the stack trace pointing to `ContinuousMaskLayer.initWithLayer:`
The existing implementation was trying to assign the new layer to the `mask` property, which was the problem for iOS.
The method `initWithLayer:` [is called](https://developer.apple.com/documentation/quartzcore/calayer/1410842-initwithlayer) by iOS in order to create the copy of the current layer for building the shadow (displayLayer) layer hierarchy. The apple's `CALayer.initWithLayer:` implementation has the code to copy the mask already. Normally in this method it's important to copy all the custom properties of the layer, like [here](https://blog.pixelingene.com/2012/02/animating-pie-slices-using-a-custom-calayer/).
Fix adds the copying of the properties and removes recreation …
> Corrected the code for making the copy of the ContinuousMaskLayer

- Wire-iOS/Sources/Components/DeviceProtocol.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
* Disable speaker button for iPod as well.
> Disable speaker button for iPod as well

- Wire-iOS/Sources/Components/ShareViewController/ShareDestinationCell.swift
In the share content screen, on the narrow screens, the title of the conversation is taking the maximum width in the stack view, pushing the icons on the right to be compressed.
Default compression resistance is most likely the same between UILabel and UIImageView.
Explicitly lower the resistance for the title label.
> Share cell: compress title instead of the images

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIInviteActionBar.m
The bottom bar, that is visible for non-team users only, was transparent, creating the unnecessary text overlap with the content of the start UI.
Make the bar opaque and resize the table view, so it ends just before the bar.
> Start UI: make bottom bar opaque, same color as top bar

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
self.traitCollection.userInterfaceIdiom is .unspecified when it is checked in init. Replace it with UIDevice.currentuserInterfaceIdiom gives correct idiom.
> Fix: iPad - in self client list screen, left navigation bar button is Done, not Back

- Wire-iOS Tests/DeviceManagement/ProfileViewControllerTests.swift
- Wire-iOS Tests/Mocks/MockUser+ProfileImage.swift
- Wire-iOS Tests/Mocks/MockUser.m
- Wire-iOS.xcodeproj/project.pbxproj
Remove duplicated methods of MockUser.
> Fix: compiler warning form wire-bot

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
In VoiceOver, it was not possible to go back to the call.
The `accessibilityActivate` method is not called on the view controller, but on it's view.
> Call VoiceOver: come back to the call activation

- Wire-iOS Share Extension/ar.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Updated "de|it|ja|pt-BR|es-ES|ru|uk|tr|nl|da|fr|zh-CN|sl|ar|et|f.." take 2

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
* Don't rely on `VoiceChannel.isVideoCall` which only captures the initial state to decide to pause / start the self video feed.
> Fix video not being paused when multitasking after upgrade from audio to video

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/UpsideDownTableView.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+TableHeader.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Conversation table 's table header's height is incorrect after accent color is updated.
If ConversationContentViewController is created behind other views, its table view's frame is zero and the table view's header view's header is wrongly calculated.
Refresh table view's header view's height when viewWillAppear.
> Fix: incorrect conversation table header height after changing accent color

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
QA noticed, that when user is switching from and to the call where the remote participant stopped the video, the label that says "video stopped" is disappearing.
The update block was designed in the way that even when no animation was desired (for example when setting the initial state), the animation was still performed with duration of 0. This caused the unnecessary async update effect: the animation completion block was called on the Nth run loop after the update. The update of view is happening in 2 steps: first we set initial "default" state, where the video is not considered stopped, and then we update the view with the real values. The problem happened because we called two updates one by one, but the animation completion blocks for 1st update where called after the 2nd update (to …
> Fix async view change without animation

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
Personal accounts could see the Guest icon inside `ShareViewController`, which should be visible only to team accounts.
I've added a `hasTeam` clause to the conditions of the `showsGuestIcon` variable.
> ZIOS-9798: Add guest icon to guests in share screen, personal accounts

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Added a footer inside the "Locations" screen of the settings, clarifying that some location links will always open with Apple Maps.
> ZIOS-9981: Add a clarification in the locations setting.

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EphemeralKeyboardViewController.swift
This would allow QA to test the clients behavior with the defined destruction time interval.
> Dev build: allow arbitrary ephemeral timer value

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+Zoom.swift
* Fix crash cuased by missing @objc annotation.
> Fix crash caused by missing @objc annotation

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+Newsletter.swift
Change marketing consent dialog's cancel button's text form "Not now" to "Decline"
> Fix: copy change on the Marketing consent dialogue

- Wire-iOS/Sources/Analytics/Events/Analytics+Collection.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchResultCell.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
Some issues connected to the fact that we are going to start showing the ephemeral messages in the collections UI.
- The text search continues to show the message content when the message is already obfuscated or expired.
- App crashes when clicking on the obfuscated image.
Weak dependency on the data model bump.
Made the cell selflsess.
> Do not crash with expired ephemerals in collection

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppDelegate.h
- Wire-iOS/Sources/AppDelegate.m
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallWindow/CallWindow.swift
- Wire-iOS/Sources/UserInterface/Calling/CallWindow/CallWindowRootViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadsViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
- Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.m
* Extract call overlay to use its own window to support chatheads above it.
* Clean up window creation code.
> Extract call overlay to use its own window to support chatheads above it

- Wire-iOS/Sources/WireApplication.swift
- WireExtensionComponents/Utilities/AutomationHelper.swift
Add launch argument flag for disabling alert asking about push notifications.
Previously we never was showing the push notification alert on Simulators since it breaks automation. This logic was removed in the push registration re-factoring.
Add a `disable-push-alert` launch argument for disabling show of the push notification alert.
> Launch argument for disabling push alert

- Wire-iOS/Sources/Components/AudioPlayer/AudioTrackPlayer.m
- Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorController.swift
1. If Soundcloud is playing and the user wants to switch to other accounts, the player still plays the song. If the user comes back to the previous account is not possible to stop the music.
2. In that case, Soundcloud crashes when the song ends.
1. We weren't specifying the song to stop playing on account switch
2. We are trying to remove the observer for keypath `status` in `self.avPlayer.currentItem`, which wasn't added before in any point of the code (but still calls the observation methods).
1. I'm calling `stop()` on the shared instance of `mediaPlaybackManager`.
2. I've removed the call to `removeObserver` on `self.avPlayer.currentItem`. Question: is it enough removing the observer about `currentItem` inside `avPlayer`, like we're doing in the line before?
> ZIOS-10059: Soundcloud still plays when switching accounts

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Since the number of participants shown in the conversation does not include the current user, we need to change this copy to prevent confusion when the conversation shows “4 people” and the Video Call icon is not available.
> Clarify GVC limitation

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/GroupOptionsSectionController.swift
The guest options are visible for everyone, however in non-team conversations they cannot be set.
Do not show the guest options when user cannot use them.
> Only show guest option when possible

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationTimeoutOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EphemeralKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
It is not possible to test how future-proof the timer is. We need to be able to set the arbitrary timer to the conversation and see how the client would behave.
Also client must display the arbitrary value in the correct way.
> Allow setting the custom timer for the conversation

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Automation sees the message text twice in the accessibility tree. My speculation is that it's showing like that because the message is buried inside another view that is also visible in the tree.
Make message text view appear on the higher level of the accessibility hierarchy.
> Reduce the accessibility tree depth

- Wire-iOS Tests/EphemeralTimeoutFormatterTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/EphemeralTimeoutFormatter.swift
For time remain larger than 1 year, display it with year and month unit.
> Display remain time with year unit

- Wire-iOS/Sources/UserInterface/Components/Views/DetailsCollectionViewCell.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationTimeoutOptionsViewController.swift
The custom value cannot be selected, so must appear as disabled.
> Conversation: Disable custom value in timers selector

- Wire-iOS/Sources/AppDelegate+Hockey.m
As reported in https://github.com/wireapp/wire-ios/issues/2318 on app startup HockeyApp manager sends telemetry to the servers even with tracking disabled.
We need to make sure to set the tracking flag before starting Hockey manager.
> Disable tracking for Hockey earlier during startup

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
In the start UI, the status icons if user has the light color scheme are displayed dark on dark initially. If user scrolls the start UI then the icons are coming back to normal.
The color scheme on the cells is set via `UIAppearance`. For the first rendered cells the setting of user is happening before the appearance is setting the color scheme.
When color scheme is set, re-render the user status icon with the correct color.
`SearchResultsViewController` was still created with the color scheme variant.
> Fix the status icons initial style

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Timer was not updating correctly on `GroupDetailsViewController` because the `destructionTimeoutChanged` event was not considered.
I've added `destructionTimeoutChanged` to the list of allowed events that are able to trigger updates on the UI.
> ZIOS-10184: Timer is not updated if other user changed a value

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationTimeoutOptionsViewController.swift
When the user selects the current timeout in the conversation details (or "Off" if the synced timeout is disabled), an error will be displayed after we attempt to update the value on the server.
We shouldn't be sending the request to update the value if the user selection didn't change.
We check if it makes sense to send the update request before sending it when the user selects a timeout.
| Current state | Allow selection & updates unless... |
|---------------|-------------|
| Timeout off | User selects "Off" |
| Local timeout on | User selects "Off" |
| Synced timeout on | User selects the current timeout again |
> ZIOS-10230: Fix error when selecting the current conversation timeout again

- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
Unarchiving a conversation would make the status bar black on a dark background.
`ArchivedListViewController` didn't have a preferred status bar style, so default (dark content) was being used.
Set the preferred style to `.lightContent`
> Set preferred status bar style

- Wire-iOS Tests/ConversationImagesViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
In ConversationImagesViewController, its toolbar is not refreshed and the user can still perform actions such as like/download a timed image, which should not be allowed.
Buttons should be refreshed according to the image message is ephemeral or not.
When the user scroll to next page in ConversationImagesViewController, refresh the buttonsBar's buttons.
> Fix: image viewer toolbar not refreshed after scrolling form a timed image to non timed image or vice versa

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
When opening StartUI close button would appear only after the transition is complete. In all other screens it's there from the beginning
> Fix for close button in StartUI 

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/GroupOptionsSectionController.swift
* Add section title `"Setting"` for conversation options menu.
> Add conversation option section title

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Remove the message cell fade-out effect to match the latest design spec.
> Fix: Remove the reduce alpha effect for message in last 10 seconds

- Wire-iOS/Sources/Vendor/SCSiriWaveformView.h
- Wire-iOS/Sources/Vendor/SCSiriWaveformView.m
Use the correct header format for imported third party code in the` SCSiriWaveformView` file headers.
> Fix SCSiriWaveformView copyright header

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
The user is able to copy/like/save/share a timed image via force touch menu.
Missing checking of currentMessage.isEphemeral when creating the previewActionItems 
Check currentMessage.isEphemeral and create different lists for both cases.
> Fix: Do not show buttons except deleteAction for ephemeral image on quick menu

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
* Remove join button from 1-on-1 conversations during a call.
> Remove join button from 1-on-1 conversations during a call

- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBarController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
* Disable animations for login flow tabbar.
* Fix initial selector alignment.
> Disable animations for login flow tabbar, fix initial selector alignment

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+TableHeader.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
After sending an image, the top avatar image's height is reduced and overlaps the username.
The table view header's height is compressed after a cell is inserted
Refresh table view header height in conversationWindowDidChange.
> Fix: After sending an image, the top avatar image's height is reduced

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+CountDown.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ZMConversationMessage+CountDown.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ZMConversationMessage+Ephemeral.swift
The pie countdown UI's percentage is wrongly calculated, the progress is to finish is higher than expected.
The calculation logic is different from the original dot style countdown UI.
Restore the logic to the original version. Refactor the logic as a ZMConversationMessage's property.
> Fix: Timer pie UI's progress should be calculated with the message's first read time

- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
* Fix showing ongoing call bug for connection requests.
> Fix showing ongoing call bug for connection requests

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
When the timeout of an audio message is extended, the app crashes when the original timer would have fired.
The timestamp label was still being updated in the extended period, however, to guard against a negative timer string, the client was force-crashed if the destruction date was exceeded. Extending the timer of an audio message doesn't change the original destruction date, it simply replaces the existing timer with a new one. Hence, one the destruction date was exceeded, the app was force-crashed.
Add extra conditions when constructing the timeout string: if the destruction date is exceeded and the message is an audio message, then fallback to the default timestamp string. If the destruction date is exceeded, but the message is not an audio message, force-crash the app.
> Don’t crash when audio message exceeds timer

- Wire-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
- Fixed a condition to the file size for audio messages - I was checking for the duration instead of file size
- Removed test code inside `startRecording()`, restored to the previous version
> ZIOS-10165: Fix for 25MB audio limit

- Wire-iOS Tests/ConversationCell/ImageMessageCellTests.swift
- Wire-iOS Tests/ConversationInputBarViewControllerTests.swift
- Wire-iOS Tests/UIView+Snapshot.swift
- Wire-iOS.xcodeproj/project.pbxproj
Freeze the layer for fixing failed DraftSendInputAccessoryViewTests's snapshot involve a cursor.
> freeze the layer for snapshot

- Wire-iOS Tests/CanvasViewControllerTests.swift
Follow up of https://github.com/wireapp/wire-ios/pull/2392. Freeze the layer for fixing failed CanvasViewControllerTests's snapshot involve a cursor.
> fix snapshot involving a cursor

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
We add the "For companies" login button to the first screen of the login flow.
- Listen to tab bar changes to detect when login screen appears and disappears
- Move the cancel button and company login button to avoid overlap
This button needs to be integrated with the SSO controller that will actually display the alert and handle authentication in a subsequent PR.
> ZIOS-10299: Add company login button to login flow

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
- Wire-iOS/Sources/UserInterface/SSO/SingleSignOnController.swift
- Wire-iOS/Sources/UserInterface/SSO/UIAlertController+CompanyLogin.swift
We present the SSO code input alert when tapping the "For Companies" button in the login screen.
When initializing the root registration/login controller we assign it a SSO controller that uses the default shared identity requester.
We call the `presentLoginAlertWithPrefilledCode` with `nil` when the user taps the button.
> Integrate SSO controller with "companies" login button

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
- Wire-iOS/Sources/UserInterface/SSO/SingleSignOnController.swift
When the user manually clicks on the "for company" login button and there is a valid code in the pasteboard, we didn't autofill the text field of the manually displayed prompt.
Always check the contents of the pasteboard before displaying the alert.
> Autofill the company login prompt when clicking button

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
The audio record keyboard is dismissed after the app is unlocked. The user can not save his audio record.
Actually, the audio record keyboard is still present but not visible after the app called endEditing method. The user can not see the audio record keyboard with audio filter UI.
In ConversationInputBarViewController, observer the .appUnlocked notification form AppLockView. Display the audio record keyboard when the notification is observed. 
This PR changes the keyboard visibility when the application is active and the lock setting is disabled. The app preserves the keyboard state instead of always resign the keyboard.
> Fix: Audio message is stopped recording if device entering screenlock mode

- Wire-iOS Tests/MessageTests.swift
- Wire-iOS Tests/XCTestCase+DayFormatter.swift
- Wire-iOS.xcodeproj/project.pbxproj
- WireExtensionComponents/Utilities/Date+Format.swift
The burst timestamp shows a wrong year(2018 instead of 2017) when displaying the date of 2017.12.31.
Unknown. Maybe a bug in this line:
DateFormatter.dateFormat(fromTemplate: "EEEEdMMMMYYYY", options: 0, locale: locale)
Simplify the method to produce the full format date string.
Create a test to check it produce a correct output.
> fix: Burst timestamp is showing the wrong year sometimes

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
When the screen lock is enabled, Audio recording stops after the screen is locked.
In AudioRecordKeyboardViewController, when viewWillDisappear (triggered by the keyboard dismissal), the audio recording stops.
Do not stop recording when viewWillDisappear, hide the keyboard instead. When UIApplicationDidBecomeActive or appUnlocked notification is fired, reveal the audio record keyboard.
> Fix: Audio message is stopped recording if device entering screenlock mode 

- Wire-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
If I long press on a content inside a conversation and then I swipe back to the conversation list, the `UIMenuController` is still there.
`UIMenuController` doesn't get dismissed during this transition.
I've added a call to the `removeHighlightsAndMenu` method, which hides the shared instance of `UIMenuController`.
> ZIOS-10329: UIMenuController still onscreen after coming back to Conversations List

- Wire-iOS/Sources/Helpers/sound/AVSMediaManager+Additions.h
- Wire-iOS/Sources/Helpers/sound/AVSMediaManager+Additions.m
- Wire-iOS/Sources/Managers/SoundEventListener.swift
It came out, that AVS is ignoring the calls to play certain sounds, since they started to manage those sounds in AVS internally.
The logic for playing those sounds was removed, since it is not used.
> Do not play sounds that are played by AVS

- Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
The call stayed minimized after it was ended and restarted.
The logic to set the current minimized call ID to nil was only called on internal builds where the tracking was enabled.
Move the logic before the guard.
> Correctly erase the minimized call when ended

- Wire-iOS/Sources/AppRootViewController.swift
When creating the login view controller after the session becomes unauthenticated, we don't hide the close button if there is only one user. This causes the skeleton view to appear and stay on screen forever, until we force-quit the app.
We hide the cancel button if there is only one account registered.
> ZIOS-10332: Do not allow single user to cancel login

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/FontSpec+DynamicType.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIFont+MonoSpaced.swift
A `FontScheme` gets re-created on every `FontSpec.font` invocation which is happens quite often.
Introduce a shared FontScheme using the configured dynamic type setting.
> Share the default font scheme so we don't re-create it unnecessarily

- Wire-iOS Tests/MessagePreviewViewTests.swift
Sometimes testThatItRendersLinkPreviewMessagePreview fails for the link preview image is not loaded.
The image caching logic takes some time and the UIView for snapshot taking is freed before the image is loaded. 
Ref to ArticleViewTests, wait for a short time before the image is loaded.
Retain the view for snapshot taking, free it in tearDown.
> Fix: snapshot test fail for testThatItRendersLinkPreviewMessagePreview

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIView+RightToLeft.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangeHandleViewController.swift
Remove the unnecessary iOS version checking for the iOS8 era.
> Remove iOS 9 version checking

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
Tracking was disabled every time the team creation flow was shown.
I've moved the deactivation to `LandingViewController` only in the case there are no accounts left logged into the app.
> ZIOS-10341: Tracking is set to No after accessing New Team page

- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
Sometimes the self profile screen would not have the buttons to create team and go to settings anymore. It was happening after the app was coming to foreground
The height of this section was pinned to the height of cells inside the child controller. At that point table view was thinking it still has 0 cells.
Reload the table view before asking for cell count.
> Fix: buttons to go to settings are not visible in self profile

- WireExtensionComponents/Views/UserImageView.swift
Wrong user image could be displayed in some cases
If a `UserImageView` was re-used while fetching the `UIImage` it could end up displaying the wrong image.
Verify that user hasn't changed in the completion handler.
> Fix wrong user image being displayed

- Wire-iOS Share Extension/ShareExtensionViewController.swift
- Wire-iOS Share Extension/UnsentSendable.swift
Currently, the Share Extension appends the original URL to the content shared through the extension, even if the user decides to hide or change it. 
I'm updating the URL attachments of the current `PostContent` object before sending it. I've also removed the old code that appends the original URL.
> ZIOS-10319: Improve share extension for links

- WireExtensionComponents/Views/TextView.h
Fix warnings caused by the recent changes of class TextView.
> Fix: reduce wire-bot warning

- Wire-iOS/Sources/AppRootViewController.swift
When Okta returns an error because it is wrongly configured, we wouldn't display an alert. It was expected to display an error alert with the code `8`.
This happens because the Safari view controller calls the custom URL handler with the result before dismissing itself. Our handler attempts to present an alert on top of the app root view controller, which fails because it isn't the topmost view controller (Safari VC is still on top of the hierarchy).
We dismiss the Safari view controller before presenting the alert, if needed.
> ZIOS-10363: Fix SSO error alert not displayed

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Design removed the back button for the participants detail screen (when opening from the system message link), now they want it back.
> Remove code for hiding back button

- Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+iOS.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Lifted the upload file size limit to 100 MB for team users (still 25MB for non-team users)
- Small refactoring on the `UIDocumentMenuViewController` instance used for testing purposes.
> Added support for uploads up to 100MB for team users

- Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift
* There was an issue in which haptic feedback was provided when opening the user details for specific users.
* We were providing haptic feedback when the user changes in `AvailabilityTitleView`, which is not as designed. We should only provide feedback if the self user changes their status, not when the status of any user changes (which will happen when we show the status initially).
> Don't provide haptic feedback when user changes in AvailabilityTitleView

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
* Fix call icons disappearing in 1-1 conversation in which the connected user blocked you.
> Fix call icons disappearing in blocked 1-1 conversations

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
Audio keyboard reveals over the call window.
When the call terminates, missing a checking for mainWindow is the top window or not before restoring audio keyboard.
Add the checking for the current top window is the main window before revealing the keyboard.
> Fix: Audio recorder overlay is shown on top of calling overlay if I accept the second call

- Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+iOS.h
- Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+iOS.m
- Wire-iOS/Sources/UserInterface/Components/CameraPicker.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
- Increased video and audio duration limits for team accounts
- New constants are now reachable by calling `ZMUserSession.shared().max{Video|Audio}Length`
> ZIOS-10391: Increase video and audio duration limits for team accounts

- Wire-iOS/Sources/Components/CompanyLoginFlowOpener.swift
- Wire-iOS/Sources/UserInterface/BlacklistViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/CannotDecryptCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/UnknownMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardPermissionsCell.swift
- Wire-iOS/Sources/UserInterface/Location/LocationSelectionViewController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamInviteTextFieldFooterView.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/BrowserOpening.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/LinkOpener.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/MapOpening.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/TweetOpening.swift
Replaced calls to the deprecated `UIApplication` method `openURL(_ url: URL)`with `open(_:options:completionHandler:)`.
> Fix deprecated method calls

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/Data+HEIF.swift
Non iOS client may be unable to open saved HEIF image file introduced in iOS 11 release.
Convert the file to JPG format for cross-platform compatibility. 
We should review this conversion is necessary in the future when HEIF becomes more popular.
> Fix: Picture with ending .heic

- Wire-iOS Tests/SavableImageTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/SavableImage.swift
App crashes when saving a 0000x20000px image.
When calling:
PHAssetChangeRequest.creationRequestForAsset(from: image)
System crashes if the image has a huge size.
Saving the image with PHAssetCreationRequest.addResource() method to simplify the saving process.
> Fix: crash when saving a 20000x20000px image

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/MediaAsset.m
- Wire-iOS/Sources/UserInterface/Components/UIImage+DownSize.swift
- Wire-iOS/Sources/UserInterface/Components/UIImage+MediaAssert.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
App crashes after confirm sending a large image(42MB, 20000x20000px) from camera keyboard.
When running this line WireImage module's wr_imageDataWithoutMetadata() method, app crash due to memory pressure:
CGImageDestinationFinalize(imageDestination)
After testing with the iPhone 5s, the limitation of image size is around 5000x5000px. If the image the user picked is over this size, request the image with limited size instead.
> Fix: App crashes after confirm sending a large image from camera keyboard

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
* De-register ui menu observers after successful callback.
> De-register ui menu observers after succesfull callback

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/GuestBar/GuestsBarController.swift
* Update guest banner state on conversation changes.
* The conversation change info does not contain the info if it changed because a user inside of the conversation changed (only when they're added or removed), so we have to check the title is accurate manually.
> Update guest banner state on conversation changes

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Collections/CollectionCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionFileCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AdditionalMenuItem.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/LocationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
* Add system to show certain menu items for ephemeral messages.
* Fix crash in collections.
> Add system to show certain menu items for ephemeral messages, fix crash in collections

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/InviteTeamMemberCell.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
The button to manage services appeared white on white in the conversation details.
The button was not updated for the current color scheme via UIAppearance.
Make sure the button (the cell in particular) is functioning correctly.
Additionally updated the logic for initial state of the no results view.
> Fix manage services button color scheme

- Wire-iOS Tests/AppStateControllerTests.swift
- Wire-iOS Tests/AudioMessageCellTests.swift
- Wire-iOS Tests/AudioMessageViewTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
When the user is playing an audio message and a call rings, the audio message is stopped and reset the start position after the user rejects a call.
The AVPlayer is stopped and wiped when the call rings.
Pause the audio player when the call rings, then play it when the call is terminated and it was paused because of the incoming call.
> Fix: Audio message reproduction is interrupted by incoming call

- Wire-iOS/Sources/UserInterface/Components/Views/RoundedBadge.swift
- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
Sometimes archive screen's collection view is not rendered completely or extra space is rendering at the bottom.
The contentSize of the collectionView is incorrect. A possible reason is it is rendering the cell when the viewcontroller's view has zero frame size.
Call collectionView.collectionViewLayout.invalidateLayout() when viewWillAppear to refresh the contentSize.
Fix all breaking constraints when some of  ConversationListCell's subitems have zero-size frames.
> Fix: archive screen rendering issue

- WireExtensionComponents/Views/UserImageView.m
Service users are considered connected, since they are enabled by the team admin. No reason to de-saturate their avatar.
> Do not desaturate the user image for service

- Wire-iOS/Sources/AppState.swift
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewControllerAccessoryType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsSectionSet.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/TextFieldValidator.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangePhoneViewController.swift
Recent Swift version can automatically synthesize `Equatable` and `Hashable` implementation. This PR removes our custom implementations where possible
There are still some cases where we keep custom implementation:
* "Fake" equality by just defining `==` operator on protocols to make it possible to compare them (e.g. https://github.com/wireapp/wire-ios/blob/develop/Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift#L51). It is a bit of a weird pattern, but seems to be used in several places.
* `FontScheme`. We have to define our own `Hashable` because only from Swift 4.2 it gained ability to synthesize `hashValue` for classes/structs with optional properties.
> Equatable and Hashable clean up

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
Undo a constraint fix which causes restore animation of sliding cell stops working.
> fix the missing bounce back animation issue

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Images.swift
- Wire-iOS/Sources/UserInterface/Components/Views/ConversationAvatarView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController+UserObserver.swift
- WireExtensionComponents/Views/UserImageView.h
- WireExtensionComponents/Views/UserImageView.m
- WireExtensionComponents/Views/UserImageView.swift
Profile images were getting purged from the cache fairly frequently.
- `UserImageView`with size  `.tiny` were erroneously downloading the complete profile image
- We weren't downscaling-scaling the profile images thus keeping unnecessarily big images in memory
Scale images based on  the given `UserImageProfileSize`
I also deleted some cases from `UserImageProfileSize` which weren't used anymore.
> Resize user images to the smallest possible size

- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
After several attempts, we still find that the collection view in Archive conversations screen is not refreshed after first loading. Debugging with view hierarchy and found that the cell is not created at all. It seems like an issue of layout and I added collectionView.collectionViewLayout.invalidateLayout() to fix this issue.
> Fix: Archive conversations are not rendered

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ReactionsView.swift
`ReactionsView` is bad for scrolling performance.
`ReactionsView` is re-creating the `UserImageView` and `UIImageView` every time it's configured for a new cell.
Create views once and re-use them.
> Refactor ReactionsView to reuse views when configured with likers

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
We've been also checking the `DeveloperMenuState` flag in the tab bar itself.
> Show services tab on all builds

- Wire-iOS/Resources/Base.lproj/Localizable.strings
The “Full house” dialog title that appears when a conversation reaches the maximum number of participants is a remnant of our earlier informal tone.
This should be revised to adapt to our recent B2B tone.
See https://github.com/wireapp/copywriting/issues/37.
> Update “Full house” dialog title

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/Analytics/CallQualityScoreProvider.swift
Call quality review was tracked using the AVS metric event.
Rename tracking event to `calling.call_quality_review`
> Fix wrong tracking event used for the call quallity review

- Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
Calling into a degraded conversation crashed the app.
The state of the `CallDegradationController` was being set just after initialisation in `CallInfoRootViewController`, whereby it creates the alert view and presents it. Immediately afterwards, the `viewDidLoad` method is invoked, where the alert is presented if it's not already presented. Although we just called to present the alert, it is not yet registered as being presented, so we try to present a second time. This leads to an exception and crashes the app.
Refactor out presenting logic, and ensure that we don't try to present the alert before the view controllers view is loaded.
> Prevent alert being presented twice

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Internal.h
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Private.h
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/WireBridgingHeader.h
App crash when ConversationListViewController creating noConversationLabel.
After moving property noConversationLabel to ConversationListViewController+Private.h, that property is not accessible from the .m file.
Put noConversationLabel in property in ConversationListViewController+Internal.h instead
> Fix: crash for missing method "[ConversationListViewController setNoConversationLabel:]"

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
The automation cannot catch the Mixpanel client ID from the logs.
Not clear, but as the system showed itself fragile, it was decided to write the ID to the file instead.
> Store mixpanel ID to the file for simulator and automation

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/Calling/CallQualityController/CallQualityController.swift
- WireExtensionComponents/Utilities/AutomationHelper.swift
Some automation tests were broken because of the call quality overlay.
We add the `--disable-call-quality-survey` command line switch to allow QA to disable this feature when needed.
> ZIOS-10490: Add flag to disable call quality survey in automation

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
The event whitelisting is not necessary, since all unnecessary events where removed.
> Remove Mixpanel event whitelisting

- Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
When swiping the interactive call overlay on iPad, the top of the conversation list UI showed the accent color (see video in ticket).
This was caused by the status bar overlay that was previously used on iPad. Before we started using the black bar, we were showing a light blur behind the status bar. The top of the conversation list UI was constrained to the bottom of this overlay.
We only showed it when the status bar style switched to `dark`, which happened when displaying the call overlay.
We remove the status bar overlay, because we no longer need it (since we use the dark bar behind the status bar). We update the constrains of the background view controller accordingly.
> ZIOS-10478: Fix visual issue on iPad status bar when dismissing call overlay

- WireExtensionComponents/Utilities/AutomationHelper.swift
There seem to be no reliable way to access device logs from command line (http://openradar.appspot.com/radar?id=4935683009413120). This poses a problem for automation because it contains useful information of what went wrong.
Added a run argument (`listen-for-logs-keyword`) that makes the app start polling clipboard each second for magic string (`paste-logs`). When this string is detected we put content of current log to clipboard. This can then be read by automation effectively bypassing the system log all together.
> Automation: workaround for accessing device logs

- Wire-iOS/Sources/Developer/DebugAlert.swift
- Wire-iOS/Sources/Developer/DeveloperOptionsController.swift
Small follow up to the log recipient changes:
- Instead of sending all logs to devs & AVS & support, give an option for devs only (as normal) or devs & AVS & support
Should help to reduce noise for the recipients.
> Give option to send logs to AVS [skip ci]

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
Self preview would disappear on the first interaction.
- Physics behaviours added multiple times in `viewWillAppear`, which is now called multiple times because we have the. interactive dismissal.
- Physics behaviours were added to early making the configuration wrong.
Only run setup once and delay physics setup to `viewDidAppear`.
> Fix self preview being positioned off screen

- Wire-iOS/Sources/UserInterface/Calling/CallWindow/CallWindowRootViewController.swift
If the user was editing text when the call UI was maximized (from the top overlay or at the initial incoming call), the keyboard was not dismissed and it was covering the call action buttons.
iOS makes the presented modal view controller the first responder and dismisses the keyboard if it returns `true` for `canBecomeFirstResponder`. The call root view controller returned `false` here (the default value).
We explicitly allow the call window root view controller to become the first responder. 
When the active call view controller is presented, the keyboard is dismissed as the call window becomes the first responder. When the call window resigns first responder, the preview input field becomes the first responder again.
> ZIOS-10477: Dismiss the keyboard when maximizing the call UI

- Wire-iOS Tests/CallViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
Remove double tap to switch video fill mode feature after discussed with the design team.
> Remove double tap to switch video fill mode feature

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
Mute button would become out of sync with the actual mute state.
If the interactive dismissal is initiated but aborted `viewWillDisappear` is called which deregisters all notification center observers, which also includes the media manger observer.
Move the registration of the media manager observer to `viewWillAppear` from `init`
> Fix mute button getting out of sync

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift
Send debug calling debug report to calling-ios@wire.com. Remove localization since they all go the same address.
> Update email address when sending calling debug report

- Wire-iOS Tests/CallViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
After Double tap gesture recognizer is removed, tapping Show All has no effect on the call overlay.
Unknown, I had tested this case when both single and double tap gesture recognizers are added.
Undo the tap gesture recognizer and restore the original touchesBegan method.
> undo the tapRecognizer

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Menu.swift
App crashes when long tapping on a ping cell.
MenuConfigurationProperties.additionalItems is nil, crashes when calling its .map method
Unwrapped it before accessing its methods.
> Fix: Crash when long tapping on a ping cell

- Wire-iOS Tests/VideoGridViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
The isMute property of VideoGridConfiguration is not updated immediately and cause the mute indication's incorrection animation.  Get mute status from AVSMediaManager.sharedInstance() instead.
> Fix: mute indication visibility 

- Wire-iOS/Sources/Components/AudioPlayer/AudioTrackPlayer.m
Audio controls (play/play/skip) were showing up on the lock screen and in control center when on a call.
`AudioTrackPlayer` was registering these actions with `MPRemoteCommandCenter`.
`AudioTrackPlayer` is registering these commands only when it's playing something and deregistering them when it stops.
> Fix audio controls showing up during a call

- Wire-iOS Tests/LicensesLoaderTests.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Services/SearchServicesSectionController.swift
Since tapping a service in the start UI or the "add participants" screen open a details view, we need to add a chevron to the right side of each list item in both screens.
> Fix: add chevron to list item of services

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallWindow/CallWindowRootViewController.swift
If you receive an incoming call (without callkit) and the UI was not already launched, the incoming call screen will not appear.
The app is launched in the background without the UI which will then miss the incoming call observers firing.
Check for any ongoing call when the UI has finished loading.
> Fix incoming 1-to-1 call not being visible when app is launched via APNS

- Wire-iOS/Sources/UserInterface/Components/CameraPicker.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
App crashes when sending a video from start UI or saving a video from a conversation.
Swift 2.0 style Selector does not work.
Update with #selector syntax.
> Fix: App crashes when sending a video from start UI or saving a video from a conversation.

- Wire-iOS Tests/CallSystemMessageTests.swift
- Wire-iOS Tests/ConversationRenamedCellTests.swift
- Wire-iOS Tests/MessageTimerSystemMessageTests.swift
- Wire-iOS Tests/ParticipantCellTests.swift
- Wire-iOS Tests/ShareDestinationCellTests.swift
- Wire-iOS Tests/Utils/UITableViewCell+Snapshot.swift
- Wire-iOS.xcodeproj/project.pbxproj
Clean up the duplicated prepareForSnapshots method in the cell snapshot tests.
> Fix: clean up cell snapshot tests

- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchResultCell.swift
The count badge in collections search was too wide and the label is not entered:
The width of the badge is ambiguous because the trailing constraint of the badge's label to the container view is not activated. (The badge is collapsed by default, deactivating the trailing constraint)
Uncollapse the badge in order to activate the missing constraint.
> Fix ambiguous contraints

- Cartfile
- Cartfile.resolved
- Wire-iOS/Sources/Helpers/String+WireLocales.swift
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+SendButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/MessageDraft.swift
Any mentions inserted in markdown editing mode would have the wrong offsets.
Offsets didn't take the additional markdown syntax into account, which is inserted after the attributed string containing markdown attributes is parsed.
Calculate the offsets after the text has gone through the markdown parser. To make this possible the markdown parser now keeps any non-markdown attributes in the resulting string.
> Calculate correct offsets for mentions when editing in markdown mode

- Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
It is possible to drag & drop mentions in messages which doesn't make sense.
Disable drag & drop for links which refer to mentions.
> Disable drag & drop for mentions

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Undo the video button removal.
> Fix: Put video button at the last of the input bar

- Wire-iOS Tests/Mocks/MockConversation+TimedMessage.swift
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Components/AccentColorChangeHandler.m
- Wire-iOS/Sources/Managers/ColorSchemeController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Mentions.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIColor+Accent.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIColor+WAZExtensions.h
- Wire-iOS/Sources/UserInterface/Helpers/UIColor+WAZExtensions.m
- Wire-iOS/Sources/UserInterface/MarkdownBarView.swift
- WireExtensionComponents/Utilities/ColorScheme.h
- WireExtensionComponents/Utilities/ColorScheme.m
Self mention background color is not updated after my accent color is changed.
Used ColorScheme.default.accentColor for the background color, which is not updated after accent color is changed.
Use UIColor.accent() instead.
This PR also removed the ColorScheme accentColor getter. UIColor accentColor property is translated to Swift to mark it as non-optional.
> Fix: self mention background color is not updated

- Wire-iOS/Sources/UserInterface/Components/Views/Mentions/MentionsTextAttachment.swift
If we mention someone with long name we should avoid wrapping it to a new line. 
Replace all regular spaces with non-breaking space. Message cell will wrap the mention to new line only if it doesn't fit full next line.
> Adding non-breaking space in full name

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
The app could crash when opening a push notification on iOS 12.
This was caused by Mixpanel's "automatic push tracking" feature. It sent a `campaign_received` event to Mixpanel every time the user opened a notification (the feature is on by default). To work, it swizzles a method from `UNNotificationCenter` to inject tracking code; but there happens to be a crash in their swizzling implementation.
We disable this push tracking feature, as we are not making any use of it.
> ZIOS-10608: Fix crash when opening push notification

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler+TextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
We have a button that should open the mentioning flow. Because we use regexps for parsing the string and find mentions we need to add additional spaces if needed. Also the cursor must be in the correct position after adding the @ sybmol.
To illustrate (`|` is the cursor position):
* `AB|CD` -> `AB @| CD`
* `AB| CD` -> `AB @| CD`
* `AB |CD` -> `AB @| CD`
> Connect @ button to start mentioning flow

- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
The order of importance for the subtitle items in the conversation list is wrong.
Current one is mentions, messages, pings, missed calls. It should be mentions, missed calls, pings, messages.
> ZIOS-10592: The sequence of subtitle items is wrong

- WireExtensionComponents/Utilities/ColorScheme.m
The draft was reset when putting the app into the background and back into foreground again.
Upon entering the foreground the notification system is activated and all observers are called so they can setup the initial state. In this case color scheme controller was observing the self user and triggering a reload of the UI if the accent color changed. Due to this bug this was always happening and since the draft wasn't saved (happens when editing ends) it was being reset.
Use `isEqual` instead of comparing instances.
> Fix draft being reset on upon entering foreground

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
We change the copy of ephemeral messages and mentions in the list UI (outside of summary):
**New description text chart**
| | 1:1 Chat | Group Chat |
|----------|--------|-------------|
| Message  | Sent a message | Someone sent a message |
| Mention   | Mentioned you | Someone mentioned you |
We also remove the name of the user that sent the ephemeral message from the description.
> ZIOS-10619: Update copy for ephemeral messages in list UI

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
Mention tokens are represented as image text attachments. This means that by default, the user was able to long press the mention in the input field and save the image to the camera roll.
In the Conversation Input Bar, we specify that we don't allow the text view to interact with any image attachment.
> ZIOS-10618: Do not allow saving the mention from the input field

- Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
Sometimes tapping on a markdown link the alert with URL would not be shown.
When a link is tapped we check if this is a markdown link. Markdown attributes are an option set and we were checking that attributes contains only a link. It would fail if there would be more attributes together with the link. 
Change the comparison method.
> Correctly check if Markdown contains a link

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
Sometimes when inserting a mention the app would crash.
It was not reproduced, but crash log shows out of bounds access when inserting space symbol.
Rewrote this place in a safer way, but appending space to the mention text attachment if needed.
> Fix crash when adding mention

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
Before this PR, pings were shown as "Someone sent a message". We now give a dedicated copy for them, as "Someone pinged".
> ZIOS-10619: Show correct description in list UI for ephemeral ping

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+SendButton.swift
Sending a message while in the mention suggestion flow would not cancel the mention suggestion.
Aways dismiss the mention flow when sending a text message.
> Dismiss mention flow upon sending a text message

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
When forwarding a message we should remove mentions because those users might not be part of the target conversation.
> Stripping mentions when forwarding message

- Wire-iOS Tests/MentionsHandlerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler+TextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/NSAttributedString+Space.swift
After tapping @ button and deleting the symbol the text field would still have content (i.e. placeholder text would not appear).
After tapping @ symbol we would unnecessary insert spaces before and after @ symbol. It would lead to a problem (`|` is cursor position and `_` is space):
1. Tap @ button - `_@|_`
2. Delete once - `_|_`
3. Delete twice - `|_`
4. Delete mamy more times - `|_`
Basically we would not able to delete contents of text field because there is whitespace after the cursor.  
Do not add whitespace when there is no text before/after the @ symbol.
> Fix issue of input field still having content after deleting @

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/UIAlertController+OngoingCall.swift
- Converted the action sheet shown while calling and switching between accounts into alert.
- Fixed copy
> [Calling] Fixed type and copy of account switching alert controller

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
On the bluetooth keyboard the user might expect to insert the mention when pressing enter or tab.
> Create mention on enter or tab key

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView+Recognizers.swift
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
When we insert a mention in input field it becomes a text attachment. Tapping on it would put cursor either before or after the mention. A better approach UX-wise would be to select the mention when tapping.
There is no useable delegate method for tapping on text attachments so we use the same approach as in 
`TokenizedTextView` and attach a gesture recognizer on whole input bar. The tap position is then used to character index on text view.
> Tapping on mention in input field should select it

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
We agreed with design that pressing enter to insert mention should only work on iPad. Additionally, on iPad user can override the behavior by pressing Shift+Enter.
> Append mentions from keyboard only on iPad

- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView+Recognizers.swift
Interraction with input field was not working as expected: only double tap would make it active, changing selection would not work etc.
In #2725 we added a `UITapGestureRecognizer` to the input field and it was blocking other recognizers from working correctly.
Allow other recognizers to detect touches simultaneously.
> Fix interactions with input field

- Wire-iOS Tests/MentionsHandlerTests.swift
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/Mentions/MentionsTextAttachment.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
The input bar does not respect the selected markdown setting when rendering mentions.
Mentions in the input bar are text attachment which have a fixed font.
Retrieve the correct from the associated text storage within the text attachment.
> Respect markdown attributes for mentions in the inputbar

- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
Performing cut action on mention would fail the cut action completely
When cutting text replace the mention with plain text similar to the copy action.
> Fix cut action with mentions

- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
When editing a message the font would be much smaller than usual.
Apply default attributes from the text view to the contents.
> Apply correct text attributes when editing message

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
It was caused by not calling a completion handler when animation is finished.
> Fix: keyboard doesn’t go up when editing a message

- Wire-iOS Tests/MentionsHandlerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/UITextView+Replace.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
When trying to insert a mention in the middle of the text the cursor would jump to the very end.
Setting `attributedText` property for `UITextView` resets the cursor position to be at the end of text. 
There is a method `UITextView.replace(range:with:)` that preserves the cursor position, but it takes `String` as a parameter. This PR adds a similar method for `NSAttributedString` that tries to preserve the cursor position by putting it to the end of the replacement string.
> Preserving cursor position after inserting mention

- Wire-iOS Tests/CheckmarkCellTests.swift
- Wire-iOS Tests/ColorSchemeControllerTests.swift
- Wire-iOS Tests/ConversationCell/TextMessageMentionsTests.swift
- Wire-iOS Tests/ConversationCellTests.swift
- Wire-iOS Tests/DestructionCountdownViewTests.swift
- Wire-iOS Tests/DeviceManagement/ClientListViewControllerTests.swift
- Wire-iOS Tests/DeviceManagement/ProfileClientViewControllerTests.swift
- Wire-iOS Tests/GroupDetailsTimeoutOptionsCellTests.swift
- Wire-iOS Tests/GroupParticipantsDetailViewControllerTests.swift
- Wire-iOS Tests/SearchResultLabelTests.swift
- Wire-iOS Tests/UserSearchResultsViewControllerTests.swift
- Wire-iOS Tests/Utils/ZMSnapshotTestCase+Swift.swift
- Wire-iOS/Sources/Managers/ColorSchemeController.swift
Conversation message's text color was not updated after the color scheme change.
After this change: https://github.com/wireapp/wire-ios/pull/2741
We now immediately re-create the markdown style after we get the change notification. Before we just nullified the old style. However the notification is fired before the color scheme is actually changed, therefore we still pick the old color when we get the notification.
Post the notification after the change.
> Update paragraph style after color scheme change

- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController+Animation.swift
- Wire-iOS/Sources/UserInterface/Registration/NavigationController.m
When using the custom keyboard, sometimes users cannot proceed with the sign in, since the UI is cut form the bottom, so the continue button is not visible.
The registration and log in flow is designed to help user easily fill the account details. In order to achieve this, we want to persist the keyboard state while user is navigated from one page of registration to another. 
One of the ways to achieve this behavior is to create the temporary responder view that would retain the keyboard up during the transition (see `NavigationController.takeFirstResponderDuringTransition`).
In iOS, it's forbidden to use the custom keyboard to enter the secure data, such as the password. What happens in case of going from the email sign in screen to restore back up screen is the following:
1. The user is …
> Sign in screen is shifted when using the custom keyboard

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewModel.swift
allow guest and service toggle has no effect after toggling if no guest or service in conversation.
Missing handling in configuration.areGuestOrServicePresent == false case
clean up the logic and make sure all the cases calls _setAllowGuests()
> Fix: Guests should not be shown in Add People list after guest access is disabled

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Missing "Guest is present" text in the grey bar after "allow guest" switch is on in conversation detail screen
The state of guestsBarController is not updated in that situation.
Call updateGuestsBarVisibilityAndShowIfNeeded in all cases, which also updates its label's text.
The animation of the guest bar reveal and dismissal does not run as expected when it is behind the conversation detail on iPad. I will check it later.
> Fix: Missing "Guest is present" text in the gray bar after "allow guest" switch is on in conversation detail screen

- azure-pipelines.yml
When making a PR that merges to release branch the CI was not triggered.
The CI is run when source or target branch is listed in trigger branches. 
Remove the trigger branches - it will build commits in all branches (even without open PRs)
> Fix: CI is not triggered when base is not develop

- Wire-iOS Share Extension/Info.plist
Share Extension was not loading link previews from `http`-based URLs. I've added the `NSAppTransportSecurity` flag inside the Share Extension Info.plist file, so now it reflects the same settings as the main container.
> ZIOS-10545: Added allows arbitrary loads flag in the Share Extension Info.plist

- Wire-iOS Share Extension/ShareExtensionViewController.swift
@billypchan reported an issue about unauthenticated accounts inside the list of the accounts list of the Share Extension. No message was shown during the selection of the desired account inside `ShareViewController`. I was not able to repro that, but I've tried to improve the sharing process.
The user was not able to share content if the current account was logged out. I'm now checking if there are other available authenticated accounts that are able to share, and I select automatically the first one available. Now, the "You're logged out" screen is visible only if there are no other available authenticated accounts.
> ZIOS-10701: Added more controls over unauthenticated accounts in Share Extension

- Wire-iOS/Sources/Authentication/Authentication/Event Handlers/Team/TeamEmailVerificationErrorHandler.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+Errors.m
When registering a team or a personal user with phone, if the user put the wrong code, we would show the "Please try again" error message. Instead, we need to show the "Please enter a valid code" prompt.
We check for the `ZMUserSessionInvalidActivationCode` error when creating the alert copy for the invalid code, and for the correct email verification step in the team event handler.
> ZIOS-10733: Show correct error message for invalid activation code

- Wire-iOS/Sources/Authentication/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
Upon registration, team users were not assigned a random profile picture, but it was working for personal accounts.
The initial sync event handler was not performing the `assignRandomProfileImage` action if there was a next step to transition to, which is the case for team registration only (the next step is the invite flow).
We make sure that it always is performed if `isRegistered` is true. We also remove the code for handling email, because it's handled in `AuthenticationNoCredentialsErrorHandler`.
> ZIOS-10732: Fix random profile picture assignation for team users

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Authentication/Authentication/Event Handlers/Post-Login/Registration Error/AuthenticationNeedsReauthenticationErrorHandler.swift
- Wire-iOS/Sources/Authentication/RegistrationPersonal/RegistrationRootViewController.m
Following the login refactor, we identified two issues: 
1. When the user logs in with phone number but the account has an associated email, we didn't pre-fill the email.
2. When the user cancels giving the passcode, we actually selected the same account that needs the passcode, so we ended up on the skeleton list and the user was stuck.
1. In the event handler for the needs password to register client error, we didn't use the error user info key to extract the login credentials 
2. When the user tapped the cancel button, we selected the first authenticated account, which is was in fact the account that could not be registered (it is authenticated, because it has an access token). Now, we look for the first authenticated account that has different credentials and switch to it.
> ZIOS-10730: Fix email login prefill after logging in with phone

- Wire-iOS/Sources/UserInterface/Components/Views/UserImageView/BadgeUserImageView.swift
Start UI was crashing when trying to show the top people line.
In `TopPeopleCell.createUserImageView` we have the following code:
```c
self.badgeUserImageView = [[BadgeUserImageView alloc] init];
```
Seems like the `BadgeUserImageView` cannot be alloc-init'ed from Objective-C.
I was really surprised by that, since me and Obj-C compiler knew that any object inherited from NSObject has init method.
The solution is to declare the init method in swift.
> Declare default init implementation for ObjC

- Wire-iOS/Sources/Helpers/syncengine/UserClient+RemoveTask.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/RequestPasswordViewController.swift
The type `Result` is more specific to the given use case.
> Remove type Either in favor of Result

- Wire-iOS Tests/Mocks/MockUser.h
- Wire-iOS Tests/Mocks/MockUser.m
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
Test crash when running SelfProfileViewControllerTests' setup() due to MockUser missing new usersCompanyLogin property.
> fix: update mock user for usersCompanyLogin property

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
~~What is dead may never die~~, what is not set cannot be reset. SSO users have no password, so they cannot reset it.
> Do not show reset password button for SSO users

- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Tapping on a mention notification for a conversation that is already loaded will not scroll to that mention.
When a conversation is selected and loaded from the conversation list, `ZClientViewController` checks to see if the `ConversationRootViewController` for the given conversation exists. If it doesn't (because the conversation is not already loaded, it will create this root view controller and all of its sub view controllers, eventually scrolling to a particular message.
However, if the conversation already exists, then the root view controller already exists, and so nothing special happens.
In order to scroll to a particular message for an existing `ConversationRootViewController` object, we need to dive down into the hierarchy to find the view controller containing the `UITableView` …
> Add methods to scroll to message from ZClientViewController

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Reply.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
- The conversation used to have the logic to scroll the content to the bottom when user is focusing on the input field. This should not happen when user is editing the message or is replying to the message.
- ~~Fixed delegate call `delegate?.conversationCell?(self, didSelect: .save, for: self.message)` -> `delegate?.conversationCell?(self, didSelect: .save)` (message is inferred from the cell now).~~
- Fixed jumping to the cell (row index vs section index).
> Do not scroll conversation to the bottom when replying

- Wire-iOS Tests/ConversationCellActionControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
Before, it was possible to reply to a message that failed to deliver.
We check for the delivery status in the `canReply` method.
> ZIOS-10812: Remove reply option for unsent message

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationMessageToolboxCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
When tapping the like, resend, delete or likers button on the new message toolbox cell, nothing was happening.
The `ConversationMessageToolboxCell` was not a delegate of the message toolbox. We now inject the appropriate cell delegate and perform the actions when the toolbox requests them.
> ZIOS-10815: Fix actions not performed for message toolbox cell

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter+DataSource.swift
App would crash on liking a message
If you like a message using the new section based cells the action would send the toolbox cell as the originating cell, the like action would them attempt find the index path of this cell which doesn't exists because it's wrapped in an adapter cell.
Look up the index path by the message instead.
> Fix crash when liking a message

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Opening files doesn't work 
We were looking up the selected message by row instead of section, this usually resulted in trying to open the last message in the conversation.
Look up by section
> Use section instead of row to look up message upon selection

- Wire-iOS Tests/ConversationReplyCellTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationQuoteCell.swift
Accessibility identifiers are needed for automation on the quote cell. This is the map of the identifiers we added:
- Container = `ReplyCell`
- Sender name = `original.sender`
- Message edited icon = `original.edit_icon`
- Timestamp = `original.timestamp`
- Text = `quote.type.text`
- Location = `quote.type.location`
- Audio = `quote.type.audio`
- Image = `quote.type.image`
- Video = `quote.type.video`
- File = `quote.type.file`
- Invalid quote = `quote.type.unavailable`
> ZIOS-10833: Add accessibility identifiers for quote

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Reply.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
When replying to a message, and the user is removed from a conversation, the keyboard and the reply composer were still displayed.
When the conversation becomes read only, we resign first responder on the input bar and remove the composing view.
> ZIOS-10819: Dismiss keyboard when the conversation becomes read only

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter+DataSource.swift
If a message was edited while showing the timestamp (message is selected) it would crash due to a tableview update exception.
When editing a message we change the nonce which means we will re-create the section controller since they are cached by nonce. The newly created section controller would be missing the timestamp cell since the selection was configured afterwards and thus crash.
Add the selection state to the constructor of the section controller.
> Fix crash after editing message

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationLinkPreviewArticleCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
Link preview weren't responding to taps or long presses.
ArticleView delegate wasn't set
- Set delegate 
- Remove long tap recognizer since that's handled by `ConversationMessageCellTableViewAdapter`
> Fix link previews not responding to interaction

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationMessageToolboxCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCellTableViewAdapter.swift
When the user long pressed a mention or a link, it was not triggering the menu with the message actions.
The long press gesture recognizer of the text view was cancelling the long press gesture from the cell container; and we were not handling the delegate method to handle link press.
We manually request showing the menu to the parent cell when the text field reports that a link was long pressed.
> ZIOS-10831: Show menu when user long presses mention or link

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
We accidentally removed the method override for `menuConfigurationProperties` in the video message cell. Which caused the long press handler to return without trying to present the menu, because there was no configuration.
We restored the missing method, and added checks in other tap gesture recognizers to prevent tap handling (for example, to prevent the link to be opened when the user taps to dismiss the menu).
> Fix showing the menu controller for a video message

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
Text messages containing only a link would display a link preview and an empty gap above it.
We we always create a text message cell even if there's not text content to display.
Conditionally create text message cell.
> Only add a text message cell if the message has text content to display

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/BurstTimestampTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationMessageToolboxCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/EphemeralCountdownView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationPingCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCellTableViewAdapter.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+BurstTimestamp.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Introduce `willDisplay`/`didEndDisplaying` on the `ConversationMessageCell` which the cells can use to start/stop timers/animations.
- Hide ephemeral timer for pings
- Refactor burst timestamp and ephemeral countdown to use the above mentioned method to start and stop the timers.
> Re-factor timers in cell

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/EphemeralCountdownView.swift
Ephemeral pie chart timer wouldn't start sometimes
The ephemeral pie chart animation only starts if it's not currently already animating. We didn't remove the animation before re-using the view so it only worked once per cell instance.
Clear all animations before attempting to start the pie chart timer.
> Fix ephemeral pie chart animation not working

- Wire-iOS/Sources/UserInterface/Components/MessagePreviewView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ReplyComposingView.swift
We would hit an assertion if a video message got deleted while we were composing reply to it.
The `MessagePreviewView` is observing the quoted message for changes but if the message gets deleted it will run into an assertion since it can't determine the message type anymore.
Don't update the `MessagePreviewView` when a message gets deleted.
- Also fixed a similar issue when a message gets deleted in the conversation, where we were briefly showing the "unknown message" cell.
> Fix when message gets deleted while composing reply

- Wire-iOS/Sources/UserInterface/Components/Views/UITableView+Scrolling.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UpsideDownTableView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter+DataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
We want to always show the message that was just sent from this device, even if user was looking on the older messages in the conversation history.
Message window observer is going to tell us if the new message is coming into the window, so we can check if this is the message that was just inserted.
Unfortunately the table view is showing the really weird behaviour w.r.t. scrolling position. Even if the position was set from the code, when some other part of the code is trying to enumerate the cells visible the table view layout is kicking in and moving the viewport back to the initial position.
The original fix is to blindly block the table view to accept any scroll position for the period of time.
> Always show the message just sent

- Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
For a message containing only a markdown link, it's very hard to open the action menu since it's interrupted by the open link alert.
Don't perform the link action if the menu controller is visible.
> Prevent link action if menu controller is visible

- Wire-iOS/Sources/Components/AudioPlayer/AudioPlaylistViewController.m
- Wire-iOS/Sources/Components/AudioPlayer/AudioTrackViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationSoundCloudAttachmentCell.swift
Soundcloud cells where unable to play the tracks.
The view controllers backing the cells where missing the reference to the player.
It turned out that the `ConversationSoundCloudAttachmentCell.init` was not called, since the `ConversationSoundCloudAttachmentCell.init(frame:)` was called instead, where we just create the backing controller with alloc-init.
Changed the default implementation of player controllers to grab the default player, if they are created with alloc-init.
> Correctly pass the player to the soundcloud controllers

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Reply.swift
If conversation had a draft with a quote it was impossible to dismiss the keyboard.
We would call restore the reply composer form the draft in `viewWillAppear` and make the input bar first responder. This is trigger when the user dismisses the keyboard.
Restore the reply composer in `viewDidLoad` and don't make it first responder.
> Don't become first reponder when restoring quote from draft

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/ZMConversationMessage+Date.swift
Separate localization string "Original message from %@" for German for the cases the timestamp is a date or a time in today.
> Separate localization string "Original message from %@" for German

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
We were crashing when trying restore a draft with quote which has been deleted.
The `ReplyComposingView` is asserting if the quoted message can't be be presented.
Don't attempt to restore deleted quotes.
> Fix crash when trying to restore draft quote which has been deleted

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
When the user was quoting a long message and they tapped the composer, we would scroll to the middle of the cell, which does not show the beginning of the original message.
Scroll to the top of the message.
> ZIOS-10871: Scroll to top of message when opening quote

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Unread dot was not always displayed for unread messages
- Burst timestamp was not always displayed for the first message of the day
- Sender should always be displayed if the burst timestamp is displayed.
> Fix logic for when the sender and burst timestamp are displayed

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.m
When the user opened a conversation with unread messages, we'd scroll them to the top of the last cell in the first unread message section (ex: the link preview) instead of the top of the first cell in the section (ex: the burst timestamp). 
Fix the index of the cell we scroll to in the section to be the last cell's index, because the table view is upside down.
> ZIOS-10877: Fix position of scroll when opening a conversation with unread messages

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
When the user opens a search result that isn't at the bottom of the viewport, it would scroll the last cell of the message section in view. While this works in some scenarios, it was only scrolling the message toolbox into view if the toolbox was open.
Like we did for scrolling to the latest unread message in #2918, we always scroll to the first cell in the section, which corresponds to the cell with the last index in the section in the context of upside down table view.
> ZIOS-10871: Searching for a message in the collection scrolls to the message toolbox

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
Failed to decrypt message were having a toolbox
Never show the toolbox for system messages.
> Never show toolbox for system messages

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/CellComponents/SenderNameCellComponent.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationQuoteCell.swift
The "Edited" icon was not visible to Voice Over and automation inside a quote displaying an edited message.
Add an accessibility label and make the element accessible when the label is set.
> Fix missing edited icon accessibility identifier

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCellTableViewAdapter.swift
We were crashing when re-using a `ConversationSystemMessageCell`.
The crash happened due to a failed cast from `ConversationMessageCellDescription<ConversationMessageTimerCellDescription>` to  `ConversationMessageCellDescription<ConversationVerifiedSystemMessageSectionDescription>`.
This happens because both these cell description use the same view `ConversationSystemMessageCell` which is what's currently used as the reuse identifier.
Use the name of the cell description as the reuse identifier.
> Fix overlapping reuseIdentifiers if cell descriptors share the same view

- Wire-iOS Share Extension/UnsentSendable.swift
Sending large PDF files crashes the Share Extension.
The Share Extension is being terminated by the OS due to excessive memory usage. On iOS12 it appears that memory budget for the Share Extension is 120MB. 
The reasons for high memory consumption vary, but the first main issue with PDF's is the generation of the preview. When I send a particular PDF (33MB) with an image embedded in the cover page, the preview generation allocated about ~350MB on the heap. These allocations are taking place in `CoreGraphics`.
A second cause for high memory consumption is when we encrypt the file data before sending. The problem is that we have the file loaded in memory while we create an encrypted copy. This effectively duplicates the amount memory being used.
I spent some time looking for ways to …
> Don't generate PDF previews in Share Ext

- Scripts/remove-bitcode.sh
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire Share Extension.xcscheme
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/WireExtensionComponents.xcscheme
- Wire-iOS/Resources/Configuration/Share Extension/Share-Extension-Base.xcconfig
- Wire-iOS/Resources/Configuration/Warnings.xcconfig
After #2941 was merged the share extension would not launch.
The extension could not launch with error:
```
dyld: Library not loaded: @rpath/WireExtensionComponents.framework/WireExtensionComponents
```
This means that it could not locate `WireExtensionComponents.framework`. 
After comparing the configuration before the changes it seems we missed adding one entry to `LD_RUNPATH_SEARCH_PATHS`. 
The framework is located in `Wire.app/Frameworks/WireExtensionComponents.framework` and the share extension lives in `Wire.app/Plugins/Wire Share Extension.appex`. 
When it is launched it would only try to look inside its own `Frameworks` folder and could not find `WireExtensionComponents.framework` because it's located inside main app . Adding `@executable_path/../../Frameworks` fixed the issue. …
> Fix: share extension fails to launch

- WireExtensionComponents/Utilities/ColorScheme.m
App hit an assertion if you account were using violet accent color.
Replace `=` with `<=` to also include the max color in the valid range of colors.
> Don't assert on violet color by fixing off by one

- Scripts/remove-bitcode.sh
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire Share Extension.xcscheme
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/WireExtensionComponents.xcscheme
- Wire-iOS/Resources/Configuration/ExtensionComponents/ExtensionComponents-Debug.xcconfig
- Wire-iOS/Resources/Configuration/Project-Debug.xcconfig
- Wire-iOS/Resources/Configuration/Share Extension/Share-Extension-Debug.xcconfig
- Wire-iOS/Resources/Configuration/Tests/Tests-Debug.xcconfig
- Wire-iOS/Resources/Configuration/Warnings.xcconfig
- Wire-iOS/Resources/Configuration/Wire-iOS/Wire-iOS-Debug.xcconfig
- fastlane/Fastfile
We were having some issues after #2941 because configuration was renamed to Development. When building with other frameworks dragged in it would not be found because they are in "Debug" folder inside build products, but the app is being built in "Development"
> Revert configuration name back to Debug

- Wire-iOS/Sources/Components/ImageResourceView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationImageMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+SaveImage.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
1. The image is not removed after the message expires (ZIOS-10912)
2. The app crashes when saving an image (ZIOS-10911)
3. The old image was displayed for a short time when reusing the cell in scrolling (ZIOS-10913)
1. We were not removing the image when the message expires.
2. We were casting the cell to the old `ImageMessageCell` type while saving.
3. When setting the image resource, we were not removing the outdated one.
1. When the message expires, set the image message resource to `nil`.
2. Pass `UIView<SelectableView>` to the action handler, as both new and legacy cells conform to this protocol. Use the selection view to perform the image save animation.
3. Set the image resource to `nil` before we start fetching the new one.
> Image message cell fixes

- Wire-iOS Tests/DismissalTests.swift
- Wire-iOS Tests/Utils/ZMSnapshotTestCase+Swift.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/UIViewController+Dismiss.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
When the user tapped to reveal a message, or tapped on a search result, nothing happened and the collection wasn't dismissed as expected.
In #2956, we introduced code that checks if the collection is already dismissed before running the reveal action, so we don't attempt to dismiss the collection view controller again.
This was necessary because the fullscreen image is responsible for dismissing itself – which means the action handler would be called on the collection controller after it was is dismissed.
However, it turns out the variable we checked to see if the view controller is presented (`isBeingPresented`) wasn't the right one, it only indicates if an animation is running. The view controller was never dismissed because of this mistake.
We were also checking the wrong action for …
> ZIOS-10935: Fix dismissal of collection when revealing

- Scripts/download-assets.sh
The CI would fail pulling updated configuration repository because there are uncommitted changes.
When we build custom app versions we copy files over to the configuration folder. Because we don't wipe workspace before each build there might be some leftover files from previous run that would prevent `git pull` from working.
Stash changes before pulling. We could simply delete the folder or `git reset`, but when running on local machine we might want to retrieve the changes we made in configuration.
> Stash changes in configuration folder before pulling

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationImageMessageCell.swift
Ephemeral timer was not activated after receiving images from another user.
This is because of the ephemeral timer that was fired before the complete download of the image inside `willDisplayCell()` and failing the condition on `startDestructionIfNeeded()` (`ZMAssetClientMessage+Ephemeral:64` from Data Model).
I've added a call to `startDestructionIfNeeded()` after downloading the image.
> ZIOS-10940: fixed issue with ephemeral images

- avs-versions
New AVS 4.8 with internal refactoring. No visible changes to the outside.
> Bump AVS to 4.8.

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/GroupDetails/Cells/GroupDetailsDisclosureOptionsCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Cells/GroupDetailsReceiptOptionsCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Cells/IconToggleCell.swift
Assign accessibilityIdentifier to GroupDetailsReceiptOptionsCell's UISwitch.
Give a proper name to GroupDetailsDisclosureOptionsCell's file.
> Assign accessibilityIdentifier to GroupDetailsReceiptOptionsCell's toggle

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/ZMConversationMessage+Date.swift
- Wire-iOS/Sources/Helpers/syncengine/Message+UI.h
- Wire-iOS/Sources/Helpers/syncengine/Message+UI.m
- Wire-iOS/Sources/UserInterface/Collections/NoResultsView.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/Tab.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageActionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsContentViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsDataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/Location/ModalTopBar.swift
The message details screen was not accessible for QA or screenreader users.
We add support for accessibility actions in message cells: now, VoiceOver users can select a cell and swipe up and down and double tap to trigger an action, instead of using the menu controller – which was not accessible at all.
In addition, we:
- Add correct accessibility IDs for QA
- Improve accessibility labels and values (ex: spell out the date in the timestamp in the message details screen, instead of saying "slash")
- Improve general experience (dismiss gesture, close buttons and default selection)
> Improve VoiceOver support in Message Details

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCell/ParticipantsCellViewModel.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m
When a wireless guest joined a conversation through a link, their name was not displayed in the system message cell on iOS clients.
When the system message is inserted, it seems that the name is not fetched yet, which means that the generated cell won’t display a name either.
Prior to the cell refactoring, the update was performed in the message window change observer callback in the message window adapter. However, this part of the code was not updated to include the new section system, which means cells were not reloaded appropriately.
We fix this by using the new section controller logic in the message window observer.
> ZIOS-10939: Fix username not shown for added guest

- Wire-iOS/Sources/Components/Settings+Logging.swift
On internal builds we can turn on logging from various subsystems. The preferences would not get saved and on next launch it would fallback to default set of logs again.
It was caused by two issues:
1. We used `value(forKey:)` which is a KVC method, instead of `object(forKey:)`. This call crashes on simulator but I assume gets optimised out (or returns nil) on release builds 🤷‍♂️.
2. We were casting the result to `Set<String>` when user defaults always return `Array<String>` in these cases, so it was falling back to default values.
Fix issues outlined above.
> Save preference for log tags

- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController.m
When the user has no email client installed, the screen jumps back to contacts overview and no one is invited/contacted. 
The "Please configure your email..." dialog is not shown in this case for the warning "Warning: Attempt to present <UIAlertController: 0x7f9d0aa37800> on <InviteContactsViewController: 0x7f9d0c16dc00> whose view is not in the window hierarchy!
"
Present the dialog in NotificationsWindow.
> Fix: Invite contacts does not work

- Wire-iOS Tests/Authentication/AdaptiveFormViewControllerTests.swift
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
This PR is part of the snapshot tests refactoring tasks.
AdaptiveFormViewControllerTests produces flaky results and it was disabled.
When running a set of snasphot tests for all device sizes, it was updated the constraints set only but may not update its child VCs. 
Wrap the AdaptiveFormViewController in a mock navigation VC as the real use case. Call setOverrideTraitCollection and traitCollectionDidChange to simulate size class update event.
> Fix: AdaptiveFormViewControllerTests flaky fails when running for iPad sizes

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxDataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
The message would not reflect the liked state change when selected.
When the message toolbox state is calculated, we check if it's different from the old one, and update the view only if it is. In case of selected message, we are always showing the timestamp, so the previous state (show timestamp) equals to the new state (show timestamp).
The problem is happening because we also have the heart view that reflects the liked state, and it is not reflected in the enum state.
I added the list of likers to the state, so when it is changing the status is considered different from the previous one.
> Message Toolbox: fix update

- WireExtensionComponents/Info.plist
After merging #2941 we have changed many configuration options and overlooked that CFBundleVersion for WireExtensionComponents is not set in Info.plist.
In the old configurations we had CURRENT_PROJECT_VERSION build parameter set which is not present in new configs. It was always set to 1.
Internal framework version number is not important, setting it to 1 to make it similar to original implementation.
> Fix: framework CFBundleVersion is not set

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationAudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationVideoMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationFileMessageCell.swift
The `isAccessibilityElement` setting on video, file and audio cell containers were causing the subviews not being accessible from the inspector, even if they had proper IDs setted. I've removed those assignments.
> ZIOS-10914: Removed isAccessibilityElement from video, file and audio cells container

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxDataSource.swift
The ephemeral timer took the priority over the delivery state string, now they are displayed together.
> Show the delivery information for ephemeral messages

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Sentence cased setting title and added extra line break in the description.
> Fix read receipts setting copy

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Typing indicator wasn't dismissed after closing the editing input bar in a conversation; this is because `conversation.setIsTyping(false)` was not called after the end of the editing.
> ZIOS-10985: Typing indicator won't dismiss after unsuccessful edit

- Wire-iOS Tests/ConversationMessageCell/ConversationCellSnapshotTestCase.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationMessageSectionControllerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ZMConversationMessageWindow+Formatting.swift
Sender is not shown when sending a message in a conversation after pinging.
I've added the `context.previousMessageIsKnock` condition inside of `isSenderVisible` method of `ConversationMessageSectionController`.
> ZIOS-10967: username/avatar is not shown when a user sends a message immediately after sending a ping

- Wire-iOS/Sources/UserInterface/SelfProfile/DotView.swift
If you were using Wire with multiple accounts the account switcher wouldn't indicate which accounts have unread messages.
The `AccountView` used in the account switcher weren't initialised with a user since it can't observe the self user of a background account. The unread dot was only updated if a user was associated with the `AccountView`.
Re-write the update method to not require a user to be present.
> Missing unread dot in the account switcher

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/UpsideDownTableView+Scrolling.swift
Scrolling to the bottom of the conversation didn't scroll _all the way_ to the bottom.
The `scrollToBottom(animated:)` method was defined on `UITableView` and it set the vertical `contentOffset`  equal to the bottom content inset. The tableview in question is actually an `UpsideDownTableView`, whose bottom content inset is 0 and top inset is 16. Thus, tableview was actually scrolling _almost_ to the bottom, with 16 points still to go. I admit, it's pretty confusing!
So, the top of of a normal `UITableView` is what visually appears as the bottom of the  `UpsideDownTableView`. This means if we scroll _all the way to the top_ of a `UITableView`, then we will scroll _all the way_ to the bottom of an `UpsideDownTableView`. So, I just provided a private extension method to scroll to the top of …
> Fix scrollToBottom method

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationPingCell.swift
App would sometimes crash when determining if it should start the ping animation
App was crashing when initialising a message window.
We don't need create a message window in order to calculate if the ping cell is the last message. Simplify logic for determining if we should start the ping animation.
> Fix crash when starting ping animation

- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
When signing in on iOS 10, the app would crash.
In the `TabBar` view, we are observing the title of a view controller through its tab bar item. When it is deallocated, the observer token is not automatically unregistered on iOS 10 (on iOS 11+, it is unregistered automatically).
Invalidate the observation tokens manually.
> ZIOS-11017: Fix tab bar deallocation crash on iOS 10

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Read receipts toggle was visible for a team user being a guest in a conversation belonging to another team.
Check that the conversation was created within your own team.
> Only show read receipts toggle if conversation was created within your own team

- Wire-iOS/Sources/Authentication/Authentication/Landing/LandingViewController.swift
When building we need to have a possibility to disable team creation and registration. This PR adds a feature flag `ACCOUNT_CREATION_DISABLED` that controls this.
> Added feature flag for account creation

- Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionView.swift
Pending connection conversations were displaying the big user image at the start of the conversation in color.
De-saturation of the user image was turned of for this view.
Allow default de-saturation logic.
> Show unconnected users as desaturated

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationNotificationOptionsViewController.swift
`SectionFooter` was shown twice (two instances at the same origin in the view) in the footer of `ConversationNotificationOptionsViewController`.
That's because the collection view has both header and footer, and we were returning only the footer view inside `viewForSupplementaryElementOfKind:`, without distinguishing between header and footer.
I'm now returning `SectionHeader` for the header and `SectionFooter` for the footer.
> Fixed double instance of footer view in notification options

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationNotificationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationTimeoutOptionsViewController.swift
Removed calls to the dismisser when updating options inside the conversation details (see ticket).
> ZIOS-10764: Removed dismissing of options view controller for conversation details

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/syncengine/Conversation+Participants.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ParticipantsPopover.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+removeUserConfirmationUI.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+KeyboardFrame.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+internal.h
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
After a user is removed from a group conversation, ProfileViewController is not dismissed.
When ProfileDetailsViewController is created in ProfileViewController, profileDetailsViewController.viewControllerDismisser is set to ProfileViewController, it can not dismiss itself by popViewController call.
inject the correct ViewControllerDismisser(ConversationViewController) when creating ProfileViewController. When the remove button of ProfileDetailsViewController is tapped, the ProfileViewController will be dismissed by ConversationViewController.
> Fix: ProfileViewController is not dismissed after the user is removed

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Message.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter+DataSource.swift
It is impossible to delete the message, if it's bottom part is not in the viewport.
The new conversation view system is separating the single message into several cells. So we can have cell for message sender name, for content and for the info footer.
The problem happens because we always presume the cell index 0 is the cell that displays the message content, so if we cannot fetch the 0 cell (it's the bottom most, since the table view is inverted), we cancel any action on the message.
We can calculate the index of the content cell and ask the table view for this cell. It must be visible.
> Allow deleting cells partially off screen

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
When building we need to have a possibility to add services to a conversation.  This PR adds a feature flag ADD_SERVICE_DISABLED that controls this.
> Added feature flag for add service to a conversation

- Wire-iOS.xcodeproj/project.pbxproj
After #3094 we have included `.xcconfig` files in the app bundle. Also there were some build settings defined in the project file that was duplicating what is already defined in `.xcconfig` files.
> Cleaned up build settings

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+SendButton.swift
Added argument to the "Message too long" alert message.
> ZIOS-11088: Added argument to localized string

- avs-versions
New AVS release 4.9.
Change log can be found here: https://github.com/wearezeta/avs/blob/release-4.9/ChangeLog.txt
> Bump to AVS 4.9.

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
App would crash when editing a message
After an edit we attempt to call the method `didFinishEditingMessage:` which doesn't have an implementation.
Restore missing methods.
> Restore missing methods

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
When tapping a reply we would scroll to the wrong message
After the unordered relation change we now need to do a fetch request to find the location of a reply message. The predicate was wrong and was counting all messages sent before the reply message.
Flip the `<` operator.
> Fix scrolling to the wrong message when tapping a reply

- Wire-iOS Tests/Mocks/MockUser.m
Fix the duplicate `@synthesize teamRole` caused by two merges at the same time.
> fix: duplicated @synthesize teamRole in MockUser

- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/RenameGroupSectionController.swift
Rename conversation cell is editable after the screen is reloaded.
The textField's isUserInteractionEnabled property is set again after cell.configure() method is called.
Remove the unnecessary property settings.
> Fix: Partner can edit the Group name after navigate from other views(Notification/People/... button)

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
Conversation table view would get corrupted and show empty messages
If you are scrolled close to the message window when a message gets deleted it could trigger a `didScroll(tableView:` event, which in turn would cause the `fetchLimit` to be extended. Changing `fetchLimit`will cause more messages to be inserted so we would be calling `performBatchUpdates()` inside a  performBatchUpdates() which corrupts the table view.
Delay changing the `fetchLimit` to next runloop.
> Avoid changing fetchLimit inside performBatchUpdate()

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+DataUsagePermissions.swift
Support `SEND_ANONYMOUS_DATA_DISABLED` and `NEWSLETTER_DISABLED` in settings by hiding the corresponding sections if these flags are present.
> Support disabling newsletter and sharing data usage in settings

- Wire-iOS Tests/SettingsTextCellSnapshotTests.swift
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift
Support for feature flag NAME_EDITING_DISABLED. A new property enabled is added to Protocol SettingsProperty and it will be checked in SettingsPropertyTextValueCellDescriptor's featureCell() method.
> Feature flag: possibility to disable editing account's email address

- Wire-iOS/Sources/UserInterface/Settings/DatabaseStatisticsController.swift
In developer settings we have a section that shows how big is your database by counting different kinds of objects. It was not showing the full picture because it used the wrong fetch requests.
Our own `sortedFetchRequest` for some subclasses does validation, e.g. for conversation it ignores conversations with `conversationType = .ignored`.
Use plain CoreData fetch requests.
> Improve database statistics counting

- Wire-iOS/Sources/Analytics/Analytics+OptOut.swift
- Wire-iOS/Sources/Analytics/Analytics.h
- Wire-iOS/Sources/Analytics/Analytics.m
- Wire-iOS/Sources/AppRootViewController.swift
We were keeping too many conversations in memory 
The analytics object was retaining the `Team` object which keeps a list of all team conversations.
Stop retaining the `Team` object.
> Remove unused method on Analytics and avoid retaining Team

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
After opening the audio keyboard and starting a recording, if the user scrolls up into the conversation such that the keyboard is dismissed, it is impossible to reopen the audio keyboard without destroying an active recording.
The only way to reopen the audio keyboard is to tap on the audio icon. However, if a recording is active, tapping the icon will try to hide the keyboard, which will stop the recording.
When opening the audio keyboard, check if a recording is in process. If so, show the keyboard.
> Don’t destroy recording when trying to present open audio keyboard

- Wire-iOS/Sources/Authentication/Authentication/Landing/LandingViewController.swift
If only one account is permitted, we don't want to show the label "Already have an account?" above the login button.
> Hide login hint if only one account is permitted

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
We no longer scroll to the bottom when replying
This behaviour broke during the conversation view re-factoring
Always scroll to bottom before appending a message
> Always scroll to the bottom before sending a message

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ZMConversationMessage+CountDown.swift
The pie count down timer starts before the message is sent successfully.
missing a checking for the message's deliveryState.
Start count down only if deliveryState != .pending
> Fix: destruction pie timer starts before the file message is sent 

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
When we play an audio message we modify the audio session category, this confuses the media manager in AVS since it expects to be in control of the audio session.
I've removed the setting of audio category from `AudioMessageView` and `AudioRecorder` classes.
> ZIOS-11136: Removed setting of Audio Category for audio messages

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
The user can not like the messages.
After https://github.com/wireapp/wire-ios/pull/3139, a guard for optional unwrapping is added and prevents the like action.
Do not guard for optional unwrapping for variable selectedMessage.
> Fix: Cannot like the last message

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Images.swift
When searching for people or scrolling a conversation we would make a save each time we fetch profile picture.
We would wrap the method to request profile picture in `session.enqueueChanges`. This is not needed because the method simply sends a notification.
> Avoid save when fetching profile picture

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+IsVisible.swift
On the conversation list, the destruction timer was starting right after receiving a message in the last opened conversation.
After https://github.com/wireapp/wire-ios/pull/3043, the ephemeral timer is started when calling `configureCell` of `ConversationMessageCell`. But, since the conversation view is instantiated even if not visible from the conversation list, the timer starts anyway.
Since we need to avoid improper calls to `configureCell`, I'm checking if the cell is visible on screen in order to start the timer. I've also added a new `isVisible` extension to `UIView`.
> ZIOS-11147: Ephemeral message gets deleted before reading if active account is running at the foreground

- Wire-iOS Tests/CompanyLoginLinkResponseActionTests.swift
- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/UserInterface/Company Login/CompanyControllerLinkContext.swift
Previously, we had a restriction that disallowed starting the flow if the user wasn't in a list of predetermined states (not logging in or registering). However, it was decided to lift that limitation and allow them to start the flow again if they click the link again.
We remove the check for "incompatible state" when receiving the link. This means that a new authentication coordinator and UI will be created, and the UI will be reset.
> ZIOS-11178: Restart the flow from scratch if the user clicks the link again

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/AppDelegate.m
- WireCommonComponents/AutomationHelper.swift
When launching the app from Appium, the automation suite passes the `-ZMBackendEnvironmentType` flag and sets it to staging.
But we cannot persist this setting, which means that for some tests where we kill the app and launch it from the URL scheme, Safari will not set the environment type back to staging and all further tests will fail.
We introduce a `--persist-backend-type` launch flag which acts as a shortcut to change the backend type in the Settings app.
If this flag is passed, we will set the value from `-ZMBackendEnvironmentType` in the standard user defaults to persist it to the next run.
> Allow automation suite to save backend type in Settings when starting

- fastlane/Fastfile
We currently use home-grown Jenkins scripts for uploading to AppStore. It would be better to use something simpler.
Added two new lanes - one for building app for AppStore and another one for uploading.
It first copies `Appfile` from `Configuration` which should contain all the AppStoreConnect-specific info (team ID etc.)
Build number is taken from environment variable to be compatible with current Jenkins setup
> Added Fastlane script for AppStore upload

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationAudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationImageMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationLocationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationVideoMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationFileMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationLinkPreviewArticleCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
Obfuscated view not shown after an image is expired.
isObfuscated is got from local struct Configuration, it is not updated after message object is updated.
Get the isObfuscated from the message.isObfuscated.
> Fix: Obfuscated view not shown after an image is expired

- Wire-iOS/Sources/AppStateController.swift
- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+PreLogin.swift
- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+Teams.swift
- Wire-iOS/Sources/Authentication/Delegates/AuthenticationCoordinatorDelegate.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+DataUsagePermissions.swift
Previously, we'd show the "Help us make Wire better" alert when the user logs in a second time with the same account on the same device. It was decided to not do this anymore.
We update the logic of checking if the alert needs to be shown. We only show it if you "add a new account" (login / registration).
> ZIOS-11170: Do not show the consent alert if the user logs in again

- Wire-iOS/Sources/Authentication/Backup/BackupRestoreController.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationButtonTapInputHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Post-Login/Registration Error/ClientRegistrationErrorEventHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Post-Login/Success/AuthenticationSuccessEventHandler.swift
- Wire-iOS/Sources/UserInterface/Components/Loading/UIViewController+LoadingView.h
- Wire-iOS/Sources/UserInterface/Components/Loading/UIViewController+LoadingView.m
- Some users were not able to restore a backup with phone number
- It was possible to dismiss the checkmark and restore again
- Do not hide the restore spinner until the initial sync finishes
- Remove the checkmark, as it was misleading: the operation wasn't actually completed until the sync finishes (discussed with @vytis and @typfel this morning)
- Show the spinner even if you ignore restoring, until the initial sync finishes
- Do not show the "add email/password" alert if the user is adding it already
> ZIOS-11112: Improve backup restoring flow

- Wire-iOS Tests/Authentication/AuthenticationInterfaceBuilderTests.swift
- Wire-iOS Tests/Authentication/AuthenticationStateControllerTests.swift
- Wire-iOS/Sources/Authentication/AuthenticationFlowStep.swift
- Wire-iOS/Sources/Authentication/AuthenticationInterfaceBuilder.swift
- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
- Wire-iOS/Sources/Authentication/Event Handlers/AuthenticationCoordinatorAction.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Flow Start/AuthenticationStartAddAccountEventHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Registration/RegistrationActivationExistingAccountPolicyHandler.swift
- Wire-iOS/Sources/Authentication/Interface/Descriptions/ScreenDescriptions/Login/LogInStepDescription.swift
- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationStepController.swift
- When pushing or popping a view controller in the login UI, the bottom buttons could be under the keyboard
- When popping a view controller in the login UI, the content was moved to the center and not adapted to the keyboard frame
- When submitting and email or phone number on the registration screen, the keyboard would appear again after accepting the TOS
- When registering with an existing email, the "log in" button would do nothing
- The wrong button was set as destructive in the logout popup
- Start observing keyboard changes after the view was presented but before we show the keyboard
- Remove multiple calls to the action handling method from email and phone fields
- Fix bottom padding calculation
- Add missing actions to handle logging in from registration
> ZIOS-11188: Fix keyboard jumping and unresponsive button

- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+Backup.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationButtonTapInputHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Post-Login/Backup/AuthenticationBackupReadyEventHandler.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+PushPermissions.swift
Fix the logic for asking for notifications and showing the popover after login. We were doing the check assuming the permissions were not asked for when logging in, which is not the case.
We also enforce asking for permissions before finishing the backup step.
> ZIOS-11195: Fix logic for showing notifications popover

- Wire-iOS/Sources/Authentication/Helpers/CountryCode/CountryCodeTableViewController.m
When searching for a country code inside the signup flow (`CountryCodeTableViewController`), the first item is always shown behind the search bar. I've added a header as padding.
> ZIOS-11173: Search bar overlaps first item inside country code selection

- Wire-iOS/Sources/Permissions/UNUserNotificationCenter+Permission.swift
Sometimes when switching accounts or opening the app the takeover screen telling users to enable notifications is shown when notifications are enabled and working fine.
We have a method that checks if pushes are disabled. It was relying on `UIApplication.shared.isRegisteredForRemoteNotifications` which returns `false` when using notifications through PushKit. In the old authentication flow we were probably registering for pushes on `UIApplication`, but this is not the case with new authentication flow.
Clean up the logic what we treat as pushes disabled - we now check only PushKit permissions. The old code was also treating `.notAuthorized` as `disabled`, but there is no realistic scenario when this could happen (i.e. we don't ask for permissions during registration/login). Even if this …
> Fix: disabled notifications screen shows up even when they are enabled

- Wire-iOS/Sources/AppRootViewController.swift
Call overlay is missing when making a call directly after logging in.
`transitionToLoggedInSession()` is no longer called when transitioning to the authenticated state after logging in. The reason for this is that associated value `completedRegistration` has changed meaning to "added new account".
I don't see a reason why we should not always call `transitionToLoggedInSession()` when transitioning to the authenticated state, so I'll just ignore the value of `completedRegistration`.
- Seems like good idea to rename `completedRegistration` to `addedAccount`
> Missing call overlay after first login

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Push notifications are removed without reading them
Since we switched to using the fetched results controller we now do table view updates in the background, which caused us to update the last read for the currently displayed conversation.
Don't allow updating the last read unless the app is active.
> Only allow updating the last read message if app is active

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Wire-iOS/Sources/UserInterface/Settings/UserRight.swift
The automation suite needs a way to check if a text field is disabled in the settings Account screen.
We change the accessibility properties of the text field cells used in the Accounts screen:
- The accessibility ID of the field will be `(property name)Field` (ex: `UsernameField`) where property name is the text of the label visible next to the field
- If the user can change the value, the element type is "text field" and it can be edited
- If the user cannot change the value, the element type is "static text" and it cannot be edited
We also add the missing logic to check if a user can reset their password (was TODO previously).
> ZIOS-11219: Update accessibility traits for disabled settings text field

- Wire-iOS Tests/AudioEffectsPickerViewControllerTests.swift
- Wire-iOS Tests/AudioRecordViewControllerTests.swift
- Wire-iOS Tests/AvailabilityLabelTests.swift
- Wire-iOS Tests/AvailabilityTitleViewTests.swift
- Wire-iOS Tests/CameraKeyboardViewControllerTests.swift
- Wire-iOS Tests/ChangeHandleViewControllerTests.swift
- Wire-iOS Tests/CharacterInputFieldTests.swift
- Wire-iOS Tests/CollectionsViewControllerTests.swift
- Wire-iOS Tests/ConversationAvatarViewTests.swift
- Wire-iOS Tests/DestructionCountdownViewTests.swift
- Wire-iOS Tests/EphemeralKeyboardViewControllerTests.swift
- Wire-iOS Tests/ImageMessageViewTests.swift
- Wire-iOS Tests/InputBar/InputBarEditViewTests.swift
- Wire-iOS Tests/LocationSendViewControllerTests.swift
- Wire-iOS Tests/NetworkStatusView/NetworkStatusViewControllerSnapshotTests.swift
- Wire-iOS Tests/SearchResultLabelTests.swift
- Wire-iOS Tests/ShareViewControllerTests.swift
- Wire-iOS Tests/TypingIndicatorViewTests.swift
We want to remove the dependency on Cartography. It was used in some test cases.
Replace Cartography by plain constraint creation in tests.
> Remove Cartography from tests

- Wire-iOS Tests/InviteContactsViewControllerSnapshotTests.swift
- Wire-iOS/Sources/Helpers/UIImage+ImageUtilities.m
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsDataSource.m
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController.h
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/InviteContacts/InviteContactsViewController.m
- Wire-iOS/Sources/Vendor/SCSiriWaveformView.m
When analyzing the app, some memory management issues were found:
- We were not releasing the dictionary of properties of an image, which caused a leak
- Some nullability annotations were not respected
- The third-party Siri waveform used CGFloat at the index of a for-loop, which is disallowed
> Grooming: Fix memory errors detected by analyzer

- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
If the keyboard was up when answering a call, it would re-appear on top of the call overlay when doing a swipe gesture.
Swiping down on the call overlay will start the interactive dismissal which calls `dismiss(animated:)`. Even though the dismissal might be canceled UIKit will still immediately attempt to restore the first responder which in this case is the input bar, if the interactive dismissal is cancelled we end up with the keyboard displayed on top of the call overlay.
Since I didn't find way to prevent UIKit from attempting to restore the first responder too early I'll instead make the input bar resign its first responder when presenting the call overlay.
> Resign any first responder when presenting the call overlay

- Wire-iOS/Wire-Info.plist
We want to have URL scheme be dynamic to be able to set it on build time.
Added build parameter `WIRE_URL_SCHEME` which can be overridden.
> Use build parameter for URL scheme

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController+Extension.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
App was crashing when sending a contact request.
This is because `fullUser()` in `ProfileViewController` could be `nil` but it was not considered `Nullable` from the Swift extension.
I've added `_Nullable` to the return type of `fullUser()` and adapted the code.
> ZIOS-11249: Searching for a contact and sending a contact request crashes the app

- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsContentController.swift
Some test code was left and merged with #3215 - no need to force-cast to `ZMUser` because `GenericUser` already provides access to this method.
> Fix: avoid force-cast

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ParticipantsPopover.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsContentViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
When opening the profile details on iPad, the action buttons popover was not visible, and had an unexpected behavior on rotation. (ZIOS-11259 and ZIOS-1160). 
We were not setting the frame of the alert properly when setting up the popover. In addition to that, presenting the popover in a popover had some unintended effects.
- Assign the popover source rect to the bounds of the bottom bar, as we do in the group details.
- Always present the profile / group details in a form sheet. The conversation details button on top was the only place that presented this view as a popover (for ex: clicking on the device degraded message would open the details in a form sheet). This also reduces the number of corner cases we can encounter, such as handling split view changes (from regular to compact and …
> Fix iPad action button frame setting and rotation

- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController+SetupViews.swift
- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController.h
- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController.m
App would crash when tapping the picture while choosing a new profile picture.
We would force unwrap the the optional `delegate` property which was not set.
Remove delegate since it's not used for anything.
> Fix optional unwrapping crash

- fastlane/Fastfile
For internal builds we need to override app configuration by passing a parameter to `setup.sh`.
Added a build type parameter to Fastlane `prepare` stage that copies configuration from predefined folder. https://github.com/wireapp/wire-ios-build-assets should be checked out to project directory before running this step.
> Added build type parameter to prepare step

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationImageMessageCell.swift
App crashed on images with an image size of zero.
Division by zero while computing constraints
Use default value when image size is zero.
> Avoid zero division

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
The text message cell's accessibilityIdentifier is not changed to "Obfuscated message" after the message is expired.
The code was checking local member message.isObfuscated for updating accessibilityIdentifier, but the message object is set to nil after the message is expired and therefore it is not update.
Add an isObfuscated to Configuration struct and update accessibilityIdentifier depends on isObfuscated's value.
> Fix: text message cell - accessibilityIdentifier is not updated after timeout

- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
When registering an account on iPad, the keyboard was showing above the text field to show the name step.
We were not using the correct animation method to replace the displayed view controller in the authentication coordinator. We were performing the transition manually, which caused `viewDidAppear` and hence `showKeyboard` to be called before the view was actually displayed.
Use `UINavigationController.setViewControllers(_:animated:)` directly.
> ZIOS-11262: Fix keyboard adjustment on iPad landscape in registration

- fastlane/Fastfile
The pipeline failed because of a missing method
`changelog_from_git_commits` method is not available when called from a different class.
Move logic to create changelog outside of `Build` class.
Also fixed a small issue that simulator builds were larger than needed. It contained some data left over from running tests. We now clean before building simulator build.
> Fix: build script failed to upload to Hockey

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Debug tool for finding unread conversation was sometimes reporting "no unread conversations" when the badge count was > 0.
`ZMConversationList.conversations(inUserSession:)` is not returning all converations.
Do a fetch request for all conversations.
> Fix search for unread conversations not iterating over all conversations

- fastlane/Fastfile
Playground build in hockey does not contain a real changelog, but should have the branch name it was built from. It was missing.
Wrong variable was used to get the branch name from.
> Fix: branch was not present in changelog when making playground build

- Wire-iOS Tests/YouTube/YouTubeServiceTests.swift
- Wire-iOS/Sources/Components/YouTube/YouTubeService.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/LinkAttachment.m
Fetching the metadata of a YouTube video could fail if it contained a non-ASCII character.
You cannot initialize a `NSURL` with non-ASCII characters. This means that we'd create a request with a nil URL, which failed to fetch the data.
When extracting the ID of the video out of the URL, escape the ID string for use in a query string URL.
> ZIOS-11294: Escape YouTube video ID when parsing URL

- Wire-iOS Tests/Authentication/MockAuthenticationFeatureProvider.swift
- Wire-iOS/Sources/Authentication/AuthenticationFeatureProvider.swift
- Wire-iOS/Sources/Authentication/AuthenticationInterfaceBuilder.swift
We want to hide the "For Companies" button on the login screen for clients that allow only email login. At the same time, we need to keep supporting SSO links and clipboard auto-detect for future proofing.
Add the `allowDirectCompanyLogin` property to the authentication feature provider protocol. It checks whether we allow company login and don't disallow email-only login.
> ZIOS-11286: Add properties to disable "For Companies" login button

- fastlane/Fastfile
We sometimes need building the app with custom AVS version.
Added one more parameter that can be passed to `fastlane prepare` - `avs_version`. This will then override the file that controls which AVS version is fetched when running setup script.
Also added the AVS version information to the app icon.
> Added support for building with custom AVS version

- fastlane/Fastfile
AVS build did not have the extra information on the icon.
We don't have a separate icon for AVS and it could not find one.
Use develop build icon instead.
> Using correct icon for AVS build

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
We would crash if you tapped in the input bar in a conversation after deleting all the messages.
App crashes when attempting to scroll to index 0 which doesn't exist because the table view is empty.
Guard against table view being empty.
> Don't attempt to scroll when table view is empty

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Keyboard doesn't appear when tapping the input bar after long pressing an image.
`isScrolledToBottom` was returning `false` even though we are scrolled to the bottom. This meant that we were trying to scroll the tableview which blocked the input bar from getting the focus.
`hasNewerMessagesToLoad` should be `false` when we are scrolled to the bottom.
> Fix keyboard not appearing after tapping input bar 

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
The sending status wasn't displayed for the last message
`isLastMessage` was evaluated to `false`, which was due to a mix up between `hasOlderMessagesToLoad ` and `hasNewerMessagesToLoad .
Replace `hasOlderMessagesToLoad` with `hasNewerMessagesToLoad`
> Fix sending status

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
App would sometimes crash after scrolling.
Stack trace show that we were force unwrapping an optional when attempting to load older messages.
Remove force unwraps.
> Fix force unwrap crash when loading older messages

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Permissions.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Devices/ProfileDevicesViewController.h
- Wire-iOS/Sources/UserInterface/UserProfile/Devices/ProfileDevicesViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+internal.h
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.h
Tapping on an unconnected user crashed the app.
We force-unwrapped the `fullUser()` property when determining whether the
- Move the checks to `UserType` so that we don't need to get the full user when making the tabs.
- Annotate the view controller header with nullability to avoid crashes in the future.
We also fix an issue where we'd try to show the devices for a guest from another team (wouldn't show any because ).
> ZIOS-11306: Fix regression crash when tapping on an unconnected user

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
When tapping on a search result, the message would be positioned right under the viewport of the table view.
We used the index 0 of the message in the message section to scroll. But the table is upside down, so the cell at the "visible" index 0 is actually the cell with the last index in the section.
Fix the calculation of the top message index and fix wrong usage of this function.
> ZIOS-11309: Fix regression with offset of message when tapping on search result

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
The self-profile screen is not shown after the open self profile button is tapped. (The app is launched with the self profile deep link)
`ProfileViewController` is not dismissed before transited to setting screen.
Dismiss `ProfileViewController` itself before the transition.
> Fix: Nothing happens when tapping OPEN PROFILE on deeplink self user profile popup

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsContentController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
User profile deep link does not show rich profile.
The rich profile section's visibility is despended on the `conversation` property, but it is nil in this case.
Add the `ProfileViewControllerContext` argument when creating `ProfileDetailsContentController`. Show the rich profile section when the `context` is `.ProfileViewer`.
> Fix: User profile deep link does not show rich profile

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.swift
On older phones the scroll position would be lost after sending a link preview
Before sending message we always scroll to the bottom. This method recently changed implementation so that it now reload the messages, this disrupts the scroll position.
Don't call method which reload the messages if we are already scrolled to the bottom.
> Don't scroll to bottom if already at the bottom

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxDataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
When multiple calls are made we group them together into one system message. When tapping on such a system message we should expand and show a timestamp for when each call was made but we only showed the first timestamp.
Label was configured with `.numberOfLines = 1`
Configure label with `.numberOfLines = 0` when displaying the call list.
> Fix grouped call system messages not showing all timestamps

- fastlane/Fastfile
App Store upload fails
`Could not find action, lane or variable 'options'. Check out the documentation for more details: https://docs.fastlane.tools/actions`
Add missing options parameter
> Add missing options parameter

- Wire-iOS/Sources/UserInterface/LaunchImage/LaunchImageViewController.swift
App would would crash when switching account 
If the account need migration we will show the launch screen with a spinner
```
case .migrating:
let launchImageViewController = LaunchImageViewController()
launchImageViewController.showLoadingScreen()
```
This will trigger a force unwrap since the views are not created yet.
Make views non optional by creating them on init.
> Fix crash when calling showLoadingScreen before view is loaded

- Wire-iOS/Sources/Helpers/sound/AVSMediaManager+Additions.m
- avs-versions
We don't want to upgrade to AVS 4.9.12 just yet so we need to downgrade.
> Revert AVS version to 4.9.9

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
We were not saving the YouTube links and for old messages when scrolling.
We did not wrap the call to `message.refetchLinkAttachmentsIfNeeded()` in the session changes enqueuing, which means the data was not saved after the message was deallocated.
Wrap in `ZMUserSession.performChanges`.
> Wrap request to refresh message links in enqueue changes

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
Fixed the issue caused by `performChanges` blocking UI thread when creating a message cell.
> fix: UI freezes when creating a cell for message

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+ViewLifeCycle.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/UIViewController+StatusBar.swift
- Wire-iOS/Sources/UserInterface/Settings/VersionInfoViewController.swift
Image view's status bar is dark-on-dark. with the user selects dark theme.
Similar to https://github.com/wireapp/wire-ios/pull/3226/files
apply the solution from https://github.com/wireapp/wire-ios/pull/3226/files
move `updateStatusBar` to `UIViewController`'s extension.
> Fix： [Dark theme] image viewer's status bar is dark after opening an image from a conversation

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+MessageFormatting.swift
App crashes when on message with markdown link & link preview
`linkPreview.characterOffsetInText` is referring to the offset before the text has been formatted for markdown, which results in an index of out of bounds crash.
Re-write method not to rely on `linkPreview.characterOffsetInText`
> Crash on markdown links

- fastlane/Fastfile
The last piece was missing in migrating build scripts - uploading app to AppStore. This PR adds the functionality missing to finish this.
Added extra information to RC build icon - app version. Also added a separate Hockey step that uploads only dSYMs for crash tracking.
> Appstore and RC builds

- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
When team 1:1 conversations are created they generate an unread dot. This unread state was however only indicated by the subtitle "x started a conversation with you", which wasn't very obvious and many people missed it. This resulted in users complaining about unread badges which won't go away after reading all messages.
Show an unread count for this scenario so that it's obvious that this conversation is unread.
> Show unread count for new conversations

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Constraints.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Cancel request button was missing for outgoing connection request conversations.
In correct guard statement prevented the `OutgoingConnectionViewController` from being created.
Revert code to previous logic.
> Restore missing cancel request button

- Wire-iOS/Sources/AppRootViewController.swift
Cannot see self-profile via deeplink.
After https://github.com/wireapp/wire-ios/pull/3324, we always start searching for the userID fro user profile deep link, but self-user does not exist in search result.
directly open profile screen if the user id is self-user's id
> Fix: Cannot see self profile via deeplink

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
Fix compiler error due to change of return type of `setDimensions` method.
> fix: setDimensions return type

- Wire-iOS Tests/AccessoryTextField/AccessoryTextFieldValidationTests.swift
- Wire-iOS/Sources/Authentication/Interface/Helpers/TextFieldValidator.swift
We previously required the users to enter a valid password in order to log in. But with the upcoming changes, we cannot guarantee that a password valid on a version will be valid on another version of the app.
Align with the behavior of web and require the user to enter a non-empty string on log in.
> ZIOS-11343: Do not validate the format of the password used to log in

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Change "profile photo" to "profile picture" in the accessibility label for the profile picture view (requested by Astrid).
> Fix VoiceOver copy for profile picture

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Fix the wording to prevent an incorrect combination for the open link target.
> Fix: Tweets list shows "Safari/Twitter" even if Firefox is chosen for the browser

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Authentication/Event Handlers/Registration/RegistrationActivationExistingAccountPolicyHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Team/TeamEmailVerificationErrorHandler.swift
Previously, when try to create a team with an email already tied to an account, there was no alert or warning, the spinner just disappeared.
The event handler for activating the email during team registration was explicitly ignoring the error about used email, for some reason. 
- Update the aforementioned event handler to never ignore errors
- Update the "existing account policy" event handler to show the alert that allows the user to register with a different email or log in, as we do for personal accounts.
- Fix the copy for "register with another email" to match the one we use for phones.
This is what happens after the fix:
> ZIOS-11368: Warn user about used email in team registration

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
When the user makes multiple calls, the cell with the message wasn't updated.
This is mostly a hot fix for this specific case and we'll probably need to look into refreshing cells more in detail. But for now, we just update the comparison method used by DifferenceKit to force refreshing the call system message cell when the description text becomes different.
> ZIOS-11370: Call cell doesn't refresh after multiple calls

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarButtonState.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Markdown.swift
When editing a message, the markdown and edit buttons were not hidden.
> 10658: Hide markdown and timeout buttons when editing

- fastlane/Fastfile
Sometimes we want to use a custom branch/repo for configuration and it causes problems on build machine.
When configuration is already there the build scripts only does `git pull`. If a previous build used custom branch of configuration then the regular build would end up using it as well.
Remove configuration when preparing for the build job.
> Remove configuration before building

- Wire-iOS/Sources/UserInterface/Components/Loading/UIViewController+LoadingView.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockView.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceView.swift
Rewrite some constraints to use native anchors API.
> Remove some deprecated layout API usage

- Wire-iOS Share Extension/ShareExtensionViewController.swift
- WireCommonComponents/Icons/UIImage+StyleKit.swift
After the icons refactor, the size of the Wire logo on top of the share extension was broken.
Fix the size by downscaling the image.
> Fix size of Wire logo in share extension

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
When opening a conversation with more unread messages than the size of the message window we would lose the scroll position.
When opening a conversation with unread message the following things were happening:
1. Load initial message window of size 30
2. Load message window which includes the first unread message
3. Scroll to the first unread message
4. We change properties of some messages when they appear on screen and save (link attachments)
5. The fetch results controller monitors the save notifications and updates its `fetchObjects` property
6. We discover that there's new messages in the message window and perform a table view update
The problem is caused by the the last table view update which is happening because the `NSFetchResultsController` is not very strict about the …
> Fix scroll position when opening conversation with many unread messages

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
Follow-up on https://github.com/wireapp/wire-ios/pull/3383
The last PR didn't handle the case when receiving many new message in conversation without previous history.
The last fix was limiting the number of messages to the `fetchLimit` but that doesn't work if the number of messages is below the fetchLimit (not enough history).
Remember the initial message count and limit the number of messages to that.
> Fix scroll position when opening conversation with many unread messages (follow-up)

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+CreateViews.swift
Typing indicator is stretched
caused by https://github.com/wireapp/wire-ios/pull/3304. `PureLayourt`'s `NSLayoutRelationGreaterThanOrEqual` has different defination with `NSLayoutConstraint`.
user `lessThanOrEqualTo` instead
I will add a snapshot case for typing indicator in another PR.
> fix: Typing indicator is stretched

- Wire-iOS/Sources/UserInterface/Settings/UserRight.swift
Managing profile picture is not yet supported for SCIM users, until that's the case we enable setting it manually.
> Allow editing of profile picture also for users not managed by wire

- Wire-iOS/Sources/Authentication/Event Handlers/Post-Login/Success/AuthenticationSuccessEventHandler.swift
After being logged out for device removal, the user gets stuck in the login flow and can't do anything until he restarts the app, while the user was correctly logged in.
That's because we usually wait for the slow sync to be completed, but in this case, the history is already on the device and we don't need to do slow sync, so the app gets stuck waiting for a sync that never happens.
I'm checking if the client has made a slow sync before inside `AuthenticationClientRegistrationSuccessHandler` If true, it returns `hideLoadingView` and `completeLoginFlow`, which causes the login flow to disappear.
> ZIOS-11361: Unable to finish login to existing account after the user removed the device

- Wire-iOS/Sources/UserInterface/Components/Views/UpsideDownTableView+Scrolling.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
When loading a conversation with unread messages we would first load and display the last messages and then reload the messages again around first unread message. This is both unnecessary performance wise and looks bad.
We didn't used to reload message when scrolling to the first unread message but after some re-factoring that's now the case.
Before displaying the table view load either the last messages or messages near the first unread message.
NOTE: this needs to be done in `viewDidLayoutSubviews` because only then is bounds set which makes it possible to scroll the table view.
> Improve initial position when a loading conversation

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Constraints.swift
Fix the issue caused by missing a bottom constraint of `listContentController.view`.
> fix: conversation list - content is missing

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/CellComponents/SenderCellComponent.swift
Allow user to tap on an avatar in the conversation to see the profile of a user.
> Conversation screen - open profile when tapped on the avatar

- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Contacts/ContactsSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/GroupConversations/GroupConversationSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/SearchSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Services/SearchServicesSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Suggestions/DirectorySectionController.swift
Add-participant button didn't appear on release builds when selecting participants.
Swift 5 had a regression where it would not call optional methods only implemented a child class.
https://bugs.swift.org/browse/SR-2919
Add empty base class implementations.
> Fix add participants button not appearing on release builds

- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController+Internal.h
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController+ShareContacts.h
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController+ShareContacts.m
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController+ViewLifeCycle.swift
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController.m
`ShareContactsViewController` is coverd by the `tableView`.
After https://github.com/wireapp/wire-ios/pull/3339, the `tableView` is created in `init` instead of `viewDidLoad`, after `ShareContactsViewController` is presented.
present `ShareContactsViewController` when `viewWillAppear`.
> Fix: Contacts permission reminder UI overlaps

- Wire-iOS Tests/CameraKeyboardViewControllerTests.swift
- Wire-iOS Tests/Mocks/MockPhotoLibrary.swift
- Wire-iOS Tests/SavableImageTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ImageManagerProtocol.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/SavableImage.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetLibrary.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/PhotoPermissionsController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/PhotoPermissionsControllerStrategy.swift
- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController+SetupViews.swift
For PR https://github.com/wireapp/wire-ios/pull/3408 and https://github.com/wireapp/wire-ios/pull/3407 I want to create snapshot tests for UIAlertController but they are always fail whening running on CI server.
There are some system dialogs for Photo and Contacts permissions and causes nil snapshot images of the UIAlertControllers
Prevent interaction with Photo API when running tests. Inject mocks of `PHImageManager` and `PHPhotoLibrary` to `CameraKeyboardViewController` and its subviews.
> Fix: prevent showing photo permission dialog when testing

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
Disable option to delete legal hold device since backend won't allow it.
> Disable option to delete legal hold device

- Wire-iOS/Resources/Configuration/Project-Release.xcconfig
Developer settings are not available on dev and internal builds
xcconfig files are applied in the following order for the release configuration:
1. Release.xcconfig
2. Project-Base.xcconfig
3. Project-Release.xcconfig
4. Wire-iOS-Release.xcconfig
`IS_INTERNAL_BUILD` is configured in the `Release.xcconfig` which is different for each build variant (develop, internal, appstore). This however got overriden in `Project-Release.xcconfig`, which set `IS_INTERNAL_BUILD` to `0`.
Don't set `IS_INTERNAL_BUILD` in `Project-Release.xcconfig`.
> Don't disable IS_INTERNAL_BUILD on project level xcconfig

- Wire-iOS.xcodeproj/xcshareddata/IDETemplateMacros.plist
When we create a file in Xcode, we need to make sure that the header format is correct, which means that we most of the times need to copy it from another file. It's happened before that we forget to fix the year after pasting it in the new file.
Add an Xcode file header template (https://oleb.net/blog/2017/07/xcode-9-text-macros/) to generate the template with the right format and year when creating a new file.
> Add file header template with automatic date

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Permissions/ShareContactsViewController+Extension.swift
- Wire-iOS/Sources/Permissions/ShareContactsViewController+Internal.h
- Wire-iOS/Sources/Permissions/ShareContactsViewController.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+ContactsViewControllerDelegate.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+internal.h
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
- the keyboard is shown above `AddressBookAccessDeniedViewController` but it has no text field
- `UIActivityViewController` for sharing via other method is not shown.
- `AddressBookAccessDeniedViewController` is added above `ShareContactsViewController` and the text field on it is focused.
- `UIActivityViewController` is presented from `StartUIViewController`, which is not visible.
- call `endediting` before `AddressBookAccessDeniedViewController` is shown
- presented `UIActivityViewController` form top view controller.
> Fix: Keyboard appears over contact permission screen and UIActivityViewController not show

- Wire-iOS/Sources/UserInterface/Calling/CallQualityController/CallQualityController.swift
Call logs popup was shown when answering from another device.
This because the `handleCallCompletion` method is called with `reason = .answeredElsewhere`, that should not be taken in account for the call logs popup.
I've added the case inside the switch that handles possible reasons.
> ZIOS-11447: iOS call failure pop-up in multiple devices

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/UserProfile/Devices/UserClientListViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ParticipantDeviceHeaderView+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ParticipantDeviceHeaderView.m
In client devices screen, the link "why verify conversations" has no reaction after tapped.
After https://github.com/wireapp/wire-ios/pull/3435,  no classes conform to `ParticipantDeviceHeaderViewDelegate` and `ParticipantDeviceHeaderView`'s delegate is not set
Make `UserClientListViewController` conforms `ParticipantDeviceHeaderViewDelegate` and set it as deleagate of `ParticipantDeviceHeaderView`.
> Fix: Unable to press "why verify conversations"

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationIconBasedCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationLegalHoldCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
Link text in the system message is not tappable in release build. (It is tappable in debug build)
Same as https://github.com/wireapp/wire-ios/pull/3403
Add an empty implementation of `textView(_ textView: UITextView, shouldInteractWith url: URL, in characterRange: NSRange, interaction: UITextItemInteraction) -> Bool` in `ConversationIconBasedCell` and let the children of `ConversationIconBasedCell` overrides it.
> Fix: "You started using *This device*" button doesn't work 

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+Zoom.swift
When double tap on an image with has the same width as the screen, it moves outside the frame.
Unknown, seems like a bug of `UIScrollView` when try to zoom the view which is not able to zoom.
Do not zoom in this case.
> Fix: GIF image moves outside the frame after double tapped

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
App crashes on launch
Missing selector  `setUserObserverToken:`
Make sure property which is declared to exist in an extension is also synthesised.
> Synthesize property declared in extension

- Wire-iOS Tests/Utils/ZMSnapshotTestCase.swift
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
There was a flag in `ZMSnapshotTestCase` to enable recording, but it was not available in Swift.
Change the flag from a conditional build flag to an environment variable that you can set to `YES` to force recording snapshots.
> Fix environment variable for recording snapshots 

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ZMUserObserver.swift
QA reported that this alert was shown mistakenly every time the user logs in, and it caused their nightly test passing rate to drop to 24%. We need to disable this alert until we have a proper mechanism for displaying it.
> [Temp] Remove legal hold disabled alert

- Wire-iOS Tests/DeviceManagement/ClientListViewControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/syncengine/ClientRemovalObserver.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
In setting screen, enter password alert not showing after entered a wrong password. (Wrong password alert appears after `remove device` cell is tapped)
Multiple instance of `ClientRemovalObserver` exists due to they are not released after created when `remove device` is button is tapped everytime. And they are not release since self-retained and captured in closures.
Refactor and make ViewControllers retain `ClientRemovalObserver`. Refactor closures not to retain `ClientRemovalObserver`.
> Fix: enter password alert not showing after entered a wrong password

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
- When a participant's legal hold status changes in a group, the indicator in the conversation wasn't updated.
- When a participant's legal hold status changes when opening the devices list, the indicator in the profile details wasn't updated.  
Implement observing for the legal hold status and reload the navigation items upon change.
> ZIOS-11497: Update legal hold indicators on user change

- Wire-iOS/Sources/UserInterface/Camera/CameraController.swift
Step to reproduce the issue:
1. enable screen lock under portrait mode
2. Launch the app in landscape orientation
3. Open camera keyboard
result: the preview image is rotated by 90 degree
The video's orientation follows device orientation. In this case, device orientation is different from UI orientation.
The video's orientation follows UI orientation as the first priority
> fix: iPad - Camera is rotated in landscape

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
Follow up of https://github.com/wireapp/wire-ios/pull/3482. Fix the issue that after switching keyboards(audio recording/normal) camera preview is rotated.
> Fix: iPad - update orientation when cell will diaplay

- Wire-iOS/Sources/Helpers/Message+Pasteboard.swift
Distinguish animated GIF from other images types when copying it to prevent it is pasted as a static image.
> Fix: When copying a GIF from conversation and paste it, the animation is lost

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/NetworkConditionIndicatorView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
We add accessibility indicators for the CBR label (`bitrate-indicator`) and the network quality indicator (`network-conditions-indicator`).
> ZIOS-11501: Add identifiers for calling indicators

- Wire-iOS/Sources/Authentication/Helpers/CountryCode/Country.m
Phone country codes shared with multiple countries (e.g. Italy and Vatican) are randomly selected every time a phone number is pasted or autocompleted.
I'm extending the filter already implemented with US to other countries in order to choose the main reference country for that prefix.
> ZIOS-11505: Numbers with prefix shared with multiple countries randomly select the country name

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
The microphone permissions alert appear behind the keyboard. This alert is shown the first time you attempt to make a call. 
Keyboard is not dismissed.
End editing after the one of the call button is tapped.
> Fix: Microphone permissions alert appear behind keyboard

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsContentViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/UICollectionView+GroupedSections.swift
- Wire-iOS/Sources/UserInterface/LegalHoldDetails/LegalHoldDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Devices/UserClientListViewController.swift
- Add accessibility identifier for legal hold details
- Rename `UICollectionView(forUserList: ()` to `UICollectionView(forGroupedSections: ())` since it's now the default configuration for our `UICollectionView` based based screens.
>  Add accessibility identifier for legal hold details

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxDataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
The "eye" icon has no text representation in the accessibility label.
`NSTextAttachment` in the attributed text does not generate text in the accessibility label.
Manually create an accessibility label for the "eye" `NSTextAttachment` and set it to the Label.
> Fix: Accessibility for Seen icon in message delivery status

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
Set `ConversationListItemView`'s `accessibilityIdentifier` to "conversation_name" for automation.
> Fix: set accessibilityIdentifier of ConversationListItemView

- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallStatusViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
The accessibility identifiers for the CBR and network status are not visible.
They are hidden since the entire `CallStatusView` is exposed as a single accessibility item.
Expose each status label individually.
> Fix missing call accessibility identifiers

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConnectRequestsCell.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell+Accessibility.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/UICollectionViewCell+Accessibility.swift
Move `accessibilityIdentifier` from `ConversationListItemView` to `ConversationListCell` and `ConnectRequestsCell`.
Customize `ConnectRequestsCell`'s  `accessibilityLabel` & `accessibilityValue`.
> Fix: add accessibilityIdentifier to ConversationListCell and ConnectRequestsCell

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell+Accessibility.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView+Update.swift
When the conversation is a 1-to-1 type with a team member, the `accessibilityLabel` is missing.
Missing `accessibilityLabel` setting for that case
Set `accessibilityLabel` for that case.
> Fix: Set accessibilityLabel for team member conversation case

- Wire-iOS Tests/LegalHoldAlertFactoryTests.swift
- Wire-iOS/Sources/Managers/LegalHoldDisclosureController.swift
- Wire-iOS/Sources/UserInterface/Helpers/LegalHoldAlertFactory.swift
If you enter the wrong password when legal hold is being requested you don't get a second chance and need to manually open the dialog again.
Show the request dialog again after entering the wrong password.
In order easily do this I removed the associated `UIAlertController` from the view state. This allows me to more easily transition between view states without having to construct an alert at the place where I decide to do a transition.
> Show legal hold alert again after entering the wrong password

- Wire-iOS/Sources/Managers/LegalHoldDisclosureController.swift
After app start, legal hold activation alert appears twice if not accept it. (The second time the alert dismisses immediately)
The `currentState` changes in this order
1. .none
2. .warningAboutPendingRequest(LegalHoldRequest)
3. (The user pressed the "not now" button) .warningAboutPendingRequest(LegalHoldRequest)
4. .none
The alert appears twice for every time the `currentState` is set to `.warningAboutPendingRequest(LegalHoldRequest)` 
Present the alert only when the `currentState`'s value is different form `oldValue`
> Fix: After app start, legal hold activation alert appear twice if not accept it

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView+Update.swift
In the conversaton list cell, if the status icon has a status other than muted, e.g. number of unread message, calling, ..., the `accessibilityValue` does not show the corresponding value.
Missing handling of those cases.
Append the icon's `accessibilityValue` to the cell's `accessibilityValue`.
> Fix: Conversaton list cell - accessibilityValue for status other than muted

- Scripts/embed-internal-resources
If you build the app with `IS_INTERNAL_BUILD = 0` it will delete `Settings.bundle` and any subsequent builds with `IS_INTERNAL_BUILD = 1` will fail.
`Settings.bundle` does not belong to any target by default and the script `embed-internal-resources` manually copying to the build product directory if `IS_INTERNAL_BUILD = 1`, so it's not necessary to delete `Settings.bundle` if are not copying it.
> Don't delete resource if we are not copying and add informative logging

- Wire-iOS/Sources/UserInterface/Components/Controllers/DefaultNavigationBar.swift
LegalHoldDetailsViewController was presented on it self.
`wrapInNavigationController()` Was executed on the presenting view controller 
Execute `wrapInNavigationController()` on the view controller that's being presented.
> Fix crash due to present view controller on itself

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Permissions.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
It was decided to show the devices tab for all users, it was previously hidden for guests.
Always add the devices tab except when viewing the profile in search or through a user link.
> Show device list for all users

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
The system message for un-verifying a device would not display the to the device.
The `link` attribute in the attributed string didn't contain a valid URL which caused it not be displayed at all.
Use correct URL.
> Use correct URL for the device's link attribute

- Wire-iOS/Sources/Helpers/UserClient+Fingerprint.swift
Legal hold devices we not always displayed first in the list of devices
Sort order function didn't handle the case when `lhs = regular` and `rhs = legalhold`.
Return `false` if the right hand side is legal hold device.
> Fix device list sort order

- Wire-iOS/Sources/UserInterface/Helpers/LegalHoldAlertFactory.swift
Error alert when entering the wrong password had the phrase "Wrong password" twice.
Replace message with "Please try again."
> Fix redundant copy when entering the wrong password

- Wire-iOS Tests/AppLockTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift
- WireCommonComponents/AppLock.swift
Implemented custom timer on app lock and possibility to force it by a custom `applock.json` file in the configuration folder. TODO: tests.
> ZIOS-11562: Force app lock and make time configurable from build config

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
For automation, we found that conversation message status label's `accessibilityLabel` does not refesh after the messaged is liked. The status label is hidden after the animation is completed and it may cause an issue for automation. 
As a work-a-round, set status label's `accessibilityLabel` to `nil` before the animation starts.
> Fix: conversation message status label accessibilityLabel does not updated after liked

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
Prevent compressing "Join" label's width and truncating the text.
> Fix: iOS join button on conversation list is missing 'JOIN' label

- Wire-iOS/Sources/UserInterface/LegalHoldDetails/LegalHoldDetailsViewController.swift
When opening  `LegalHoldDetailsViewController` from the conversation list screen, the status bar is still in the light style
same as https://github.com/wireapp/wire-ios/pull/3316
same as https://github.com/wireapp/wire-ios/pull/3316
> Fix: LegalHoldDetailsViewController status bar style when opening from conversation list screen

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Follow up of https://github.com/wireapp/wire-ios/pull/3535, try to fix the automation issue which still seeing `statusLabel`'s accessibility label even it is hidden. Set the attributed text to nil to prevent the generation of accessibility info.
> clean status label's text when hidden

- Wire-iOS Tests/AppLockTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift
- WireCommonComponents/AppLock.swift
share extension crashes after https://github.com/wireapp/wire-ios/pull/3528 is merged
Missing `applock.json` in share extension target 
add the missing file in the share extension target and add a fatal message if missing.
> Fix: share extesnion crash due to missing bundle file

- Wire-iOS.xcodeproj/project.pbxproj
Fix share extension crash due to missing `session_manager.json` file
> Fix: share extension crash due to missing file

- Wire-iOS/Sources/Analytics/Events/Analytics+Settings.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- WireCommonComponents/AppLock.swift
- WireCommonComponents/SettingsPropertyName.swift
When `forceAppLock` is enabled, no applock displayed after restarting the app.
If the `timeout` is not reached, applock is not shown.
~~When the app launches, set `lastUnlockedDate` to invalid value and app lock screen will be shown.~~ Set `lastUnlockedDate` to an invalid value so that app lock always appear when app launches.
Remove `lockAppLastDate` from `SettingsPropertyFactory` and not save the value in the keychain.
> Fix: no applock displayed after restarting the app

- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
When there's no passcode set and app lock is required the keyboard would be shown on top of the app lock screen.
The below the app lock the login screen would make the e-mail field first responder and trigger the keyboard to be shown. If the passcode was set the authentication window would dismiss it again.
Make the app lock window the key window when it's displayed on top of the app, this will prevent the login screen from triggering the keyboard to be shown.
> Prevent keyboard showing up when app lock is active

- Wire-iOS Tests/AppLockTests.swift
https://github.com/wireapp/wire-ios/pull/3572 introduced some failing tests
After https://github.com/wireapp/wire-ios/pull/3572 the key window gets changed in the `AppLockTests` which causes some other snapshots to fail due to minor pixel changes.
Restore the key window in the `AppLockTests` tearDown method.
> Fix broken tests

- Wire-iOS/Resources/Configuration/Version.xcconfig
- fastlane/Fastfile
Reopen of https://github.com/wireapp/wire-ios/pull/3577.
To allow submitting a build to Hockey app with custom configuration sets and send it under different hockey_app_id. New options are added to `fastfile`.
- add `config_folder` option to `prepare` lane
- add `hockey_app_id` option to `upload_hockey` lane
If the options are not provided, the default value will be applied.
> Allow config config_folder and hockey_app_id in fastfile 
