wireapp/wire-ios

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetLibrary.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

- Removed unnecessary second confirmation when taking picture/video with integrated camera
- Do not ask for sound recording permissions immediately when opening camera keyboard
- Open camera keyboard even if scrolled back in conversation on tap
- Close keyboard when doing file sharing
- Fetch new images when app becomes active

Camera keyboard follow ups

---

.travis.yml

* Enables caching of CocoaPods and Bundler on Travis-CI, see https://docs.travis-ci.com/user/caching/

Enable CocoaPods and Bundler caching on CI

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetCell.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraCell.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
Wire-iOS/Sources/UserInterface/Helpers/UIView+Zeta.m

- Fixed blinking previews on iPad
- Do not reload previews twice
- Use default camera for fullscreen camera
- Fixed camera orientation on iPad
- Fixed camera keyboard too small on iPad

Camera keyboard bugfixes

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/AppController.m
Wire-iOS/Sources/AppDelegate+Hockey.m
Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationViewController.m
WireExtensionComponents/Utilities/AutomationHelper.swift

If the argument `SkipLoginAlerts` is provided with a value other than 0 on the command line the registration for notifications, reminder for notifications, address-book upload screen, screens to add missing phone numbers or email addresses, as well as the modals used to communicate a missing history will not be displayed.

Add possibility to skip notification and other login alerts for automation

---

WireExtensionComponents/Utilities/AutomationHelper.swift
WireExtensionComponents/Views/TextView.m

This PR allows disabling auto correction for `TextView` instances by passing `-DisableAutoCorrection` as launch argument.

Add command line option for disabling auto correction

---

Wire-iOS/Sources/Components/Vimeo/VimeoService.m

- This should make the open-source client stop crashing on Vimeo videos
- Implication: the preview for Vimeo is not loaded

Do not instaniate Vimeo helper when API key is not present

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationViewController.m

There was a delegate call missing to notify that the sign in did succeed.

Insert missing delegate call

---

Scripts/download-avs.sh

Update the script to download the AVS binary from multiple sources
If the right environment variables are set, the AVS binary can be downloaded from a custom location (GitHub repository that has a release with an attachment).
The variables to set are:
- `AVS_REPO`: the custom "organization/repo" where to find AVS binaries
- `GITHUB_USER `: the GitHub user that has access to that repository (if auth is needed)
- `GITHUB_TOKEN `: the GitHub password or personal access token (if auth is needed)
More variables can be set to override the version, if needed:
- `AVS_VERSION` to download a specific version

Update the script to download the AVS binary from multiple sources

---

WireExtensionComponents/Views/Loading/UIViewController+LoadingView.m

- Issue happens when `showLoadingView:YES` is called immediately after `showLoadingView:NO`
- What happens is when loading view stops loading it removes the animation from layer, this makes it call animationDidStop on next run loop spin (1)
- When it asked to start again, the animation is re-added to the layer and view is set to be visible
- However, when (1) occurs the view is set to be invisible again
- Fix: do not use `hidesWhenStopped`

Fix invisible loading indicator when stop and start loading

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/DeviceProximityListener.swift

* When playing an audio message, we were checking the proximity sensor as well as the device orientation and only switched to the earpiece when the device was held vertically.
* This PR removes the requirement for the phone to beheld vertically which makes this functionality less fragile as some people don't hold there phone vertical when listening.

Remove requirement that device has to be held vertically to switch to earpiece

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraCell.swift

- Camera keyboard observes current camera change
- When user clicks back button with camera keyboard it is not being deallocated
- When user starts to pick image in self profile camera sends current camera change notification, that is received also by camera keyboard
- Camera keyboard tries to animate the camera change and fails unboxing the videoSnapshot
- To avoid this behaviour we verify if animation is needed

Check if animation is needed when camera change notification arrives

---

Wire-iOS Tests/Message+FormattingTests.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/Message+Formatting.m

`NSDataDetector` gets confused by URLs prefixed with `abc:` which led to a crash. We avoid this by checking that any URL attachment is in range.

Handle the case when NSDataDetector detects URLs wrong gracefully

---

.travis.yml

* Only build pushes to `master` and `develop` to avoid creating 2 integrations for each push to a PR.

Update .travis.yml to only build pushes to master and develop

---

Scripts/download-avs.sh

This allows the Xcode project to find the library and headers always in the same folder

Always use the same library folder for AVS in download script

---

Scripts/download-avs.sh
avs-versions

Extract version of AVS to separate file for ease of access
This was requested to make it easier for people outside of the team to find the version and bump it

Extract version of AVS to separate file for ease of access

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift

- Common transitioning delegate `FastTransitioningDelegate.sharedDelegate` gets confused when it's used to dismiss a controller, and then immediately to present the new one
- Inserted minimal artificial delay

Fix UI corruption after rotation

---

Podfile
Wire-iOS/Sources/Components/Vimeo/VimeoService.m

- On automation we use builds from jenkins that have proper API keys
- Also we have a setting in those builds to crash on assert to unveil the bugs on early stage
- However simulator keychain is not perfect, and it cannot save vimeo API key (do not ask me why vimeo needs to save it to keychain)
- It asserts and crashes
- Solution: use special VIMNeworking version that ignores keychain errors on simulator

Fix for Vimeo simulator crash

---

Dangerfile
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Analytics/AnalyticsTracker.h
Wire-iOS/Sources/Analytics/AnalyticsTracker.m
Wire-iOS/Sources/Analytics/Permissions/AnalyticsTracker+AddressBookPermissions.swift
Wire-iOS/Sources/Analytics/Permissions/AnalyticsTracker+Permissions.h
Wire-iOS/Sources/Analytics/Permissions/AnalyticsTracker+Permissions.m
Wire-iOS/Sources/Managers/AddressBookHelper.m
Wire-iOS/Sources/Permissions/ShareContactsViewController.m
Wire-iOS/Sources/UserInterface/Registration/ShareContactsStepViewController.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m

* All address book related events have been moved into AnalyticsTracker+AddressBookPermissions.
* We now track the result of the `preflight` screen shown before asking for system permissions as well as the system permissions result.

Add new address book analytics events

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Wire-iOS/Sources/UserInterface/Sketchpad/SketchViewController.h
Wire-iOS/Sources/UserInterface/Sketchpad/SketchViewController.m

* The issue from https://github.com/wireapp/wire-ios/pull/62 was still present on iPhones.
* I could only reproduce it when the camera keyboard was not dismissed when dismissing the `SketchViewController`. We now ensure the keyboard is dismissed before dismissing the controller.
* This PR also fixes an issue where the image selected from the camera keyboard was lost when tapping the " Add a sketch " button and then confirming without sketching.

Fix corrupted ui after sketch dismissal

---

Wire-iOS Tests/CameraKeyboardViewControllerTests.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift

- Slow-motion videos are exported as regular per default
- Using export session, it can be exported as slow motion and converted to mp4 / network quality in one go

Support for slow-mo export

---

Wire-iOS/Sources/UserInterface/Components/Controllers/ImagePickerConfirmationController.m

* Fixes [7049](https://wearezeta.atlassian.net/browse/ZIOS-7049), crash when querying the `cameraDevice` when the source type was not camera

Only query image picker camera device if it has a sourceType .Camera

---

Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

* The `BackgroundViewController` had the wrong initial state on iPad. Enforcing non-fullscreen state initially fixes this.

Update backgroundViewController state to avert wrong initial state

---

Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.h
Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.m

- All ObjC methods without nullability declarations are visible in Swift as force-unwrap
- It is sad and annoying, while in ObjC they are just optional per default
- Solution: add proper nullability in headers

Fixed crash while unboxing firstActiveParticipantOtherThanSelf

---

README.md

Update README to mention that clients build from source won't be able to receive notifications

Add APNs issue as known limitation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m

* Today in "Bugs that could have been prevented using Swift": A missing `break` statement lead to the wrong cell being displayed in certain scenarios.

Insert missing break leading to wrong cell being displayed

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m

* Always use `UITableViewRowAnimationFade` for deletion animations

Use UITableViewRowAnimationFade when deleting cells in a conversation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/LocationMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/PingCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
Wire-iOS/WireBridgingHeader.h

* The `UIAlertController` showing the different delete options did not have a target view and rect and did crash no iPad as it is presented as popover on tablets. 
* To prevent this the view and rect used to present the `UIMenuController` have been extracted to be a getter on `ConversationCell` so that they can be reused in different contexts, e.g. presenting the delete option action sheet.

Fix crash when delete option presenting action sheet on iPad

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift

* [7085](https://wearezeta.atlassian.net/browse/ZIOS-7085): Message should only be deleted if the selfUser is still an active member of the conversation

Only show the delete for everyone option if self is still a member of the conversation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

* The `selectionRect` and `selectionView` properties were not overridden by `ImageMessageCell` which lead to a wrong location for the deletion popover [(7080)](https://wearezeta.atlassian.net/browse/ZIOS-7080)

Fix deletion popover location for image message cells

---

Wire-iOS Tests/DeleteMessageTests.m
Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Resources/de.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift

* The delete menu item in the `UIMenuController` is now always the last item ([7086](https://wearezeta.atlassian.net/browse/ZIOS-7086)).
* Reverting the changes made in https://github.com/wireapp/wire-ios/pull/90 conforming `ConversationCell` to `UIKeyInput`, these changes were made to prohibit the keyboard of being hidden when displaying the `UIMenuController`, but made it always appear instead if it was not being shown (which makes sense as the cell was expecting text input then).
___
From the Apple documentation:  
> Custom items appear in the menu after any system menu items. 
This means that the `-delete:` selector can not be used, but instead a custom menu item has to be added to the menu controller to guarantee that the delete item is displayed last (after other custom items like …

Unify UIMenuController item order to make `delete` always appear last

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* When the input bar becomes first responder we scroll the conversation to the bottom, we don't want this behavior when editing a message.

Don't scroll to the bottom of the conversation when editing

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m

Fixes for: 
* [7097](https://wearezeta.atlassian.net/browse/ZIOS-7097): "Do not show Edit option if user has been removed/left the group conversation"
* [7098](https://wearezeta.atlassian.net/browse/ZIOS-7098): "Edited unsent message is shown as sent to the sender" – This is now restricted from the UI side but will be added in `wire-iso-sync-engine` as well.

Restrict editing to messages in conversations where self is an active member

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* [7093](https://wearezeta.atlassian.net/browse/ZIOS-7093): "Message edited with spaces isn't shown as deleted"
* [7094](https://wearezeta.atlassian.net/browse/ZIOS-7094): "Message edited with space is impossible to send by tapping on send button on the keyboard" 
* [7095](https://wearezeta.atlassian.net/browse/ZIOS-7095): "Not edited but submited message is shown as edited"

Fix being able to send empty edits and sending unedited content from return key

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* The input field was pre-filled with the `draftMessageText` text when leaving the conversation while editing and then re-entering again.
* Unify the sending editing logic when using the return key and confirm button.

Remove draft message text when leaving editing mode

---

.gitignore
ConfigurationSets/Base.xcconfig
ConfigurationSets/Development.xcconfig
ConfigurationSets/Release.xcconfig
Scripts/download-assets.sh
Wire-iOS.xcodeproj/project.pbxproj
setup.sh

- It was unclear for Wire developers where the private assets are located
- The CI system required extra configuration to fetch assets from GitHub
- Solution is to make a setup of private assets as part of `setup.sh`
- The 3rd party developers who don't have access to private repos would not have issues with compilation, since the assets and step in `setup.sh` are optional

Updated private xcconfigs loading

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Components/Views/NextResponderTextView.h
Wire-iOS/Sources/UserInterface/Components/Views/NextResponderTextView.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewControllerDelegate.h
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
Wire-iOS/WireBridgingHeader.h

- The cell takes first responder when shows the menu
- Cell can support text input, and then the keyboard stays up, but it brings an issue of opening the keyboard when it was hidden and menu is activated
- Solution is to remain text field a first responder, but make cell a part of it in the responder chain (not to confuse with view hierarchy)
Inspired by http://stackoverflow.com/questions/13601643/uimenucontroller-hides-the-keyboard

Persist keyboard when showing the cell menu

---

Wire-iOS/Sources/Analytics/AnalyticsVoiceChannelTracker.m

We would send too many `ConnectionEstablished` tracking call because every time we switch connection (3G, Wifi, 2G etc), we would be notified that the connection is established.
This is now fix.

Fix calling tracking

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewControllerDelegate.h
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

- The issue is that sometimes the menu is showing wrong elements in conversation view
- It happens because of the new responder logic in connection to keeping the keyboard up
- The exact issue is that the cell is not always becoming first responder, but only if there is no other current responder (implemented in that way to keep keyboard up)
- So the previously selected cell is remaining "selected"
- Solution is to check with delegate if cell should become first responder when showing menu. Delegate knows if the keyboard is up.

Fix incorrect cell menu in conversation

---

Wire-iOS/Sources/Components/Soundcloud/SoundcloudService.m

- On link "soundcloud.com/sirdonqui/likes" and similar the API response gives an Array instead of HashMap (Dictionary)
- Swift can help in this case next time

Avoid crashing on inconsistent soundcloud response

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

* The cell should stay in selected state while showing the deletion options `UIAlertController`.
* This adds a completion closure to the helper method to present the sheet in order to deselect it in case the cancel action is selected.

Leave cell in selected state while showing deletion action sheet

---

Wire-iOS/Sources/Permissions/ShareContactsViewController.h
Wire-iOS/Sources/Permissions/ShareContactsViewController.m
Wire-iOS/Sources/UserInterface/Registration/ShareContactsStepViewController.m

* [6943](https://wearezeta.atlassian.net/browse/ZIOS-6943): If an onboarding user selects to share his contacts in the preflight dialog an then decides not to share them in the system alert we display the permission denied dialog. The `Not Now` button on the top right is owned by the `ShareContactsStepViewController` and would still trigger the tracking of the preflight analytics if tapped in this state.

Don't always track `Not Now` tap as denied preflight permissions

---

Cartfile
Cartfile.resolved
Wire-iOS/Sources/UserInterface/Components/Magic/UI Magic/UIFont+MagicAccess.m
WireExtensionComponents/Views/Buttons/IconButton.m

- On iOS 10 the loading of font `UIFontDescriptor` is changed
- Also fixed same logic in Classy https://github.com/ClassyKit/Classy/pull/114

Fixed fonts weights loading for iOS 10

---

Wire-iOS/Sources/Analytics/AnalyticsVoiceChannelTracker.m

**What is in this PR**
We failed to reset the call establish date when the call ended, failing to report any other call established. This is now fixed.

Properly reset call establish date when call ended

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

* Remove “only”
* Use title case per platform style guides

Align deletion copy across clients

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift

* The "This can not be undone" description of the `UIAlertController` shown when deleting a message should not be displayed using a medium font weight, which is the case if a message is set and no title is set. To avoid this we now set the title and not the message.

Set the alert title as title and not as message to ensure non-bold font

---

Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

[7180](https://wearezeta.atlassian.net/browse/ZIOS-7180): The adding of a reaction was not performed inside of a `ZMUserSession.enqueueChanges(_:)` block.

Wrap adding a like in a `enqueue changes` block

---

Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift

* Revert https://github.com/wireapp/wire-ios/pull/144 as the action already is enqueued on level higher

Revert wrapping liking in enqueue changes, as this is already done a level higher

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ZMConversationMessageWindow+Formatting.m

- The message toolbox was not correctly updated when liking by double tapping. 
- The message toolbox was not collapsed when unliking.
`showToolbox` was computed once when configuring the cell and became outdated on message updates. The fix is to do the computation on each message update instead.

The like reactions was not updating properly when double tapping a message

---

Wire-iOS/Sources/Helpers/syncengine/Message.m
Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

* Restrict liking to `normal` message types as liking of the "deleted" system message was possible and the like button was shown.

Restrict liking to `normal` message types

---

Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift

* Knock messages should not be likable, the wrong behavior was introduced in https://github.com/wireapp/wire-ios/pull/151

Disable likes for knock messages

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift

Crash on deleting a message, then inserting another message
When a message is deleted, the cell in the table view is disposed. However, the cell keeps a reference to the message. When a new message is inserted, the cell is prepared for reuse, and it still has a reference to the old message; accessing the old message causes a crash.
- Clear any reference to the old message before preparing the cell for reuse

Fix crash on message deletion

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift

* Only notify the delegate that the likers have been tapped if they are currently shown in the `MessageToolBoxView`

Only notify the delegate that the likers have been tapped when they are shown

---

Wire-iOS/Resources/Magic/conversation.plist
Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/LikeButton.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/SavableImage.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewControllerDelegate.h
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* From design review: The full screen image view should only show the close button.
* When saving from the image cells menu the camera icon should bounce.

Remove title and timestamp from single image view, bounce photo icon

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

There was a bug preventing the delete menu to be added to the `UIMenuController` of the `LocationMessageCell`, it was caused by making a mutable copy of the menu configuration properties `additionalItems` which can be nil.

If the additional items were nil no other menu items would be added

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift

Constraint was allowing the `statusLabel` to grow indefinitely.

Fix contraint causing status label not being clipped

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Like.swift

- On slow device we first set the new state, then update the view with animation
- On fast device the notification of update arrive before we put the animations in
- Solution is to perform the animated update right after property is set

Fix animations order for like state in timestamp

---

Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewControllerDelegate.h
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* Animate the image moving into the photo button when saving (the animation is the same as previously in `FullScreenImageViewController`).
* Fix close button alignment in `FullScreenImageViewController`.

Animate image moving down into the photo button on save

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

* Fixes a bug that lead to the snapshot view being upside down when saving an image.
* Inverting the transform is no longer needed as we now create a snapshot of the image view.

Fix upside down snapshot view when saving an image

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift

* Some message are not likable and the tooltip to like them should not be displayed, sorry ping.

Restrict showing the `like this message` tooltip to likable messages

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

- Bug: when A and B like the message
- On B's client you see "A, B like the message"
- On B's client B unlike the message
- Current: On B's side you see timestamp
- Expected: On B's side you see "A like the message"

Display list of likers if any after unlike

---

WireExtensionComponents/Utilities/NetworkStatus.h
WireExtensionComponents/Utilities/NetworkStatus.m

Apple rejected the binary of 2.16 because it thinks that our internal method name `-networkStatusDidChange:` in our internal protocol is violating the private API use.
~~Use android.~~ Rename the method.

Fix for the rejection reason method name

---

setup.sh

setup.sh shows an error when xcodebuild points to xcode8, simple fix to allow versions 8 and above

Remove version error in setup.sh when using xcode8

---

Wire-iOS/Sources/AppDelegate.m
Wire-iOS/Sources/Helpers/NSData+MD5.swift

* The  new AVS version 2.9.5 has a workaround for the `AVCaptureSession` crash on Simulator
* Fix a unused result warning

Remove disabling AVS by default

---

Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift

* The `SettingsTechnicalReportViewController` was not correctly migrated to Swift 3 and thus crashed.

Fix technical report view controller Swift 3 migration

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

* We were passing a `nullable` `NSData` into a method expecting a non-optional , which now crashes ¯\\\_(ツ)_/¯

Fix crash when sending image

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Wire-iOS/Sources/UserInterface/Helpers/UIView+SlideInState.swift

* We were force unwrapping a view snapshot that might be `nil` in rare cases.
* Fix a layout bug where the `ReactionsView` was included in the status label.

Fix crash when force unwrapping a view snapshot

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift

* There was a bug preventing the individual names of likers being displayed even though there was enough space. 
* Clean up & move view setup and constraint creation in separate methods.

Fix wrong liker copy being shown

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift

* Fixes [#7306](https://wearezeta.atlassian.net/browse/ZIOS-7306), the function returning a `UIColor` was not called and thus a `() -> UIColor` was assigned instead of a `UIColor`

Fix crash loop caused by a typo

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift

* `ZMUserSession.resetStateAndExit` already calls `exit(0)` after deleting the keychain items (for the QA logout function), but it does this async and the app was terminated before the keychain could be deleted.

Fix keychain deletion on logout

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ProgressView.swift

The midi player reports incorrect progress. 
More general issue is that midi does not really play. This we can fix in the future by declaring midi as a non-media type or finding the way to play it.
Guard for correct progress in `ProgressView`

Guard for non-nan progress

---

Wire-iOS/Resources/Base.lproj/InfoPlist.strings

Use parallel constructions: “Allow Wire to access…”
@teller This fixes the issue you raised with the “You would be able to…” copy, which was introduced on September 23 in fe24cba with Feature/swift3 (#235).

Align permission request copy

---

Wire-iOS Tests/Settings/SettingsPropertyTests.swift
Wire-iOS/Sources/AppDelegate+Hockey.m
Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
Wire-iOS/Sources/UserInterface/Settings/SettingsNavigationController.swift
Wire-iOS/WireBridgingHeader.h

We continue to use hockey when user selected not to track.
Check the proper settings and sync the state between hockey and localytics.

Disable Hockey when localytics is disabled

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift

* Move dark theme toggle and send button toggle into new settings section "By popular demand" in the options menu.
* Extract options descriptor into it's own file.
* Move the dependency version info into the advanced section and add the build number to the footer in the about section

Move dark theme and send button into new options section

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_objects.plist
Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_symbols.plist
Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_travel.plist
Wire-iOS/Sources/UserInterface/Conversation/InputBar/EmojiSectionViewController.swift

* Don't animate scrolling to a emoji section when the user pans between the sections.
* Update section selection in `scrollViewDidScroll` instead of `collectionView(willDisplayCell:)` as it's not ensured there there will be new cells displayed when the selection should change.
* Some emoji were missing their correct variation selector to be displayed properly (`U+FE0F`).

Fix slow performance when scrolling in emoji sections

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
Wire-iOS/Sources/UserInterface/Helpers/KeyboardHeight.swift
Wire-iOS/Sources/UserInterface/Helpers/UIView+Zeta.m

* Larger emoji in the keyboard on iPad.
* Increase right margin of the new send button.
* Update default keyboard sizes with values for different device types.
* Don't show send button when editing
* Do not allow switching from emoji to text input with tap on input field, only tapping the text input button should show the alphabetic keyboard again.
* Whitespace only text should not trigger the send button to be shown in the input bar.

Update emoji size on iPad and right margin of new send button

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* If an edit of a message was started while there was text input in the input bar / the send button was visible, then we did not update the state of the send button correctly.

Fix send button staying visible when starting edit with text input

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Analytics/Events/Analytics+EmojiKeyboard.swift
Wire-iOS/Sources/Analytics/Events/Analytics+SendButton.swift
Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* Add tracking for emoji keyboard with event name `media.opened_emoji_keyboard`.
* Add tracking for the send button setting with event name `settings.changed_send_button_option`

Add tracking to emoji keyboard and send button setting

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ZMConversationMessageWindow+Formatting.m

Showing the delivery receipts was suppressed due to rollout schedule. Now it's time to show them.

Re-enable delivery receipts showing

---

Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift

The alert was shown over controller that has modal presented. 
Now alert is shown over current topmost controller.

Show correctly name set error on iPad

---

Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift

Crash on this line:
> `suitableEffects[Int(arc4random()) % suitableEffects.count]`
On 32-bit platforms, `Int` is actually `Int32` which ranges from `-2^31` to `2^31-1`. However `arc4random` returns `UInt32` up to `2^32-1`. I think the crash we were seeing was on 32-bit machine generating a random that was too big to fit in `Int32`.
Additionally, according to Apple's documentation:
> arc4random_uniform() is recommended over constructions like ``arc4random() % upper_bound'' as it avoids
> "modulo bias" when the upper bound is not a power of two.
(https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/arc4random.3.html)
so I replaced all `arc4random() % ...` with `arc4random_uniform()`

Use safer random functions

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/TypingIndicatorView.swift

Crash because observer was not unregistered

Remove observer on deinit

---

Wire-iOS/Resources/Classy/stylesheet.cas
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* For some reason classy got confused after a vie controller was presented modally and the send button lost it's styling. Using a style class fixes this issue.

Fix wrong send button color after presenting modal view controller

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

The cursor hint (& feature name) is TIMED MESSAGE to correspond with the hourglass icon that accompanies it, and the timer setting copy helps explain that timed messages are temporary.

Update ephemeral messaging copy

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Resources/Classy/stylesheet.cas
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarButtonState.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
WireExtensionComponents/Views/Buttons/IconButton.h
WireExtensionComponents/Views/Buttons/IconButton.m

* Use ephemeral color for send button when in ephemeral mode
* Extract button hide logic into a separate class to declutter the `ConversationInputBarViewController` a bit.
* Add a flag to `IconButton` to adjust the backgroundImage when highlighted.
* The hourglass is now only shown when in not in ephemeral mode and no text is in the input bar, the destruction time indicator is shown when no text is in the input bar but when in ephemeral mode.
* This also includes some fixes to the destruction countdown being shown before the actual timer did start which resulted in it being shown with a fraction of 0 initially.

Use ephemeral color for send button when in ephemeral mode

---

Wire-iOS/Sources/Helpers/syncengine/Message.m
Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadView.m

* Enable chatheads for ephemeral messages again, but using the redacted font.

Enable chatheads for ephemeral messages using the redacted font

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Resources/de.lproj/Localizable.strings
Wire-iOS/Resources/es.lproj/InfoPlist.strings
Wire-iOS/Resources/es.lproj/Localizable.strings
Wire-iOS/Resources/it.lproj/InfoPlist.strings
Wire-iOS/Resources/it.lproj/Localizable.strings
Wire-iOS/Resources/it.lproj/Localizable.stringsdict
Wire-iOS/Resources/ja.lproj/InfoPlist.strings
Wire-iOS/Resources/ja.lproj/Localizable.strings
Wire-iOS/Resources/ja.lproj/Localizable.stringsdict
Wire-iOS/Resources/nl.lproj/InfoPlist.strings
Wire-iOS/Resources/nl.lproj/Localizable.strings
Wire-iOS/Resources/nl.lproj/Localizable.stringsdict
Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
Wire-iOS/Resources/ru.lproj/Localizable.strings
Wire-iOS/Resources/tr.lproj/InfoPlist.strings
Wire-iOS/Resources/tr.lproj/Localizable.strings
Wire-iOS/Resources/tr.lproj/Localizable.stringsdict
Wire-iOS/Resources/uk.lproj/Localizable.strings
Wire-iOS/Resources/uk.lproj/Localizable.stringsdict

What in this PR:
- Adding support for new languages: Japanese, Italian, Dutch, Turkish
- Small improvements to already existing strings
- Placeholder strings (in English) for ephemeral messaging, will be localised for next release

Adding new languages: Japanese, Italian, Dutch, Turkish

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* The conversation draft message text was reset for all input bar state changes, but it should only be reset in case the user finished to cancelled an edit.
* This also fixes an issue in which the right accessory view visibility was not updated in some cases (e.g. after finishing an edit).

Fix a regression which lead to the draft message text being reset

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m

* Tear down linkAttachmentController when message gets obfuscated or deleted
* This only applies if the message is in the view port, if the user scrolled the message out of the viewport we do not receive any change notifications and thus can not stop playing attachments, this is only an issue for Soundcloud link attachments as Vimeo and YouTube play fullscreen.

Tear down linkAttachmentController when message gets obfuscated or deleted

---

Wire-iOS/Resources/Magic/misc.plist
Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadView.m

* Fix too small bottom insets for ephemeral catheads using the redacted font

Fix too small bottom insets for ephemeral chatheads

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Resources/Classy/stylesheet.cas
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h

**These changes are only relevant for sending ephemeral messages (2.20)**
* Update ephemeral timeout indicator font weight.
* Update ephemeral timeout selection keyboard title copy.
* Use popover for ephemeral time selection on devices which are horizontally compact.

Move ephemeral keyboard into popover on iPad

---

Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.h
Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.m
Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadView.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m

We are removing `inactiveParticipants` from data model.
Do not rely on participant count to know if a conversation is one to one or group.

Remove reference to inactive participants and use conversation type instead of participants count

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Components/Settings+Logging.swift
Wire-iOS/Sources/Components/Settings.m
Wire-iOS/Sources/Developer/DeveloperOptionsController.swift

Need to debug some decryption errors, this will allow testers to set the log on once instead of having to set it every time they restart the app. This will also allow to get logs when we are decrypting the notification stream, which happens immediately and there is no time to switch on the log manually.
Save list of log tags that are enabled to user defaults

Persist log level switches between runs

---

Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift

* The type of the attributes dictionary was `[String: String?]` which resulted in `"Optional(\"31-60\")"` values being tracked.

Fix optional strings in audio message tracking

---

Wire-iOS/Sources/Helpers/syncengine/ZMAccentColor+Additions.swift
Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift

The indexes where not aligned between `ZMAccentColor.all()` array and `self.colors` array.

Fixed accent color selection when no yellow is shown

---

Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.h
Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.m
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift

As the method `leaveActiveCallsWithCompletionHandler` was changed from instance to static, the compiler seemed to ignore the fact that `self` was used in the method:
```
if (conversation == self) {
```
So one more reason to use Swift (it would detect this error on compilation).
It was impossible to join the call when callkit was disabled or on iOS 9.

Do not leave call when joining

---

Wire-iOS/Sources/Managers/SoundEventListener.m

We where not observing the call states in SoundEventListener in case we are using CallKit, because in this case iOS plays the incoming call sound. Now we observe it, but explicitly do not play incoming call and play other sound events.

Play ringing from me, do not play from them on CallKit

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift

* Move the "Open-In" options menu from the advanced group into the options group.

Move Open-In options from advanced to options settings menu

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift

People seem to frequently accidentally click on the call button in the big group chats, resulting in calling everyone in this chat. Especially bad experience happens when user clicks the button during the night time.
Confirm calls in chats with 5+ participants with an alert.

Confirm call in the group conversation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift

* There was an issue with the rounded corners of several cells not being present when the cells are shown for the first time.
* `layoutSubViews` is not called the first time a cell is created, which is why we need to call `setNeedsLayout()` and `layoutIfNeeded()` manually in the initializers of `AudioMessageCell`, `FileTransferCell` and `VideoMessageCell`.

Fix missing rounded corners when cells are presented initially

---

Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientUnregisterFlowViewController.swift

* When registering a new client with already the maximum number of clients registered we were showing the list of clients to let the user choose one to delete it. In this we included temporary devices as well, but the deletion of a users temporary client does not allow them to register a new, non-temporary one, as the limit of 7 clients is only counting the non-temporary ones.

Hide temporary user clients when registering a new device and hit client limit

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift

* This fixes [#7281](https://wearezeta.atlassian.net/browse/ZIOS-7448) and [#7448](https://wearezeta.atlassian.net/browse/ZIOS-7281).
* There was a bug with the delete for me option not being present if the message failed to send as well as in left conversations. The issue was that we were adding the delete `UIMenuItem` to the menu if a message can be liked. To ensure we do not show a delete for everyone if the message failed to sent an additional check has been added.

Enable deletion for the selfUser for failed to send messages and in left conversations

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationTitleView.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

* As `UINavigationItem` doesn't really play nicely with auto layout we are now just recreating the title view when the security status changes.

The conversation title view was truncated when initially verifying all clients

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/TextMessageCell+Internal.h

Link preview with multiple lines is cut because of link preview view height collapse. Fix is to force labels to be one-line in this case.

Fix for clipping message with multiline link preview title

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

* Change group title to “CALLS”
* Change setting toggle to "Share with iOS"
* Change explanation copy to:
> Show Wire calls on the lock screen and in iOS call history.
> If iCloud is enabled, call history is shared with Apple.
> Restart Wire to apply this setting.

Fix CallKit switch copy (#408)

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/IconSystemCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/PingCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/UIView+LayoutMargins.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift

**This PR contains multiple fixes for layout issues present when using the application on a device with a right-to-left layout direction ([#4822](https://wearezeta.atlassian.net/browse/ZIOS-4822), [#7665](https://wearezeta.atlassian.net/browse/ZIOS-7665))**
* Align text in text messages to the right.
* Fix input bar misalignment and emoji button location.
* Reverse system message cell alignment for RTL languages.
* Update alignment of the cells in settings for RTL languages.
There are still a lot of issues when using a RTL language which are tracked in [#7665](https://wearezeta.atlassian.net/browse/ZIOS-7665).

Add first fixes to support RTL languages

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Components/Transitions/PopTransition.m
Wire-iOS/Sources/UserInterface/Components/Transitions/PushTransition.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
Wire-iOS/Sources/UserInterface/ConversationList/SearchView/SearchViewController.m
Wire-iOS/Sources/UserInterface/Helpers/UIView+RightToLeft.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchSectionHeaderView.m
WireExtensionComponents/Views/TextView.m

**As follow up on https://github.com/wireapp/wire-ios/pull/416 this PR adds more adjustments for right-to-left languages:**
* `MessageToolboxView` is now correctly mirrored.
* The transitions in settings are adjusted for RTL.
* Some layout adjustments to controls in `CameraKeyboardViewController`.
* Mirror the conversation list correctly (indicator was clipped).
* Update input fields and their placeholders to use the correct text alignment.

Add more right-to-left layout adjustments

---

Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.h
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m

* Tapping user avatars in the search UI was broken with https://github.com/wireapp/wire-ios/pull/439 when the change was made to present the search UI, archive list etc instead of adding them as child view controller. Due to this change the `parentViewController` property was nil and we failed to present the controller.
* Remove some unused code as the common connections have been removed from the `ProfileDetailViewController`.

Fix user avatar tap not working anymore

---

Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionView.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationTitleView.swift

* The `ConversationTitleView` was showing the downwards arrow and was tappable in case of an outgoing connection request, which should not be the case as the presented profile detail view will display the same information.

Fix tappable title view in outgoing connection request

---

Wire-iOS Tests/UserNameTakeOverViewControllerTests.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationList+Handles.swift
Wire-iOS/Sources/UserInterface/ConversationList/UserNameTakeOverViewController.swift

* The wrong name was used in the `UserNameTakeOverViewController`.

Show name instead of displayName property in username takeover

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Analytics/Events/Analytics+Usernames.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationList+Handles.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/ChangeHandleViewController.swift

* Add analytics calls to the username takeover and the username screen in settings.
* This implements the first half of [#7675](https://wearezeta.atlassian.net/browse/ZIOS-7675).

Add tracking calls to username takeover screen and username settings

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

* The `ConversationTitleView` does not display the downwards arrow anymore if the conversation is not connected (and the user interaction is disabled), but it was not reloaded when the connection gets established.

Reload conversation title view on connection state changes

---

Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

The conversation list was extra sorted to pick the latest conversation by last date. This is not correct since the list is already sorted by last modified date.

Removed unnecessary sorting

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConnectionRequestCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

* The height of the `ConnectionRequestCell`, which should neither be used nor inserted anymore was set to 0, which unfortunately will make the table view set it to the default height of 40. We now set it to 0.5 to ensure the header view does not get pushed up (as we use a rotated tableview we actually set the footer view when setting a header view, but as the default position will be scrolled to the bottom the header view will be pushed out of the visible viewport).
* The underlying issue that we still insert connection request system messages into the conversation should be fixed in `wire-ios-sync-engine` which is tracked in [#7737](https://wearezeta.atlassian.net/browse/ZIOS-7737).

Fix header view moving up on successive connection requests

---

Wire-iOS/Sources/Managers/AddressBookHelper.swift
Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.h
Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileHeaderViewModel.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.h
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileHeaderView.swift
Wire-iOS/Sources/UserInterface/UserProfile/Views/UserNameDetailView.swift

* Request refreshing user data when entering a connection view.
* Use a search users underlying user (if there is one) to access an eventual address book entry.
* Use properties from bare user instead of casting it (this was causing a missing username and common connections label when the profile details were opened from search for an unconnected user).

Use the search user and it's underlying user when presenting profile from search

---

Wire-iOS/Sources/AppController.h
Wire-iOS/Sources/AppController.m
Wire-iOS/Sources/AppDelegate.m
Wire-iOS/Sources/Managers/AddressBookHelper.swift

* We now persist the last address book authorisation status so we can check if it changed on app start.
* If the status changed and became available we upload the address book immediately.
* We also check if we should upload the address book every time the application enters the foreground and not only on network reachability changes.

Add check if address book access status changed and upload if it became available

---

Wire-iOS/Sources/UserInterface/ContactsUI/ContactsDataSource.m

Contact search results from SE are in the "non-connected" users (otherwise they would already be displayed as a user); the UI was expecting them to be in "connected". This PR changes that.

Show contact search from address book

---

Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m

* Remove unused common contacts search token code as we receive the amount of common contacts through the search results.

Remove unused common contacts search token code

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationList+Handles.swift

* There was a bug preventing the takeover screen event to be tracked on non `.pad` devices, guard considered harmful.

Fix analytics event not being triggered on phones

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationList+Handles.swift

* The tracking call was only reached when on iPad

Fix tracking call for when username takeover is shown

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/IconSystemCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiSectionViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileHeaderView.swift

It comes out that inferring type for swiftc is a very challenging task sometimes. This unfortunately significantly decreases the overall compilation speed of the project, making it challenging to change the sources and run the app quickly.
The swiftc option to warn about functions that are taking too long to compile is used: `-Xfrontend -warn-long-function-bodies=1000` where 1000 is the duration in milliseconds that is minimum required to generate the warning. The option is set only for debug builds, so the new code can be checked against compiler performance.
The compilation on different computers can take different time, but as option is set only on debug configuration, the issues should not disrupt CI (but make it faster). On the other hand, the developers supposed to have the …

Fixed swift type infer performance

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* This fixes [#7734](https://wearezeta.atlassian.net/browse/ZIOS-7734), a jumping `UserConnectionView` when an outgoing connection request gets accepted. 
* Hide the input bar view controller instead of collapsing it.
* There was an issue with the username label jumping up once an outgoing connection request got accepted, which was caused by the input bar height being expanded and thus the table view size decreasing. As the table header view is actually a footer view and attached to the bottom (as we use an upside down table view) we need to create the view in the correct size for it to appear with the image in the center. Thus the header moved up once the table view size decreased.

Set input bar hidden instead of collapsing it

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* Align emoji and send button sticky to the bottom instead of to the top of the input bar.
* Increase the hit area of the send button to the right.

Add input bar send and emoji button improvements

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m

* Opening a 1-on-1 conversation was not tracked (see [#7675](https://wearezeta.atlassian.net/browse/ZIOS-7675)).

Insert missing tracking call when opening one-on-one conversation

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationList+Handles.swift

* We were tracking the result of a tap on the `"Keep suggested"` button on the takeover view controller when we receive the callback from sync-engine. When selecting choose own we do not remove the observer as we want to dismiss the controller once a different username has been chosen, this lead to non matching tracking numbers as the keep suggested event was tracked in this case as well.
* The intention of the user is more important so we now track the button taps directly.

Track button taps instead of waiting for BE results

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/ChangeHandleViewController.swift

* There was a crash when trying to input an emoji as username.
* We now check if the handle, which we already checked to be composed out of the valid characters is equal to its transliteration to Unicode names. As alphanumerics will stay the same in this process but emoji will be transformed in a way like `🐷 → {PIG FACE}` we can know that there is an invalid character.
* I previously tried to make this more generic an detect emoji in a string in general, however as other non-emoji characters are not equal to their Unicode name this does not work (see https://github.com/wireapp/wire-ios-utilities/pull/10 for more information).

Fix crash when using emoji as handle input

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift

Messages are already ordered by timestamp in a descending order. They do not need to be resorted in the UI.

Messages are already ordered by descending timeStamp

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift

We need to call tearDown on the AssetCollection to avoid ongoing fetchRequests which might be blocking sync tasks.

Cancel fetchRequests when closing the Collection VC

---

Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel.m

This will cause sorting in many cases where this is not needed, but is guaranteed to fix the order

Force sort conversation list on coming back from background

---

Wire-iOS/Sources/AppController.m
Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+iOS.h
Wire-iOS/Sources/Managers/AddressBookHelper.swift
Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationNewDeviceCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/ChangeHandleViewController.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientUnregisterFlowViewController.swift
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
Wire-iOS/Sources/UserInterface/Settings/SettingsNavigationController.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift

In some cases, the user session could still be nil (e.g. if performing a migration). However it was forced unwrapped in a few cases, e.g. when checking whether to upload the AB.
Now I'm using the user session as optional, and I don't start the AB upload if the session is not there yet

Fix shared user session assumed to be not nil when uploading AB

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
Wire-iOS/Sources/UserInterface/Components/Controllers/RotationAwareNavigationController.swift

- Collections view used to rotate on iPhone
- Collections view has a broken layout after rotation
- On dark theme the status bar color is not correct

Fixed rotation bugs for collections

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
Wire-iOS/Sources/Analytics/Analytics+iOS.h
Wire-iOS/Sources/Analytics/Analytics+iOS.m
Wire-iOS/Sources/Analytics/AnalyticsConsoleProvider.swift
Wire-iOS/Sources/AppDelegate.m

This PR adds a new analytics provider that will simply log in the console the requests sent to analytics. Used for debugging purposes.
Insert `-ConsoleAnalytics` as command line argument to force enable console logging.

Add console provider for analytics that can be enabled by command line

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

The ’get.wire.com’ variant is used in more places and offers platform-specific redirects that take users directly to the app stores on supported platforms.

Align download links

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Unifying copy between platforms, using singular "Collection" everywhere.
CC @priiduzilmer @olivereitalu @Yorgos-V @infotexture

Changing "Collections" to singular "Collection"

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m

With the new collections icon, some people are accidentally clicking the collections button instead of the back button. 
Initial approach is to increase the tap area of the back button and move it a little bit to the right.

Make back button bigger & update the collections icon

---

Wire-iOS/Sources/Helpers/UserClient+Fingerprint.swift
Wire-iOS/Sources/Permissions/ShareContactsViewController.m
Wire-iOS/Sources/UserInterface/Components/FormGuidance/FormGuidance.m
Wire-iOS/Sources/UserInterface/Components/Giphy/GiphyNavigationBarController.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationIgnoredDeviceCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/Message+Formatting.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Headers/GroupConversationHeader.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/InviteBannerViewController.m
Wire-iOS/Sources/UserInterface/Helpers/NSString+Fingerprint.m
Wire-iOS/Sources/UserInterface/Helpers/TextTransform/UILabel+TextTransform.m
Wire-iOS/Sources/UserInterface/Registration/EmailInvitationStepViewController.m
Wire-iOS/Sources/UserInterface/Registration/EmailVerificationStepViewController.m
Wire-iOS/Sources/UserInterface/Registration/TermsOfUseStepViewController.m
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIView.m
Wire-iOS/Sources/UserInterface/UserProfile/Views/ParticipantsDeviceHeaderView.m
WireExtensionComponents/Utilities/AttributedStringOperators.swift

According to the issue that QA detected, the use of mutable attributed strings in the UI with automation causes crashes: http://www.openradar.me/25623858
I did not found the particular issue, but it looks like the + and && operators are returning the mutable attributed strings. I updated the implementations to always return the immutable instance, which also seems to be a correct approach.

Use immutable attributed strings

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m

* There was a bug when creating an `ArticleView` in `TextMessageCell`, for forwarding we do not want to show the image, but if there is none and the context is not forwarding we do not want to show one as well.

Fix showing image placeholder in link previews in text messages cells.

---

Wire-iOS Share Extension/ShareViewController.swift

Archived conversations were not listed in conversations list and it was not possible to share to them.

Share extension: show archived conversations in the list

---

Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift

Tests where failing when extracting a property that was set as a boolean, because it was extracted as a number instead.
I just fixed the casting to the right type (number/bool). However the entire SettingsPropertyValue system seems a bit complicated and I think it could be simplified in more concise code. Let's keep it in mind for the future.

Fix failing property tests

---

Wire-iOS.xcodeproj/project.pbxproj

With adding share extension and thus app group to our project we needed to define proper development teams and signing identities to all targets.
Also removed references to exact provisioning profiles (PROVISIONING_PROFILE is deprecated now, PROVISIONING_PROFILE_SPECIFIER should be used instead).

Fixed app and share extension signing for the release

---

Wire-iOS Share Extension/SendableBatchObserver.swift
Wire-iOS Share Extension/SendingProgressViewController.swift
Wire-iOS Share Extension/ShareViewController.swift
Wire-iOS.xcodeproj/project.pbxproj

* The batch observation of sendables was done in `SendingProgressViewController`, to clean this code up it is now contained in a separate class responsible for batch observing, the `SendableBatchObserver`.
* The observer is owned by the `ShareViewController`, which now updates the `SendingProgressViewController` on progress changes as well as dismisses the share extension when all messages have been sent.
* There is a new field `progressDisplayDelay` which I experimentally added and which is currently set to 0.5 seconds. The set time will delay the display of the progress and will dismiss the extension without showing the progress if all messages are sent in that time (which in case of 0.5 seconds should be enough for one text message in good network conditions), if they are not sent the …

Extract batch observing of sendables and delay progress view controller push

---

Wire-iOS Share Extension/SendableBatchObserver.swift
Wire-iOS Share Extension/SendingProgressViewController.swift
Wire-iOS Share Extension/ShareViewController.swift

* Share extension sending cancellation broke due to changes made in https://github.com/wireapp/wire-ios/pull/550, this PR fixes this.

Fix share extension sending cancellation

---

Wire-iOS Share Extension/Base.lproj/Localizable.strings
Wire-iOS Share Extension/ShareViewController.swift

* Change post button title and add Wire logo to the navigation bar in the share extension.

Change share extension copy and add wire logo

---

Wire-iOS Share Extension/ShareViewController.swift

When sharing a file, there is no title and no icon. We want to display an icon instead.
When there is no icon, `super.loadPreviewView()` will return `nil`. So I just display the icon every time the preview is `nil`, we have no text and there is a URL. 
I can not check that the URL is a `file://` (which would be safer) because this is an async operation that will run on the main thread on the next run loop, and the `loadPreviewView()` must return synchronously.

Display an icon for files when sharing

---

Wire-iOS Share Extension/ShareViewController.swift

When sharing files from the share extension, the name of the file was a random UUID. This PR changes it to preserve the original file name, if any

Send files from share extension preserving the original file name

---

Wire-iOS Share Extension/ShareViewController.swift

Display a placeholder text in the share extension popup when there is no predefined text (e.g. for files)

Display a placeholder text in share extension

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift

With Swift 3.0.2, casting from a dictionary value to an Int (or Bool) will always fail if it is a NSNumber. It seem to have been working before. Fixed.

Fix not working boolean flags in settings screen

---

Wire-iOS Tests/ImageCacheTests.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Components/ImageCache.h
Wire-iOS/Sources/Components/ImageCache.m
Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift

- Possible to observe the end of images loading.
- Useful for writing async UI tests when waiting for the image cache to finish the processing.

Added dispatch group to image cache

---

Wire-iOS Share Extension/ShareViewController.swift

* There was a crash caused by force unwrapping an Optional, as the UTI does not provide information about the file extension in the case of `public.file-url`.

Fix crash when sending a file from iCloud

---

Wire-iOS Share Extension/ShareViewController.swift

* Immediately disable the share extension's send button once tapped.
* Add dismissal animation to share extension.

Immediately disable the send button when tapped. Add dismissal animation

---

Wire-iOS Share Extension/SendableBatchObserver.swift
Wire-iOS Share Extension/ShareViewController.swift

* Fix memory leaks.
* Reload `SharingSession` on each share extension start to ensure the conversation list is up to date (otherwise we would need to store and merge the change notifications from the main app into the extension which would be a lot).

Recreate sharing session on each share extension launch

---

Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

When the collection view is open and user selects other conversation with push we would like to close collection together with the old conversation view. This applies more generally to all cases when we change right controller in split view container.

Dismiss overlay when split view changes controller

---

Wire-iOS Share Extension/Base.lproj/Localizable.strings
Wire-iOS Share Extension/SendingProgressViewController.swift
Wire-iOS Share Extension/ShareViewController.swift

* The current way the share extension sends messages is by calling the `send` method, which prepares and appends all messages and then showing the progress view.
* As some messages, for example videos, need additional time to be prepared before being appended, the UI is stuck and the user does not get any feedback until the preparation has been done.
* This PR adds a workaround for this issue, a proposal for a better solution (which will take some refactoring and time) is appended at the end of this description.
* The workaround is to pass in an additional block that will only be invoked if there are items that need preparation into the `send` method.
* This workaround requires to keep track if the operation has been cancelled, as the messages might not yet have been appended they can not …

Show progress spinner when attachment needs preparation

---

Wire-iOS/Sources/UserInterface/Collections/CollectionHeaderView.swift
Wire-iOS/Sources/UserInterface/Collections/CollectionViewLeftAlignedFlowLayout.swift
Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift

- Incorrect initial layout (1)
- Crash on rotation on iPad (2)
- Crash on rotation in detail (picture) view and going back
The issue (1) is related to the fact that we are using the custom transition that lays out the view several times. The layout gets confused for some reason with the section headers (other items are laid out correctly). Before we used to invalidate the collection layout on every layout change, which seem to cause the infinite layout loop on automation.
Second issue is caused by the fact that we have different count of cells in images section in portrait and landscape. Asking the collection view to reload data does not help (it seems to cache the number of cells in the section for some reason). What helps is to reload the sections. Unfortunately this can only happen …

Fixed rotation layout issues

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift

* Disable collections for devices with a OS version below 8.3

Hide collections button for versions below iOS 8.3

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift

* We were dispatching to a different thread inside of a `ZMUserSession.performChanges`, which lead to the message being appended on the wrong queue.

Append file messages on the correct queue when forwarding

---

WireExtensionComponents/Controllers/ShareDestinationCell.swift
WireExtensionComponents/Controllers/ShareViewController.swift

* The forward UI did not contain any indication if the conversations are verified or not.

Show verified shield in forward UI

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift

Apart from renaming messageToolboxView to toolboxView :)
- `MessageToolboxView` content is lazy-loaded, so no unnecessary layout and views loading is performed for every cell
- Countdown view is also lazy-loaded for cells where it is actually needed
- PureLayout constraints are bulk installed. It comes out that it installs every constraint separately and every new constraint installation is making a performance hit.

Conversation views optimisation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

Issue happened when
- The counter was loaded once
- The cell gets reused for the new ephemeral message (which is a frequent case)
- Cell does not show the indicator

Fix for logical bug in countdown rendering

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/UserProfile/CopyableLabel.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift

* Add a `UILabel` subclass called `CopyableLabel` which can be selected and copied.
* Clean up the `ProfileClientViewController`, most of the properties were implicitly unwrapped optionals which was not necessary. also updated the access protection levels of most of the methods which do not need to be internal.

Add support to copy fingerprint label in device detail view

---

Wire-iOS Share Extension/PostContent.swift
Wire-iOS Share Extension/SendController.swift
Wire-iOS Share Extension/UnsentSendable.swift

* Add more documentation to the recently refactored share-extension classes (see the comments in https://github.com/wireapp/wire-ios/pull/594).

Add documentation to SendController and UnsentSendable

---

Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/FingerprintTableViewCell.swift
Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift

* d57732f Use `CopyableLabel` in `FingerprintTableViewCell` (this change was missed in https://github.com/wireapp/wire-ios/pull/623).
* 7f202ba Fix warning introduced with new Swift version.

Make fingerprint copyable in fingerprint cell

---

Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Private.h
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

When user selects accent color on iPad, the whole settings controller is dismissed.
Recently in SplitViewController was added the code to dismiss the modal controllers over the right controller when the right controller is changed. For some reason, when anything is presented over the app the right controller also says that it is presented over it. When the accent color changes we reload the conversation controller, which triggers the dismissal of the controller that is presented over the right controller. iOS dismisses the settings, so the user is getting confused.
I changed the conversation controller so it would keep track on it's own about the presented collection controller and dismiss it if it's being deallocated.

Fixed bug with dismissing settings as the result of color selection

---

Wire-iOS Share Extension/ShareViewController.swift

* It was possible to go to the home screen and open the main application while the share extension was still preparing or sending messages, which is undesired as the host app could pick up and send  messages, which are not yet marked as sent, again.
* We now subscribe to the `NSExtensionHostDidEnterBackground` notification in the `init` of the `ShareViewController`. If we receive this notification we ask the `PostContent` to cancel, which will only invoke the completion closure in case a preparing or sending operation is in progress, which is good as in any other case the share extension will not be dismissed and still be present when the user returns to the host application.

Cancel sending when the host application enters the background

---

Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m

iOS allows the automatic detection of many data types in the text:
```
UIDataDetectorTypePhoneNumber                                        = 1 << 0, // Phone number detection
UIDataDetectorTypeLink                                               = 1 << 1, // URL detection
UIDataDetectorTypeAddress NS_ENUM_AVAILABLE_IOS(4_0)                 = 1 << 2, // Street address detection
UIDataDetectorTypeCalendarEvent NS_ENUM_AVAILABLE_IOS(4_0)           = 1 << 3, // Event detection
UIDataDetectorTypeShipmentTrackingNumber NS_ENUM_AVAILABLE_IOS(10_0) = 1 << 4, // Shipment tracking number detection
UIDataDetectorTypeFlightNumber NS_ENUM_AVAILABLE_IOS(10_0)           = 1 << 5, // Flight number detection
UIDataDetectorTypeLookupSuggestion NS_ENUM_AVAILABLE_IOS(10_0)       = 1 << 6, // Information users …
```

Enable data detectors in conversation content

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Helpers/UIApplication+RTL.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationListBottomBar.swift
Wire-iOS/Sources/UserInterface/Registration/CountryCode/Country.m
Wire-iOS/Sources/UserInterface/Registration/CountryCodeView.m
Wire-iOS/Sources/UserInterface/Registration/GuidanceLabel.m
Wire-iOS/Sources/UserInterface/Registration/NavigationController.m
Wire-iOS/Sources/UserInterface/Registration/PhoneNumberStepViewController.m
Wire-iOS/Sources/UserInterface/Registration/PhoneNumberViewController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationTextField.m
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
WireExtensionComponents/Views/Buttons/IconButton.m

Several fixes for layout issues in RTL languages:
* Registration and login fields had problems, especially the phone number input.
* Arrows in registration screens were pointing the wrong way
* Contacts list button from the conversation list screen was overlapping the label
* Contact name in the contacts list had wrong alignment

Layout fixes for right to left languages

---

Wire-iOS/Sources/AppDelegate.m

After changing to localytics auto integration the app's UIApplication.sharedApplication.delegate is replaced with Localytics multicast delegates wrapper. This forwards all messages to our app delegate, but still can potentially bring issues with being not the AppDelegate we as developer expect from UIApplication.sharedApplication.delegate. 
Solution is to save the reference to the original app delegate to the static variable and return it's value in `sharedAppDelegate`.

Do not rely on UIApplication.sharedApplication.delegate value

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

Even with RTL layout we have the conversations list opening on the same side, so it makes sense to keep the toolbar buttons in the same order as well.

Right to left: keeping the same conversation list toolbar buttons order

---

Wire-iOS/Wire-Info.plist

Itunes Connect always checks on submission if the app's encryption algorithms are changed. If it's not, they suggest to add this key, so they don't have to ask any more.
The downside is if we actually change the encryption then we have to remove it.

Added the key for the itunes connect to indicate no encryption changes

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Settings/ChangeEmailViewController.swift

* Showing proper error message when something goes wrong
* Providing feedback when resending confirmation email
* When coming back to email edit screen after e.g. mistyping email, your original email was shown, not the edited one.

Email changing: fixing several small issues

---

Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Settings/LinkOpening/LinkOpener.swift

1. Fixed the behavior on iOS 9 when certain kinds of detected elements where not possible to open.
The issue happened when the special iOS internal kind of URL was provided for address and other special types and we tried to open it directly.
2. The issue with iOS integrated menu with "Add to reading list" and other default elements where displayed for long press menu on the URL. Now we display the default menu instead.

Fixes for data detectors

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelController.h
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelController.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m

This popup was preventing you from making a while in a call when the call
UI was not fullscreen.

Remove warning popup about concurrent calls

---

Wire-iOS/Sources/Components/Settings.m

It was decided to lock the next release into using calling protocol 2.

Make calling 2 the default protocol for now

---

Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift

Apparently in current observer system there is a bug that causes the `changeInfo.fingerprintChanged` not to be initialized. As far as I know the change flags are going away anyway so the code is updated to reload fingerprint for any `UserClient` update.
Also updated to new method name `markForFetchingPreKeys` -> `fetchFingerprintOrPrekeys`

React to fingerprint update

---

Wire-iOS Tests/Settings/SettingsPropertyTests.swift
Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift
Wire-iOS/Sources/UserInterface/Settings/LinkOpening/LinkOpener.swift
Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift

* When retrieving a value from the UserDefaults we were losing the type information, specifically if the value we set represents a `Bool` or for example an `Int`, this lead to bugs (e.g. [#8005](https://wearezeta.atlassian.net/browse/ZIOS-8005)).
* We now store all numbers and booleans as `NSNumbers`, the `.bool` case has been removed from the `SettingsPropertyValue`.
* Convenience initializers have been added to the `SettingsPropertyValue` to create a new value using an `Int`, `Bool` or `UInt`, this avoids duplicated `NSNumber` wrapping on the caller side.
* A test to catch the bug storing an integer value higher than 1 has been added, before this change retrieving the value would result in a `true` / `1` being returned.
* Add `@discardableResult` to `open()` method on `URL` to remove …

Remove .bool case from SettingsPropertyValue

---

Wire-iOS/Sources/Managers/SessionObjectCache.h
Wire-iOS/Sources/Managers/SessionObjectCache.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel.m

Instead of resorting the list when re-entering the foreground, it should be recreated. Otherwise conversations that were inserted or deleted while the app was in the background may not be included in the list.
Note: This need a new ZMCDataModel release with https://github.com/wireapp/wire-ios-data-model/pull/151
and then retested before merging

instead of resorting, recreate conversationlists

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Helpers/UIViewController+Errors.m
Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangePhoneViewController.swift

Adding ability to remove phone number if you have both email and phone in your profile.
This is part of the functionality needed for #665, split into a separate PR to make it smaller.

Phone number removal

---

ConfigurationSets/Wire-Share-Extension.debug.xcconfig
ConfigurationSets/Wire-Share-Extension.release.xcconfig
Wire-iOS.xcodeproj/project.pbxproj

* Remove leftovers from HockeySDK integration using CocoaPods (e.g. framework search paths etc.)

Remove leftovers from HockeySDK integration using CocoaPods

---

WireExtensionComponents/Utilities/AutomationHelper.swift

We would like to log tags that we log through ZMLog via command line. This should enable us to add a comma separated list of tags to log.

Add command line argument for logging tags

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

A conversation's participants' displayNames are now calculated on the fly for each conversation.
There is still a bug: the selfUser currently shows their fullName. Will be fixed tomorrow.
Names in the reaction list should still always be givenNames.

Use conversation based user displayNames for message sender names

---

Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift

Verifying clients did not update the shield, because the operation was not wrapped in a block with a save.

Wrap device verification in enque block to make sure we save

---

Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter+ConversationImages.swift

When the swiping view is opened from the conversation the images order must be inverted to match the logical images stream direction (top-down to left-right).

Inverse images order in fullscreen images view

---

Wire-iOS Tests/ZMSnapshotTestCase.m

* Add a test failure when running snapshot tests with the wrong simulator.

Add a test failure when running snapshot tests with the wrong simulator

---

WireExtensionComponents/Views/TokenField/TokenField.m

First token in the input field got `maxTitleWidth` == 0 because the value is calculated based on the input field size, and it is 0 because the layout pass is not yet done.

Update token.maxTitleWidth when token created before layout

---

Wire-iOS/Sources/Analytics/AnalyticsVoiceChannelTracker.m

Display popup in case of AVS I/O error on internal builds. We want to monitor how often this happens on internal builds

Display popup in case of AVS I/O error on internal builds

---

Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.h
Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

We where not hiding the conv list view when the conversation was open, therefore drawing the voiceover quite useless.
- Also removed "expanded" mode for left view controller when it used to occupy the whole viewport, for example in self profile;

Fix conversation list visible in conversation (voiceover)

---

Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchViewController.swift

* Adjust when we show the "No Results" screen and when an empty screen is shown in the search.
* Clear the last search when tapping the cancel button or deleting the last valid character.

Adjust no results and empty screen in search

---

Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m

- The left view should be always visible on iPad - landscape

Fix left controller visibility after rotation on iPad

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m

- So the observers can see the new file message
@evr3n this would most likely fix automation for files/video/audio sending

Wrap file sending with performChanges

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Not all people are “friends”, particulary in a business context.
(Aligning this recently-added string with invitation copy that appears elsewhere in the app.)

Invite “people” (not “friends”)

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/AppController.m
Wire-iOS/Sources/Managers/FileBackupExcluder.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/RecentlyUsedEmojis.swift
Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ConfirmPhoneViewController.swift

- Logic can be used for other random files that iOS creates

Logic to exclude emoji cache from the backup

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/ContactsUI/ZMAddressBookContact+LocalInvitation.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/InviteActionSheet/ShareItemProvider.m

* Use most recent (username) variant for all three
* Drop trailing punctuation per YV preference

Align invitation copy

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/AppDelegate.m
Wire-iOS/Wire-Info.plist

- Customers complained about us using the permanent ad ids
- Localytics needs this to track FB installations
- Removing it and using localytics seems to work out of the box

Remove AdSupport.framework

---

Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m

* There was an issue in the `SearchResultsCell` not showing the username in specific cases as we did not use the underlying user of a bare user.

Fix username not being shown in search results for some users

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift

- Link preview permanent URL could be redirecting to the incorrect location, for example
- Malicious websites.
- iframes (we use the outer frame html as the link preview source).
- Websites with broken but present link previews.

Use original link per default in the link preview

---

Wire-iOS Share Extension/UnsentSendable.swift
Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
WireExtensionComponents/Utilities/ExtensionSettings.swift

* Remove the developer options to disable fetching link previews when sending from the share extension.

Remove toggle to disable link preview fetching when sending using share extension

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

* We were dismissing the image view controller when deleting an image from the image view controller before the user selected if the message should be deleted for everyone or not.
* The same issue was occurring when linking a message from the same view controller.
* The completion handler of the `DeletionDialogPresenter` was not invoked in case the user selected the cancel option, which lead to the cell in the conversation not being deselected.

Do not dismiss image view controller when showing deleting dialog

---

Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m

* Adjust the constants used for the context menu revelation in the conversation list. Swiping very fast should trigger the menu now.

Adjust swipe to reveal constants

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* Workaround for `UITextView` truncating the text in some cases.
* Fixes https://github.com/wireapp/wire-ios/issues/370.

Add workaround to fix UITextView truncation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

- With the current design it is hard to understand that tapping on file icon opens it
- Already working like that in collection
- It was decided to unify with images too: now tapping on image once is opening it

Open images and files by one tap

---

Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/TopPeopleLine/TopPeopleLineSection.m

* We cache the previous top people computation result but were not using it until now.

Show cached top people results immediately

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift

* Set output device to earpiece initially when playing audio message.
* Fixes https://github.com/wireapp/wire-ios/issues/725.

Set output device to earpiece initially when playing audio message

---

Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+PullToDismiss.h
Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+PullToDismiss.m
Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m

The method `gestureRecognizerShouldBegin` was implemented both in `FullscreenImageViewController` class body, and in the extension. Which leads to the undefined behavior.

Fixed double method implementation for gestureRecognizerShouldBegin

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* https://github.com/wireapp/wire-ios/pull/764 added a workaround to fix `UITextView` truncating its content. However, this workaround broke the text view on iOS 8. This PR makes the workaround conditional.
* This PR also fixes the access control modifiers in `AudioMessageView`.

Disable text view workaround i os 8

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

Elderly people and regular users are liking images when they want to look at them.

Disable double tap to like image

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* https://github.com/wireapp/wire-ios/pull/777 against `release/2.31`.

Add OS version condition to text view workaround

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

It was crashing when showing the menu for a not downloaded file message because then
there are no additional actions and we try to put the like action at index 1. The fix
is to add a check if the actions list is empty.

Fix crash when showing menu for file cell

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraCell.swift

- The camera feed follows the device physical orientation (since it's attached to the device physically :) )
- The UI orientation is fixed to portrait on the iPhone, and it is rotating on the iPad
- We have to rotate the video feed only on the iPad to compensate the UI rotation

Do not rotate the camera feed on the iPhone

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

* We update the state of the input bar from `viewDidLoad` which is fine, we just shouldn't do it animated.
* This PR also inserts some missing calls to `didMoveToParentViewController` (`addChildViewController` only calls `willMoveToParentViewController` internally).

Fix flickering input bar when opening a conversation

---

Wire-iOS/Sources/Managers/ColorSchemeController.m

The underlying issue seems to be caused by Classy and the reason is unknown. This workaround fixes the problem, but we should find the root cause as well.
N.B. This PR merges to the `release/2.32` branch

Workaround for call overlay buttons loosing background color

---

Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.h
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift

The underlying reason was that the video view is created when setting `videoViewFullscreen = true`. In the Obj-C version it was assigning it to ivar, bypassing the setter.

Fix: video permissions dialog is shown on audio calls

---

Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
Wire-iOS/Sources/UserInterface/Settings/LinkOpening/BrowserOpening.swift
Wire-iOS/Sources/UserInterface/Settings/LinkOpening/LinkOpener.swift
Wire-iOS/Sources/UserInterface/Settings/LinkOpening/MapOpening.swift
Wire-iOS/Sources/UserInterface/Settings/LinkOpening/TweetOpening.swift

* When we enabled data detectors in `LinkInteractionTextView` the behaviour when tapping on a link was broken. The text view no longer asked its delegate to open a link but instead opened it by itself, which means opening it using Safari.
* Also added some debug logs to the link opening logic which can be enabled using the `"link opening"` log tag.

Fix links without previews not opening in third party applications

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift

* Since we removed the animation in https://github.com/wireapp/wire-ios/pull/800 we failed to actually set the input bar state.
* Fixes [8221](https://wearezeta.atlassian.net/browse/ZIOS-8221) and [8243](https://wearezeta.atlassian.net/browse/ZIOS-8243).

Set input bar state correctly

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/Message+Formatting.m

* Emoji were not displayed enlarged with Markdown enabled.

Fix large emoji not being displayed

---

Wire-iOS/Resources/Classy/stylesheet.cas

Snapshot tests failed because call button lost its background color ¯\\\_(ツ)_/¯

Call Overlay: fix failing tests

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ZMConversationMessageWindow+Formatting.m

* The ping cell no longer shows the author image, which is why we now always show it in case the previous message is a ping.

Show sender if previous message is ping

---

Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift

- Issue happens when user clicks on the bottom part of the bar. If all the buttons are having the bigger tap area the bottom invisible row of buttons is receiving the tap.

Set regular tap area on bar buttons to avoid overlap

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift

- Also fixed overlapping collections placeholder, when:
- Open collections in the empty conversation.
- Close it.
- Post asset.
- Open collections again.

Fixed swipe back from collections first screen

---

Wire-iOS Tests/ParticipantCellTests.swift

* The `ParticipantsCellTests` are flaky, looks like the contained `UICollectionView` sometimes isn't fully done layouting and moves the cells 1pt downwards.

Add tolerance to flaky tests

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift

Sharing a link with text would freeze the app (stuck in Autolayout)
Hide the toolbox before reusing the cell for forwarding
Thanks to Mike for the fix

Hide the toolbox before reusing the cell for forwarding

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/IconSystemCell.swift

* The line to the right of the `UILabel` in `IconSystemCell` was pinned to the top with a hardcoded distance. With dynamic type the font size can change and the label will not be aligned to the center of the first line of text in the label anymore. 
* We now calculate the y-Position of the center of the first line of text to take changing fonts into account.

Pin line view to xHeight of the first line of text in IconSystemCell

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

- Background view controller manages the status bar background.
- On iPad an on the iPhone the logic is identical, the content is under the status bar.
- New notification to observe the current status bar state.

Refactored status bar logic for conversation list

---

Wire-iOS/Sources/Managers/SoundEventListener.m

Using `remoteIdentifier` for mapping conversation call state was causing a crash because remote identifier might be nil. `ObjectID` will never be nil (worst case: it will be a temporary one).

Use objectID instead of remoteIdentifier for mapping conversation call state

---

Wire-iOS/Resources/Magic/conversation.plist
Wire-iOS/Resources/Magic/people_picker.plist
Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchResultCell.swift
Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionView.swift
Wire-iOS/Sources/UserInterface/ContactsUI/ContactsCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCell/ParticipantsCollectionViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ReactionsView.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsCollectionViewCell.m
Wire-iOS/Sources/UserInterface/Conversation/ReactionsList/ReactionCell.swift
Wire-iOS/Sources/UserInterface/ConversationList/SearchView/SearchView.m
Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadView.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelParticipantCell.m
Wire-iOS/Sources/UserInterface/Participants/ParticipantsListCell.h
Wire-iOS/Sources/UserInterface/Participants/ParticipantsListCell.m
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/TopPeopleCell.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
WireExtensionComponents/Views/UserImageView.h
WireExtensionComponents/Views/UserImageView.m

UserSession has to be injected now, since the UserImageView is ported to WireExtensionComponents, and there the user session is not possible to have.

Fix crash in UserImageView (missing UserSession)

---

Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel.m

- We used to calculate the changeset for UITableView (default value of moveType is NSTableView).

Fixed crash when conversation list updates with move

---

Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel.m

- Capture the list state that was used to calculate the update to use in the collection view data source.
- Removed the check for initial sync completed (this most likely caused the crash on automation).

Conversation list update fixes

---

Wire-iOS/Sources/Developer/DebugAlert.swift
Wire-iOS/Sources/Developer/DeveloperOptionsController.swift

We get many log reports where it's not clear why they were sent.
If the log comes from a popup, include the message of the popup in the report

Add message to logs, and more warnings

---

Wire-iOS/Resources/Base.lproj/Localizable.stringsdict

* Merging back `release/2.33` into `develop` in 6e80fc97638b4276cc69c04c60581c10efe026dd removed a couple of used pluralisation rules.

Re-add pluralisation rules lost in merge

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCellBurstTimestampView.swift

* Respect `isShowingUnreadDot` property when showing separators.
* When `isSeparatorHidden` was set to `false` after `isShowingUnreadDot` was set to `tue` the state of the view was inconsistent.

Respect isShowingUnreadDot property when showing separators

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

* Conversations were not scrolled to the last unread message when opening them, it seems like placing the call to `scrollToRowAtIndexPath:` from inside ``viewDidLayoutSubviews` was to early. Unfortunately `viewWillAppear` is too early as well, so we will try if there are any visible effects placing it in `viewDidAppear`. If there are any then we need to investigate the underlying issue further (looks like some cell height calculations ore other layout is not fully done yet).

Move call to scroll to last unread message to viewDidAppear

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Several recent commits introduced terminology and typography regressions that should be aligned for consistency with our standard usage.

Align recent copy changes with preferred terms

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

* For v3 file / image messages the transfer state will change once the image is downloaded.

Check if transferState changes in message change info

---

Podfile

Updating Localytics SDK to latest available version: 4.3.0
According to their change log there should not be any major functional changes, just improvements to in-app etc messaging.
```
4.3.1: April 5th, 2017
Fixed a bug that caused In-App creatives in test mode to not be approprately responsive.
4.3.0: March 23, 2017
In-App Messaging improvements including:
Per campaign UI modification. Using a callback, a number of properties on the In-app campaign can be modified such as centered In-App aspect ratio, Banner In-App offset from the edges of the screen, full-screen In-App transparency, and dismiss button image, location and visibility.
A new campaign test mode UI including the ability to preview all creatives in an A/B test.
The ability to delay In-App campaigns triggered by "Session …
```

Updating Localytics SDK to 4.3.0

---

Wire-iOS Tests/ConversationStatusLineTests.swift
Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift

- System message about added participants is marked read automatically.
- The added participants are stored in `users` and not in `addedUsers`.

Conversation status: added participants

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift

* As requested by automation this adds an `accessibilityLabel` to the VBR switch in settings.

Add option to set a accessibilityLabel on UISwitch cells in settings

---

Wire-iOS/Sources/UserInterface/Helpers/NSString+Filename.swift

* Audio messages were temporarily stored in a file with a name created from the users name, this logic didn't work for users with emoji in their name (or other non-latin characters I assume). This PR fixes this issue and uses the `remoteIdentifier` instead of the users name.

Fix audio message temporary urls for users with non latin names

---

Wire-iOS/Sources/UserInterface/Components/Views/ImageToolbarView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

* Hide sketch button for GIFs.
* Don't scale down GIFs.
* Don't show border for images smaller than 48pt.

Don't scale down GIFs

---

Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m

* We were checking for the wrong voice channel state. 
* Warp the call to join the ongoing call in an `enqueueChanges` block.

Check for correct voice channel state and enqueue changes

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m

* Forwarding and sending from the start UI did not use the asset v3 setting.
* I am removing the assets v3 flag from `wire-ios-data-model` (as well as the strategies used to send v2 assets), but this is still work in progress and requires a lot of tests to be fixed.

Check assets v3 setting everywhere

---

Wire-iOS/Sources/Analytics/AnalyticsConversationListObserver.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelController.m

* There were some recent changes to the calling threading, which most likely broke the voice channel overlay in some rare cases. When using CallKit and accepting a video call form the lock screen no overlay was visible when returning to the application. 
* This PR adds a call to check for the current overlay state to ensure the UI overlay logic is not dependent on the calling order / notifications from SE.
* However this PR does not fix the fact that there are notifications that are not received in this special case, which could be related to the threading changes or the general fact that the UI might not yet be loaded at the point when the notifications are fired.

Update visible voice channel overlays when coming on screen

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m

* The `ConversationListViewController` somehow no longer was a `ZMInitialSyncCompletionObserver`, which it needs to be in order to only show the username takeover screen once the initial sync is done. This is due to the fact that the user might already have set a username on another device and we need to wait for the user to be refetched.

Re-add initial sync observer to conversation list controller

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+TopBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m

- The top bar was not added to intended `contentContainer` view.

Fix for showing the top bar together with username overlay

---

Wire-iOS/Sources/Managers/FileBackupExcluder.swift

* Try to exclude the whole Library directory from the iCloud backup. We currently exclude all relevant folders manually.

Exclude whole library dir from backup

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/Space.swift

- The update notification was throttled to avoid recreation of the spaces view.
- Spaces view was looking on the wrong instances of Spaces object.

Fix for spaces not working

---

.gitignore
Wire-iOS Tests/Info.plist
Wire-iOS Tests/TestSetup.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS.xcodeproj/xcshareddata/xcschemes/ImageNotificationExtension.xcscheme
Wire-iOS.xcodeproj/xcshareddata/xcschemes/NotificationFetchComponents.xcscheme
Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
Wire-iOS.xcodeproj/xcshareddata/xcschemes/WireExtensionComponents.xcscheme
circle.yml

* Sharing schemes for all extensions
* Added a NSPrincipalClass for test suite. XCTest makes sure it gets initialized only once and it's possible to add all global init code there. Currently it only has default time zone override which makes sure that snapshots are tested with the same timezone as reference images
* Setting a variable so that failed snapshots would be saved to a (git-ignored) folder in the root source directory. This enables us saving it in build artefacts for later inspection.
* Because the VM instance we get from Circle is completely empty it also doesn't have CocoaPods main repo. This takes around 7-9 mins to download, but we can use a handy script that instead of downloading it with Git from Github gets it from S3 and unzips in the right directory
* `xcodebuild` was …

Added CircleCI integration

---

Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift

- If there is at least one device in the list then the loading spinner would not be initially displayed.

Do not show loading if devices list is available

---

Wire-iOS Tests/ConversationStatusLineTests.swift
Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift

- The spec was not precisely implemented, the group actions should not be shown in case self user performed them.

Conv list: do not display self actions

---

setup.sh

A new Carthage version was just released, when running `carthage version` and the installed version is not the current one it will print something like:
```
*** Please update to the latest Carthage version: 0.21.0. You currently are on 0.20.1
0.20.1
```
Which our `./setup.sh` did not parse correctly.

Only check the last line of `carthage version` output

---

Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m

* Dismiss ProfileDetailViewController after removing user from conversation.

Dismiss ProfileDetailViewController after removing user from conversation

---

WireExtensionComponents/Utilities/DeveloperMenuState+Debugging.swift

* Enable pingback logs by default for internal builds.

Enable pingback logs for internal builds

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

This is called when the view disappears as well as when the textView stops being first responder (e.g. when the user scrolls in the list)

Also end typing when view disappears or user scrolls

---

Wire-iOS/Resources/Settings.bundle/Root.plist

* `Titles` and `Values` array have to be of the same count in order for the settings entry to appear.

Remove edge backend from Titles array to sync it with Values

---

Wire-iOS/Resources/Base.lproj/Localizable.stringsdict

New conversation list was missing copy string for received new file transfer for muted conversations

Adding missing copy string for new file in conversation list for muted conversation

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/DraftListViewController.swift
Wire-iOS/Sources/UserInterface/DraftsRootViewController.swift

* Adjust empty label visuals in drafts list.
* Fix status bar style change timing when dismissing `DraftsRootViewController`.

Adjust empty label visuals in drafts list

---

Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelController.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m

When we receive a call while we are already in a call and reject the new incoming call we are currently creating a new `VoiceChannelOverlayController` for the already ongoing call instead of reusing the old one. Furthermore we never deallocate the previously added `VoiceChannelOverlayController` except the last one we created. This leads to crashes when we receive another call in one of the conversations already observed by the left-over controllers.
This PR includes two changes: 
(1) It removes the previous childViewController
(2) It adds the voiceChannelParticipantController on viewDidLoad when the call is in callState connected

Reuse existing VoiceChannelOverlayController

---

Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift

`wcall_is_video_call` is not reliable until AVS has processed the start of the call on their thread.

Un-hide video view if we later discover that we are in video call

---

Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift

- Issue happens when the clients list is visible for the significant time (slow network).
- User is able to delete the self client, which leads to crash.

Filter out self client from clients list (if any)

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m

* Show "everything archived" label and update bottom bar archived state when active team changes.

Show everything archived label and update bottom bar archived state

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m

- The inset is bigger when team selector is visible.
- Property was nil at the time of the `ConversationListTopBar` creation.

Fix conversation list inset calculation

---

Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel.m

* Re-add removed call to reload conversation lists when entering foreground.
* The call was removed by accident when removing the `SessionObjectCache` (https://github.com/wireapp/wire-ios/pull/1031/commits/5326251ff3242a91ab610198ec6b55d224903ed8#diff-c400ceedcde8d0bf071098407ee787c8L309).

Re-add removed call to reload conversation lists when entering foreground

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Handles.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.h

Had to listen for user changes and update the label when teams change.

Fix: empty conversation label stays visible after team deletion

---

Wire-iOS/Resources/Classy/stylesheet.cas
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIView.m

- The button was covered by the overlay.
- Overlay contained black text over black.

Do not cover share button with overlay

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIQuickActionsBar.h
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIQuickActionsBar.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m

The fix is to initiate the call only after the conversation is created. However, @typfel found that there is a race condition because the conversation needs to exist remotely for this to work.
This PR partly fixes the issue, more robust fix coming soon.

Start UI: not possible to make a call to person without existing conversation

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m

`[ZMConversation existingOneOnOneConversationWithUser:inUserSession]` should not be used anymore. It also does the same as [user oneOnOneConversationInTeam:].
Also fixed: Profile image in detail view was still grey because team was not set.

Open team oneOnOne and set team in userImageView

---

Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.m
Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift

When creating a new group conversation from a one-to-one we should not filter out the existing participants. We also pre-select the one-to-one user.

Fix AddParticipantsViewController when creating a new group conversation from one-to-one

---

Wire-iOS/Resources/Base.lproj/Localizable.stringsdict

The copy that appears within group conversations when all other users have left the conversation should be consistent with the message that appears in the conversation list:
> Everyone left

Align in-conversation copy w/ conversation list

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift

They become visible only when searching

Not showing contacts when adding people in team conversation

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

A big white gap is visible instead of the input bar, because it was simply hidden but none of the views were resized to occupy the empty space.

Fix: whitespace visible after being removed from a group conversation

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift

We collapse the view when the keyboard is shown in order to be able to scroll to the end of the list. Issue happens on iPad where the higher level view is collapsed by the iOS, so we are collapsing it twice.
Check if the view controller is currently presented in popover by checking is any parent has a valid `arrowDirection` on it's `popoverPresentationController`.

Do not collapse the add participants view in popover

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

This would become visible only after app comes to foreground, so maybe the margins are added slightly later than we create the view.

Input bar has layout issue when pinned to superview margins

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift

* 1-on-1 team conversations should show the conversation content search, as the team might be deleted due to the transition to a multi account setup we check the `teamRemoteIdentifier` instead.

Show conversation content search for (ex-)team conversations

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
Wire-iOS/Sources/UserInterface/Helpers/UITextView+Autocorrect.swift

Users complained that when writing a message, the last word is not being autocorrected. The issue happens because the iOS does not know when we are taking the text from the input text view and therefore is unable to figure out when to trigger the autocorrect.
@alanddd

Autocorrect last word in the message

---

Wire-iOS/Sources/UserInterface/Helpers/UITextView+Autocorrect.swift

* Wrap `resignFirstResponder` and `becomeFirstResponder` in `UITextView.performWithoutAnimation` block.

Wrap resign- / becomeFIrstResponder in performWithoutAnimation block

---

Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift

https://wearezeta.atlassian.net/browse/ZIOS-8718
https://rink.hockeyapp.net/manage/apps/42908/crashes/search?per_page=10&query=cmethod%3AdesaturatedImageWithContext%2A&type=groups
This crash seems similar to https://forums.developer.apple.com/thread/21884 where an `EAGLContext` is not properly shutdown (`AVSVideoView`) which leads to a crash on the following `EAGLContext setCurrentContext:` which in this case is done by `CIContext`.

Fix crash on updating profile picture

---

Wire-iOS Tests/Mocks/MockUser.m
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/EphemeralTimeoutFormatter.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift

Adjust ephemeral timeout formatting. Unfortunately `ZeroFormattingBehavior.pad`  does not add a leading 0 to the first unit (e.g. 5:21 instead of 05:21), which is the reason we need to fallback to manual formatting in some cases.

Adjust ephemeral timeout formatting

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Invitations are not relevant in all contexts

Remove invitation references from conversation list

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

I just had to quickly implement the first part of https://github.com/wireapp/wire-ios/issues/1125 as it enhances the usability of Wire on iPad greatly and also makes sending messages on Simulator so much easier.

Add keyboard shortcut to send message (⌘⏎)

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

* The join call button was not properly updated when a call was terminated or even started while on the conversation screen.

Fix join call button not appearing and disappearing in some scenarios

---

Wire-iOS Tests/ArticleViewTests.swift
Wire-iOS Tests/AudioMessageCellTests.swift
Wire-iOS Tests/FileTransferCellTests.swift
Wire-iOS Tests/InputBar/InputBarTests.swift
Wire-iOS Tests/LocationMessageCellTests.swift
Wire-iOS Tests/LocationSendViewControllerTests.swift
Wire-iOS Tests/UnknownMessageCellTests.swift
Wire-iOS Tests/VideoMessageCellTests.swift
Wire-iOS Tests/ZMSnapshotTestCase.m

Since we no longer have self user in during the snaphot tests we were falling back to the default blue accent color. Since all tests expect the account color to be red I now explicitly set it in `ZMSnapshotTestCase`

Set default accent color in base snapshot test class

---

Wire-iOS/Sources/AppDelegate.m

We call `registerForRemoteNotifications` before we are authenticated during registration, so it's possible that's will get a deviceToken before the `ZMUserSession` exists. Attempting access the user session before it exists will result in assert (crash). We can avoid this by wrapping the code in a `performAfterUserSessionIsInitialized `.
---
https://wearezeta.atlassian.net/browse/ZIOS-8823

Delay reporting new device token until user session is initialized

---

Wire-iOS/Sources/UserInterface/Registration/EmailSignInViewController.m

We are intentionally not validating the login credentials to avoid the situation were a user can't login because the validation rules changed after he/she his/her account. However since the backend only gives us a 400 bad request response if the validation rules doesn't pass we were showing a very generic "something went wrong" error message.
To fix this we now validate the credentials on receiving this error in order to display a more helpful error message.
https://wearezeta.atlassian.net/browse/ZIOS-8822

Show more helpful error messages when login fails

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m

We were crashing because were trying to call a method for de-registering a user profile observer which had been removed.
`Fix:` restore method.
https://wearezeta.atlassian.net/browse/ZIOS-8830

Fix crash after selecting your handle

---

Wire-iOS/Sources/AppController.m

We crashed because we were trying to access a non existing user session.
`fix:` add check if user session exists.
https://wearezeta.atlassian.net/browse/ZIOS-8831

Fix crash on returning from background on login screen

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/DraftListViewController.swift
Wire-iOS/Sources/UserInterface/DraftSendInputAccessoryView.swift
Wire-iOS/Sources/UserInterface/MessageComposeViewController.swift
Wire-iOS/Sources/UserInterface/UIAlertController+DraftDeletion.swift

- move separator view between send button & markdown tool bar
- extend text view to the top of the markdown bar, but set the bottom content inset above the send button
- replace delete button with an alert when dismiss button tapped

Design fixes/drafts

---

Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.h
Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationViewController.m

The user is asked right now to add the phone if it is not added yet after the email login. This step is obsolete and should be removed.

Removed add phone screen after email login

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift

- move 'open in' section to bottom of options settings

Fix: Link Preview Settings

---

Wire-iOS/Sources/Components/Constants.h
Wire-iOS/Sources/UserInterface/Registration/EmailSignInViewController.m
Wire-iOS/Sources/UserInterface/Registration/NoHistoryViewController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationTextField.m
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientUnregisterFlowViewController.swift
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientUnregisterInvitationViewController.swift

1. On iOS11, the placeholder on the input fields was collapsed vertically.
2. Implicit animation from zero frames on manage devices and you are using the device first time screens.
3. Spinner disappearing on email sign in screen.

Fixed annoying bugs with animations during the registration

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationListBottomBar.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationTitleView.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+TopBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView+Update.swift
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.h
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m

Navigating the app using voice over is pretty broken at the moment. We would like to have the basics working so we could improve it in the future.
This PR includes part of the basic flow fixes, mainly focused on conversation list:
* Added descriptive labels for conversations and statuses
* Added labels for profile and all bottom bar buttons
* Supporting "two finger Z" gesture to go back to conversation list
* Notify screen reader that conversation view was opened.

VoiceOver: initial changes to make the app usable with screen reader

---

Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Actions.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m

1. The team account does not have the "..." right footer button in the profile view.
2. The team account does have the block button in the context menu, it should be removed since there is no connection between the team users, and the block therefore is not possible from the BE perspective.

Fixed menu with block for team accounts

---

Wire-iOS Share Extension/UnsentSendable.swift
Wire-iOS/Sources/Components/Settings.m
WireExtensionComponents/Utilities/ExtensionSettings.swift

- disable link preview setting not considered when sharing link from the share extension

obey link preview setting within share extension

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationTitleView.swift
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift

Automation broke after changes in #1169. The main takeaway is that accessibilityIdentifier should be a static string and would not change together with element state.

Fixed accessibility identifiers for automation

---

Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m

Since the introduction of `ConversationImagesViewController` the snapshot view background used by `FullscreenImageViewController` as not properly aligned anymore, leading to a visual glitch when flicking away images as it is not presented in a `UINavigationController`.

Fix view snapshot inset

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsShareDatabaseCellDescriptor.swift

Debug button that would be only visible on the builds with the developer menu. Archives the current cryptobox state and sends it with the iOS integrated email client.

Share cryptobox button

---

Wire-iOS/Resources/Classy/stylesheet.cas
WireExtensionComponents/Views/OverflowSeparatorView.swift

- Uses runtime heavily and most likely makes Classy loading slow.

Do not use all subclasses classy selector (^)

---

Wire-iOS/Sources/AppRootViewController.swift

On launch you would see a black screen for 0.5 second because we didn't
configure a view controller on didFinishLaunching. We can fix this by
always configuring the launch controller view controller before any
other view controller.

Fix flashing black screen on launch

---

Wire-iOS/Sources/UserInterface/SelfProfile/AccountView.swift

- The unread messages information is not available in account manager.

Removed the unread dot (not supported yet)

---

Wire-iOS Tests/NSURLWireLocaleTests.m
Wire-iOS/Sources/Helpers/NSURL+WireLocale.m

- Before we where adding the parameters per hand.
- `NSURLQueryItem` is very nice.

Fix adding locale to an URL

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

Tapping on an obfuscated image presented a blank fullscreen image view controller with a never ending activity indicator
When the image is tapped, only invoke the normal delegate method when the image is not obfuscated

don't open obfuscated image

---

Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

The reason was that ConversationListViewController was leaking after tearing down UI and UserSession. It was listening for app lifecycle notifications and was doing things with user session after coming back from background.

Fix crash when putting app in background while switching accounts

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

On smaller screens (such as iPhone 5s), the current copy is cut off:
The explanatory text below provides enough context that we can do without the extra words in the setting itself.

Fix truncated copy in Link Previews setting

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/WireApplication.swift

Since we moved code for handling this to SE there was no easy way to intercept the calls except from subclassing UIApplication.

Avoid asking notification permissions when testing in automation

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m

On iOS9 the system is throwing an exception if the object is deallocated while KVO is registered to it.
Make sure object is still alive before deallocating the observer.

Retain MediaPlaybackManager while obsetving it with KVO

---

Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift

If Safari is not set as the preferred browser, opening a location address (e.g. 123 Example St) would open in the 3rd party browser with an error message, instead of in the `Maps` application.
When tapping on a link within the `UITextView` we check to see if the link is a data detected link, i.e. `URL.scheme == "x-apple-data-detectors`. If so, we bypass the `interactionDelegate` and allow the system to handle the link.
The location link will always open in the default Apple `Maps` application, even if the user has set `Google Maps` as the preferred application. I did some investigation into how I could extract the location data from the URL but it appears this is done at a hidden level, unless anyone has some ideas?

make opening of data detected links responsibility of textview

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
Wire-iOS/Sources/UserInterface/Overlay/MediaBar/MediaBarViewController.m

Fix to dealloc properties in the correct order, otherwise it still crashes.

iOS9 crash: deallocation order

---

Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

The reason was that we try to fetch shared ZClientViewController, but it is not in the expected place because the registration controller is being animated out it.

Fix crash when registering with email on iPad

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/LocationMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m

We now allow ephemeral messages to be deleted prematurely by long pressing on the ephemeral message. This reveals the usual action menu, however the only item it will contain is `delete`.

Add an option to delete ephemeral message

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+TopBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/NewDevicesDot.swift
Wire-iOS/Sources/UserInterface/SelfProfile/AccountView.swift

Two issues:
- Initially the new devices dot is briefly visible.
- If the user image is not updating then we cannot see the user image change, so only selection is not updated with the new property `autoupdateSelection`.

Fix account button selection ring and dot

---

Wire-iOS Tests/Settings/SettingsPropertyTests.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Components/Settings+Account.swift
Wire-iOS/Sources/Components/Settings.h
Wire-iOS/Sources/Components/Settings.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

Currently all the settings are general and saved in user defaults. The last viewed conversation is also the part of those settings. We need to save the last viewed conversation per account.

store last opened conversation per account

---

Wire-iOS Tests/NSData_ImageTypeTests.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Helpers/NSData+ImageType.swift
Wire-iOS/Sources/UserInterface/Registration/ProfilePictureStepViewController.m
Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController.m

iOS 11 introduced the new **HEIF** file format for images, however the backend expects the images to be **JPEG** files. As a result, other *non iOS* clients can not render the image correctly.

ensure profile image data represents JPEG file

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m

- Issue happens when the `SessionManager` tries to swap the acounts, and keyboard is dismissed. - The dismissal of the keyboard triggers the reload of the table view content when the `UserSession` is not active any more.

Fix crash when switching the account with keyboard up

---

Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
Wire-iOS/Sources/UserInterface/SelfProfile/ProfileView.swift

If when changing name we tap X to exit settings the app crashes. A minor related issue is that after successfully changing name and handle it is not updated in the main account view.
* The crash happens because `unowned self` is gone by the time we save changes. The fix is to extract user and use that instead.
* Added observing for name and handle changes

Fix crash when changing name

---

Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadsViewController.swift

When switching accounts without notifications enabled the app sometimes crashes. It happens because we try to access ZClientViewController before it was created during switching.

Fix crash when switching accounts

---

Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.m

- On creation the app lock controller shows itself, but it is an issue since we are re-creating it as the part of the overlay window.
- Keeping the shared instance is OK, since it's not bound to the user.

Do not re-create the app lock controller

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

I manged to isolate the error better.
When tapping on a message, some information will be displayed under the message (e.g. "Tap ❤️ to like" suggestion). When this happens, the message is stored as "selected message". If I later delete that message, the "stored message" was not set to nil, and then accessed and used when the conversation window changes, causing a crash. 
This would happen only for file messages, as `[Message isVideoMessage:]` was previously not crashing with `nil` values, but it does now because we are using a non-optional in Swift somewhere down the code. This PR fixes it by checking that the message is not `nil` before accessing it.

Crash on no message

---

Wire-iOS/Sources/UserInterface/SkeletonViewController.swift

Previously it would fallback to the initial user image as teams don’t have image yet.

Showing the team avatar when switching to team account

---

Wire-iOS/Sources/Analytics/AnalyticsDecryptionFailedObserver.m

- Notification arrives on the background thread, note.userInfo contains the CoreData object from the background context.

Fixed notification threading

---

Wire-iOS/Sources/AppDelegate+Network.swift
Wire-iOS/Sources/UserInterface/Overlay/InAppNotifications/ChatHeadsViewController.swift
Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.h

This happens when switching accounts and the UI is torn down, but you still get a new message.

Fix: some controllers could be gone while notifications arrive

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationViewController.m

Login can take several paths atm which makes it a bit complicated. The login would miss to register for initial sync in the `path 3` case and `path 5`.
Previously this was not an issue because then the login observation was:
```
if (nil != [ZMUserSession sharedSession]) {
self.initialSyncObserverToken = [ZMUserSession addInitialSyncCompletionObserver:self userSession:[ZMUserSession sharedSession]];
} else {
self.sessionCreationObserverToken = [[SessionManager shared] addSessionManagerObserver:self];
}
```
But this had a problem in `path 4` where the we would start observing initial sync for the user session which was in the process of tearing down.
1. launch app
2. login
3. register client
4. done
1. launch app
2. login
3. fail to register client (because you have to many clients)
4 …

Fix getting stuck when resuming an aborted login

---

Wire-iOS/Sources/AppStateController.swift

This was happening because we were switching to an account without authentication cookie. It immediately fired login failure notification, but app was thinking it is still in loading state.

Fix: app freezes while showing skeleton screen

---

Wire-iOS/Sources/Managers/SoundEventListener.swift

Without a parentheses all the negative cases got skipped.
https://wearezeta.atlassian.net/browse/ZIOS-9045

Add missing parentheses in guard expression

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift

Fix the no audio issue caused by AppDelegate.shared().mediaPlaybackManager?.audioTrackPlayer is nil when AUdioMessageView is created.
Move the audioTrackPlayer's assignment (from app delegate's shared property) from AudioMessageView to AudioMessageCell.
do nil check every time when AudioMessageCell want to asscees audioTrackPlayer and assign again if it is nil.

[fix]ZIOS-8958 Audio message is not playable after killing and reopening the app

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationPhoneFlowViewController.m

The bug occurs when server responses "The SMS or voice call budget for the given phone number has been exhausted. Please try again later. Repeated exhaustion of the SMS or voice call budget is considered abuse of the API and may result in permanent blacklisting of the phone number."

[bug fix]Mike fixed spinner not dismiss after register with a phone number

---

Wire-iOS/Sources/UserInterface/Helpers/UIImagePickerController+GetImage.m

Images were appearing small when picking an edited image from the Photo Library because of an option of Photos framework (`PHImageRequestOptionsDeliveryMode`, now set to `.highQualityFormat`). Reference: https://stackoverflow.com/questions/28042697/phimagemanager-requestimageforasset-returns-low-res-image-in-ios-swift

Added image picking options in order to set the high quality format.

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift

move audioTrackPlayer nil check from the beginning of the func to the place uses audioTrackPlayer.

bugfix: move audioTrackPlayer before it is used. When it is nil, get duration from fileMessage

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift

disable confirm button after it is pressed

bugfix: prevent creating multiple audio message if user click the green tick button multiple times in a second

---

Wire-iOS/Sources/UserInterface/Registration/EmailSignInViewController.m

iOS 11 supports pre-filling account names and passwords from keychain. Added support in login screen

Added password and email pre-filling in login screen

---

Wire-iOS/Sources/AppDelegate.m

Notification actions were getting ignored unless the app had previously loaded the UI. If the
app gets launched from a push the `AppState` will be` .headless` and any calls to
`performWhenAuthenticated:` will get queued until the UI is loaded.
Don't wrap push notification action in `performWhenAuthenticated:` which should now be
unnecessary since they now get forwarded to the SessionManager.

Handle notification action also when UI is not loaded

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift

fixed the case when more then 1 audio message view in the same conversation.

Fix/zios 9042 audio not switching back to speaker after switching to earpiece(phase2)

---

WireExtensionComponents/Controllers/ShareViewController+Views.swift

Share View Controller was shown without margins on iPhone X.

Fixed sizes for share view controller on iPhone X

---

Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift

`speakerMuteChanged` is not related to `isSpeakerEnabled` which is the property we are reading.

Observe speakerEnableChanged instead of speakerMuteChanged

---

Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift

The `VoiceChannelViewController` wasn't deallocated directly after ending the call. Causing a crash if you tried to re-join the call.
Make sure the `VoiceChannelViewController` gets deallocated immediately.
https://wearezeta.atlassian.net/browse/ZIOS-9097

Stop call timer when stopping call to prevent retain cycle

---

Wire-iOS Tests/VoiceChannelOverlayTests.swift

This should fix tests failing locally but passing on CI.

Make sure the debug pattern doesn't show during tests

---

Wire-iOS/Sources/UserInterface/SkeletonViewController.swift

We have been showing wrong icon during the account switch in the bottom right of the skeleton view

Show archive icon in skeleton view

---

Wire-iOS/Sources/UserInterface/Registration/EmailSignInViewController.m

The reason behind this is still unknown, maybe some bug in UIKit. It seems that if we switch the order of login and registration tabs (thus showing login first, not registration) all seems to be working fine. Another workaround was to simply activate the password field and then put focus to email field immediately.

Workaround for failing to pre-fill password on iOS11

---

Wire-iOS/Sources/UserInterface/Overlay/NetworkStatus/NetworkStatusView.swift

This PR fixes the issue that is currently avoiding status bar to be touched, e.g. when the "Back to previous app" action is available. Touch is enabled on the Network Status View only if it's currently expanded - when the "No internet" message is shown.

Status bar not touchable

---

Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift

Clean up the application state observations logic.
Delay the display for system PIN/touchID screen to prevent may not show issue.

Zios 9082 random touch id   locks out of app

---

Wire-iOS/Resources/Base.lproj/Localizable.stringsdict

The actual part that needs to be localised differently depending on how many things we are talking about was not part of what gets translated.

Cleaned up some plurals translations

---

Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift

If a `VoiceChannelViewController` is created with an already ongoing group call the the call participants wouldn't be centered. This happens because the collection view insets is calculated with a zero sized frame.
Create `VoiceChannelParticipantsController` in `viewWillAppear` so that collection view will have a non zero frame when configuration the initial cell layout

Create VoiceChannelParticipantController after frame has been set

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/Helpers/NSURL+WireURLs.h
Wire-iOS/Sources/Helpers/NSURL+WireURLs.m
Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
WireExtensionComponents/Icons/ZetaIconTypes.h

- Manage team item is only shown for admins and owners. Button is taking user to the login screen of the admin panel.
- Add item is showing now add team or add account, add team takes to the team creation flow, add user opens the log in screen.

Improved flow for managing team

---

Wire-iOS Tests/Mocks/MockUser.h
Wire-iOS Tests/Mocks/MockUser.m
Wire-iOS/Sources/Analytics/Analytics.m
Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift

- Reset the team property when re-creating the mixpanel object.
- Reset the team size to 0 when no team is set.
- Correctly erase the city and region property.

Fixes for mixpanel integration

---

Wire-iOS Tests/AnalyticsTests.swift
Wire-iOS/Sources/Analytics/TrackingManager.swift

- Localytics must be initialized, otherwise the opt-out value is not accessible

Properly migrate value from Localytics

---

Wire-iOS Share Extension/UnsentSendable.swift

There was a bug when sharing images from the Photo Library. The extension was skipping the control to load pictures by using the local URL. Now, it tries to load the content from local URL first - if it fails, it loads the content directly.

Crash on sharing images from Photo Library

---

Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift

Images weren't saved while tapping on the "Save" button of the UIMenuController (via long press) due to the weak reference of the object - it was deallocated before completing the operations.
Related to ZIOS-9181.

Fixed weak reference for SavableImage object in CollectionImageCell

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Calls sounds are no longer controlled by the sound intensity setting.
Remove reference to calls in the option description.

Remove calls from sound intensity level description

---

Wire-iOS/Sources/Helpers/syncengine/SessionManager+Shared.swift
Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Calling.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m

If you receive a Callkit call with microphone access disabled you can accept the call but the call
will never connect.
Disable CallKit if microphone access is disabled.
- Remove unused completion handlers in joinCall methods
- End call if we are missing permissions

Disable callkit if we are missing microphone permissions

---

Wire-iOS Tests/Soundcloud/SoundcloudServiceTests.m
Wire-iOS/Sources/Components/Soundcloud/SoundcloudService+Testing.h
Wire-iOS/Sources/Components/Soundcloud/SoundcloudService.m

The QA reported that on simulator it's possible to crash the client by sending the particular soundcloud link. 
The SoundCloud seem to forbid playing some tracks on third-party services. For those the API fetch request returns 403. This error is forwarded by the backend proxy to Wire clients. However with the completion of the request we receive the empty data. According to the crash the data is nil for the QA client. During the testing the data returned was not nil but a data object of 0 length.
Verify if the request was successful before trying to parse the response.

Correctly handle SoundCloud response errors

---

Wire-iOS Tests/0x0.pdf
Wire-iOS Tests/FilePreviewGeneratorTests.swift
Wire-iOS.xcodeproj/project.pbxproj
WireExtensionComponents/Utilities/FilePreviewGenerator.swift

PDF with the layout size of 0 to 0 points would make the existing preview generator crash.
Fail the preview generation in the graceful way.

Do not create the preview of malformed PDF

---

Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/Helpers/UIApplication+Permissions.h
Wire-iOS/Sources/Helpers/UIApplication+Permissions.m

If the user has not granted us audio permission we will not enable Callkit, because the call wouldn't be established if answered outside of the app. The user would then need to restart app in order to have Callkit activated. This behaviour breaks automation test which can't restart the app in the middle of a test.
Attempt to re-activate Callkit immediately after being granted audio permissions.

Enable Callkit immediately after granted audio permissions

---

Wire-iOS/Sources/Managers/SoundEventListener.swift
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift
avs-versions

The incoming-call sound which is played while you are already in a call wasn't played if you had CallKit activated.
Allow sound to be played also when CallKit is activated.
* Bump AVS to latest version
* Improved debug logging for the call overlay

Play incall sound also when Callkit is active

---

Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
Wire-iOS/Sources/Analytics/AnalyticsProviderFactory.swift
WireExtensionComponents/Utilities/AutomationHelper.swift

The analytics is disabled on the simulator builds. For testing the Mixpanel integration with automation we need to have the way to enable Mixpanel.

Enable analytics from command line

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Analytics/TrackingManager.swift
Wire-iOS/Sources/AppDelegate.m
Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/Helpers/sound/MediaManagerLoader.swift

The app takes a really long time to cold start (10s+).
The MediaManger is waiting for some thread to spawn, but seems like it's happening too late.
The AVS libarary consists of several components, those are:
- FlowManager: the component for establishing the network media flows.
- MediaManager: the part responsible for audio routing on the device.
- wcall: the Calling3 implementation.
The entities must be initialized in certain expected order. The main requirement is that the MediaManager is only initialized after the FlowManager.

Load MediaManager only after FlowManager

---

Podfile.lock
Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Private.h
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

Fix the issue left navigation bar item not updates when iPad app transits to slide over mode/fullscreen mode
iPad: left navigation bar item not updates when iPad app transits to slide over mode/fullscreen mode
In SplitViewController.m, this line was called after  [super willTransitionToTraitCollection:newCollection withTransitionCoordinator:coordinator];
[self updateLayoutSizeForTraitCollection:newCollection size:self.view.bounds.size];
which causes ConversationViewController can not get the updated trait collection when going to display.
call [self updateLayoutSizeForTraitCollection:newCollection size:self.view.bounds.size]; before  [super willTransitionToTraitCollection:newCollection withTransitionCoordinator:coordinator];
implement func willTransition(to newCollection: …

Zios 9275 search icon does not switch to menu icon when switch form fullscreen mode to slide over mode

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift

Conversation view - toolbar's expandRowButton is shown when trait collection changes to regular.
expandRowButton is not included in first row but not removed form the view or set hidden
set expandRowButton hidden when multilineLayout == false

hide expandRowButton when it is not added to row one

---

Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
Wire-iOS/Sources/UserInterface/Sketchpad/SketchColorPickerController.m

implement viewDidLayoutSubviews for CanvasViewController and SketchColorPickerController, refresh their subviews.
Fix the issue:
Sketch gets stretched upon device orientation. 
https://github.com/wireapp/wire-ios/issues/13
When iPad rotates, CanvasViewController and SketchColorPickerController did not layout or redraw their subviews.
implement viewDidLayoutSubviews for CanvasViewController and SketchColorPickerController, refresh their subviews.

Fix the issue: Sketch gets stretched upon device orientation.

---

Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.m

The overlayWindow contains AppLockViewController does not resize after app become active.
For unknown reason, overlayWindow's frame didn't update even viewWillTransition is called when app became active after device rotated
`
override public func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
mainWindow.frame.size = size
overlayWindow.frame.size = size
}
`
add an observer in AppRootViewController for UIApplicationDidBecomeActive. Update overlayWindow.frame.size when app become active.

ZIOS-9273 Lock screen does not block some of the view when user disabled rotation lock 

---

Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/NavigationController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.h
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationViewController.h
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationViewController.m
WireExtensionComponents/Views/TabBar/TabBarController.swift

After adding a new landing screen (from #1423) the logic of the registration flow changed slightly. It needs to be able to open login OR registration screens separately from dedicated buttons. However there are other cases where we need to open the screen in an old way (e.g. when adding account).
Added a new type (`AuthenticationFlowType`) that controls what sort of registration flow needs to be displayed. We also wanted to not change existing code as much as possible so we had to work around some issues. Namely the problem that registration flow creates its own navigation controller, but landing screen also needs to create its own navigation controller. So in certain situations we have navigation-inside-navigation stack, but this should get cleaned up when we overhaul the registration …

Support for added landing screen in authentication flow

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Components/AudioPlayer/AudioTrackPlayer.m
Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift
Wire-iOS/Sources/Managers/MediaPlaybackManager.h
Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m

If you play a video message you do not hear the audio if the silence switch is enabled.
In order to play audio while the silence switch is enabled the audio category must be `Playback`.
The audio category is controlled by AVS's media manager,  we should not change audio category directly in the client code. Instead the AVS exposes a protocol called `AVSMediaDelegate` which we should implement so that AVS can select the right category for any external media we play in the client. This protocol also allows AVS to pause the playback of external media if we for example receive a incoming call during media playback.

Allow sound while playing videos with the silence switch on

---

Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift

Verifying one of your own devices is not saved if you kill the app right after.
All all methods which alter data model must be wrapped in `enqueueChanges` in order for the change to be persisted.
Wrap `trustClient()` method in a `enqueueChanges` block.

Wrap trustClient in enqueueChanges

---

Wire-iOS Share Extension/ShareExtensionViewController.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
WireExtensionComponents/Utilities/SharedConstants.swift

Actually, you're able to send messages longer than 8KB.
- Added a control that shows the same alert that is shown on the web version. The alert is visible when tapping on the Send button, if the content of the input bar is greater than 8.000 characters.
- Added support to the `charactersRemaining` property of `SLComposeServiceViewController`. In this way, the remaining characters count is shown on the share extension.

ZIOS-9089: Do not allow sending the text messages longer than 8KB

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m

After design review it seems we have changed too much in the current registration flow. We should keep it as it was and coming from landing page show both login and registration tabs.
We simply preselect login or registration, but show both tabs.

Showing both tabs in login and registration

---

Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m

App crashes when pressing to play button on a video message.
We subclass `AVPlayerViewController` to be able to track when the video playback ends. In this subclass we add property called `playerController` tracks the internal `AVPlayer`. This property however clashes with a private property which leads to a crash.
Prefix our property with `wr_ playerController `.

Fix crash on playing video

---

Wire-iOS Tests/CharacterInputFieldTests.swift
Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift

Issue happened when user tried to delete the text from the input field when it was empty.

Fixed issue with crashing when deleting from empty char field

---

Wire-iOS Tests/CharacterInputFieldTests.swift
Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationState.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/TextFieldDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/VerificationCodeFieldDescription.swift

The accessibility values for the following parts of the team creation where added:
1. `CharacterInputField` now returns the correct accessibility value (it's textual content). Covered with tests.
2. The instance of `CharacterInputField` is returning the correct accessibility label and identifier for automation.
3. The confirmation button in the input fields is now having the localized description.

Added accessibility information to team creation flow

---

Scripts/download-avs.sh

Crashes that were originating in AVS would not have descriptive function names in crashlogs.
For each `.framework` that we use in the app we also have a corresponding `.framework.dSYM` that contains all the symbols needed to make crash reports readable.
For few last AVS releases the symbols are present in the archive, but the script was not moving them to the right place
Updated `download-avs.sh` script that is called from `./setup.sh`

Copying AVS debug symbols together with the framework

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/VerificationCodeFieldDescription.swift

In the team creation flow only code view haven't received the responder state automatically (keyboard is not up when opening the email code screen).
In every screen we call `mainView.becomeFirstResponder()`, in all other cases it's an input field, whereas on the email code screen the input is hidden inside the `UIView` wrapper.
Implement the wrapper that is forwarding the responder calls to the subview.
In the past I was under an impression that `becomeFirstResponder` is a recursive call.

Allow email code input field to get the responder automatically

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/TextFieldDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/VerificationCodeFieldDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/TextFieldValidator.swift

We should do local validation of values in the textfield depending on the type of value to be entered.
After discussing with design, we decided to enable the arrow button after first character has been entered. When user presses the button we first do local validation and show an error if there are any problems.
There is a nice protocol `LocalizedError` that an `Error` can conform to and then `error.localizedDescription` works as expected, no need to cast to concrete type.

Add textfield validation

---

Wire-iOS Tests/AccessoryTextField/AccessoryTextFieldValidateionTests.swift

Tests were failing because the confirm button is now always enabled when there is some text entered in the textfield.
Updated tests and added a new test case checking changed behavior

Fixed failing AccessoryTextField tests after confirm button changed behavior

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/SetEmailStepDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/SetFullNameStepDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/SetPasswordStepDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/SetTeamNameStepDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/TeamCreationStepDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/VerifyEmailStepDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift

Solves several of the issues noticed:
* Tapping "what is wire" and "change email" buttons would do nothing
* After validating email and tapping back we should go back to email screen
There were some weird issues happening because we would not keep a reference to `TeamCreationStepDescription`.
Rewamped the `TeamCreationStepController` so that it takes only one parameter and keeps a reference to the step description. This meant that all view descriptions inside a step need to be stored properties, not computed ones.
Another quick fix was to remove email verification controller when pushing a new one on top, so that when coming back we would skip it.

Few fixes to the flow

---

Wire-iOS Tests/CharacterInputFieldTests.swift
Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/TextFieldDescription.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/VerificationCodeFieldDescription.swift

There are steps in the team creation flow that involve asynchronous operations (round trip to the server) and we need to have some feedback to the user about it.
We show a spinner on the whole screen while the operation is in progress. The spinner unfortunately does't cover the keyboard. To work around this we make the textfields ignore keyboard input while the spinner is visible. The user is able to tap on the keyboard but nothing happens.

Team creation: add loading spinners

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift

The layout constraints on the team name page we're not updating to the keyboard offset when returning from the "what is teams for wire" webview is dismissed.
This view controller registers to observe keyboard changes in `viewDidLoad` and removes itself as an observer in `viewWillDisappear`. Thus, when the view re-appears, the keyboard offset is initially zero, and it doesn't update when the keyboard eventually appears.
Move observer code to `viewWillAppear`.

observe keyboard changes when view appears

---

Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift

Simplification of the character input view, as suggested by the design. As the field does not allow moving the cursor, showing it could be misleading.

Removed the cursor from character input field

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Since timestamps are dynamic, they may appear as either date or time values.
‘On’ works for date values, but not for time values, where ‘at’ would be correct.
Rather than creating 2 separate strings to handle these grammar differences, this commit removes the preposition entirely, so the same text can be used for both cases.

Remove ‘on’ from Edited/Deleted timestamps

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/VerificationCodeFieldDescription.swift

As the title suggests. The callback is set once in `TeamCreationFlowController` and clears the error message if `.none` is passed in.

Clear the error code when typing in a new code

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift

When in activation code screen entering wrong code and tapping "resend code" button would advance to next screen.
The delegate is called when the activation code is sent out. We have used it to advance to the activation code screen. Also this is called when we re-send the code which then also advances to the next screen. 
In delegate we check which state we are in. Also clearing wrong code error after resending

Fix: possible to advance to next screen by tapping resend code

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift

Initial designs has email address placeholder in lowercase, but this is not needed anymore

Team creation: No need to have email placeholder lowercase

---

Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.m

Some events regarding calling and registration are not declared inside `AnalyticsMixpanelProvider.enabledEvents`, so actually they're not tracked.
- Added events to `AnalyticsMixpanelProvider.enabledEvents`
- Changed `calling.established_successful_(video)_call` to `calling.established_(video)_call` (need confirmation from @shumengye)

ZIOS-9058, ZIOS-9193: copy calling and registration events to Mixpanel

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift

Safe area is introduced on iOS 11 and  back buttons's vertical position is not correct on iOS <= 10 devices.
The constraints design does not match the design guideline.  
Set a different value of back buttons's top margin for ios 11/<=11.
Call setNeedsLayout instead of layoutIfNeeded to fix the backbutton move down visual flaw when iOS10 enter name screen shows.
Rewrite constraints for top and bottom spacing. Two spacer view are created and their heights are calculated with these rules:
|            | iPhone | iPad |
| ------- | ------- | ------- |
| keyboard is shown | topSpacer.height >= 20, bottomSpacer.height ==  24 + keyboardHeight | topSpacer.height == bottomSpacer.height + keyboardHeight |
| keyboard is hidden | topSpacer.height == bottomSpacer.height | topSpacer.height == …

fix constraint design for iPad and iOS 10

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/ProfilePictureStepViewController.h
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
Wire-iOS/WireBridgingHeader.h

We were not setting any profile picture after account with team got created which caused many weird issues.
Downloading a random picture from unsplash.com (the same what we do during normal registration) and set it as profile picture.

Team Creation: Setting default profile picture to account

---

Scripts/download-avs.sh
avs-versions

Bump AVS which contain a crash fix
AVS dSYM file wasn't working consistently on hockey.
The unpacking script for AVS would fail to unpack the dSYM if the directory contained a previous version of the dSYM.
Delete any previous dSYM files before unpacking.

Bump AVS and fix avs download script

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingButton.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift

We want to arrange landing button in horizontal on iPad (fullscreen mode).
The header and footer should be closer to the buttons.
Create a stack view and put the buttons inside it. Changes stack view's axis when size class changes to fullscreen mode. Switch constraints set when size class changes.

iPad's Landing screen button layout

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift

Landing button stackview's axis is horizontal by default, iPhone should have a stackView with vertical axis.
Set the stackview's axis to vertical with the stackview is created. If the app runs on iPad, the axis will be updated at the end of viewDidLoad().

set default stackView.axis value

---

Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.m

In NotificationWindowRootViewController, supportedInterfaceOrientations() is recursive called and it crashes when stack overflowed.
1. A iOS internal class UIInputWindowController is the top view controller. When getting topViewController.supportedInterfaceOrientations, it calls NotificationWindowRootViewController.supportedInterfaceOrientations recursively. 
Check the topViewController's name. If it is "UIInputWindowController", return [UIViewController wr_supportedInterfaceOrientations].

zios-9040 fix crash when image screen rotates

---

Wire-iOS/Sources/Helpers/NSURL+WireURLs.m

We had a hardcoded link to point to team creation page. It is used from team creation flow and should contain background information about Wire teams.
Changed to a more general link that can be easily redirected on the server side to a relevant page.

Updated link with more information about teams

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift

After creating a team sometimes the profile picture of the user is not set.
After logging in we are nil'ing the unauthenticated session. This introduces a race condition, because profile picture setting is handled by it. In the case where we manage to login quicker than download an image from Unsplash the unauthenticated session is gone and profile picture is not set.
We retain the unauthenticated session in the request completion block. 
After looking into memory debugger it seems we are leaking the unauthenticated session because there is a retain cycle in sync engine. We will have to address it at a later point to avoid introducing any new issues.

Team creation: fix for profile picture not being set sometimes

---

Wire-iOS/Resources/Base.lproj/Localizable.strings

Added a missing full-stop in enter email screen.
Run a spell check and fixed some typos.

Added missing full-stop and fixed typos

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.h
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

Up arrow keyboard shortcut starts editing of last message.
(The same shortcut is already available on desktop app)
Keyboard shortcuts support requested in #1125
Up Arrow key in InputBar initiates editLastMessage in ConversationContentViewController (via ConversationViewController).
If there is a lastEditableMessage in the conversation, wantsToPerformAction is sent to ConversationContentViewController for the message found.

Added support for up arrow key

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

I've added a minor extension to the  "edit last message" keyboard shortcut (thanks @vorobievalex ) so that it is aligned with the functionality found on desktop, namely that once we are editing a message, the `esc` will cancel editing. Furthermore, I've restricted which shortcuts are available depending on the input bar state, so that the `edit last message` shortcut is only available when the user is not already editing a message, and the `cancel` shortcut is only available when the user is currently editing a message.

add shortcut to cancel message editing

---

Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift

- menu button in conversation view is not hidden after rotates to landscape mode
- conversation list is not visible after rotates to landscape mode
In SplitViewController, updateLeftViewVisibility() is not called after updateForSize() is called.
in ConversationViewController, updateLeftNavigationBarItems() should be called when viewWillLayoutSubviews
Add the missing UI update code.

ZIOS-9337 iPad - conversation list is not visible after rotation

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Helpers/UIStackView+CustomSpacing.swift
Wire-iOS/Sources/UserInterface/Availability/TitleView.swift
Wire-iOS/Sources/UserInterface/SelfProfile/ProfileView.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
WireExtensionComponents/Views/AvatarImageView.m

On smaller screens the availability status would overflow the screen space.
Re-arrange the screen so that we we'll shrink the user image until all elements fit on the screen.
This also fixes showing the availability status in personal accounts on the  user profile screen.

Fix layout of profile screens for small screens

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
Wire-iOS/Sources/Analytics/Events/Analytics+Availability.swift
Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift

Added Mixpanel events tracking for Availability. They're inside `Analytics+Availability.swift`.

Added Mixpanel events for Availability

---

Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift

According to Hockey, the users seems to be facing the crash loop with the crash in `ZMConversation+Status.swift:440`.
The line of code seems harmless except the force unwrap of the user's display name. I failed to trace the particular case when user's display name in the conversation can be nil.
I fixed the force unwrap by using the fallback value for the name. Also I extracted the duplicated code into the separate method.

Fix for crash with ! the user's display name

---

Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift

App crashes after tap done button of AVPlayerViewControllerWithoutStatusBar.
It only happens on iOS10- devices. Crash log: "Wire.MediaPlayerController was deallocated while key value observers were still registered with it."
The objc helper KeyValueObserver does not de-register the observer when set a KeyValueObserver var to nil.
Use standard NotificationCenter.addObserver/removeObserver instead of KeyValueObserver.
Reviewed nearest 10 crash groups out of ~100 similar to  
"Wire.XXX was deallocated while key value observers were still registered with it."
Those crashes only happens on iOS9/10 devices. May be related to this PR's reason.

ZIOS-9361  MediaPlayerController KVO crash

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m

Crashes when tap a user in ConversationListViewController search user screen.
In the method:
- (void)startUI:(StartUIViewController *)startUI didSelectUsers:(NSSet *)users forAction:(StartUIAction)action
users contains user that is a ZMSearchUser, which does not have oneToOneConversation method.
check the user object responds to the method oneToOneConversation.

ZIOS-9369 fix a crash in ConversationListViewController

---

Wire-iOS Share Extension/ShareExtensionAnalytics.swift

Extension sends the link of the file stored inside the app sandbox, but not the file. Also, the share extension is stuck on the "Sending" screen. 
Links look similar to this one: file:///var/mobile/Containers/Data/Application/F116986B-E4BE-43E6-9E5E-94C7835C7F2C/Documents/drivekit/users/115009962656775385314/files/1jdEpnsFN8SCuCr2ItUXElhy9BwX3Vu0glR7DmOag0eM/License%20Application.pdf
When sharing a system item, like texts, images or videos, the resulting `NSItemProvider`contains only the UTI relative to the shared content, e.g. `public.image`. But, when sharing a file from an external app like Google Drive or Apple Files, `NSItemProvider`contains two UTI types. One is relative to the file itself, like `com.adobe.pdf` for PDF files. The other one is `public.url`, probably because the Item …

ZIOS-9348: PDF files shared from Google Drive causing the Share Extension to get stuck in Sending

---

WireExtensionComponents/Views/TabBar/TabBarController.swift

App crashes when user fast tapping "REGISTRATION" and "LOG IN" tab buttons in Tabbar screen
UIViewController.transition() is called before earlier transition is done.
Add a flag to indicate the transition is in process. It is false in init, set to true when transition starts and set to false when transition completes. If the flag is true, transition is not called.

ZIOS-9372 fix crash when fast tapping "REGISTRATION" and "LOG IN" tab buttons in Tabbar screen

---

Wire-iOS Share Extension/AccountSelectionViewController.swift
Wire-iOS Share Extension/Base.lproj/Localizable.strings
Wire-iOS Share Extension/ShareExtensionViewController.swift
Wire-iOS.xcodeproj/project.pbxproj

Currently, it's not possible to switch between accounts inside the Share Extension. You should open the container app and open the Self Profile view. It's pretty annoying!  😄
I've added the possibility to switch between accounts. The behavior is similar to the one already implemented for choosing conversations: if multiple accounts are logged into the app, the "Account" row appears before the "Conversation" row. Then you can select which account to switch. If the user is in a team, you'll also see the name of the team in the account selection view.

ZIOS-9347: Added support for switching between accounts in share extension

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift

Changed "Choose a status" label for Availability ActionSheet to "Set a status"

Changed "Choose a status" label to "Set a status"

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift

App crashes when AudioMessageCell is calling prepareForReuse()
AudioMessageCell gets class member var message (type: id< ZMConversationMessage >), which may be nil at that time point.
Add a nil check guard in menuConfigurationProperties() (which is called in ConversationCell.prepareForReuse())

Fix crash in Wire.AudioMessageCell prepareForReuse()

---

Wire-iOS/Sources/UserInterface/Availability/AvailabilityStringBuilder.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m

The color of the Availability icon was white on the Add People screen, with the light theme activated.
This was caused by the default behavior of the label, which was taking the dark variant (= white text color).
I'm passing the right icon color when asking the function `[AvailabilityStringBuilder stringFor:fullUser with:AvailabilityLabelStyleList color:textColor]`.

Fixed bug with availability icon color on Add People screen

---

Wire-iOS/Sources/UserInterface/Components/CameraPicker.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.h
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m

Users noticed that on iPhone X the custom picture picker camera UI is pretty broken. In other places of the app the custom UI seems to work fine.
I decided to replace the custom UI with iOS integrated one, since then we don't have the overhead of supporting it.

Fixed start UI camera picker using iOS integrated one (iPhone X)

---

Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m

The devices Tableview was cut off by the Safe Area. I've changed the constraints for the TabBarController, allowing it to reach the bottom margin under the safe area, and I've moved the footer view of the profile in order to achieve the same appearance as before.

Fixed insets margin on Profile Devices Screen

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIQuickActionsBar.m

When adding a people from Start UI, the list was cut off under the safe area. I made some changes in order to let the list go behind the safe area. I've also fixed a visual bug with the size of the Add People bar while opening the keyboard.

iPhone X: fixed UI issues with Accessory view of Search Results View Controller

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m

Opening team one-to-one conversation didn't work the first time.
We we were missing save 
Open the conversation after we've save the context.

Fix not opening one-to-one in teams

---

Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift

The accessory view was overlapping the search results view without its blurry effect, also avoiding to choose the last people on the list.
This issue was caused by setting this constraint: `collectionView.edges == container.edges`. I was also leaving out  the `accessoryContainer.top` constraint.
I've restored the correct behavior of the accessory view handled in `SearchResultsView`.

Search Results Accessory View visual fix

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

Up arrow key starts latest message editing only if the input text is empty.
There was an error in https://github.com/wireapp/wire-ios/pull/1511 - up arrow key press erased entered text.
non-empty input text use case was missed during the up arrow feature development.
Up arrow key responder is only added to the Input Bar if it is empty. Otherwise up arrow key is handled by the TextView.
no

Fix text erase when up arrow key pressed

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift

Issues
App crashes when VideoMessageCell is calling prepareForReuse()
Causes
VideoMessageCell gets class member var message (type: id< ZMConversationMessage >), which may be nil at that time point.
Solutions
Add a nil check guard in menuConfigurationProperties() (which is called in ConversationCell.prepareForReuse())
This PR is a clone of https://github.com/wireapp/wire-ios/pull/1539 .

 Fix crash in Wire.VideoMessageCell prepareForReuse() 

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Like.swift

App crashes when ConversationCell is calling likeMessage()
ConversationCell gets class member var message (type: id< ZMConversationMessage >), which may be nil at that time point.
Add a nil check guard in likeMessage()
This PR is a simliar to https://github.com/wireapp/wire-ios/pull/1539 .
In ConversationCell, nullable keyword should be added  to 
````
@property (nonatomic, readonly) id<ZMConversationMessage>message;
````
to make sure Swift code must unwrap it before access. All other properties in ConversationCell should define Nullability also.

add a guard for message nil check

---

Wire-iOS/Sources/Managers/SoundEventListener.swift
Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift
Wire-iOS/Sources/UserInterface/Components/Views/SwipeMenuCollectionCell.m
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelParticipantsController.swift
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift

The haptic feedback is available on the iOS devices that are utilizing the new Taptic Engine chip from Apple.
More info: https://developer.apple.com/ios/human-interface-guidelines/user-interaction/feedback/
Added actions:
- Open conversation from list ui: Feedback "Select"
- Setting a status (as soon as the icon appears next to the name): Feedback "Impact: Medium"
- opening conversation option by swiping right on a list item (as soon as the 3 dots are in position): Feedback "Impact: Light"
- Sending a ping (synchronized with the sound of ping): Feedback "Notification: Success"
- Sending any kind of message (as soon as the me message is placed into the conversation): Feedback "Impact: Medium"

Added haptic feedback for common user actions

---

Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift

This fixes the issue of showing the Quality UI after you accepted a callkit call on lock screen and receive a second call. Quality UI should not be shown in that case, because it blocks the call UI of the second call.
I am checking if when the callstate is answered and the quality ui controller is already presented, to dismiss it right away.

Fix: callkit call and not show Quality UI incase of second call

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m

The video call button was disabled for the team users.
Teams have the `fake` 1-1 conversations that are just the group conversations with 2 participants. Back in the day the video calls where not supported in such conversations.
The check is not necessary any more.

Removed unnecessary check for team users in Start UI

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

App crashes when passing a nil NSDate object to a Swift method.
Message dayFormatterWithDate was rewritten in Swift and does not accept nil Date object.
Add nil check before pass serverTimestamp to dayFormatterWithDate()
message property is nullable but nullable keyword is not yet added in header.

Fix crash for Message.dayFormatterWithDate()'s nil parameter

---

Wire-iOS/Sources/UserInterface/Availability/AvailabilityStringBuilder.swift

App crashes when access user name.
user name is nil when access.
Unwrap user.name before access.

fix: unwrap user name before access

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift

App crashes when deleting a message.
message parameter should be optional and unwrapped before access.
change the type to ZMConversationMessage? and unwrap before use.

fix app crash when delete a nil message

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift

App crashes when forwarding a message.
message parameter should be optional and unwrapped before access.
change the type to ZMConversationMessage? and unwrap before use.

fix app crash when forward a nil message

---

Wire-iOS Tests/VoiceChannelViewControllerTests.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift

In VoiceChannelViewController, timer was created with  Timer.scheduledTimer(timeInterval: target:self  selector:  userInfo: , repeats: ) which cause self is still retained by the timer and can not be freed.
Timer.scheduledTimer(timeInterval: target: selector:  userInfo: , repeats: ) makes a strong reference to target. 
Rewrite Timer.scheduledTimer related call with scheduledTimer(withTimeInterval interval: TimeInterval, repeats: Bool, block: @escaping (Timer) -> Swift.Void) and capture self weakly in the block. 
UIApplication (runDuration) and NetworkStatusViewController  are still using Timer.scheduledTimer(timeInterval: target:  selector:  userInfo: , repeats: ). Will check they are necessary or not in next PR.

Fix/voice channel view controller timer retain 

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift

Users reported that sometimes it's not possible to record an audio message: the duration is 0, and it's not possible to send such message.
The cause is the update of how we are handling the audio sessions. To reproduce the issue it is enough to place one call, start speaking over wire and end the call. Afterwards it is going to be impossible to record the audio message.
The root issue is that the AVS media manager is deactivating the audio session after the call is ended. Therefore it is necessary to re-activate it when the recording is about to start.
Another fix introduced for the case when another audio message is playing, and user is trying to record the new audio message. In this case we first stop the player, and then start the recording.

Fix issue when it's not possible to record an audio message

---

Wire-iOS/Sources/UserInterface/Availability/TitleView.swift

AvailabilityTitleView misplaced after status changes
AvailabilityTitleView's frame is reset to zero after update.
reserve the frame's origin after update the content
@nicorsm It is better not to call configure() for UI refresh since it will call createConstraints() every time.

prevent changing frame's origin after config is called.

---

Wire-iOS/Sources/AppRootViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m

On iPad, if camera keyboard or other custom keyboards is toggled, it changes to text keyboard after rotation.
In ConversationInputBarViewController, inRotation is not set to true when rotation. The reason is viewWillTransition is not called in the same class.
Add super.viewWillTransition(to: size, with: coordinator) in the AppRootViewController, which is the root of ConversationInputBarViewController.
"In your current view controller, if you override viewWillTransitionToSize:withTransitionCoordinator:, make sure you call super. Otherwise, this message won't get propagated to children view controllers."
ref: 
https://stackoverflow.com/questions/32884147/viewwilltransitiontosize-not-called-in-ios-9-when-the-view-controller-is-pres

Fix/zios 9280 i pad   automation   keyboard gallery and voice recorder are replaced with keyboard upon orientation change

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m

This PR is a follow up of https://github.com/wireapp/wire-ios/pull/1572
Tap on image cell does not open full screen view immediately.
A new container view's z-index is higher than messageContentView.
move marginContainer to back most.

move marginContainer to backmost

---

Wire-iOS/Sources/Components/AudioPlayer/AudioTrackPlayer.m
Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift
Wire-iOS/Sources/UserInterface/Components/MediaPreview/MediaPlayer.h
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift

After playing an audio message preview AVS would be confused about in which state the audio session is.
When playing an audio message preview we would manually change audio session  category to `.playAndRecord`. 
Generally AVS has the ownership of the audio session and we should therefore request any changes to to it by using the API they expose for telling them when we are about to play sounds on our own.
- Removed `error` property from the `MediaPlayer` since it was never referenced.
- MediaPlayers without a `sourceMessage` won't get a media bar in the conversation.

Let AVS handle the audio category when previewing audio messages

---

Wire-iOS/Sources/WireApplication.swift

There was no functionality to send debug logs before being logged in.
This PR adds showing the debug alert to send debug logs after shaking the device (only in case the developer menu is enabled).

Show debug alert when registering a shake motion gesture

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
Wire-iOS/Sources/UserInterface/Components/Controllers/DefaultNavigationBar.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationTitleView.swift

Two issues inside Collections View Controller:
1. The hairline under the navigation bar was not visible on 3x displays (iPhone Plus, iPhone X, etc.)
2. `ConversationTitleView` inside the navigation bar had a clickable right arrow. 
1. The left cap inset was too broad on 3x displays.
2. The `interactive` flag was not considered.
1. I've set an inset of 18px, which fits on both 2x and 3x displays. Furthermore, I'm using `resizableImage(withCapInsets:)` instead of `stretchableImage(withLeftCapWidth:topCapHeight:)`, because the last one is deprecated.
2. I'm considering the `interactive` flag when deciding to display or not the right arrow.
Partially related to _ZIOS-9106 - iOS 11 and iPhone X visual fixes_. Thanks to the Design team for reporting the issues.

Collections View Controller UI fixes

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+BurstTimestamp.swift

App crashes when calling ConversationCell.willDisplayInTableView()
message is nil when reading.
unwrap message before access 
Need further study about why message is nil when willDisplayInTableView(). (viewWillAppear & UITable.willDisplayCell are the callers.)

Fix crash in (extension in Wire):__ObjC.ConversationCell.willDisplayInTableView() -> (), line 41

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+CameraPicker.swift

If you tap on the Camera button inside the Conversation List, you'll need to grant access to the camera. If you refuse access, the camera will open with a black view on the next attempt.
I've added the `UIApplication.wr_requestOrWarnAboutVideoAccess`, so now the user is informed to grant access to the camera from the Settings app, in order to take pictures.

ZIOS-8569: Added control about camera permissions in Conversation List

---

Wire-iOS Tests/AvailabilityTitleViewTests.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift

If you try to update your username on the settings, it won't get updated on the header of the Conversation List until you restart the app or switch to another account.
Currently, the two versions of the header in Conversation List don't have a mechanism to update the username on changes.
I've updated the `UserChangeInfo` observer into the `AvailabilityTitleView` (Teams) class and I've added it into `ConversationListTopBar` class (Non-teams).

ZIOS-9429: Update username for current user in the header of Conversation List

---

Wire-iOS/Sources/Developer/DebugAlert.swift
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
Wire-iOS/Sources/WireApplication.swift

Tweaked copy of the dialogues to send logs (internal builds only).
The log sending dialogues had labels that were confusing with certain messages (e.g. "Please confirm sending" -> "Send logs" or "OK").
I fixed the alert to have "Send debug logs" as title, and "Send" and "Cancel" as buttons.

Better labels for the log sending dialogues

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift

This PR addresses a few bugs relating to the audio messages UX:
1. In the audio message keyboard, the recording timer label is not visible.
2. Whilst previewing a recording, tapping the *redo* icon returns to the recording view, however, the previous recording will play until it finishes.
3. If the max recording limit is reached (25min), the user is presented with an alert view with two actions *cancel* and *send*. Meanwhile, the audio recording is lost. Cancelling dismisses the alert, but the user can not preview nor send the recording. Tapping *send* does nothing.
1. The font color of the timer label is exactly the same as the background colour of it's superview.
2. Although the `AVAudioPlayer` within the `AudioEffectsPickerViewController` is stopped in `viewWillDisappear(:)`, this is …

ZIOS-9434: Audio Message Fixes

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift

After recording an audio message and selecting a filter, removing the filter before sending still applies the last selected filter. As a result, the delegate (`AudioRecordKeyboardViewController`) `currentEffect` property still contains the last selected effect.
When selecting `none` as a filter (original recording), the `AudioEffectsPickerDelegate` was not being notified of the selection.
Notify the delegate.

ZIOS-9469: audio filter applied when no filter should be applied

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift

Fix for https://github.com/wireapp/wire-ios/issues/1593 - 'Version Technical Details' are not displayed at iPad
The “Version Technical Details” button (Found in Settings / Advanced) on the iPad version it not tappable / doesn’t function at all
Code was trying to present VersionInfoViewController from UIApplication.shared.keyWindow?.rootViewController, which is behind the presented Settings form sheet.
Present VersionInfoViewController from presentedViewController when available (on iPad).
modalPresentationStyle for the both VersionInfoViewController  and navigationController set to overCurrentContext to draw in the same form sheet.
None
None

“Version Technical Details” button should also work at iPad

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamInviteTextFieldFooterView.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamMemberInviteViewController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/TextFieldValidator.swift

This PR includes multiple minor team invitation UI fixes such as:
* Attempt to fix the accessibility identifiers.
* Show a "learn more" button in case the email is already registered.
* Remove the client-side check wether or not the email is already in use and rely solely on the server response.

Show learn more button when email is already in use

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamInviteTextFieldFooterView.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamMemberInviteViewController.swift
WireExtensionComponents/Views/Loading/CABasicAnimation+Rotation.h
WireExtensionComponents/Views/Loading/CABasicAnimation+Rotation.m
WireExtensionComponents/Views/Loading/ProgressSpinner.m
WireExtensionComponents/WireExtensionComponents.h

* Remove the full screen loading indicator when inviting a team member.
* Adjust `AccessoryTextField` so it can show a loading spinner instead of the confirm button.

Remove full screen loading indicator from invite screen

---

Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamInviteTextFieldFooterView.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamInviteTopBar.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamMemberInviteViewController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/TextFieldValidator.swift

* It was still possible to invite already invited email addresses, this PR reverts removing the custom validator logic to fix that.

Revert removing custom validation logic

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardPermissionsCell.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift

I've added highlight effect to the "Settings" button inside `CameraKeyboardPermissionsCell`. I've also handled the `delaysContentTouches` flag of `UICollectionView`, in order to display the effect whenever the cell is shown onscreen.

Added highlight effect to Settings button of CameraKeyboardPermissionsCell

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Helpers/URL+Wire.swift
Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/UsersInContacts/UsersInContactsSection.m

* For tracking purposes, the team admin panel url now includes a url parameter called `utm_source ` which specifies the source from where the website was opened (settings or start-ui).

Add source parameter to team admin url

---

Wire-iOS/Sources/Components/TokenField/TokenField+DefaultAppearance.swift
Wire-iOS/Sources/Components/TokenField/TokenField.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
WireExtensionComponents/Views/TextView.h

**Recreation of https://github.com/wireapp/wire-ios/pull/1624/ against `release/3.6`**
* Disable dynamic type for the `TokenField` for now until the vertical alignment of the separator dot has been fixed.
* Fix the placeholder not appearing when tapping the clear-all button of the text field.

Fix TokenField placeholder not appearing, disable dynamic type for TokenField  

---

Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift

When recording an audio message with a Bluetooth headset, the timer label does not start at zero.
The timer label reflects the value of `AVAudioRecorder`s `currentTime` property, which according to the documentation is
> The time, in seconds, since the beginning of the recording.
When the internal iPhone microphone is used, this works correctly. But when a Bluetooth microphone is connected, it appears to be displaying the device time, since the label increases monotonously. I have not been able to identify what the problem is, but a [similar issue](https://stackoverflow.com/questions/45162064/avaudiorecorder-sets-current-time-to-negative-values-when-plugged-headphone-at-i) on stack overflow indicates that it could be a bug with `AVAudioRecorder`.
The first attempt at a solution is to use …

Audio recorder timer with Bluetooth headset

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Resources/Base.lproj/Localizable.strings
Wire-iOS/Sources/UserInterface/Helpers/UIAlertAction+Convenience.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/SignInViewController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/UIAlertController+PasswordVerification.swift

Users with an associated email address have to enter their password after trying to login via phone number. To make this flow less confusing an alert controller will now be presented in that case.

Show informational alert if password is needed after phone verification

---

Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift

On iOS9, ServiceDetailViewController.view overlaps with navigation bar.
(Follow up of https://github.com/wireapp/wire-ios/pull/1628)
iOS11 new save area feature affects the top margin constraint. 
For iOS11-, include navigation bar's height for margin calculation.

fix iOS10 top margin with navigation bar issue

---

Wire-iOS/Sources/Components/TokenField/TokenField.m

The text view placeholder visibility was not updated after removing tokens from the token field.

Update placeholder visibility after removing textview tokens

---

Wire-iOS Share Extension/ShareExtensionViewController.swift
Wire-iOS Share Extension/UnsentSendable.swift
Wire-iOS/Sources/Helpers/NSData+Fingerprint.swift
Wire-iOS/Sources/Helpers/String+WireLocales.swift
Wire-iOS/Sources/Helpers/UserClient+Fingerprint.swift
Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchViewController.swift
Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift
Wire-iOS/Sources/UserInterface/Components/Views/MarklightTextView.swift
Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionView.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationIgnoredDeviceCell.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/UnknownMessageCell.swift
Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/TextFieldValidator.swift
Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangeHandleViewController.swift
Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/RequestPasswordViewController.swift
Wire-iOS/Sources/UserInterface/UserProfile/Views/UserNameDetailView.swift
WireExtensionComponents/Utilities/AutomationHelper.swift

Restore build on current IOS/XCode
The application wasn't building anymore in recent versions of XCode
`.characters` seems to be deprecated
Simple removal of all `.characters.`
None

Remove deprecated calls to .characters

---

Wire-iOS/Sources/Components/TokenField/TokenField.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift

The `TokenField` filterText was containing the object replacement character [`U+FFFC`](http://graphemica.com/%EF%BF%BC), which is probably due to the token text attachments, but shouldn't be part of the filter text.
This lead to `isEmpty` called on the filter string returning wrong values which in turns was leading to the clear button staying visible in certain cases.

Strip object replacement character (U+FFFC) from token field filter text

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift

The app was crashing after searching for unconnected users in the Start UI and tapping on one of them.
This was caused by 
https://github.com/wireapp/wire-ios/blob/301b0843217a58669b62de53ab5996c76a39102c/Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift#L357-L362
If you select an unconnected user, you'll fall on the first case, because now `ZMSearchUser` is compliant with the `ServiceUser` protocol. Search users don't have `providerIdentifier` and `serviceIdentifier`, so that's why the app crashes some steps later.
Now I'm checking if the object is compliant with the `ServiceUser` protocol **and** if the `isServiceUser` property is `true`.

ZIOS-9497: While selecting a unconnected user from search to connect to, App crashes

---

Wire-iOS Share Extension/Account+ShareExtensionDisplayName.swift
Wire-iOS Share Extension/ShareExtensionViewController.swift
Wire-iOS.xcodeproj/project.pbxproj

* Show team name in parentheses behind account name in account selection.

Show team name in parentheses behind account name in account selection

---

Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift

If you receive a status update while you app is in background this wont be reflected in conversation list title until you restart the application.
The observation system in SE gets shutdown every time the app goes into the background and all snaphots are cleared. This means that any changes which occur in the background will never trigger a change notification.
For now I will refresh the status when the apps enters the foreground but we should probably also think about better way to handle this in the observation system.

Status update are not visible in UI if received in background

---

Wire-iOS Tests/DateFormatterTests.swift

A date related test fails if runs at midnight.
A prefix is added if the date is another day.
Add logic to for accept the date string with "Yesterday at " prefix.

fix unit test that fails at midnight

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift

CallKit option was not visible in settings when you have multiple accounts.
Multi account restriction was still active in settings.
Remove restriction

Remove check which disable callkit option with multiple accounts

---

Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift

After creating a conversation with a service, that conversation was shown in the search of Start UI with the same layout and the same behavior of a service (the same of the "Services" tab).
This was caused by:
- behavior: `searchResultsViewController(_ searchResultsViewController:, didTapOnConversation:)` was not checking the case with service users.
- UI: while deciding which UI elements to show, the conversation was treated as a service user - and not as a search result
Now I'm checking in both places if the conversation has a service user.

ZIOS-9538: Single bot conversations shows up in people search not as that 1:1 conversation but as a bot service

---

Wire-iOS/Sources/Components/Youtube/MediaPreviewViewController.m
Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserBarView.h
Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserBarView.m
Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.h
Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.m

- Fixed margins for Browser View Controller on iPhone X
- Removed usage of `useWithStatusBar`, since now we're calculating the space occupied by the status bar in `UIScreen.safeArea` (even on iOS versions before 11.0).
Also referenced in https://github.com/wireapp/wire-ios/issues/1582

ZIOS-9546: Fixed margins for Browser View Controller on iPhone X

---

avs-versions

Shiny new version of AVS 4.1.
From ChangeLog.txt:
==============================================================================
AVS Release 4.1
Date:	    29. January 2018
GIT:	    https://github.com/wearezeta/avs/tree/release-4.1
Android:    Android NDK r12b
iOS:	    iOS SDK 8.0
OSX:	    OSX SDK 10.9
Linux:	    Ubuntu x86_64 14.04 (LTS)
Summary:        - Improved BT handling (both iOS and Android)
- Increased ptime for group calling (also with Webapp)
- bug fixes

Bump AVS to 4.1.

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Helpers/AddBotError+UIHandler.swift
Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift

Add Participants View Controller was not handling errors with bots.
I've added (almost) the same error handling of Start UI. Error messages and alerts are now managed in the `AddBotError+UIHandler` extension.
In the current build, the Service Detail dismisses all the modal views in case of success or error. In this PR, I'm dismissing the modal views only in case the service is added successfully to the conversation; otherwise, it will display the error alert without closing the modal view. I believe it's a better implementation since in this way you're still able to choose another service or add another contact.

Support for error handling with bots in AddParticipantsViewController

---

Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NoHistoryViewController.m

Added Safe Area bottom margin to the "Ok" button inside `NoHistoryViewController`.

Added Safe Area bottom margin in No History View Controller

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationListBottomBar.swift

In the current public build, after logging into Wire with a new account, the arrow below the "Start a conversation" hint is not pointing anywhere since the Start UI button is positioned on the left-hand side. 
I'm displaying the Start UI button on the center. When the user archives something, the Start UI button moves to the left and the Archive button appears on the right.
Ta-dah!

ZIOS-9529: Moved Start UI button to center when there are no conversations

---

Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m
Wire-iOS/Sources/UserInterface/Participants/ParticipantsHeaderView.m
Wire-iOS/Sources/UserInterface/Participants/ParticipantsViewController.m
Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.h
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m

The service detail controller is designed to be shown as the part of the navigation sequence. Therefore during the original implementation of services I had to put in the ugly solution of
1. Wrapping Start UI/Add Participants VC into the navigation controller.
2. Showing / hiding the nav bar depending on the screen being looked on.
It was semantically inconsistent and simply not future-proof.
It was noticed that the start UI view controller is showing it's title in the way that is very similar to the navigation view controller's navigation bar. Therefore the proposed solution is to replace the title line of Start UI / Add people with the navigation bar. The benefits of this solution:
1. Style of the bar is consistent between the screens.
2. No need to hide / show the bar.
The …

Unified the nav bars in Start UI, AddParticipants

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Preview.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCellLayoutProperties+Preview.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m

The share preview views had a large leading margin in some cases, which was caused by the `contentLayoutMargins` being reset to a non `.zero` value when the trait collection changes (which is the case when presenting a view controller).
The height is still not rendered correctly in some cases, which will be addressed in a separate PR.

Don't reset margins on trait collection changes when rendering for preview

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Preview.swift
Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift

**Follow up on #1675** 
Fix preview view height for non-image messages in share view controller.

Fix preview view height calculation

---

Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.m

Notification form other account user account is visible when the device is locked by lock screen.
chatHeadsViewController.view is added after appLockViewController.view is added to NotificationWindowRootViewController's subviews.
Reverse the added order.

Fix: Notification form other account user account is visible when the device is locked by lock screen

---

Wire-iOS/Sources/UserInterface/Participants/ParticipantsHeaderView.m

On iPad, when participant view is show in full screen mode, then switch to split mode, the user can not go back to conversation screen.
Cancel button hidden property is not updated when ParticipantsHeaderView's trait collection (size class) changed.
Update cancel button hidden property in traitCollectionDidChange method.

Fix: Update cancel button hidden property in ParticipantsHeaderView when traitCollectionDidChange

---

Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m

When leaving the application with the settings screen being visible last and opening a push notification to get into the app again, we try to dismiss all presented view controllers before showing the selected conversation. The settings screen is presented using a custom view controller transition `SwizzleTransition` which is presented over the current context and applies some transforms and alpha modifications to the conversation list.
For some reason though, the `transitioningDelegate` is not being queried to provide an `UIViewControllerAnimatedTransitioning` object when the view controller is being dismissed without animation. I would have assumed the delegate being queried and the transition contexts property `isAnimated` evaluating to false, so that the pre-presentation state can be …

Add workaround to fix empty list when opening push

---

Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/UserInterface/Services/ProfileHeaderServiceDetailViewController.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileHeaderViewModel.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+headerView.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+internal.h
Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileHeaderView.swift
Wire-iOS/WireBridgingHeader.h

On iPad, when ProfileHeaderView(subview of ProfileViewController and ProfileHeaderServiceDetailViewController's view) shows in full screen mode, then switches to compact mode, the dismiss icon is not updated to corresponding appearance.
Dismiss button 's icon and constraints are set when ProfileHeaderView is created. UI styles are not updated when ProfileHeaderView's trait collection (size class) changed.
Update dismiss button's icon and constrants in traitCollectionDidChange method. Move the button type definition from the parent classes to ProfileHeaderView. ProfileHeaderView choose headerStyle depends on userInterfaceIdiom, horizontalSizeClass, context(ProfileViewControllerContext) and parent's navigationController.viewControllers.count

Fix: Update dismiss button apperance in ProfileHeaderView when traitCollectionDidChange

---

Wire-iOS/Sources/UserInterface/Participants/ParticipantsCollectionHeaderView.swift
Wire-iOS/Sources/UserInterface/Participants/ParticipantsViewController+CollectionView.swift
Wire-iOS/Sources/UserInterface/Participants/ParticipantsViewController.m

When there are no regular users in the group conversation, the collection view used to show the second section slightly scrolled down from the top of the collection view.
The collection view that is showing the conversation participants is designed to show 2 sections: users and bots. When the first section is empty, the collection view still thinks it's in the view, even without the cells. The collection view layout is configured in the way that both sections are having the inset, so the second section is off from the top on the height of the first section insets.
There is a way to supply the inset per section dynamically via the collection view flow layout delegate.

Fix layout of the participants when only one bot is added

---

Wire-iOS/Sources/UserInterface/Components/Transitions/SwizzleTransition.m

The navigation bar is jumping from the very top (under the status bar) to it's normal position right after showing.
Navigation controller has a special tailored logic for positioning the navigation bar when the status bar is visible or not.
Any view controller, when presented with custom transition, is being laid out when it's not the part of the view hierarchy yet. Therefore the navigation controller does not know when it's laid out if it should adopt for the status bar or not. Existing call was not laying out the presented view controller view's position.
Re-layout of the view controller when it's already in the view hierarchy is putting the navigation bar in place.

Fixed initial layout of the navigation bar when presented with Swizzle transition

---

Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift

The app sometimes crashes when it checks the availability status upon entering the foreground.
The app crashes with an error: `An NSManagedObject must have a valid NSEntityDescription.` which is still unclear why that would be the case of the self user.
Delay querying the vailability status until the app is active and observe the crash logs to see if that has an impact.

Delay checking the availability status until the app is active

---

Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift

* Hide the action button from `ServiceDetailViewController` if the current user is a guest in the conversation.

Hide action button for guests

---

Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
Wire-iOS/Sources/UserInterface/Components/Controllers/DefaultNavigationBar.swift

Remove the separator line above the search field in the collections view controller.
The design has changed so that the navigation bar and the content view has different colours making the separator line unnecessary.

Remove separator line from collections view

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift

On iOS 10, when the constraint is created with Cartography, the top of the search bar is not pinned to the bottom of the navigation bar of the parent view controller.
Seemingly the Cartography is missing this bit of functionality for iOS10.
Use iOS integrated layout anchors functionality in order to create the necessary constraint to layout margin.

iOS10: Pin the top to the bottom of the navigation bar

---

Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileHeaderView.swift

The close button is missing from user profile when entering it on iPhone.
[Some refactoring](https://github.com/wireapp/wire-ios/pull/1684) was done on the header of participants view in order to adopt it better for the traits change. During the refactoring we broke the tests, so [another fixes](https://github.com/wireapp/wire-ios/pull/1691) have to be done to address this. During those fixes, we missed to check the functionality on the iPhone: the call to `updateHeaderStyle` is necessary in order to make sure the initial close button style is configured.
Missing call is added, so the view is initially correctly configured.

Profile: Fix missing close button

---

Wire-iOS/Sources/UserInterface/SelfProfile/ProfileView.swift

The app was crashing in the `AvailabilityTitleView` due to  an exception: `An NSManagedObject must have a valid NSEntityDescription`
There was a retain cycle in the `ProfileView` which contains a `AvailabilityTitleView`. The steps leading up to a crash:
1. Launch app into  account 1
2. Switch to account 2 (this will leak a `AvailabilityTitleView`)
3. App gets a memory warning which will shutdown the user session for account 1
4. Open app and the `AvailabilityTitleView` will try access no longer existing user object and crash.
Fix retain cycle.

Fix self profile retain cycle

---

Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m

Start UI now has 2 groups: users and services. It is necessary to remove the pre-selected users when switching to services while the pre-selected users are not used on the services tab: they are not added to the conversation that we create with the service.

StartUI: Clear search input when selecting services

---

Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.m

When opening the create conversation flow, the input is not initially visible if the keyboard is up.
The initial size of `KeyboardAvoidingViewController` was not correct, since the keyboard size observer was not created initially.
I added the creation of the observer when the class is loaded. In this way it would know the current keyboard state and size at any moment.
Additional fix was added to take in account the bottom safe area.

Fix keyboard avoiding view controller's initial constraint value

---

Wire-iOS/Sources/Helpers/UIColor+Hex.swift
Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/BackButtonDescription.swift
Wire-iOS/Sources/UserInterface/Settings/SettingsNavigationController.swift
Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Create Group/CreateGroupSection.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift

- Deselect the cell when the controller is presented.
- Fix the unnecessary keyboard animation or show the keyboard initially.
- Fix navigation buttons selection color.
- Allow ClearBackgroundNavigation to work with non-transparent controllers.

Fixed multiple issues with conversation creation controller

---

Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.m

The inset was not correctly calculated for the case when the keyboard was not shown.

Correctly adjust the bottom inset in KeyboardAvoiding on iPhone X

---

Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m

QA automation is seeing the cells with accessibility labels like "Name - (nil)".
The label calculation was relying on the string that can be nil (subtitle).
Develop complex Objc-Style logic to fix the issue :)

Fix accessibility label for start UI cells

---

Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift

The back button from participants selection screen to the name screen was not reacting on touches.
The instance of `BackButtonDescription` was created locally and was deallocated at the point when the button was clicked. Therefore the callback on it was not called. We need to consider not using the `BackButtonDescription` to host the callbacks, since it's not obvious that the instance of descriptor should persist in order to receive callbacks. Also it's not obvious that it is not possible to call the viewDescriptor.create several times. This questions the concept of view descriptor.

Fixed missing back button action

---

Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewModel.swift
Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/BackButtonDescription.swift

There are no navigation bar buttons in the conversation creation flow.
On iOS 10 and 9, the status bar was not supporting the autolayout yet, therefore the button with 0 frame was not displayed properly.

Fix conversation creation flow navigation bar buttons

---

Wire-iOS/Resources/Classy/stylesheet.cas
Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift

The linear conversation creation flow can be opened from both start UI and the conversation details. The `AddParticipantsViewController` is designed to respect the user's dark theme mode, since it's shown from the conversation details. 
Therefore, if user has the dark mode selected then when opening the linear conv creation flow from start UI, the conv name screen is white and add participants screen in dark.
For the moment the linear conv creation flow would always be white, does not matter from where it is presented. This is achieved by passing in the color scheme variant.

Ignore dark mode for linear conv creation flow

---

Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewModel.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift

Skip button in the linear group conversation creation flow used to have the wrong color. Also the order of sections in the start UI should be starting with create group button.

Linear conv. creation flow: fixed sections order; color of skip button

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift

If you are the only one participant in the conversation, then the call cannot be established.
Hide calling button in self conversation.

Hide calling buttons in self conversation

---

Wire-iOS/Sources/UserInterface/Conversation/Create/SimpleTextFieldValidator.swift

* Validate using string byte size instead of character count.

Validate using string byte size instead of character count

---

Wire-iOS/Sources/Components/ShareViewController/ShareDestinationCell.swift

There was a little glitch when tapping on a service in `ShareViewController` - the background of the avatar view was switching between light and transparent. That's caused by the default value of the  `selectionStyle` property in `ShareDestinationCell`, now set to `.none`.

ZIOS-9501: set ShareDestinationCell selection style to none

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m
Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/BackButtonDescription.swift
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m

- Fixed the back icon size (should be 16).
- Fixed presentation of conv. creation controller from conv. details (should be modal).
- Fixed not opening the conversation in iPad Landscape.

iPad fixed #2 for linear conv creation flow

---

Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift

* Only use default transitions when the background is neither clear nor translucent.

Only use default transitions for non-clear opaque backgrounds

---

Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift

The error message was showing the unnecessary internal error description.
Use default error message alert.

Fixed error message for changing the user name

---

Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m

1) `AddressBookCorrelationFormatter` in `SearchResultCell` was receiving a fixed white color, so the label was almost not visible on white backgrounds
2) Consequently, that label was overlapped by the right checkmark view
1) I'm passing the color from the current scheme
2) I'm now calculating the right margin of the label within all the possible cases, also with both checkmark view and guest label visible.

Fix to Address Book correlation label color, adjusted margins

---

Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift

Team account would sometimes crash bringing the app into foreground.
A retain cycle in the AvailabilityTitleView's tapHandler was leaking `AvailabilityTitleView` when switching between accounts. If the account was purged from memory the app would crash upon entering the foreground.
Fix the retain cycle.

Fix retain cycle in tapHandler of title view

---

Wire-iOS/Sources/UserInterface/Services/ProfileHeaderServiceDetailViewController.swift

Background color of `ProfileHeaderServiceDetailViewController` was fixed to white and, consequently, not respecting the preference for dark or light theme. Now I'm fetching the colors from the current color scheme.

ZIOS-9624: Fixed background color of ProfileHeaderServiceDetailViewController

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

The linear conversation creation flow started on iPad from the conversation details does not create the conversation.
The callback was expecting that the conversation details popover is still visible. Unfortunately after the last update the conv. creation flow is presented in the form sheet, so the conv. details controller is dismissed before that. This creates the situation when we try to dismiss controller, but there is nothing presented, so iOS is not calling the completion block.
Check if there is a controller to dismiss before trying to dismiss it.

Linear conversation creation for iPad: always call the creation

---

Cartfile.resolved
Wire-iOS/Sources/UserInterface/UserProfile/Views/UserNameDetailView.swift

Title color of `UserNameDetailView` doesn't reflect changes, so while switching from dark to light, the title stays white, and while switching light to dark the title stays gray.
The color was set statically, so now I'm picking the color from a dictionary that keeps the correct color for each variant.

ZIOS-9674: Fixed UserNameDetailView that doesn't reflect theme changes

---

Wire-iOS/Sources/UserInterface/Settings/TailEditingTextField.swift

The width of the input field inside `TailEditingTextField` (used in `SettingsCell`) was not updated after typing something inside it, only on iOS 10. So, for example, if you write a short display name inside the Account settings, you go back and return on that screen, the width of the text field doesn't get updated until you press the spacebar.
I'm setting the `text` property of the text field every time. This is causing the text field to update its frame.

ZIOS-9649: Fix for TailEditingTextField width on iOS 10

---

Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift

- If it is not possible to add the guest to the conversation, we should not show the bots selection.

Do not allow adding bots to team only conversations

---

Wire-iOS/Resources/Base.lproj/Localizable.stringsdict

Changed "Everyone left" for `participants.people.count` value in Localizable.stringsdict (Base) to "Only you".
This string is used in two places:
- `ParticipantsViewController` to display the number of people in the current conversation
- `MessageToolboxView` to display the number of likes of a post
So it shouldn't interfere with the second case since we're not displaying the message when we have zero likes.

ZIOS-9677: Changed zero variant of participants.people.count to "Only you"

---

Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m

Long pressing on a message while editing another message inside a conversation was causing the input field to discard changes. This because `conversationCell:shouldBecomeFirstResponderWhenShowMenuWithCellType:` was calling `[ConversationInputBarViewController endEditingMessage]`.

ZIOS-9679: Removed endEditingMessage while displaying UIMenu in conversations

---

Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift

When user opens the linear conversation creation flow and selects some users on the second screen, it is still possible to go back to the first screen and choose not to allow guests in the conversation.
We are not re-filtering the list of participants in case user selects to disable the guest access.
Filter the list once again.

Remove non team members when user disables the guest access

---

Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.m

User profile opened from search was missing the navigation bar.
Since we know use a real navigation bar in the user profile we should not hide the navigation bar anymore.
Use our default navigation bar.

Fix presenting profile from search

---

Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m

Pictures were disappearing while scrolling inside the conversation photogallery.
The main cause is that `UIPageViewController` pre-loads the next page in memory before scrolling, but its view has size zero, in the beginning, causing a wrong calculation of the initial zoom (which is zero). In fact, the imageView has the correct bounds, but frame is zero.
I'm calculating the initial zoom in ~`viewDidLayoutSubviews`~ incorrect! That's causing the zoom to reset on device rotation.
Related to https://github.com/wireapp/wire-ios/issues/1766

ZIOS-9688: Images disappear when scrolling between pictures in a conversation	

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Wire-iOS/Sources/UserInterface/Conversation/GuestsBarController.swift

Wire crashes in most of the conversations when user selects the input field.
The constraint in `GuestBarController` is not created until the view is loaded. However the controller is trying to access it.
Guard the access checking if the view was already loaded.

Fix crash with conversation input; disable bar in 1-1

---

Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsFooterView.swift
Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift

We are showing "add participants" - button for guests
We always show it
Hide it when you (self user) are a guest in a conversation.

Don't show add participants button for guests

---

Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m

The issue appeared that the users outside the team are seeing the bar.

Do not show guests bar for people not in the team

---

Wire-iOS Tests/GroupDetailsParticipantCellTests.swift
Wire-iOS.xcodeproj/project.pbxproj
Wire-iOS/Sources/Helpers/Themeable.swift
Wire-iOS/Sources/UserInterface/Components/Views/GuestIndicator.swift
Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsParticipantCell.swift
Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m

The guest indicator has the wrong colour in search results.
The guest indicator view was shared with the profile view screen which requires a different colour.
Use a plain a `UIImageVIew` in the `SearchResultCell` so it can have it's own colour.
I'm adding a `Themeable` protocol which can be quite useful when combined with `UIAppearance` since we would then not need to pass along a `ColorSchemeVariant` through the whole view hierarchy.

Fix guest indicator color in search results and add participants screen

---

Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCell/ParticipantsCells.swift

When an external guest joins a conversation that you are watching the system message does not show the name. 
We insert the system message immediately after we get a push event that a member joined conversation. However at this point we only know the `remoteIdentifier` and user has no other information (name, profile picture etc.). We fetch all the details of this user, but the system message is not actually updated when we receive all this.
Reload all the information of the cell when a user changes. This should solve other similar issues that were happening in various types of `ParticipantCell`.

Fix: system message for guest user

---

Wire-iOS/Sources/UserInterface/Conversation Options/Conversation+OptionsConfiguration.swift

There are two places where we check that guests are allowed in a conversation - in participants screen and then inside the conversation options screen. They were using different ways of doing the same check and values were not matching sometimes.
After https://github.com/wireapp/wire-ios-data-model/pull/444 is merged `allowGuests` will be true if any type of guests are allowed and it is not the same as `conversation.accessMode == .allowGuests`.
Use the same check in both screens for consistency

Use same method for guests conversations
