- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
Refactor `didFinishPickingMediaWithInfo` in `CanvasViewController` to prevent using `UIImagePickerController.image(fromMediaInfo:)`, which calls depercated `[PHAsset fetchAssetsWithALAssetURL]`.
> Fix: Remove calling deperated Photo libarary method in CanvasViewController 

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
If you tried to logout from the "add emails & password" screen you would get stuck on a spinner.
When you delete an account we now correctly signal this with the error `.accountDeleted` instead of `.addAccountRequested` which we didn't handle correctly if the account was deleted during the login flow.
Restart the unauthenticated flow on `.accountDeleted`
> Fix user getting stuck when logging out from "add email & password"-screen

- WireCommonComponents/BackendEnvironment+Shared.swift
The app would get logged out if you tried to use the share extension when running against any backend other than production.
The backend environment was being read from the user defaults. The share extension however has its own user defaults since it is being run as a separate process. That means when we launch the share extension it will attempt to read the backend environment and fail since it doesn't exists and then fall back to the production environment.
Read the backend environment form the shared user defaults which can be accessed by all applications within the same app group. This will work since in `setupBackendEnvironment`, which is executed on every launch, we copy any environment found in there standard user defaults into the shared user defaults.
> Fix share extension when running against a non standard backend

- fastlane/Fastfile
- setup.sh
`download-assets.sh` failed to run
When the path contains a space and pass to `download-assets.sh` via `setup.sh`, the unquoted path is treated as 2 arguments.
Quote the path and pass the arguments with double-quote to keep the single quote.
> Fix: download-assets.sh failed to run

- Wire-iOS Tests/CameraKeyboardViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ImageManagerProtocol.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
Prevent passing an instance of `PHImageManager` (`PHImageManager.default()`) which may be cleaned after passed to `CameraKeyboardViewController`. Pass the type of `PHImageManager` instead and call its `defaultInstance` property when needed.
> Fix: Crash in PLPhotoLibrary

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController+ActiveMediaPlayerObserver.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
App crashes when calling `[ConversationListContentController activeMediaPlayerChanged:]`
Missing class type checking before calling `updateAppearance`
`SIGABRT: -[Wire.ConnectRequestsCell updateAppearance]: unrecognized selector sent to instance `
try downcasting `cell` before calling `updateAppearance`
> Fix: Crash in ConversationListContentController

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
on iOS13, the user can not share video via input bars's file button or camera keyboard's image picker
Can not move a file from a URL given by `UIImagePickerController`'s info
`[[NSFileManager defaultManager] moveItemAtURL:videoURL toURL:videoTempURL error:&moveError];`
Copy the file instead for moving
> Fix: iOS13  - can not share video via input bars's file button or camera keyboard's image picker

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+ViewLifeCycle.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
Remove unnecessary `FirstReponderView` which replaced the view of `FullscreenImageViewController`
> Fix: Crash in FirstReponderView

- Wire-iOS/Sources/UserInterface/Conversation Options/CellConfiguration+ConversationOptions.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/CellConfiguration.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewModel.swift
App crashes when sharing a conversation link.
`In its current trait environment, the modalPresentationStyle of a Wire.TintCorrectedActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.' `
Config the popover and assign `sourceview` to the popover.
> Fix: [iPad] - app crash when share a guest link 

- Wire-iOS/Sources/Developer/DebugAlert.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift
On iPad, app crash when sending report with share popup
Same as https://github.com/wireapp/wire-ios/pull/3605
Same as https://github.com/wireapp/wire-ios/pull/3605
> [iPad] - app crash when sending report with share popup

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
On iOS 13 beta 8, app freezes after adding participants when creating a group.
Unknown, but it seems like related to animation workload is too high/the invisible view does not reposed to response to display call.
Dismiss `ConversationCreationController` first, then show the conversation in complete closure.
> Fix: iOS13: unable to create group 

- Wire-iOS/Sources/Helpers/FontScheme.swift
Remove FontScheme's `objcMembers` signature to reduce the size of the generated header for objc.
> Remove FontScheme's objcMembers signature 

- Wire-iOS Share Extension/Info.plist
- Wire-iOS Share Extension/NSExtensionContext+Attachments.swift
- Wire-iOS Share Extension/SLComposeServiceViewController+Preview.swift
- Wire-iOS Share Extension/ShareExtensionAnalytics.swift
- Wire-iOS Share Extension/ShareExtensionViewController.swift
- Wire-iOS Tests/EmptySearchResultsViewTests.swift
- Wire-iOS Tests/Utils/VariantsBuilder.swift
Support share all file types via Safari or File app (with `UTI = public.fileurl`).
The filename is extracted from the file URL and prefilled in the text editor.
> Feature: support sharing all file type

- Wire-iOS Share Extension/PostContent.swift
- Wire-iOS Share Extension/SendController.swift
- Wire-iOS Share Extension/ShareExtensionAnalytics.swift
- Wire-iOS Share Extension/ShareExtensionViewController.swift
- Wire-iOS Share Extension/UnsentGifImageSendable.swift
- Wire-iOS Share Extension/UnsentSendable.swift
- Wire-iOS.xcodeproj/project.pbxproj
Sharing a GIF via share extension from Photo app or other app loss animations after sent
GIF image is treated as a normal image.
Create a new `UnsentGifImageSendable` to handle GIF sharing
- We can show animated GIF preview in the preview image view after upgrading the GIF library. (using current `FLAnimatedImageView` library have to refactor a lot.)
> Fix: Sharing a GIF via share extension loss animation

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+State.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Fix app crash due to missing `state` in `ConversationListViewController `'s implementation.
> Fix: app crash when accessing ConversationListViewController 's state

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+ConversationMessageCellDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MediaPlayer.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+SaveImage.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+ScrollViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.h
App crashes for `Selector name found in current argument registers: delegate` when calling a method of `ConversationContentViewControllerDelegate`
`ConversationContentViewController`'s `delegate` is marked as weak but not `nullable`. It crashes when force unwrapping `delegate` when it is nil.
Mark `delegate` as nullable and optional unwrap it.
> Fix: Crash when opening opening app from push

- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsViewController.swift
App crash after back from the rotated message detail screen
`MessageDetailsViewController` is not designed for landscape mode.
Override `shouldAutorotate` so that rotation is not allowed.
> Fix: App crash after back from rotated message detail screen

- Wire-iOS/Sources/Helpers/UIActivityViewController+FileSaving.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+FilesPopover.swift
App crash after https://github.com/wireapp/wire-ios/pull/3591
similar to https://github.com/wireapp/wire-ios/pull/3605
same as https://github.com/wireapp/wire-ios/pull/3605
>  Fix: [iPad] - app crash when pressing the file share button 

- Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter+Internal.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter+Orientation.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.m
https://github.com/wireapp/wire-ios/issues/3642
After merging https://github.com/wireapp/wire-ios/pull/3640,  accessing `controllerToPresentOn` in Swift without unwrapping causes the crash.
Define the properties' nullability and unwrapping the parameters before access.
> Fix: Crash - controllerToPresentOn is nil after allowing contact permissions

- Wire-iOS/Sources/UserInterface/Components/Views/UpsideDownTableView+Scrolling.swift
As described in crash from ZIOS-11665, tableview is crashing because the section index passed is outside bounds (`section (9223372036854775807) beyond bounds (4)`)
I've added a condition to avoid scroll if section index is over bounds.
> Fix: table view section outside bounds

- Wire-iOS/Sources/UserInterface/Components/Controllers/SectionCollectionViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsContentViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/LegalHoldDetails/LegalHoldDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
On `GroupDetailsViewController` when switching between `regular` and `compact` mode, the cell's content may be clipped by the boundary.
The cells' layouts do not refresh after rotation.
Call `invalidateLayout` when `viewWillTransition`.
> Fix: [iPad] When rotating the app in split view with the conversation details open, some text is displayed outside of the visible area

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.swift
Label "EVERYTHING ARCHIVED" is missing from the conversation list
`paragraphStyle` is nil 
Creating `paragraphStyle` and assign value with `setParagraphStyle`
Snapshot test will be created in another PR.
> Fix: Label "EVERYTHING ARCHIVED" is missing from conversation list

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+DeleteGroup.swift
Confirm dialogue button says `Delete Group...`. It should not include the `...`
Update copy.
> Update copy on confirm group deletion dialogue

- Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel+ConversationListContentDelegate.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
If a conversation is deleted it is confusing to be in the next conversation in the list so we decided to always transition back to conversation list when the currently selected conversation goes away.
> [Fix] Transition to the conversation list when the selected conversation is deleted

- Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel+Handles.swift
- Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel+StartUIDelegate.swift
Move conversation creation methods to `ConversationListViewControllerViewModel+StartUIDelegate.swift` where they are used
> [Refactor] Move conversation creation methods

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
Call the viewModel's select coversation method instead of calling `UIResponderStandardEditActions`'s `select`.
> Fix: app crash when calling  conversationListViewController.select

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell+Internal.h
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell+Scroll.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController+ConversationListCellDelegate.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
After https://github.com/wireapp/wire-ios/pull/3646,  `ConversationListContentController` does not conforms to `ConversationListCellDelegate`
Add back the protocol implementation and convert the caller to Swift to make sure compile error is generated for missing match type casting.
> Fix: missing ConversationListCellDelegate implemention of ConversationListContentController

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
App Lock setting would still be visible if you disable your passcode until you close & re-open the settings.
The AppLock cell descriptor is only calculated once when the Setting screen is opened.
- Hide/show the App Lock setting dynamically by implementing the `visibilityAction` on the cell descriptor
- Add support for dynamic headers & footers so that we can display the correct AppLock subtitle
- Reload the settings tableview when the app becomes active.
I re-factored the `SettingsTableViewController` to only calculate the visible section when necessary since it's expensive now that we query the `LAContext` in the `visibilityAction`.
> [Fix] Update the App Lock setting when the app comes into foreground

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsSignOutCellDescriptor.swift
We started to remove the client when logging out from an account which normally requires the login password. User's who logged in via SSO or phone number doesn't have a password associated with their account though.
- Don't attempt to delete client for phone login users.
- Don't ask for a password if the user uses SSO since the backend doesn't require it in this case.
> Fix: Don't ask for a password on logout if the user doesn't have a password

- Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel+StartUIDelegate.swift
When archiving or deleting the content of a 1:1 conversation, which implicitly archives, it would not open the conversation when selecting it from search.
The conversation is not unarchived when we try to select it in the conversation so it fails to open.
Unarchive the conversation before we try to select it in the conversation list.
> Fix: archived 1:1 conversation not opening when selected from search

- Wire-iOS/Sources/Authentication/Event Handlers/Flow Start/AuthenticationStartReauthenticateErrorHandler.swift
Prefill the credentials when user gets logged after a reboot.
> Show re-authentication screen on .needsToReauthenticateAfterReboot

- Wire-iOS Tests/ConversationList/ConversationListViewModel/ConversationListViewModelTests.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
Expend the collapsed folder when one of the items is selected.
> Fix: update conversation selection behaviour

- Wire-iOS Tests/ConversationList/SectionHeader/ConversationListHeaderViewSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
Set `ConversationListHeaderView`'s `accessibilityValue` to reflect its collapse status.
> feature: Add value to Folder showing wether it is collapsed or expanded

- Wire-iOS/Sources/UserInterface/Components/Views/LinkInteractionTextView.swift
On iOS13, when pressing a link, it is opened immediately and the user can not trigger the menu.
Seems like a bug of iOS 13. `shouldInteractWith` delegate method is called multiple times.
Check the tap gesture has `.ended` state before opens the URL.
> Fix: It's not possible to copy link in a message by long pressing

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBarViewController.swift
Reduce user name label's `ContentCompressionResistancePriority` to prevent it breaks the leading anchor to the left icon view.
> fix: avatar image overlaps user name if user name is very long

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
The conversation list updating is breaking in some cases with the introduction of folders.
The collection view update logic is not build to handle multiple sections.
Reload the collection view on changes for now and take the time to implement proper support for multiple section updates.
> Fix: conversation list updates showing an incorrect state

- Wire-iOS/Sources/UserInterface/Folders/FolderPickerViewController.swift
Status bar would be white on white when showing the folder picker.
We weren't updating the status bar style when displaying the folder picker
Update status bar style.
> Fix: incorrect status bar style when showing the folder picker

- Wire-iOS/Sources/UserInterface/Folders/FolderPickerViewController.swift
Define `preferredStatusBarStyle` to adapt dark/light mode variations.
> fix: folder picker status bar is black on black

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
You can crash the app if 
1. You are navigate to the guest settings the conversation details. 
2. You get removed from the conversation
3. You press "create guest link" button
It's an illegal action to create a guest link for a conversation you're not a member of and if you do it we will intentionally crash the app.
Dismiss the guest settings if you are removed from a conversation.
> Fix: crash when perusing "create guest link" button

- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
In https://github.com/wireapp/wire-ios/pull/3730, we found that the other window in front of main window overrides status bar style and hidden.
The notification windows and call windows always exist and cover the main window
Set empty windows hidden instead of calling `makeKey` to prevent it overrides the status bar.
> fix: hidden notificationsWindow without using makeKey

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
When a favourite conversation is selected and the favourite folder is collapsed, app crash
When the favourite conversation, the favourite folder is not expanded and hence the calculation of collection view index path is incorrect.
Remove the guard for reloading the section.
Change the reload section to animated.
> Fix: app crashes when expanding a section

- Wire-iOS/Sources/UserInterface/Components/Controllers/RotationAwareNavigationController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileActionsFactory.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController+Extension.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
When unblocking a user form search UI, the profile screen dismisses immediately.
`transitionToListAndEnqueue` is called for all the cases.
When the context is `search` do not call `transitionToListAndEnqueue` and update the footer bar to let the user opens the conversation.
> Fix: app goes back to search ui after unblocking user 

- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- WireCommonComponents/AppLock.swift
The `AppLock` screen requires to unlock twice.
When the app become active, `applicationWillResignActive` notification is fired, then when the Touch ID system dialog dismisses, `applicationWillResignActive` notification is fired second time and calls `evaluateAuthentication` again. At the moment the first `evaluateAuthentication` request is not yet done.
Keep a weak reference to `LAContext`, if it is not nil, i.e. `evaluateAuthentication` is not done, do not start a new request.
> Fix: Applock unlock needs two fingerprint scans to unlock. 

- Wire-iOS/Sources/Helpers/syncengine/ClientRemovalObserver.swift
Change `ClientRemovalObserver`'s member `controller` form `unowned` to `weak` and the type to optional to make sure it is unwrapped before access.
> fix: app crashes when accessing unowned view controller

- Wire-iOS Share Extension/ShareExtensionViewController.swift
Unwrap `sharingSession` before access.
> Fix: Share Extension crash at ShareExtensionViewController.appendPostTapped

- Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Calling.swift
- We were equating `CallParticipant` to `ZMUser`
- The cast from `CallParticipant` to `ZMuser` always fails
- Compare `CallParticipant.user` to `ZMUser`
- Remove the cast altogether
> [Fix] Fix cast warning

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
The muted conversations are counted in folder badge.
We did not consider the muted status of the conversation.
Check the `showingAllMessages` property of the conversation and only count it when it is true.
> fix: folder badge - Exclude the muted conversations

- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
On 'ConversationCreationController' after rotating in compact mode, the cell's content may be clipped by the boundary.
The cells' layouts do not refresh after rotation.
Call 'invalidateLayout' when 'viewWillTransition'.
> [iPad] Fixed text field cropping after rotation

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
Badge count not updating when collapsed folder and added to group conversation
The differenceKit method `UICollectionView.reload()` does not call the completion closure `setData` when the section to reload has no cell (when the section is collapsed)
Do it manually in this case.
> fix: Badge count not updating when collapsed folder and added to group conversation

- fastlane/Fastfile
Allow override `app_name` for `appcenter_upload` method.
> support custom app_name for app center

- Wire-iOS Tests/UITextView+ReplaceTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/UITextView+Replace.swift
Fix: crash in UITextView replace method
Crash when replacing text in TextView.
Replacing text with a given range that >  string length.
Add a range length check.
> Fix: crash in UITextView replace method

- Wire-iOS Tests/Calling/VoiceChannelVideoStreamArrangmentTests.swift
- Wire-iOS Tests/VideoGridViewControllerSnapshotTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
GIVEN a group call with 3 participants (A, B, C)
WHEN participant A enables its video stream
THEN participant C (on iOS) sees A's video stream 
BUT also sees a black screen for B, who hasn't enabled video
`videoStreamArrangment` in `VoiceChannel` extension would fail to filter out the video streams that weren't active and thus returned an array of all the connected streams. In our case, we only need to get the active video streams in order to display them.
Update logic of `videoStreamArrangment` to only select and return the active video streams.
> [Fix] Group call streams arrangement 

- Wire-iOS/Sources/Helpers/UIApplication+Permissions.m
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+Alert.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
For the case of microphone permission:
GIVEN microphone permissions are revoked
WHEN user accepts an incoming call
THEN call overlay is dismissed without asking user to grant microphone permissions
The logic responsible for displaying the alert asking the user to grant permissions failed to make the `notificationsWindow` visible
- Make `notificationsWindow` visible when displaying permissions alert
- Hide `notificationsWindow` upon completion of the alert
> [Fix] Permission alerts not showing

- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Suggestions/DirectorySectionController.swift
…conView
The guest icon is overlapping the + button on search UI.
We set the visibility of guestIconView 2 times. That's why, during the search, we show this icon for a moment, and then hide it.
Add a new parameter in the UserCell config method to show/hide guestIconView.
> Fix: set the guestIconView on search UI

- Wire-iOS Tests/ConversationList/ConnectRequestsCell/ConnectRequestsCellTests.swift
- Wire-iOS Tests/UserCellTests.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConnectRequestsCell.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.h
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
Change the accessibilityIdentifier for the UserCell according to which section (admins/members) it's in.
> Feature: Change the accessibilityIdentifier for UserCell

- Wire-iOS/Sources/UserInterface/Components/TextView/TextView+Placeholder.swift
- Wire-iOS/Sources/UserInterface/Components/TextView/TextView.m
App crash at the line `[super setAttributedText:attributedText];`
Unknown. But we should be calling super.setAttributedText since it may cause race condition, e.g. the attributedText may be changed by dictation at the same time.
Observe value change with `didSet` and update the placeholder.
> fix: app crash when calling TextView.setAttributedText

- Wire-iOS/Sources/UserInterface/ConnectRequests/ConnectRequestCell.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionViewController.swift
App crash when init `IncomingConnectionViewController`
`user` would be nil in this case
Unwrap user with the guard.
> Fix: app crash in ConnectRequestCell

- fastlane/Fastfile
Upload dsym to AppCenter to resolve the crash reasons
> Fix: upload dsym for testing builds to app center

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Clicking on the Giphy search button will not prefill the Giphy search with the message being typed. This has been raised as a security concern (accidental tapping on Giphy) and this is a simple attempt at addressing the issue. In future we could move this to a user preference to allow for both behaviours.
This was manually tested on simulator
> Remove prefilling of Giphy search box

- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsContentController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsViewController.swift
Add a new state for the `ProfileDetailsViewController` and the method for the `ProfileDetailsContentControllerDelegate protocol` to track the current group role in the UI.
> Feature: Update UI for the user profile: add status to change group role 

- fastlane/Fastfile
Fastlane failed to update to appCenter for `Using deprecated option: '--ipa' (true)`
`ipa` option is deprecated.
Replace with `file` option
run `fastlane update_plugins` to bump app center plugin
> fix: deprecated IPA parameter

- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsDataSource+Searching.swift
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsDataSource.m
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController+ShareContacts.m
For an unknown reason `ContactsDataSource.search` can not compile on CI sevser due to `searchDirectory` member property is not seen by this Swift extension. Pass it by parameter to try to solve it.
> fix: pass searchDirectory to ContactsDataSource.search

- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsContentController.swift
Hide a groupAdminStatus if the user is a  wireless guest.
> Fix: Hide a groupAdminStatus for the wirelessUser

- Wire-iOS Tests/StartedConversationCellTests.swift
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
disable crashing StartedConversationCellTests
> disable crashing StartedConversationCellTests

- Wire-iOS Tests/ProfileDetailsViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/Cells/IconToggleSubtitleCell.swift
- if the profile is of an external user who is also a group admin, the external and admin indicators overlap
- The spacing after the admin toggle is too large
- The admin indicator is placed after the external indicator in a custom spacing stack view, however there was no custom spacing after the external indicator.
- The `IconToggleSubtitleCell` has a top container and subtitle below it. In the case that there is no subtitle, subtitle label has zero height (as expected) but the top and bottom padding for the subtitle label still remains (total of 40pt).
- Add custom spacing of 20pt.
- Hide the subtitle label if there is no subtitle, and addition set the top and bottom margins appropriately.
The `IconToggleSubtitleCell` should be unified with the `ToggleSubtitleCell`, since the only …
> [Fix] Profile details design fixes

- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
Hide a "Group admin" label in the Profile screen if it's not a group conversation.
> Fix: Hide a "Group admin" label in the Profile screen

- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
This PR adds a check for consistency of the conversation when the conversation is loaded. If we ever end up in a situation where the roles are not present for a conversation, we will try to re-download them.
This is mostly useful for internal users that already have the new data model and were using an early version where roles are not fetched.
> Force refreshing roles if missing from a conversation

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/ConversationAvatarView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Header.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
For connecting user case:
- no avatar on the conversation list
- no avatar on the conversation screen
After changes of the data model, `ZMConversation.localParticipants` and `sortedActiveParticipants` no longer contains connecting user.
add `conversation.connectedUser` when the conversation type is `connection`
> Fix: Wrong visual avatar and user profile for pending outgoing connection

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
The visibility of the read receipt toggle should be based on the conversation role of the user and not on its team membership
> Fix read receipts not displayed for admin personal users

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Read receipt toggles is visible in every conversation. It should not be visible for personal conversations. 
This PR makes sure that the read receipt switch is visible only if the conversation is a team conversation.
> Show read receipts toggle only if conversation is a team conversation

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Header.swift
Avatar is not display for 1:1 condition
In https://github.com/wireapp/wire-ios/pull/3894, the guard logic for hiding header is wrong.
Refactor it to guard and correct the logic.
> fix: Missing avatar picture and unique username in 1:1 

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Replace  firstActiveParticipantOtherThanSelf with the connectedUser to cancel the connection request.
> Fix: Cancel connection request doesn't really cancel

- WireCommonComponents/AppLock.swift
Undo the changes in https://github.com/wireapp/wire-ios/pull/3754 as the issue still reproducible.
> undo: Fix: Applock unlock needs two fingerprint scans to unlock. 

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+ConversationMessageCellDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
No response when tapping badge item (Reply/Share/Delete) .
The conversationDidChange event reloads all tableView.
Add an observer of the conversation change in the cell.
> Fix: Add a conversation change observer to a cell

- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsViewController.swift
Message details screen would appear rotated if you return to this screen while holding the phone in landscape mode.
`shouldAutorotate` prevents the screen form rotating when it's the front most screen but not when when it's covered by another modal screen.
Implement `supportedInterfaceOrientations` to limit the orientation to `.portrait`.
> Fix: message details screen rotating by limiting supported orientations

- Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
GIVEN AppLock is active
AND AppLock uses account password
AND User is logged out
WHEN Wire comes to foreground (on the login screen)
THEN AppLock will ask account password BUT there is no active session to verify the password against
Do not show app lock if user is logged out (= has no active session).
The user will have to log in anyway, so the appLock requirement is fulfilled by the login page.
> [Fix] app lock when logged out

- Wire-iOS/Sources/Helpers/UIApplication+Permissions.m
App crash.
Alert was presented in the background queue.
Presenting alert in the main queue.
> Fix: Show alert  in the main queue

- Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
When creating a new account via email, the confirmation button is placed at the origin of the enclosing text field.
The button is a right accessory view of the text field, thus its layout is handled by UIKit. However, the buttons `translatesAutoresizingMaskIntoConstraints` property was set to `false`. This affects only iOS 13.
Don't set the property to false.
> [Fix] Misaligned button

- Wire-iOS Share Extension/Info.plist
- Wire-iOS.xcodeproj/project.pbxproj
- WireCommonComponents/BackendEnvironment+Shared.swift
- WireCommonComponents/UserDefaults+ApplicationGroup.swift
Share extension didn't run when Wire was running against a custom backend.
The custom backend was stored in the `.standard` user defaults which are not accessible by the share extension.
Store the custom backend info in the user defaults shared tied to the application group, which is accessible by the share extension.
> [Fix] share extension not working with a custom backend

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- WireCommonComponents/AutomationHelper.swift
Adds the launch flag:
`--disable-interactive-keyboard-dismissal`
Which disables the interactive keyboard dismissal of the conversation input bar keyboard. This is necessary since the automation doesn't see the buttons underneath the UITextView `accessoryView` when running on iOS 13.
> [Feature] Add launch flag for disabling the interactive dismissal of keyboard

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
When I open a 1:1 conversation, close it and open it again, app is stuck on wire logo
Conversation view controller is not loaded after https://github.com/wireapp/wire-ios/pull/3915/files#diff-0c732e18693b9c2c28bbd3cc2bdd252f
Compare conversation object with `===`, when conversationRootController is not created, create it.
> fix: When I open a 1:1 conversation, close it and open it again, app is stuck on wire logo

- Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/AppStateController.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
AppLock wasn't showing up after app launch
We relied on `isUserSessionActive` to decide if we need to show the appLock.
However, on app launch, the userSession is instantiated after checking `isUserSessionActive`.
This leads to the condition evaluating to `false` instead of `true`, therefore the appLock will not show.
Rely on appState transitions instead of userSession.
> [Fix] AppLock not showed on launch

- Wire-iOS/Sources/Authentication/Helpers/CountryCode/CountryCodeTableViewController.m
Search bar in the country selection screen is black on iOS 13
On the iOS 13 the background color of search bar is transparent.
Manually assign the background color to white.
> [Fix] black search bar when running on iOS 13

- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.swift
On devices that have a safe area at the bottom (iPhone X), the KeyboardAvoidingViewController would show a black bar above the keyboard.
This happens because we include the safe area twice when calculating the offset from the bottom.
1.  The view controller is attached to the `safeAreaLayoutGuide.bottomAnchor`
2. The keyboard frame includes safe areas.
Exclude safe areas from the keyboard frame calculating the intersection between keyboard frame and the `safeAreaLayoutGuide.layoutFrame`
Additionally the KeyboardAvoidingViewController copies the background color of the view controller to avoid a black safe area.
> [Fix] incorrect bottom offset in the KeyboardAvoidingController 

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Pull latest localization from crowdin.
> [Chore] Update localization

- Wire-iOS/Sources/Managers/MediaPlaybackManager.swift
Fix crash due to missing @objc signature of `activeMediaPlayer`, which causing it is not KVC-compliant.
> fix: crash with ConversationContentViewController viewWillAppear

- Wire-iOS/Sources/Managers/MediaPlaybackManager.swift
A swift property for KVO should have `dynamic` keyword.
> mark activeMediaPlayer dynamic

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InvisibleInputAccessoryView.swift
After https://github.com/wireapp/wire-ios/pull/3953, on conversation screen, view size is not reduced after the keyboard pops up
The calculation of constraint is wrong due to name conflict. 
Rename parameter from `view` to `invisibleInputAccessoryView` to prevent conflicting with `self.view`.
> Fix: conversation screen - size not adjusted after keyboard appear

- Wire-iOS/Sources/UserInterface/Components/Views/WebLinkTextView.swift
When running on iOS 13 the "this device" link, included in a system message, is no longer exposed to automation/accessibility.
By trial and error I discovered that `isEditable` must now be true for links to exposed as accessibility elements in iOS 13.
Remove code which sets `isEditable` to `false`. The textview is still not editable since we override `canBecomeFirstResponder` and the gesture recogniser.
> [Fix] Make links accessible to automation on iOS 13

- Wire-iOS/Sources/UserInterface/Components/Views/PopUpIconButtonView.swift
Refactoring updateSelectionForPoint method in PopUpIconButtonView
> Refactor: Switch loops to map and filter.

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InvisibleInputAccessoryView.swift
Replace `KeyValueObserver` with Swift observe method.
> replace KeyValueObserver with Swift observe

- Wire-iOS/Sources/UserInterface/Components/Views/WebLinkTextView.swift
The "You device" link in system message are not tappable on iOS 12
`isEditable` was set to true in https://github.com/wireapp/wire-ios/pull/3963 to fix an issue with automation.
Only set `isEditable` to true in iOS 13 or above.
> [Fix] system message links not working in iOS 12

- Wire-iOS/Sources/Helpers/TextTransform/String+Transform.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewModel.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
Extra space at the end is a cause that the user disappears in the search UI.
We use the original search string (with spaces) to search.
Remove whitespaces.
> [Fix] Remove all whitespaces at the end of a search string

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Suggested mention list does not stay when navigating to conversation list and navigating back to conversation.
We show a mention list only after editing the textView.
Check in the `viewWillAppear` method of `ConversationInputBarViewController` if we need show a mention list.
> [Fix] Show a mention list if necessary.

- Wire-iOS/Sources/AppDelegate+AppCenter.swift
Implement `MSDistributeDelegate` and display release info in the update dialog.
> AppCenter distribution alert with readable message

- Wire-iOS/Sources/AppDelegate+AppCenter.swift
Show more details on the AppCenter update dialog:
- include the short version
- add a button to open release URL
- change to action sheet style for more space to display the text.
> Fix: AppCenter update dialog with more actions

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
Prevent possible out-of-bound access of array in `numberOfRowsInSection`
> Fix: App crash when numberOfRowsInSection

- Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel+StartUIDelegate.swift
When tapping on the a `TopPeopleCell` in the Start UI, the conversation for that cell would open as expected. However, immediately after tapping, the conversation list would flash on screen with a transparent background, before the conversation slid in.
The start UI view controller was not dismissed before triggering the animation to open the conversation.
Dismiss the start UI first.
> [Fix] Dismiss Start UI Before Opening Conversation

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+TypingIndicator.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
This PR is part of an ongoing effort to improve the use of `UserType`. Part of our aim is to make `UserType` a Swift only protocol, so that we are able to conform to `Hashable` in the future. To set this up, we must first remove all objective c references to the `UserType`.
This PR moves the `ZMTypingChangeObserver` conformance of `ConversationInputBarViewController` over to Swift.
> [Refactor] Move ZMTypingChangeObserver conformance to Swift

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
The ephemeral timer below a message is not visible to automation on iOS 13
The label displaying the timer is not visible to voice over
Set `isAccessibilityElement = true` on the label.
> [Fix] ephemeral timer not being visible to voice over / automation

- Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift
Remove KeyValueObserver from MediaPlayerController. Tested on simulator with player video in conversation.
> Fix: remove KeyValueObserver from MediaPlayerController

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
iPad status bar is always dark after refactoring
iPad has a black bar area and status bar is always invisible
Do not follow child view's status bar config when iPad is in regular mode
Fixed `SettingsClientViewController` status bar style
> fix: iPad status bar style

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.swift
Remove the notch check when hiding the bars. 
Refactoring animation code of fading out/in navigation bar.
> Fix: iPhone without notch - full screen image viewer can not re-show the navigation bar

- Wire-iOS/Sources/AppDelegate+AppCenter.swift
Fix the issue that AppCenter alert sheet is covered by the keyboard.
> Fix: AppCenter update dialog - dismiss keyboard before showing

- Wire-iOS/Sources/AppDelegate+AppCenter.swift
Config the alert's source view to prevent the crash.
> Fix: iPad - app crash when showing app center update dialog

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.swift
App crash with accessing `dataSource?.messages`
It may access out of bound elements
Add a guard to check whatever `indexPath.section` is within `dataSource?.messages.indices`
> Fix: app crash at ConversationContentViewController.willSelectRow

- Wire-iOS/Sources/UserInterface/Components/Controllers/SectionCollectionViewController.swift
Add guards to prevent out of bound access.
> Fix: app crash - SectionCollectionViewController shouldHighlightItemAt

- Wire-iOS/Sources/AppRootViewController.swift
When iPad is rotated of switching split mode, the main window is not fully covered by the app lock screen.
`NotificationWidow` is not resized correctly.
Pass the new size to `updateOverlayWindowFrame` and resize to the new size instead of the old size.
> Fix: iPad - app lock screen does not cover the main screen

- Wire-iOS/Sources/Permissions/ShareContactsViewController.swift
If the access to the device contacts in defined and we tap on the "invite more people" button in the Start UI, then we see a blank screen. Instead, we expect to see UI asking us to grant access to the device contacts.
The `ShareContactsViewController` is responsible for displaying the UI to prompt the user to grant permissions. When the view loads, we invoke `displayContactsAccessDeniedMessage(animated:)`, which in turn will call `addressBookAccessDeniedViewController.view.isHidden = false`. However, this property gets set to `true` not long afterwards. 
This is happening because all the view setup occurs in the `init` method after `super.init()`. Soon after the super initializer completes, `viewDidLoad` is invoke. However this happens before `init` completes, so we always hide the view. …
> [Fix] ShareContactsViewController is hidden

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
- Wire-iOS/Sources/UserInterface/Company Login/UIAlertController+CompanyLogin.swift
Show correct error on enterprise login while already logged in.
> [Feature] Show correct error on enterprise login while already logged in 

- Wire-iOS/Sources/Helpers/ColorScheme+Helper.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangePhoneViewController.swift
Conversation screen has a white status bar after call ends.
`CallTopOverlayController` has a dark status bar
`ChangePhoneViewController`'s status bar is dark on dark after dismissed country screen
Call `setNeedsStatusBarAppearanceUpdate` in these cases.
Clean up the animation code.
> Fix: incorrect status bar style

- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsController.swift
The app sometimes crashes in group calls.
The `CallHapticsController` tries to generate a dictionary with the call participants using the call participant itself as the key, this crashes if a call participant exists twice in the list.
Don't assume that call participant list doesn't contain any duplicates and employ a uniquing strategy.
> [Fix] Don't assume list of call participant doesn't contain any duplicates

- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
We show an unread count for a conversation without indicating it with an unread badge next to it (when the self user has been added to / or kicked from a conversation).
We don't display an unread badge next to a conversation, when it's a system message, and display a badge on the folders grouping.
To display an unread badge next to a conversation when the self user has been added to / or kicked from a conversation.
> [Fix] Displaying the badge count without unread conversation

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
There's a badge count without unread conversation.
Expose two methods for finding conversations with unread messages under Settings > Advanced > Debugging Tools. It would help to find a badge problem by triggering a debug action.
> [Fix] Add the debugging tools section to public builds

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
CS raised a concern that the new debugging tools section under settings is confusing.
The section currently contains:
First unread conversation (badge count)
First unread conversation (back arrow count)
1. Remove "First unread conversation (back arrow count)" since it's doing the same as "First unread conversation (badge count)" but doesn't include pending connection requests.
2. Rename "First unread conversation (badge count)" to "Find first unread conversation" so that it's more clear what the button does.
> [Fix] Simplify debugging tools sections

- Wire-iOS/Sources/Helpers/TextTransform/String+Transform.swift
- Wire-iOS/Sources/Helpers/TextTransform/TransformLabel.swift
- Wire-iOS/Sources/UserInterface/Components/TextView/TextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
After https://github.com/wireapp/wire-ios/pull/4050/, the `TextView` can not use display accessibility value. (It was the text of placeholder)
Unknown, but accessibility value should be customized in this case.
override accessibility value and use the placeholder's text if it is shown.
Clean up unnecessary `public` and `@objc` signatures.
> Fix: TextView missing accessibility value

- Wire-iOS/Sources/Helpers/UITraitEnvironment+LayoutMargins.swift
Name and avatar is not aligned correctly on iPad.
We use a smaller margin (as for iPhone) to display name and avatar on iPad.
Remove an extra check.
> [Fix] Name and avatar is not aligned correctly on iPad

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
This PR fixes the incorrect conversation screen navigation bar bottom assignment. Perviously we have custom swapping navigation bar items but it is not needed.
After the fix the UI is like this, the arrow button is on the right and call button is on the left:
> fix: right to left language navigation item position

- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+ErrorAlert.swift
After the first failed attempt to log in, any subsequent attempt is ignored.
When the first attempt fails an error alert is shown as expected. Dismissing the alert should unwind the authentication state so that new attempt can be made. Unfortunately, the dismissing the alert does not invoke the necessary closure to unwind the state. This is due to a recent refactoring where the `handler` parameter is not passed to the `UIAlertController`.
Pass the parameter to the alert controller.
> [Fix] Can't login after first failed attempt

- Wire-iOS/Sources/UserInterface/Components/MediaAsset.h
- Wire-iOS/Sources/UserInterface/Components/UIPasteboard+MediaAsset.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
Change `MediaAsset.data` to optional and unwrapp it before access.
> fix: app crash when accessing MediaAsset.data

- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.swift
After removing a device, the bottom inset of client device table is negative and scroll to bottom is impossible.
`bottomOffset` should not add `frame.minY` when keyboard is not shown.
Check for this case and not change the `bottomOffset`.
> fix: client device screen bottomOffset

- Wire-iOS/Sources/UserInterface/Components/Loading/CABasicAnimation+Rotation.swift
Fix the jagged rotation caused by using keyPath `CAValueFunctionName.rotateZ`. Refactor the code for readability.
> Fix: jagged spinner rotation

- Wire-iOS/Sources/AppDelegate+URL.swift
- Wire-iOS/Sources/Components/CompanyLoginFlowOpener.swift
When you try to sign in with SSO and the provider is misconfigured, there should be a error alert.
The alert is not shown because it's presented on the rootViewController which isn't in the view hierarchy since a browser view controller currently visible.
Present on `UIApplication.shared.topmostViewController()` instead.
> [Fix] SSO error alert is not shown

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBarViewController.swift
The long user name overlaps the avatar image in the conversation list header after the username  changing.
We do not update avatar constraints.
Update title and avatar constraints.
> [Fix] Avatar image overlaps user name

- Wire-iOS/Sources/UserInterface/Components/Controllers/DefaultNavigationBar.swift
- Wire-iOS/Sources/UserInterface/Components/Transitions/CrossfadeTransition.swift
- Wire-iOS/Sources/UserInterface/Components/Transitions/NavigationTransition.swift
- Wire-iOS/Sources/UserInterface/Components/Transitions/SwizzleTransition.swift
- Wire-iOS/Sources/UserInterface/Components/Transitions/VerticalTransition.swift
- Wire-iOS/Sources/UserInterface/Components/Transitions/ZoomTransition.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBarViewController.swift
When swizzle transition is done, the navigation bar "jumps" down.
After https://github.com/wireapp/wire-ios/pull/4088, missing `containerView.layoutIfNeeded()` call.
Add `containerView.layoutIfNeeded()` instead of `containerView.setNeedsLayout()`
Refactoring other Transition classes to call `layoutIfNeeded()` after `addSubView`.
Refactor `CATransform3DMakeTranslation` to simpler `CGAffineTransform`.
> Fix: swizzle transition jumps after transition

- Wire-iOS Tests/ChangeEmailViewControllerTests.swift
- Wire-iOS Tests/ChangeHandleViewControllerTests.swift
- Wire-iOS Tests/ContactsViewControllerSnapshotTests.swift
- Wire-iOS Tests/Settings/SettingsTechnicalReportViewControllerSnapshotTests.swift
- Wire-iOS Tests/StartUIViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/DefaultNavigationBar.swift
- Wire-iOS/Sources/UserInterface/Components/TextView/TextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController+State.swift
Remove `wrapInNavigationController` objc interfaces and convert their callers to Swift.
> Remove wrapInNavigationController objc interfaces

- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Devices/ProfileClientViewController.swift
Add missing `preferredStatusBarStyle ` overriding to `MessageDetailsViewController`, `SettingsClientViewController` & `ProfileClientViewController`.
> Fix: status bar style in presented screens

- Wire-iOS/Sources/AppDelegate+URL.swift
When SSO is not configured correctly we show an error alert describing the problem. This works but we should also dismiss the inline browser before we display it.
Dismiss any presented view controller before presenting the error alert.
> [Fix] browser not being dismissed when a SSO login error occurs

- Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallWindow/CallWindowRootViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/InteractiveModalTransition.swift
- Wire-iOS/Sources/UserInterface/Overlay/ActiveCallViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
Do not allow rotation in `CallWindowRootViewController`. 
In `InteractiveModalTransition`, set `modalPresentationCapturesStatusBarAppearance = true` to fix status bar not updated in presented view controller issue.
> Fix Call window status bar and rotation

- Wire-iOS/Sources/AppStateController.swift
App throws "Something went wrong" on First Time Overlay when user logs in with the same phone number for the second time.
To use `ZMUserSession.shared()?.selfUser` when we need to set the user email.
> [Fix] Login with a phone number

- Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.swift
app lock screen: status bar is dark on dark.
`NotificationWindowRootViewController` get `childForStatusBarHidden` from `topmostViewController`, which is `AppRootViewController` and behind the lock screen.
Get `childForStatusBarHidden` instead from `AppLockViewController`. Hide the status bar in this case.
> fix: lock screen - status bar is dark on dark

- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationCallController.swift
The status bar turns white after multiple callee alert is shown.
Unknown, the status bar style is not refreshed by the OS.
Call `setNeedsStatusBarAppearanceUpdate()` after the alert dismissed.
> fix: Status bar turns white after multiple callee alert is shown

- Wire-iOS/Sources/Components/Settings+Logging.swift
- Wire-iOS/Sources/Components/Settings.swift
If you enable log tags under the develop menu they are not restored on the next re-launch when running on a device.
Log tags are only restored when running on the simulator.
1. It's only interesting to restore log tags when running on a device since when we run on a simulator the log tags are supplied via a launch argument. I will therefore invert this logic and only restore log tags when running on a device.
2. We always want to start the log recording so I'm removing the logic for starting/stopping when enabled/disabling log tags.
> [Fix] Enabled log tags are not restored when running on a device

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsSignOutCellDescriptor.swift
[iPad] On Log Out, entering a wrong password does not show error dialog.
The alert was presented form `ZClientViewController.shared` which is hidden by the sheet style Setting screen.
Present the alert form `UIApplication.shared.topmostViewController(onlyFullScreen: false)` instead.
> Fix: [iPad] On Log Out, entering a wrong password does not show error dialog

- Wire-iOS/Sources/UserInterface/Components/Transitions/ZoomTransition.swift
The connection request modal is not presented on iPad
The custom transition animation is never completed because we guard against `transitionContext.fromView` being nil, and return early. When presenting using the `.formSheet` presentationStyle the `fromView` is not set when presenting and `toView` is not set when dismissing.
Don't assume `toView` and `fromView` is always available.
> [Fix] Connection request modal not showing on iPad

- Wire-iOS/Sources/UserInterface/Components/Transitions/CrossfadeTransition.swift
- Wire-iOS/Sources/UserInterface/Components/Transitions/SwizzleTransition.swift
Follow up of https://github.com/wireapp/wire-ios/pull/4141, allow `CrossfadeTransition` and `SwizzleTransition.swift` having nil toView/fromView.
> allow Transition 's toView/fromView to be nil

- Wire-iOS/Sources/Helpers/UIImage+ImageUtilities.swift
- Wire-iOS/Sources/Helpers/syncengine/ProfileImageFetchable.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/Data+HEIF.swift
- Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
App crashes at the line `CIContext.init()`.
Unknown, but ref to "Performance Best Practices"
https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_performance/ci_performance.html, `CIContext` should not be created repeatedly.
Create `CIContext.shared` and clean up repeated created instances.
> Fix: crash with creating CIContext

- Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleViewController.swift
- Wire-iOS/Sources/UserInterface/Availability/UIAlertController+Availability.swift
On iPad, the availability popover is not properly positioned.
Config the alert with `configPopover` method.
> Fix: iPad - availability popover is not properly positioned

- Wire-iOS Tests/LocationMessageCellTests.swift
disable `testThatItRendersLocationCellWithAddressCorrect` which snapshots a `MKMapView`.
> fix: disable testThatItRendersLocationCellWithAddressCorrect

- Wire-iOS Tests/LocationMessageCellTests.swift
Disable `testThatItRendersLocationCellWithoutAddressCorrect` since it's flaky.
> [Fix] Disable testThatItRendersLocationCellWithoutAddressCorrect

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/UserSelection.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
There is a lot a lot of redundant public access and `@objc` annotations. This can lead to some issues where other types must also be unnecessarily marked public because some public API exposes it.
It's likely that several of the Objective C classes that have been converted to Swift recently made this interoperability redundant.
Remove public access modifiers and `@objc` annotations where possible.
By no means is this a comprehensive clean up, it just covers a few of the classes I've encountered.
> [Chore] Clean up redundant objc interoperability

- Wire-iOS/Sources/Components/Settings+Logging.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Devices/ProfileClientViewController.swift
Cryptobox logs are not activated for public builds
We don't activate any log tags for public builds
Activate the default log tags for all builds.
In order to make easier to test crypto box error logs I've added a debug action for corrupting a session on the device details screen.
> [Fix] missing cryptobox logs on public builds

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationMessageToolboxCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.swift
When the user deleting a message (when the message failed to send), app crashes.
`ConversationContentViewController` presents the alert and configs, but not conforms to `PopoverPresenter`.
`ConversationContentViewController`  conforms `PopoverPresenter`.
Change the alert source view form the toolbox cell to the `delete` button.
Call `updatePopoverSourceRect` when the app windows size changes to update the popovers positions.
> Fix: iPad - app crashes when delete message popover shows

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileActionsFactory.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
The profile acton item to unblock an user had the wrong text, It has to be changed form "unblock..." to "unblock".
wrong localisable string used.
changed the localisable string for the text of the action item.
Jira Ticket: https://wearezeta.atlassian.net/browse/ZIOS-12570
> Wrong text on profile action item to unblock and user.

- Scripts/download-avs.sh
Using the `access_token` query parameter in GitHub API endpoints is deprecated and will be removed July 1st 2020.
Use the Authorization HTTP header instead, via `curl -u <username:token> <endpoint>`
I also added echoed an error message when either the access token or username isn't set and return early.
> [Chore] Don't use deprecated Github API

- Wire-iOS/Sources/Helpers/syncengine/ProfileImageFetchable.swift
Sometimes the profile image in the search result is not loaded
`ZMSearchUser` was not conforming the protocol `ProfileImageFetchable`
`ZMSearchUser` now conforms to the protocol `ProfileImageFetchable`
Jira Ticket: https://wearezeta.atlassian.net/browse/ZIOS-12605
> [Fix]: Profile Image Not Loaded In Search

- Scripts/download-avs.sh
The check for git was incorrect, causing the credentials not to be set. 
The check was `command -v git >dev/null` when it should have been `command -v git >/dev/null` (note the missing forward slash).
Although inserting the forward slash is fine, I decided to use the same checks we do in `setup.sh` when we check for Carthage. It uses `hash` instead.
Also I moved the credential checks further down the script to the point before we try to download the avs binary. This will prevent issues with the credential checking in the case they're not even needed.
Some helpful error messages are now returned when either git or the credentials are not found.
> [Fix] AVS script

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ViewLifeCycle.swift
- Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
On iPad when is in landscape after logging in a conversation was opened, but it shouldn't
Managed incorrectly to present the initial conversation
fix issue to present the initial conversation
> After login on iPad wrong conversation is opened instead none

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
I couldn't reproduce the crash but it seems that sometimes after loading an image from the camera in a conversation the app crashes.
The causes could be 2:
1) force unwrapping on image initialisation from a Data
2) in onConfirm block [unowned self] is nil.
1) use a guard statement to avoid the force unwrapping on the image initialisation
2) [weak self] instead of [unowned self].
> [Fix] conversation camera crash

- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
The navigation bar hides containing the search bar hides the giphy collection view
Wrong content insets on the giphy collection view
Added content insets on the giphy collection view
https://wearezeta.atlassian.net/browse/ZIOS-12575
> [Fix]: Navigation Bar hides Giphy on top

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.swift
Adding a second account crashes the app.
When adding a second account, we log out of the current account and the app transitions to an `unauthenticated` state. This causes the `SelfUser.provider` to be set to `nil`. Any calls to `SelfUser.current` will cause a crash.
The offending call to `SelfUser.current` is in `ConversationListItemView` --- a descendant of the `ConversationListContentController`. It is triggered  the content controller's `viewWillAppear(:)` is called. As a comment already notes, `viewWillAppear` may be called when the parent view controller is dismissed (which happens when we transition to the landing page), and a check that the shared user session exists is there to prevent loading the UI.
Unfortunately, this check fails when there is no self user.
Update the guard to …
> [Fix] Crash when adding new account

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCell.swift
Use `ButtonMessageState`'s string value as `Button`'s accessibility value.
> Feature: accessibility for button selected state

- Wire-iOS/Sources/Components/Settings.swift
- Wire-iOS/Sources/Developer/DebugAlert.swift
App crashes when goes to background, or sending a bug report.
1. called `UIApplicationDelegate.applicationDidEnterBackground` instead of `Setting.applicationDidEnterBackground`
2. `SelfUser.current` may be nil when sending the debug report.
Fix with calling property method.
> fix crashes when the app goes to background or sending bug report

- Wire-iOS/Sources/Developer/DebugAlert.swift
Correct the alert button text. Change the cancel action button title from OK to cancel.
> Fix: If there's no email client and sending debug report, alert shows 2 OK buttons

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
When the app goes to background and switch to other app and then come back to the app, the draft text is cleared.
the draft text is not stored in this case. ( currently we only save the draft text when keyboard dismisses, e.g. switching conversations)
Store the draft text when the app goes to the background.
> Fix: app does not keep message when typing a message and switching apps before sending

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
Implement `isConfigurationEqual` to fix button state not updated after tapped issue.
> Fix: button state not change

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCell.swift
Create default impletement of `isConfigurationEqual` for where `View.Configuration : Equatable`.
Remove repeated implementation in cell classes where `Configuration` are `Equatable`.
> Create isConfigurationEqual for View.Configuration : Equatable

- Wire-iOS/Sources/Components/Buttons/SpinnerButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
Reset button state before config.
Do not allow tapping confirmed buttons.
> Fix: reset button state and do not allow tapping confirmed button

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
- Add `hasError` to the Configuration hash
> [Fix] button cell configuration hash

- Wire-iOS Tests/UIAlertViewController+CompanyLoginTests.swift
- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
- Wire-iOS/Sources/UserInterface/Company Login/UIAlertController+CompanyLogin.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIAlertAction+Convenience.swift
When a SSO code in copied to clipboard, it repeatedly appear even cancel is pressed.
1. The `pollingTimer` keep creating alert even it is already shown
2. After cancel is pressed, it is still trying to show the alert when going to another screen.
1. Check if there is a exist SSO alert before presenting a new one
2. Stop polling after cancel is pressed, and set the flag `cancelSSOPressed` to true to prevent the alert shows again.
> Fix: [iPad iOS 13] when having SSO code on clipboard, login page gets stuck in loop

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/Buttons/SpinnerButton.swift
- Wire-iOS/Sources/UserInterface/Components/Loading/ProgressSpinner.swift
- Wire-iOS/Sources/UserInterface/Components/Loading/Spinner.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
1. `SpinnerButton` animation may not start with changing its `isAnimating` property
2. Spinner may be visible when the button has a solid color background
1. `ProgressSpinner` has some code related to `UIWindow` and `UIApplication` which causes side effects to animation
2. `SpinnerButton`'s background image is not updated when switching style.
1. Create a simpler `Spinner` class just for `SpinnerButton`
2. Reset`SpinnerButton`'s background image when switching style.
> Fix: button spinner animation unstable behaviour

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
Create `PollMatcher` to display poll message in the cell's subtitle.
> Feature: display poll message in conversation list cell status

- Wire-iOS Tests/TeamMetadataRefresherTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Helpers/TeamMetadataRefresher.swift
- Wire-iOS/Sources/Helpers/TimeInterval+Units.swift
Clients will no longer receive update events when the team metadata changes (e.g. team name, logo). Therefore the client needs to regularly fetch the team metadata from the backend.
It is sufficient to refresh the team metadata only once in a 24 hour period. `TeamMetadataRefresher` is a helper class that exposes the method `triggerRefreshIfNeeded()`. This method is called whenever the app becomes active. The method will only trigger a refresh if it has been 24 hours since the last refresh.
**JIRA:**  https://wearezeta.atlassian.net/browse/ZIOS-12822
> [Feature] Refresh team metadata daily

- avs-versions
Bump AVS to 5.5.10
There are 2 important bug fixes that should make it into a release as soon as possible:
- Decrease amount of logging such that debug reports can be sent by email again
- Remove an unnecessary UPDATE for video call signaling
> Bump AVS to 5.5.10.

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
We are renaming the "Contacts" section in search to "Recents", since it will no longer contain all your team members.
> [Feature] Rename Contacts section to Recents for teams

- Wire-iOS Tests/AvailabilityStringBuilderTests.swift
- Wire-iOS Tests/Mocks/MockUser.m
- Wire-iOS Tests/Mocks/MockUserType.swift
- Wire-iOS/Sources/UserInterface/Availability/AvailabilityStringBuilder.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
Currently there exists code that disables displaying statuses of other users if the team contains more than 400 members. It has been decided that we now want to show the availability of all other users, if they have one.
Remove the related code.
**JIRA:** https://wearezeta.atlassian.net/browse/ZIOS-12885
> [Fix] Always show availability status of other users

- Scripts/download-assets.sh
Change the branch for the `wire-ios-build-configuration` project which contains new backend URLs.
> [Feature]Change the branch for the wire-ios-build-configuration project

- fastlane/Fastfile
Modify the fastlane file to be able to use another branch of the wire-ios-build-configuration project.
> [Feature] Modify the Fastfile script

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
Spinner does not dismiss on `ClientListViewController`
The spinner is show on `ClientListViewController` when init. But the dismiss method tries to dismiss it on its `navigationController `
Dismiss both spinners if presented.
> fix: Endless spinner on my Devices page when I only have 1 device

- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
When entering an invalid SSO code after pressing the "Enterprise login" button, we don't show the expected error alert.
The error alert is triggered by:
```
input.apply(inputHandler)
```
but it's not shown due to the following guard statement:
```
// Do not repeatly show alert if exist
guard ssoAlert == nil else { return }
```
nil out `ssoAlert` before executing:
```
input.apply(inputHandler)
```
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12922
> [Fix] invalid SSO code alert not appearing

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
Make a pause of 1 sec before retrieving a signature
> [Fix] Make a pause of 1 sec before retrieving a signature

- Wire-iOS Share Extension/UnsentSendable.swift
- Wire-iOS Tests/CameraKeyboardViewControllerTests.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+Shared.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetLibrary.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+FilesPopover.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
- WireCommonComponents/AVAsset+VideoConvert.swift
When sending a video from camera keyboard, the file can exceed file size limit and not visible on Android devices. (Sending form image picker has no such issue)
If pick a 4K video from the camera keyboard, the video is not resized. (Pick from image picker would have default quality, which is 720p)
If the video has a width wider than 1920px, Export the video with `AVAssetExportPreset1920x1080`.
Set default video preset when select a video from image picker.
Set `fileLengthLimit` to self user's max file size limit.
> Fix: sending a 4K video is allowed and it is not viewable on android

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
when we have no message data in the cache to start the digital signature process an error is shown.
> [Feature]: digital signature show error

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
App crashes when changing the local ephemeral timeout
App will crash intentionally crash if we try to change the local ephemeral timeout when the timeout is set via the conversation options and thus synchronised for everyone in the group. This scenario can happen if you open the dialogue for setting local timeout while someone else changes ephemeral timeout in the conversation options.
Dismiss the local ephemeral dialogue when the conversation ephemeral timeout is set.
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12903
> [Fix] Crash when ephemeral timeout is changed

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.swift
To digital sign a PDF it is necessary that it is already downloaded. When the PDF is not downloaded the client shows and alert and when the user tap on "download" the PDF will be downloaded.
> [Feature] Digital Signature download alert

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
GIVEN There is a poll message
WHEN The app becomes active (after being in background)
THEN Spinner doesn't show on selected buttons
AND User needs to navigate back and forth to the conversation to refresh buttons statuses
The main conversation controller (`ConversationContentViewController`) reacts to `applicationDidBecomeActive` notification by calling `dataSource.resetSectionControllers()`.
Resetting the section controllers causes the `ConversationMessageSectionController` to be deallocated. Which in turn prevents observation of the `ButtonState` of our buttons. Thus, when a button is selected and its state changes, we don't notice and can't update the UI.
According to a conversation with @typfel:
Originally, the logic in `applicationDidBecomeActive` is to reload everything after coming …
> [Fix] poll button spinner

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> Tier1: Revert contacts title in startUI to "Contacts"

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
Share extension crash when searching a name.
Unknown, but it does not occur in pervious and seems related to objc removal tasks.
To prevent using `NSPredicate` with non-objc protocol and String, use range search instead.
> fix: crash - share extension crashes when search a name

- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+CompanyLogin.swift
- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
https://wearezeta.atlassian.net/browse/ZIOS-13118
For custom backends with a fixed SSO code,
Instead of presenting the Enterprise Login landing page after the backend switch,
We need to open the SSO flow automatically.
> [Feature] Linear onboarding - automatic SSO login for fixed SSO BE

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Human readable error message for username too long
Wrong localisable text
provided a new text
Jara ticket: https://wearezeta.atlassian.net/browse/ZIOS-12503
> [Fix]: Human readable error message for username too long

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Self.swift
When archive the project for release, Xcode 11 fails due to `While emitting IR SIL function "@$s4Wire36ConversationListTopBarViewControllerC014createSettingsfG0So06UIViewG0CyFTf4d_n".`
It is related to casting `MockUser` to unrelated class `ZMUser`.
Cast in Simulator target only.
> Fix: do not force cast MockUser to ZMUser for device target

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
App crash at getter `ConversationTableViewDataSource.messages`
Unknown, but the stack trace stops at the objc getter first line.
Remove the @objc interfaces in `ConversationTableViewDataSource` to see this issue still occurs or not.
> fix: app crash at ConversationTableViewDataSource.messages

- Scripts/update_stylekit/main.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserImageView/BadgeUserImageView.swift
Remove `StyleKitIcon` support of objc in the generated code.
> remove objc support of StyleKitIcon

- Wire-iOS Tests/LicensesLoaderTests.swift
- Wire-iOS/Sources/Components/LicensesLoader.swift
After removing objc/NSObject marks in `LicensesLoader`, `LicensesLoaderTests` fails.
It can not meet the expectation query after the line `@objc var cacheEmpty` removed the `@objc` signature.
Refactor with `NSPredicate(block:)`
> Fix: refactor NSPredicate query to block in LicensesLoaderTests

- Wire-iOS Tests/SelfProfileViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
If the team metadata has changed remotely and the user opens the account screen, they do not see the refreshed data until the dismiss the screen and reopen it.
When the account screen is presented, the team is marked as needing to be refreshed. However the refresh won't be triggered until the managed object context is saved, which is probably happening when the screen is dismissed. Therefore opening the screen a second time will show the new metadata.
Trigger the refresh immediately.
> [Fix] Trigger team refresh immediately in account screen

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Digital Signature: Incorrect error message when document is not downloaded before signing.
wrong text in the localisable string text.
right text in the localisable string text.
> Wrong error message

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewControllerViewModel.swift
`ProfileViewController` title does not update when other user's name changes.
Update title when the user name changes.
> Fix: ProfileViewController monitors user name change

- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
Observes team name update in `SelfProfileViewController` and update the team name label text.
> fix: SelfProfileViewController observes team name update

- Wire-iOS.xcodeproj/project.pbxproj
Warning when build the app: `:-1: Linking against a dylib which is not safe for use in application extensions: /Users/bill/Documents/wire/wire-ios/Carthage/Build/iOS/PINCache.framework/PINCache`
ref to: https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html
"To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”."
But actually WireCommonComponent and WireShareExtensions do not use `PINCache`, seems like and issue of Carthage, which includes the the framework to all targets.
Set …
> fix: remove warning when building extension and framework

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.swift
Unwrap the data before creating `FLAnimatedImage `
> Fix: app crash when create a FLAnimatedImage with nil imageData

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+DragAndDrop.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
On Xcode 11, confirm image screen not shown after tapped a photo on camera keyboard.
Unknown, but after removed `FastTransitioningDelegate` it works again.
Remove `FastTransitioningDelegate` completely to prevent similar cases.
> Fix: Xcode 11: confirm image screen not shown after tapped a photo on camera keyboard

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
Call `endEditing` before presenting `confirmImageViewController` to prevent keyboard overlaps the presented screen.
> Fix: XCode11: Keyboard appears after image confirmation screen presented

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/ViewControllerDismisser.swift
After a call screen is minimised, the conversation screen is not responsible to touch events.
`CallWindow` is not hidden, and touch evert does not pass though that window.
Hide the window after dismissal
> Fix: Xcode 11 - UI is not response to touch event after a call is minimised 

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
- Wire-iOS Share Extension/ShareExtensionViewController.swift
- Wire-iOS Share Extension/TargetConversationCell.swift
- Wire-iOS Share Extension/UIColor+NamedColors.swift
- Wire-iOS.xcodeproj/project.pbxproj
Colors are not  readable when running the share extension in dark mode.
The share extension is using hard coded UIColors (.white, .black), which doesn't look correct when running in dark mode.
Start using semantic UIColors in the share extension which adapt to the current appearance (dark/light).
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13388
> [Fix] Colors in share extension when running in dark mode

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
Temporarily disable tests not pass on Jenkins.
> Fix: disable tests passed on Azure but not Jenkins

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/GroupDetails/Cells/GroupDetailsNotificationOptionsCell.swift
Add missing localisation for "Notifications" cell title.
> Fix: add missing localization in Setting screen

- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
When popped to Collection Screen, the search bar is covered by navigation bar.
Seems like a autolayout issue.
Set `navigationController?.navigationBar.isTranslucent = false` in `viewWillAppear` (The collection view does not go under navigation bar)
> Fix: collection screen - search bar is covered by navi bar after popped from image viewer

- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
For iOS 13, uses `UIColor.label` which adapts system apperance for alert's tint(text) color.
> Fix: Xcode 11: action sheet has dark text in iOS dark mode

- Wire-iOS/Sources/UserInterface/Conversation Options/UINavigationController+CloseButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ParticipantsPopover.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ProfileViewControllerDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Status bar is white on white after dismissed conversation detail screen.
Unknown, status bar should be updated by the system.
Call `setNeedsStatusBarAppearanceUpdate` after the presented screen is dismissed.
> Fix: Xcode 11: status bar is white on white after dismissed the conversation detail screen

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
The temporary device(s) were shown in the remove device scree after the login.
Wrong filter applied
Correct filter applied
> [Fix]: Remove devices step during login includes temporary clients

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewControllerViewModel.swift
The app would crash if you tried to open the 1:1 conversation of deleted user in a tier 1 team.
The user is no longer a member of the team after the he/she been deleted which causes `ZMUser.oneToOneConversation` to return `nil`. This was resulting in a crash because we where force unwrapping the conversation.
1. Guard against conversation being nil
2. Hide the "open conversation" button if we discover that a user is deleted.
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13343
> [Fix] Crash opening 1:1 conversation in tier 1 team

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/InteractiveModalTransition.swift
After dismiss a call screen by panning, the UI does not response to touches.
same as https://github.com/wireapp/wire-ios/pull/4339
hide window when dismissal is done.
> Call window blocks touches to conversation

- Wire-iOS Share Extension/UnsentSendable.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
- WireCommonComponents/AVAsset+VideoConvert.swift
- WireCommonComponents/FileManager+TempDirectory.swift
When sharing a file from file app, only file name is sent but not the file.
After update SDK, `NSItemProvider.loadItem` provides the URL of file instead of `Data`
Upload file instead of Data in for this case.
> Fix: XCode11: endless spinner when sharing a text file from file app

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Helpers/Delay.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallQualityController/CallQualityController.swift
When a call quality screen is presented and a new incoming call is ringing, the call screen does not present, tap on the top bar does not open the call screen.
The dismissal of the call quality screen and the presenting of the call screen starts at the same time and the later one fails to complete.
Delay the presenting of the call screen in this case.
> Fix: Call screen is not presented when call quality screen is dismissing

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
This is a follow up for https://github.com/wireapp/wire-ios/pull/4332
When selecting a video from the keyboard, the video preview is shown but the text keyboard overlaps it.
Not entirely sure.
Call `endEditing()` as the other PR does.
> [Fix] Keyboard covers video preview screen

- Wire-iOS/Sources/UserInterface/Location/LocationSelectionViewController.swift
Fix the similar issue as https://github.com/wireapp/wire-ios/pull/4362 when opening location screen
> Fix: keyboard is shown over location picker after changing ephemeral timer

- Wire-iOS Share Extension/UnsentGifImageSendable.swift
Fix the similar issue as https://github.com/wireapp/wire-ios/pull/4353 for GIF files.
> Fix: Share Extension: using share extension from Giphy results in endless spinner

- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
The app would get stuck with a spinner during login if you:
1. Login into an account with 7 devices 
2. When the it asks you to remove a device kill the app 
3. Launch the app again and resume the login flow 
4. It will ask you remove a device again and this time you actually remove a device
When launching the app at step 3 we already have a UserSession at launch but it doesn't have a self client so we ask to user to remove a device so we can register a new device. This all works and the slow sync finishes but the UI never realises this because the initial sync observer is not registered in the `AuthenticationCoordinator`.
During the regular the login the initial sync observer is registered when `sessionManagerCreated(userSession: ZMUserSession)` is called but that doesn't happen in this …
> [Fix] Getting stuck with a spinner after removing a device during login

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Only the `deliveryStatus` is visible for automation inside the message toolbox
The delivery status and the ephemeral count are layed out using a stackview. Since the stack view is itself marked as being an accessibility element it will not expose its children and instead picks one (random) child element as its accessibility element.
Set `isAccessibilityElement = false` on the stack view so that all child  accessibility elements are exposed.
> [Fix] Ephemeral countdown not being visible to automation

- Wire-iOS/Sources/Components/Buttons/ButtonWithLargerHitArea.swift
The like button for a message is not visible in automation.
Even though the Apple [documentation](https://developer.apple.com/documentation/uikit/uiaccessibilityelement/1619580-isaccessibilityelement) states that a UIButton will return true for `isAccessibilityElement`, this is not always the case. 
https://stackoverflow.com/questions/21144375/standard-uibutton-isaccessibilityelement-returns-no-by-default
Set `isAccessibilityElement` to  `true` in our button base class.
> [Fix] Like button not being exposed to automation

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
During a call with many participants, the participant list may have a "show all" row at the bottom. Tapping on this button will present a scrollable participant list. If any participant leaves or joins, then change will not be visible on this screen until it is popped and represented.
There are two `CallParticipantsViewController` instances, one is for the truncated version on the call overlay, and one is for the full screen scrollable list. Only the first instance is updated when the `CallInfoConfiguration` changes.
When the call configuration changes, also update the fullscreen participant list, if it exists.
> [Fix] Presented call participant list not updated

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationPreviewViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
After updating to iOS 13 SDK, old peek and pop feature does not work anymore since 3D touch is no longer triggers. Implement `UIMenu` to restore the preview feature of conversation list.
> Feature: iOS 13 UIContextMenu support of conversation list

- Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
- Wire-iOS/Sources/Helpers/ColorScheme+Helper.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphyNavigationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Folders/FolderCreationController.swift
- Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
- Wire-iOS/Sources/UserInterface/SkeletonViewController.swift
After updating to iOS 13 SDK, some screens has status bar with light content when changed to system dark mode.
on iOS 13, `UIStatusBarStyle.default` can be either light or dark.
Replace `.default` with `.compatibleDarkContent`.
> Fix: When system dark mode is enabled, conversation screen status is white on white

- Wire-iOS/Sources/UserInterface/Components/AvatarImageView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SwipeMenuCollectionCell.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
Follow up of https://github.com/wireapp/wire-ios/pull/4376, sometimes long touch can not trigger preview
The hack to fix 3D touch seems no longer works on iOS 13. The pan gesture of the conversation list cell cancels the long-press gesture.
Remove the hack of iOS11
> Fix: sometimes haptic touch not work on Conversation list cell

- Wire-iOS Tests/Message+FormattingTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+MessageFormatting.swift
`:(` is displayed as an emoticon.
Do not replace emoticons in code blocks.
> [Fix] Emojis rendering inside code blocks

- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
- Wire-iOS/Sources/UserInterface/Helpers/InteractiveModalTransition.swift
Sometimes the call overlay does not dismiss when hanging up the call. Additionally, some people are reporting a similar issue that the calling overlay no longer receives touch events and the app must be terminated.
A dismiss closure in which `activeViewController` is set to `nil` is being called when the calling overlay is dismissed. However, it is also being called when the user interactively starts to dismiss the calling overlay but cancels the transition. This can also occur just by tapping the screen.
When this happens, the the app loses all references to `activeViewController` and so it can't be dismissed programatically. It is still retained by the system, because we are using custom transitioning objects to present and dismiss it. This means the calling overlay can still be …
> [Fix] Call overlay does not dismiss

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationMessageToolboxCell.swift
When sending a message the accessibility hierarchy is not updated to reflect the views state after it's been delivered.
We update the cell outside a table view update block which seems to not trigger the accessibility hierarchy to update. See: https://github.com/wireapp/wire-ios/blob/32038b8f3d975cc652c8214b43e5f0cfe521f391/Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift#L132
Make the cell's configuration adopt `Equatable` and add the delivery state as a field. This will cause the cell to be reloaded using [reloadRows](https://developer.apple.com/documentation/uikit/uitableview/1614935-reloadrows) since DifferenceKit will now know that cell has been updated.
Would be nicer to re-factor the `MessageToolBox` to not rely on having …
> [Fix] Accessibility hierarchy not updating

- Wire-iOS/Sources/UserInterface/Components/Controllers/RotationAwareNavigationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.swift
Image view can not be roatated.
The new card style does not roatates, due to parent screen can not be roatated.
Present image viewer in full screen style.
> Fix: iOS 13: screen does not rotate when viewing image full screen and rotating iPhone

- azure-pipelines.yml
- fastlane/Fastfile
The PR reduces the CI step `QA: build for simulator` with the following adjustments:
-  do not clean the project when building again for QA testing
-  add build number when `build for test` (i.e. build product is same as the `QA: build for simulator` step)
- add `skip_detect_devices` for both steps
- remove unnecessary `devices` & `code_coverage` options.
> Reduce the build time on CI

- Wire-iOS/Sources/UserInterface/Components/Controllers/ConfirmAssetViewController/ConfirmAssetViewController.swift
Disable `crossDissolve`  modalTransitionStyle which does not fit iOS 13 card modal animation.
> disable cross resolve when opening emoji/sketch screen 

- Wire-iOS Share Extension/UIColor+NamedColors.swift
Fix label color to black for iOS 12-
> Fix: Share extension text is white on white

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.swift
GIVEN conversation is open on mobile
WHEN deleting a conversation from the webapp, 
THEN the conversation content is cleared 
BUT the conversation remains open
AND is only deleted after returning to conversation list
That case was not covered. When observing a change in the conversation, no action related to deletion was taken.
Transition to the conversation list if the conversation was deleted
> [Fix] Conversation not disappearing after deletion

- Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
Bot detail screen status bar is dark on dark
`ClearBackgroundNavigationController` does not define `childForStatusBarStyle` and `ServiceDetailViewController` does not define `preferredStatusBarStyle`.
Add the missing status bar style preferred.
> fix: ZIOS-12884 bot detail screen status bar is dark on dark

- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
The status bar is white on white after dismissed collection screen.
Same as https://github.com/wireapp/wire-ios/pull/4348
Same as https://github.com/wireapp/wire-ios/pull/4348
> Fix: Status bar is white on white when back from collection screen

- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
Add accessibility identifier to canvas element to help speed up automation.
> [Fix] Add accessibility identifier to canvas element

- Wire-iOS/Sources/UserInterface/Components/Views/UpsideDownTableView.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/ConnectRequestsViewController.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionViewController.swift
When multiple incoming requests in coming. The user would like to scroll to the next incoming request instead of the first one.
~~In the `UpsideDownTableView`, the top and bottom are reversed.~~ The `scrollToRow` does not work as expected for unknown reasons.
~~Replace `UITableView.scrollToLastRow` with `scrollToFirstRow`.~~ Use `setContentOffset` instead. (tested and it works.)
> Fix Page scrolling to top after accepting one request

- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsView.swift
When viewing the full call participant list (after tapping the "show all" cell), it is not possible to scroll the list.
`CallParticipantView` contains code that limits all touch events to the "show all" cell. This was introduced in https://github.com/wireapp/wire-ios/pull/2204/ but it's not clear why. In any case, because the full call participant list never contains the "show all" cell, the view was forwarding all of its touch events and therefore the internal scroll view gesture recognizers were not receiving these events.
Remove the code limiting touch events. 
After several manual tests, there doesn't seem to be any negative side effects. The interactive dismissal of the call UI works (vertical pan) and touching any of the user cells still results in the call info overlay being …
> [Fix] Call participant list not scrollable

- Wire-iOS Tests/ArticleViewTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Rich Content/ConversationLocationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationLinkPreviewArticleCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageActionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MessageAction.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ContextMenuDelegate.swift
- WireCommonComponents/Icons/UIImage+StyleKit.swift
Add Context menu preview support to `ConversationLocationMessageCell` to show the mapview preview of a location message.
> Context menu for ConversationLocationMessageCell

- Wire-iOS Share Extension/PostContent.swift
- Wire-iOS Share Extension/SendController.swift
Share extension gets stuck on sending
In https://github.com/wireapp/wire-ios/pull/4387, missing a line `progress(.done)`.
add the missing line of code.
> Fix: missing Share extension gets stuck on sending

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarEditView.swift
Input field does not preserve text after the app goes to background.
After updated to iOS 13 SDK, the `traitCollectionDidChange` is called twice when the app is going to the background (e.g. from `.light` to `.dark` and then from `.dark` to `.light`.) and triggers `.SettingsColorSchemeChanged` twice, which recreates the input field and loading the old preserved text before the app saved the current input bar text.
Do not triggers `.SettingsColorSchemeChanged` when the app going to the background.
Instead of recreating the whole view controls stack, we should use the new adaptive color in the future.
> fix: Input field does not preserve text

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Components/ShareViewController/ShareViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/UINavigationController+CloseButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter+ConversationImages.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ParticipantsPopover.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
We have a lot of fixing regarding status bar not updated like this: https://github.com/wireapp/wire-ios/pull/4428
After a discussion in 1-1 lab in WWDC, we found that we misused `override var childForStatusBarStyle: UIViewController?`.
We should only choose a child of the view controller, not a presented view controller
Only choose a child of the current view controller.
Clean up unnecessary `setNeedsStatusBarAppearanceUpdate` call.
It should fix all status bar issues on conversation screen.
> Fix: status bar not updated when back from iOS 13 card style presentaion

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/GroupOptionsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ReceiptOptionsSectionController.swift
The "invite people" button is shown when a personal account user created a new conversation. Click the button and he/she can see the guest option screen which is not permitted.
`GuestsAllowedCellDescription` is created without checking the current user is a team member or not.
Do not create `GuestsAllowedCellDescription` if the user is not a team member.
> Fix: personal account user should not be able to create a invitation link

- Wire-iOS Tests/HandleChangeStateTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangeHandleViewController.swift
the PR implement the ticket https://wearezeta.atlassian.net/browse/ZIOS-13561. Now the chars - and . are allowed and the length is increasing from 21 to 256.
N.B: currently the localisable string is just for English and it is temporary. Waiting for new info form the product team.
> [Feature]: Increase Handle Length

- Wire-iOS/Sources/UserInterface/Components/Views/IconImageView/IconImageView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/IconImageView/MicrophoneIconStyle.swift
- Wire-iOS/Sources/UserInterface/Components/Views/IconImageView/UserTypeIconStyle.swift
- Wire-iOS/Sources/UserInterface/Components/Views/IconImageView/VideoIconStyle.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
https://wearezeta.atlassian.net/browse/ZIOS-13610
Accessibility identifiers for `guest` and `external user` have been replaced by a single identifier `"img.userType"`, making the icons indistinguishable.
`guest` and `external user` icons were two separate instances of `UIImageView` but have been replaced by a single instance of `IconImageView` causing it to have a single accessibility id 
add an `accessibilityIdentifier` property to `IconImageStyle` protocol and associate a different id per icon style
> [Fix] user cell accessibility identifiers

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
Audio message can't be played sometimes
Audio message which are visible when the app launches don't have the `mediaPlaybackManager` property set since they will try access it through the `AppDelegate` but it is not available until the RootViewController has finished the transition to `ZClientViewController`.
Fetch the `mediaPlaybackManager` later on first use.
It would be nicer to get rid of the `mediaPlaybackManager` from the `AppDelegate` and do a proper dependency injection instead but that would require a large re-factoring and I don't want delay this bug fix.
> [Fix] audio message can't be played sometimes

- Wire-iOS Tests/CountryCodeTableViewControllerTests.swift
- Wire-iOS/Sources/Authentication/Helpers/CountryCode/Country.swift
- Wire-iOS/Sources/Authentication/Helpers/CountryCode/CountryCodeTableViewController.swift
In the country selection screen, app crashes after entered a number in the search field.
`@objc` signature of `Country` class is removed in https://github.com/wireapp/wire-ios/pull/4255
Add `@objc` to member `e164`.
> Fix: app crash when entered a number in country selection screen

- Wire-iOS Tests/Calling/VoiceChannelVideoStreamArrangmentTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
https://wearezeta.atlassian.net/browse/ZIOS-13483
- Display floating video tile only in one to one calls (not in group conv/calls)
- Fixed issues with floating video (see below)
1. Floating video never shows over the grid
2. Floating video freezes after first grid update
1. Floating video relied on `selfPreviewView` property, which was never set
2. Floating video view was removed from cache on `updateState()`
1. Make `selfPreviewView` a computed property returning cached self preview
2. Remove views from cache based on all streams from video configuration (higher source of truth)
> [Fix] Don't display floating video tile in group calls

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
When a call participant has a paused video tile, their user details view (microphone state and name label) are not visible.
The blur view and "Video is paused" label are above the user details view.
Insert the blur view and label beneath the user details view.
> [Fix] User details not visible when video paused

- avs-versions
This reverts commit 7418d7564a08ac47ee1995ed5251c46847923d65. We are reverting because the web team encountered a blocker and is not able to push a new internal with the same AVS bump.
> Revert "[Chore] Bump AVS to 6.2.7 (#4474)"

- Wire-iOS Share Extension/ShareExtensionViewController.swift
- Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/AppState.swift
- Wire-iOS/Sources/AppStateController.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
- WireCommonComponents/AppLock.swift
When the database is locked we need to unlock it using biometrics or the passcode and we need to disable any fallbacks which requests that the user to enter his/her password since we can't use it to unlock the database.
* Introduce `AuthenticationScenario` which encapsulates the rules which apply when are unlocking the app.
* Add `isDatabaseLocked `parameter to the `.authenticated` `AppState` to signal that the database is locked.
> [Feature] Unlock database with app lock screen

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
I am investigating possible causes for decryption errors when exchanging messages. I added this setting to automate sending messages back and forth between two devices to see if I can reproduce the problem. I am committing this because I believe this to be useful debugging tool that might come in handy at some other time.
> Add developer setting to send many messages at once, for debugging purposes

- avs-versions
AVS was bumped to a `6.1.12` on the `release/3.63` branch, but we need to have `6.0.47` on `develop`. The release branch was merged back to develop with https://github.com/wireapp/wire-ios/pull/4481, so this PR is to correct the AVS version.
> [Chore] Downgrade AVS to 6.0.47

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Add the ability to export the cryptobox under option debugging tools.
> [Feature] Expose sharing cryptobox under the debugging tools

- avs-versions
Bump AVS to 6.2.11, which has targeted messaging enabled.
> [Chore] Bump AVS to 6.2.11

- avs-versions
> [Chore] Bump AVS to 6.2.12

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
https://wearezeta.atlassian.net/browse/ZIOS-13648
- Add accessibility id to beta toggle
The `SettingsPropertyToggleCellDescriptor` class sets the toggle `accessibilityLabel` instead of the `accessibilityIdentifier`
> [Chore] add accessibility identifier to beta toggle

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/Components/Settings.swift
- WireCommonComponents/AutomationHelper.swift
- Launch argument that overrides the conference calling toggle
> [Feature] Add launch argument for conference calling

- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
Wrap `unlockViewController` in navigation controller to allow pushing wipe database screen.
> wipe UnlockViewController in navi

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/UIAlertController+Permissions.swift
- Wire-iOS/Sources/Helpers/UIApplication+Permissions.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Changed alert displayed when user taps video button in a call & video permissions are not granted. Now displays the correct message and actions instead of the incorrect alert ("Too many people for Video")
- Small refactor of the camera permission alert
> [Fix] video button disabled message

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Components/Settings.swift
- Wire-iOS/Sources/Helpers/AutomationHelper+ConferenceCalling.swift
- WireCommonComponents/AutomationHelper.swift
https://wearezeta.atlassian.net/browse/ZIOS-13665
When we're using `-UseConferenceCalling 1` launch argument, and switch off the conference calling toggle, UI will behave as if conference calling is enabled but calls will be using legacy group calling
The conference calling override was only overriding the `get` of the `Setting` property for conference calling, while the `set` would still change the conference calling configuration in the SE 
Redefine the launch argument behaviour to only override the `Setting` property once after launch.
> [Fix] conference calling launch argument override

- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationPreviewViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel+ConversationListContentDelegate.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
App crashes after deleting conversations with context menu.
https://github.com/wireapp/wire-ios/issues/4504
The confirm alert is not setting the popover source rect.
Config the popover alert with `configPopover` method. This PR also fix similar cases which create action alert popover with `ConversationActionController`.
> Fix: iPad - app crash when opening conversation list cell context menu

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppDelegate+AppCenter.swift
- WireCommonComponents/AppCenter.swift
AppCenter update dialog no longer shown.
We only distribute the apps to private groups, and the new version SDK requires to config the related setting.
set ` MSDistribute.updateTrack = .private`.
> Fix: AppCenter update dialog not shown

- Wire-iOS.xcodeproj/project.pbxproj
it is mandatory add the Security-Flags.xcconfig default file for build reasons
> [Feature]: Feature Flag Added Default Configuration File

- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.swift
- Wire-iOS/Wire-Info.plist
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13683
> [Feature]: Feature Flag Open File Preview Enabled

- avs-versions
> [Chore] bump avs

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
https://wearezeta.atlassian.net/browse/ZIOS-13689
Self video freezes after toggling video off then on
Instance A of `SelfVideoPreviewView` is deallocated after Instance B is added as subview of `GridCell`
Causing `stopCapture()` of A to be called after `startCapture()` of B
Since the capturer on avs side is the same instance, it causes the video capture to stop for B
Make sure to deallocate instance A before starting video capture on instance B
might need to change the base branch
> [Fix] Frozen frame after re-enabling video

- Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupPresenter.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
Allow the user to press the return key on the keyboard to create passcode.
When the passcode is valid, update the keyboard return key type to `done`
> Press keyboard return key to create passcode

- Wire-iOS Share Extension/Info.plist
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Wire-Info.plist
Disable share extension for the client.
Modify `NSExtensionActivationRules` in the `Info.plist` to be able to enable/disable the Share extension.
https://wearezeta.atlassian.net/browse/ZIOS-13529
> [Feature] Feature Flag: Share extension Enabled 

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
https://wearezeta.atlassian.net/browse/ZIOS-13707
The name and microphone view is missing from the video tile when it appears in the grid.
It only shows up after being covered, then uncovered, by the call info overlay.
The view's alpha is set to `0` during setup
The view's alpha should be set according to the visibility of the video grid
> [Fix] name & mic view missing after video preview creation

- Wire-iOS/Sources/AppRootViewController.swift
Message banners are not shown inside the app.
The guard statement is incorrectly assuming that the optional value for `.chatHeadsDisabled` will evaluate to `true` if the value is `nil`. 
Unwrap the optional value and explicitly declare the default value.
> [Fix] message banners not being shown when enabled

- Wire-iOS Tests/ConversationMessageActionControllerTests.swift
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
Badge items on conversation message shows `"Cut"` and `"Paste"` actions.
**Actual result**
the badge items show:` Cut Copy Paste Copy Reply > Edit Delete Share Like`
**Expected result**
the badge items show: `Copy Reply Edit Delete Share Like`
To hide `"Cut", "Paste" and "Copy"` actions only if the SecurityFlags.clipboard is disabled.
https://wearezeta.atlassian.net/browse/ZIOS-13695
> [Fix] Badge items on conversation message shows "Cut" and "Paste"

- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
For BSI we won't to allow the user accessing to the camera roll or photo album. Currently from the sketch view is that possible tapping the button on the bottom left corner. Do avoid this we decided to hide that button
> [Feature]: Security Flag Photo Album Access

- Wire-iOS/Sources/Components/AudioPlayer/MediaPlayerController.swift
On iOS 10 devices, app crash for `An instance 0xxxx of class AVPlayer was deallocated while key value observers were still registered with it.`
missing calling `invalidate` of the `NSKeyValueObservation`
Call `invalidate` in `deinit`
> Fix: iOS 10 app crash when MediaPlayerController is deinit

- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Authentication/AuthenticationFlowStep.swift
- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/Authentication/Event Handlers/AuthenticationCoordinatorAction.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
- Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
- Wire-iOS/Sources/Authentication/TeamCreationState.swift
- Wire-iOS/Sources/Helpers/AppLock/AppLock+PasscodeExistence.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Unlock/UnlockViewController.swift
Clean up unused `allowsUnwind`.
Fix the back button is shown on passcode screen issue by changing the action to `.transition(.passcodeSetup, mode: .reset)`
Unlock screen - support tap keyboard return button to unlock
Tested cases:
When force app lock is true:
- registration on new device - show set up passcode screen
- login second acct on the same device - set up passcode screen not shown
- logout second acct - unlock screen is shown
- logout first acct - unlock screen is not shown
- login second acct on the again same device- set up passcode screen not shown (since passcode is still stored )
- (When the user upgrade from a version not support custom passcode) start the app after upgrade - show set up passcode screen, when the code is created, show the unlock screen
When force app lock …
> Fix: show passcode setup screen when login or unlock

- Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
Set the keyboard type to `.asciiCapable` to prevent the user input a emoji to the passcode field
> Fix: disable emoji input when the passcode is revealed

- Wire-iOS Tests/Search/SearchResultsViewControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Contacts/ContactsSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/GroupConversations/GroupConversationSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/InviteTeamMember/InviteTeamMemberSection.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Services/SearchServicesSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Suggestions/DirectorySectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/TopPeopleLine/TopPeopleLineCollectionViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/TopPeopleLine/TopPeopleSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.swift
`SearchResultsViewController` and its children leak every time when the search screen is dismissed. 
`SearchServicesSectionController` and `DirectorySectionController` are keeping a strong reference to `SearchResultsViewController`.
Add `weak` keyword to prevent cyclic reference.
Clean up the code for better readibility.
> Fix: SearchResultsViewController leaks after search screen is dismissed

- Wire-iOS/Sources/Authentication/Interface/Descriptions/ScreenDescriptions/Login/BackupRestoreStepDescription.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Wire-Info.plist
For the BK build and BSI client we need to disable the creation and restoring of backup to avoid having an app with an invalid state.
Added a Security Flag to hide/show the 'create backup' button and the 'restore backup' button
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13723
> [Feature]: Feature Flag Create Restore Backup

- Scripts/download-assets.sh
- Wire-iOS Tests/Bundle/URL+WireTests.swift
- Wire-iOS Tests/Bundle/WireEmailTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Developer/DebugAlert.swift
- Wire-iOS/Sources/Helpers/URL+String.swift
- Wire-iOS/Sources/Helpers/URL+Wire.swift
- Wire-iOS/Sources/Helpers/WireEmail.swift
- Wire-iOS/Sources/UserInterface/Helpers/Bundle+config.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift
- fastlane/Fastfile
Move the hardcoded email address in Swift code to `email.json` configure file.
> Fix: move hardcoded email address to configure json file

- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
When switching off applock switch and go back to root setting page, app lock switch is still on.
Applock setting is not set.
Set `AppLock.isActive = false` after deleted passcode.
> Fix: switch off app lock does not saved in the perference

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Wire-Info.plist
Add a new security flag which allows forcing encryption at rest to be enabled. If the flag is enabled, then encryption at rest is enabled when the user session is created. Additionally, the option in the account settings is hidden to prevent the feature being disabled.
> [Feature] Security flag to force encryption at rest

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Call participants list in calling overlay were sorted in case sensitive fashion
- Sort call participants in case insensitive fashion using `.lowercased()` on participants names
> [Fix] make sorting of call participants case insensitive

- Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
By default, when the user forgets his/her passcode code, the user can fill in the text field store passcode with touch id/face id and then screen lock passcode. 
Prevent the user auto fill passcode from keyboard accessory. A hack is applied by setting `textContentType = .oneTimeCode`.
> Fix: disable auto fill passcode

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Advanced.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/DebugActions.swift
As part of an investigation about decryption errors with the security team, I want to add more debugging capabilities to the app. In particular, we want to add a debug console to the app that will allow us to enter specific commands with parameters (such as the user ID or conversation ID that should be affected by that command).
This PR does some ground work, by adding more options to the troubleshooting public menu. As I was adding these menu items, I also noticed a lot of code related to (internal) debug options.
I thought it would be cleaner to have debug logic in its own file, instead of inside `SettingsCellDescriptorFactory`. I moved that code to its own file. In the process I removed some duplicated code (e.g. code for alerts) by refactoring to common functions.
I created this PR …
> Moving debug actions to their own file

- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
fix for https://github.com/wireapp/wire-ios/pull/4495#discussion_r483703698
Create tests for showing create passcode screen or not when app lock screen is shown.
> add tests for upgrade form old version without custom app lock

- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+PasscodeSetup.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupPresenter.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewControllerDelegate.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/WipeDatabaseViewController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
Fix for https://github.com/wireapp/wire-ios/pull/4495#discussion_r483714903
Move logic of close button to `PasscodeSetupViewController`
> fix: move close button logic inside PasscodeSetupViewController

- Wire-iOS Tests/AudioRecordKeyboardViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
After discarding a recorded audio message, it is impossible to start a new recording.
When tapping the "redo" button, the audio record keyboard state transitions to `ready`, but the underlying audio recorder state is not reset and remains `stopped`. When tapping record again, the recording does not begin because state is not `initializing`.
When transition to the `ready` state, delete the existing recording and reset the recorder state to `initializing`.
Jira: https://wearezeta.atlassian.net/browse/ZIOS-13748
Fixes: https://github.com/wireapp/wire-ios/issues/4567
> [Fix] Unable to re-record an audio message

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
https://wearezeta.atlassian.net/browse/ZIOS-13786
User details view appears out of safe area after the call starts (for self video)
User details contraints are set before the view controller's view appeared, thus the `safeAreaInsets` are `nil` 
Adjust the constraints in `layoutSubviews`
> [Fix] user details layout in video tile

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Hide App Lock setting when encryption at rest is enabled by default, since it's not possible to have both activated at the same time.
> [Feature] Hide App Lock setting when encryption at rest is enabled by default

- Wire-iOS/Wire-Info.plist
When the user tries to open an https links when the default browser is not safari the links is not opened.
Error: "error: "This app is not allowed to query for scheme https"
iOS 14 bug: https://developer.apple.com/forums/thread/660241
Add https to the plist LSApplicationQueriesSchemes
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13799
> [Fix]: Links No Opened When Safari is NOT default browser on iOS 14

- Wire-iOS/Sources/AppRootViewController.swift
If the phone is on dark mode and the app respects this system setting, then all throughout the registration flow the status bar is white on white.
The navigation controller containing the registration flow does not use the child status bar style.
Use the top view controller to determine the status bar style.
> [Fix] Status bar white on white

- Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
Move the common URL scheme from xcconfig to the the code.
> move scheme form xcconfig

- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationStepController.swift
The status bar in the login flow is white on white.
No preferred style was set.
Set the preferred style.
> [Fix] Status bar in login flow is white on white

- Wire-iOS/Sources/Analytics/Events/Analytics+Settings.swift
- Wire-iOS/Sources/AppRootViewController.swift
With this PR we are going to modify the way the app displays the "Help us make wire better" alert considering the user type. The new logic will be the following
- show the alert just for a user that is not a team member.
- disable by default the tracking setting for a user that is not a team member.
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13755
> [Feature]: Analytics Tracking Alert Logic

- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
Tag event when the user likes a message.
> tag message like event

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/ApplicationStateObserver.swift
- Wire-iOS/Sources/Helpers/UIApplication+Permissions.swift
- Wire-iOS/Sources/NotificationObserver.swift
This PR represent an idea how to centralise observing notification without having them spread everywhere in the UI project.  Here I put just few of the notifications just to show you the solution and get some feedback from you. It would not be difficult extend the `NotificationObserver` class to all the other notifications in the project and implement the observing protocols where we need.
IMHO some to the main advantages of this approach are:
- Avoid spreading NotificationCenter.default.addObserver method all around the UI project.
- Since they are centralised it would be much easier debug when we are waiting for a certain notification.
- Cause it is protocol oriented we don't have different naming of the call back for a certain notification.
- It is easy to apply all around the project
> [Feature]: Notification Observing Centralisation 

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
https://wearezeta.atlassian.net/browse/ZIOS-13841
- re-enable fill mode on screensharing video streams
> [Feature] (re)enable fill mode on screensharing video streams

- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
The state of the mute icon in top overlay doesn't reflect the mute state changes of the ongoing call.
The mute state observer changed. 
Change to the correct mute state observer
> [Fix] mute icon in call top overlay

- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.swift
Fix the issue: double-tap on an image on full-screen image viewer to zoom in has no animation
> Fix: double tap to zoom in an image has no animation

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppDelegate+Network.swift
- Wire-iOS/Sources/AppDelegate.swift
- Wire-iOS/Sources/AppRootRouter.swift
- Wire-iOS/Sources/ForegroundNotificationFilter.swift
- Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
- Wire-iOS/Sources/QuickActionsManager.swift
- Wire-iOS/Sources/SessionManagerLifeCycleObserver.swift
- Wire-iOS/Sources/SwitchingAccountRouter.swift
- Wire-iOS/Sources/URLActionRouter.swift
- Wire-iOS/Sources/UserInterface/Components/Loading/LoadingSpinner.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIApplication+StatusBar.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorController.swift
the scope of this PR is clean up a bit the `AppRootRouter` trying to encapsulate as possible its properties and moving not necessary code from it.
> [Refactoring]: AppRootRouter Clean Up

- Wire-iOS/Resources/fr.lproj/Localizable.strings
App (with a French localization) is crashing when creating a new group conversation.
The argument placeholder type should be a number (not a string).
To fix the argument placeholder type.
https://wearezeta.atlassian.net/browse/ZIOS-13850
> [Fix] Crash when creating new group conversation

- Wire-iOS Tests/AccessoryTextField/LinkInteractionTextViewTests.swift
A test was failing due to an out of bounds exception.
I made some changes to the test when writing it but decided to undo those changes. Unfortunately I didn't undo far enough and the test was committed incorrectly. The out of bounds exception occurs because of an incorrect test string.
Use the correct test string.
> [Fix] Test containing out of bounds exception

- Wire-iOS.xcodeproj/project.pbxproj
- setup.sh
CI fails to building with the following error during Carthage bootstrap:
```
*** Downloading appcenter-sdk-apple.framework binary at "3.3.1"
***  Skipped installing appcenter-sdk-apple.framework binary due to the error:
"The file couldn’t be saved."
```
Bug in Carthage: https://github.com/Carthage/Carthage/issues/3056
Apply workaround described in the issue.
> [Fix] Apply carthage workaround for 'The file couldn’t be saved'

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Components/Settings+Logging.swift
- Wire-iOS/Sources/Helpers/Logging.swift
- WireCommonComponents/BackendEnvironment+Shared.swift
We are trying to debug some issues regarding custom backends, and while we do have logging when the backend is switched, we do not know which backend environment is being used when the app is launched.
Add some logs when to describe the value of `BackendEnvironment.shared` when the app launches and whenever the value changes.
Additionally, include the backend environment log tag as enabled by default.
> [Chore] Add logging to describe value of BackendEnvironment.shared

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootViewController.swift
- WireCommonComponents/UIColor+NamedColors.swift
The document picker which is shown when restoring a backup has black labels on a dark background when the phone has dark appearance enabled.
We set `mainWindow.tintColor` to `.black` during the login flow.
Use the the color `UIColor.Wire.primaryLabel` instead which takes the current appearance into account.
> [Fix] Wrong color in backup picker when dark apperance is in use

- Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
- Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
Add a test to verify that non-team members do not start Countly session.
> add test for non team member do not start Countly session

- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
- Wire-iOS/Sources/Authentication/Interface/Views/PhoneNumberInputView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/EmailPasswordTextField.swift
When your session expires you are asked to login with your email / phone number fields pre-filled. It's possible to edit these fields but those edits are ignored when trying to login, which is confusing.
Fields are editable but the email / phone number is not taken from the input field when submitting the login request.
Make input fields non-editable when re-authenticating.
> [Fix] Make email and phone fields non-editable when re-authenticating

- Wire-iOS Tests/RandomGeneratorFromDataTests.swift
- Wire-iOS/Sources/UserInterface/Components/Views/ConversationAvatarView.swift
App crash at the method `Array.shuffled()`
The crash line is `generic specialization <__C.ZMUser> of Swift._ArrayBuffer._getElementSlowPath(Swift.Int) -> Swift.AnyObject`. No reason for that, but it seems related to copying an array of `ZMUser`s.
For suffled and array, copying the original array is not necessary. Refactoring the function with suffling the indices instead.
> Fix: app crash at zm conversation stable random participants

- Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
- Wire-iOS Tests/Analytics/AnalyticsTests.swift
- Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
- Wire-iOS/Sources/Analytics/AnalyticsProviderFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/DebugActions.swift
Countly integration is broken since 3.68. The majority of iOS users have zero sessions recorded and therefore are not showing any recorded events. Some users however do show recorded events and sessions. 
Manual session handling is enabled, however the sessions were never being explicitly updated nor explicitly ended. As a result, Countly was recognizing users but never received any events or session information from those users. In some cases though events would be uploaded, but (I believe) this would only happen when the self user changes (due to an account switch).
Explicitly start, update and end the session. The lifetime of the session matches the default behavior of Countly (when manual session handling is disabled), which means sessions begin when the app is foregrounded, updated …
> [Fix] Analytic sessions are not being updated

- Wire-iOS Tests/Calling/VoiceChannelVideoStreamArrangmentTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
This is an update to show the self user video stream in the floating tile when a call has 2 participants **and** 2 active video streams. 
This was a feature restricted to 1:1 conversation that we now have on any kind of conversation as long as there are 2 participants in the call.
> [Feature] show self stream in floating tile when call has 2 participants

- Wire-iOS Tests/ConversationMessageCell/ConversationImageMessageTests.swift
- Wire-iOS Tests/SettingsTableViewControllerSnapshotTests.swift
- Wire-iOS Tests/SwiftSnapshotTesting/CoreDataFixture.swift
- Wire-iOS/Sources/Analytics/Analytics.swift
- Wire-iOS/Sources/Analytics/TrackingManager.swift
- Wire-iOS/Sources/Managers/ColorSchemeController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+DataUsagePermissions.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
When testing with Xcode 12.2, the test crashes when setting `SelfUser.provider` to nil.
`EXC_BAD_ACCESS` occurs when running the test.
It seems like `SelfUser.provider` is corrupted after accessing second time.
When `CoreDataFixture` deinit, clean `SelfUser.provider`. (It may had side effect to other tests, which may assume `SelfUser.provider` is set)
Refactor `SettingsCellDescriptorFactory.dataUsagePermissionsGroup()` to prevent getting default parameter argument from  `SelfUser.current`
Should we protect `SelfUser.provider` in a queue, to prevent racing condition?
> clean up SelfUser.provider when deinit

- Wire-iOS Tests/NetworkStatusView/NetworkStatusViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Components/NetworkStatus/NetworkStatusViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
Network indicator is not shown on the conversation list.
Constraints are breaking for the height of the indicator.
`TopBar` is connected to `contentContainer` and the same time `networkStatusViewController.view` is connected the `contentContainer`and the `topBarView`. This leaves zero space for the network indicator to grow when needed.
Detach the `TopBar` from the `contentContainer` and only leave it connected to the bottom of the network indicator, so that the network indicator can push the `TopBar` down when needed.
> [Fix] Network indicator not shown on conversation list

- Wire-iOS/Sources/Managers/FileBackupExcluder.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/GridCell.swift
- Wire-iOS/Sources/UserInterface/Components/NetworkStatus/NetworkStatusViewController.swift
- Wire-iOS/Sources/UserInterface/Components/ThreeDotsLoadingView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/BreathLoadingBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/TypingIndicatorView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/KeyboardBlockObserver.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- WireCommonComponents/CircularProgressView.swift
On Xcode 12, test crashes when calling NotificationCenter.default.removeObserver in deinit
Unknown, but it may be related to the racing condition issue when multiple tests release objects.
Remove the unnecessary NotificationCenter.default.removeObserver in deinit, which is not needed after iOS 9.
> remove NotificationCenter.default.removeObserver in deinit

- Wire-iOS Tests/VideoPreviewViewTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
Maximise / minimise video stream on double tap.
**given** we have a video grid containing one or more video tiles
**when** user double taps on a video tile
**then** the video tile's fill mode is toggled (either fills or fits the available space in the tile)
**given** we have a video grid containing one or more video tiles
**when** user double taps on a video tile that is **not** maximised
**then** the video tile is maximised to **fit** the **video grid**
**given** we have a video grid containing one or more video tiles
**when** user double taps on a video tile that is maximised
**then** the video tile is minimised to allow all video tiles to be shown
> [Feature] maximise / minimise video stream on double tap

- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
When the app tries to open the Call TopOverlay when it was already opened a crash occurred
Something was going wrong in the view hierarchy 
Avoid to show the TopOverlay when it is already shown
> [Fix] Call Routing Refactoring: Avoid to open the Call topOverlay when it is shown

- Wire-iOS Tests/AudioEffectsPickerViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift
On Xcode 12, exception break point is trigged when load a audio asset.
It is working in a queue and not stopped after test is done
The audio asset is not tested inside the view controller snapshot tests, disable the loading when running tests.
> do not call AudioEffectsPickerViewController.loadLevels when testing

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
- adding accessibility ID to the thumbnail view
> [Chore] add accessibility ID to thumbnail

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
Cleanup up no long needed code which may crash when running tests with Xcode 12 at the line `NSObject.cancelPreviousPerformRequests(withTarget: self)`.
> [Chore] Clean up cancelPreviousPerformRequests

- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsSignOutCellDescriptor.swift
on iPad when there is no connectivity and the user is logging out, after entering password and tapping OK dialog is closed, but nothing happens, no spinner is shown and no alert is shown.
The `topMostViewController` (`KeyboardAvoidingViewController`) is not of type `SpinnerCapable`
`KeyboardAvoidingViewController` is now `SpinnerCapable`
> [Fix]: On iPad no Spinner and Network Alert is shown when logout

- Wire-iOS/Wire-Info.plist
Due security reason we should disabled the app might establish HTTP connections. 
Consequences:
1) SSO via plain HTTP will not work anymore
2) Not displaying anymore link previews for non-https
> [Feature]: (ATS) Disabled the app establish HTTP connections

- avs-versions
Bump avs to 6.6.9
It introduces a change that breaks compatibility with earlier avs versions (< 6.6)
> [Chore] bump avs to 6.6.9

- Wire-iOS Tests/AudioEffectsPickerViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffect.swift
Similar to https://github.com/wireapp/wire-ios/pull/4739, disable apply audio effects when running tests
> do not apply audio effect when testing

- Wire-iOS Tests/CallInfoRootViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
In some tests, `BackgroundViewController` uses `ZMUser.selfUser()` which is not as same as the mock user of the parent view controller
In `CallInfoRootViewControllerSnapshotTests`, the self user injected into `CallInfoViewController` is different from the `user` in `BackgroundViewController`
Inject self user instead of using `ZMUser.selfUser()`
> inject self user in CallInfoViewController

- Wire-iOS Tests/CallInfoRootViewControllerTests.swift
- Wire-iOS Tests/ConversationInputBarViewController/ConversationInputBarViewControllerDelegateTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationCellSnapshotTestCase.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
- Do not create unnecessary observers when testing
- Clean up observer tokens when deinit
- Clean up tests which do not release resources
- Clean up redundant checkers
> clean up tests and do not set up observer when tests

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
QA Automation can't match the video tiles with their test users
QA doesn't have access to users client ids
Use user's name in accessibility identifier instead of hashed client id
> [Chore] Accessibility: replace hashed client id by participant name

- Wire-iOS/Sources/UserInterface/Components/UserImageView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/CellComponents/SenderCellComponent.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSenderMessageCell.swift
When running tests, test crashes when dealloc `UserImageView` and `MockConversation`
Unknown, but seems related to zombie object dealloc again.
Remove not used `conversation` property from `SenderCellComponent`
Do not observe User info in `UserImageView`
~~change `user` of `UserImageView` to unowned reference (when deinit, do not call `ZMUser`'s dealloc method since do not own it.)~~ (still not proved this solves the issue.)
> [Fix] Removed unused ZMConversation in SenderCellComponent

- Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
- Wire-iOS/Sources/AppStateCalculator.swift
- Wire-iOS/Sources/NotificationObserver.swift
- Provide default implementation of ApplicationStateObserving protocol in order to reduce boilerplate in classes implementing it
> [Refactor] provide default implementation of ApplicationStateObserving protocol

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
In order to simplify the implementation of QA automation, we're adding the thumbnail view accessibility identifier only when it is populated with a content view.
> [Chore] update thumbnail view accessibility id

- Wire-iOS/Sources/AppRootRouter.swift
The app lock setting is not always disabled when the app lock is forced.
A request to fetch the app lock config is enqueued when the app comes to the foreground. This request won't be triggered until the next managed object context save, so it was happening that the settings property cell was reading an outdated value.
Enqueue and **trigger** a fetch of the app lock config when the app comes to the foreground.
> [Fix] App lock setting is not disabled when app lock is forced

- Wire-iOS Tests/CallInfoRootViewControllerSnapshotTests.swift
- Wire-iOS Tests/CallInfoRootViewControllerTests.swift
- Wire-iOS Tests/CallParticipantsViewTests.swift
- Wire-iOS Tests/UserCellTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallAccessoryViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/CallParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsView/ShowAllParticipantsCell.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/IconImageView/UserTypeIconStyle.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Mentions/UserSearchResultsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsContentViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ServicesSectionController.swift
- Wire-iOS/Sources/UserInterface/LegalHoldDetails/Sections/LegalHoldParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Contacts/ContactsSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Services/SearchServicesSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Suggestions/DirectorySectionController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileTitleView.swift
When running `CallInfoRootViewControllerTests`, test crashes
`ZMUser.selfUser()` is called and can not released on Xcode 12.
Inject mock self user to `BackgroundViewController` and `UserCell`.
> Fix: Do not use ZMUser.selfUser() when running CallInfoRootViewControllerTests

- Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupInteractor.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/WipeDatabase/WipeDatabaseInteractor.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
In https://github.com/wireapp/wire-ios-data-model/pull/1096 direct access to the app lock passcode in the keychain has been prohibited. Instead, the app lock controller is responsible for storing, deleting, and updating the passcode. This PR integrates this API change.
I've opted for simplicity by accessing the app lock controller though the shared user session. Ideally we should be injecting and instance of the app lock controller, however it's not a trivial task and I would address it in a separate PR.
> [Refactor] Use app lock controller to manage passcode

- Wire-iOS Tests/SettingsTableViewControllerSnapshotTests.swift
rework of https://github.com/wireapp/wire-ios/pull/4787, assign a dummy Analytics singleton object to prevent crashes when force unwrapping  `Analytics.shared`
> assign dummy Analytics to prevent crash when running SettingsTableViewControllerSnapshotTests.testForSettingGroup

- Wire-iOS Tests/Data_ImageTypeTests.swift
- Wire-iOS/Sources/Helpers/NSData+ImageType.swift
On Xcode 12, testThatItIdentifiesJPEG fails
image is not loaded with `#imageLiteral(resourceName: "wire-logo-shield")`
Load the jpg data with `dataInTestBundleNamed`
> fix: testThatItIdentifiesJPEG fails on Xcode 12

- Wire-iOS Tests/CallInfoRootViewControllerTests.swift
Remove `coreDataFixture` from `CallInfoRootViewControllerTests` to prevent creating `ZMUser`.
> Fix: remove coreDataFixture from CallInfoRootViewControllerTests

- Wire-iOS Tests/DismissalTests.swift
Clean up `DismissalTests` to remove unnecessary subclassing and clean up when tearing down.
> clean up DismissalTests

- Wire-iOS Tests/ConnectRequestsViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/ConnectRequestCell.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/ConnectRequestsViewController.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/UserConnectionViewController.swift
When testing `ConnectRequestsViewController` in `ConnectRequestsViewControllerSnapshotTests`, we had to create `ZMConversation` and `ZMUser` for assigning `connectedUser` (type: `ZMuser?`). This PR creates a simpler interface `ConnectionRequest` for easier to mock `connectedUser` with type `UserType?` and prevent creating `ZMConversation`.
> create ConnectionRequest protocol for testing ConnectRequestsViewController

- Wire-iOS Tests/ConnectRequestsViewControllerSnapshotTests.swift
- Wire-iOS Tests/ConversationInputBarViewController/ConversationInputBarViewControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/ConnectRequests/ConnectRequestsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationProtocol.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarButtonState.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Editing.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Language.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Location.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EphemeralKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarConversationType.swift
When testing `ConversationInputBarViewController` in `ConversationInputBarViewControllerTests`, we had to create `ZMConversation` and `ZMUser`. This PR creates a simpler interface `InputBarConversationType` for easier to mock a conversation to prevent creating ZMConversation.
> replace ZMConversation with InputBarConversationType

- setup.sh
The `setup.sh` script is failing on CI machines.
The failure is caused by the recently added step to install the Viper template files in Xcode. On the CI machine we don't have permission to copy the files to the right location, so it fails.
Don't install the viper templates in the setup script.
> [Fix] Setup script failing on CI machines

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Adding a value allowing to differentiate active speakers from inactive speakers in the accessibility identifier of `BaseVideoPreviewView`
> [Chore] add active speaker accessibility id

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- updating the active speaker limit in the participants list from 1 to 4 participants
> [Fix] active speakers limit in participants list

- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
If change `isAppLockActive` state in the settings and terminate the app, the new value is not saved.
`isAppLockActive` is a `managedObjectContext` property and we didn't persist the changes.
Save `managedObjectContext`.
> [Fix] Persist isAppLockActive value

- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQSERVICES-201
If a user who has no device passcode set, when when app lock becomes mandatory, then when they open the app they are warned twice about the configuration change. First they see the warning screen, then they see the same warning but on the create passcode screen.
There are two screens that contain the warning. One should be shown when the user has at least a device passcode set, and the other is for the case when they need to create a custom passcode. The current code path first displays the first warning, then proceeds to attempt to authenticate. The result from this attempt indicates that the custom passcode is needed, then we see that the custom passcode needs to be set, in which case we display the warning again.
Before we …
> [Fix] App lock warning is displayed twice

- Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorController.swift
Application would sometimes crash after switching accounts
The `ConversationListViewController` had a retain cycle which would prevent it from getting released and therefore continue to observe the conversation list changes. When it attempted to apply a conversation list change it would crash because the `SelfUserProvider` would not be set during the account transition.
Fix the retain cycle by dismissing the `SelfProfileViewController` before the switching accounts. The `SelfProfileViewController` is presented by the `ConversationListViewController` and therefore holds a strong reference to it.
> [Fix] Crash when switching accounts

- Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQSERVICES-195
If the app Lock Screen is shown and we need to create a custom passcode, then after creating the passcode the user is required to enter that passcode again to unlock the app. Product has decided that this is an unnecessary step so we should no longer require the user to enter the passcode a second time.
> [Feature] Unlock app after creating passcode

- Wire-iOS Tests/Calling/VideoPreviewViewTests.swift
- Wire-iOS Tests/Calling/VideoStreamStubProvider.swift
Use the `VideoStreamStubProvider` class in `VideoPreviewViewTests`. This helps reduce the code redundancy in creating `VideoStream` and `Stream` instances in calling tests
> [Chore] use VideoStreamStubProvider in VideoPreviewViewTests

- Wire-iOS Tests/ConversationCell/MarkDownSnapshotTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationCellSnapshotTestCase.swift
- Wire-iOS Tests/Mocks/MockMessage+Creation.swift
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
Rewrite `MarkDownSnapshotTests` to prevent subclassing  `ConversationCellSnapshotTestCase` which creates `ZMUser` objects can not be released.
> Fix: MarkDownSnapshotTests without subclassing ConversationCellSnapshotTestCase

- Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
- Wire-iOS Tests/ZClientViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+FeatureChange.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/AppLockChangeWarningViewController.swift
https://wearezeta.atlassian.net/browse/SQSERVICES-203
Disabling app lock in team settings doesn't delete the custom passcode in keychain. 
Delete the passcode when the client receives a notification that the team admin has disabled mandatory app lock.
> [Fix] Delete passcode if app lock is disabled in team settings

- fastlane/Fastfile
Add a new fastlane option `s3_subfolder` to allow upload build artifact to a subfolder.
> Feature: upload to S3 with custom subfolder

- Wire-iOS Share Extension/ShareExtensionViewController.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQSERVICES-221
The app lock is not shown in the share extension.
Authentication is only required if the current status is not `granted` **AND** the database is locked.
1. Always start in a `denied` state.
2. Require authentication if in a `denied` state **OR** the database is locked
Additionally, since app lock is per account now, we only require authentication when selecting the conversation (and not also when selecting the account). When the account changes, we reset the authentication state back to `denied`.
> [Fix] App lock not shown share extension

- Wire-iOS Tests/Calling/VideoGridViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
Active speaker frame is shown when it shouldn't be. It should only be shown in group calls.
- Presently only hiding when there are strictly 2 participants, but still showing when only one participant is in the call.
- Missing update of the self preview's `shouldShowActiveSpeakerFrame` property
- Update condition for showing the frame
- Assign value to `shouldShowActiveSpeakerFrame` property of the self preview when configuration changes
> [Fix] hide active speaker frame when not in group call

- Wire-iOS Tests/ConversationAvatarViewModeTests.swift
- Wire-iOS Tests/Mocks/MockConversation.h
- Wire-iOS Tests/Mocks/MockUserType+Creation.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserImageView/BadgeUserImageView.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
Refactor `ConversationAvatarViewModeTests` to prevent creating `ZMConversation`
> Fix: ConversationAvatarViewModeTests without creating ZMConversation

- Wire-iOS Tests/Calling/SelfVideoPreviewViewTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/SelfVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
start self preview capture only when video state is `.started`
> [Fix] video capture state

- avs-versions
> [Chore] bump avs to 6.6.15

- Wire-iOS/Sources/Authentication/Backup/BackupRestoreController.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupViewController.swift
From the request of QA, remove the hack for the simulator for loading and saving a backup file.
> remove Backup hack for simulator build

- Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
If encryption at rest is enabled, it is possible that the user is asked to use Touch ID or Face ID twice to unlock the app.
Authenticating with device owner credentials (biometrics or device passcode) is handle via the LocalAuthentication framework. The authentication result is returned to us asynchronously, which we use to mutate local state. Because of this concurrent behavior, it's possible to ask the user to authenticate a second time before the results of the first time are fully finished being processed. Such a case can happen when encryption at rest is enabled and the user authentication happens very quickly.
Use a binary semaphore to prevent beginning a new authentication request before the last one has been fully completed.
> [Fix] App lock shown twice when encryption at rest is enabled

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
https://wearezeta.atlassian.net/browse/SQSERVICES-62
Conversation search in share extension is case sensitive
Add `.caseInsensitive` option to the search.
> [Fix] Conversation search in share extension

- Wire-iOS Share Extension/ShareExtensionViewController.swift
https://wearezeta.atlassian.net/browse/SQSERVICES-263
Conversation list can't be opened on tapping while using a Share extension.
When app lock and EAR feature are not active we send the wrong authentication status.
Don't ask for authentication if app lock and EAR feature are not active.
> [Fix] Conversation list can not be opened from the Share extension

- Wire-iOS Tests/ConversationMessageCell/XCTestCase+VerifyMessage.swift
- Wire-iOS.xcodeproj/project.pbxproj
remove no longer use `ConversationCellSnapshotTestCase`.
> remove ConversationCellSnapshotTestCase

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Generated/Strings+Generated.swift
- swiftgen.yml
Localized string keys are stringly typed which is error prone for several reasons:
1. A typo in the localization key is not caught at compile time and the result is that the misspelt key becomes the string value at runtime.
2. Argument placeholders accept specific types and will crash at runtime if an invalid value is passed into it.
3. It is tempting to construct long localized keys by joining together parts of the key. This makes search for both the usage and definitions of localized keys in code and the base string file respectively.
Add type safety to localization keys by generating Swift types to mimic the inherent tree structure of localized keys. This is achieved through the [SwiftGen](https://github.com/SwiftGen/SwiftGen) tool, which will read the `Resources/Base.lproj` directory …
> [Chore] Add type safe localization keys

- Templates/Viper/Module.xctemplate/___FILEBASENAME___Module.Interactor.swift
- Templates/Viper/Module.xctemplate/___FILEBASENAME___Module.Presenter.swift
- Templates/Viper/Module.xctemplate/___FILEBASENAME___Module.Router.swift
- Templates/Viper/Module.xctemplate/___FILEBASENAME___Module.View.swift
- Templates/Viper/Module.xctemplate/___FILEBASENAME___Module.swift
- Templates/Viper/Tests.xctemplate/___FILEBASENAME___Module.MockInteractor.swift
- Templates/Viper/Tests.xctemplate/___FILEBASENAME___Module.MockPresenter.swift
- Templates/Viper/Tests.xctemplate/___FILEBASENAME___Module.MockRouter.swift
- Templates/Viper/Tests.xctemplate/___FILEBASENAME___Module.MockView.swift
- Wire-iOS/Sources/Viper/Viper+Interfaces.swift
Update the both the Viper templates to align with the implementation outlined [here](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/245105434/Viper+architecture+Draft). With these changes, the only thing that you need to do after generating a module is to define the `Event`, `Request`, `Result`, `ViewModel` and `Action` enum cases (and how to handle them of course!).
In summary:
- Provide empty enums for each message type.
- Provide protocol requirements for each relationship.
- Provide implementations of those requirements which empty switches.
- Provide a default `viewDidLoad` event.
- Simplify the mock components to record only the message types.
- Moved the position of "Router" from first to last in the `build` method and other places.
- Added missing mark labels
> [Chore] Update Viper templates

- crowdin.yml
Add a [Crowdin CLI config file](https://support.crowdin.com/configuration-file/) to allow use of the [Crowdin CLI](https://support.crowdin.com/cli-tool/). We currently upload source strings and download translations through a jenkins pipeline, which is good at what it does, but it only does those two things. 
The `crowdin` cli offers more ways to interact with crowdin and can help solve issues like renaming localization keys without losing existing translations. Or, instead of logging on to Bob, you could pull in all translations with `crowdin pull` and make a pr yourself. 
To be able to use `crowdin`, you need to set two environment variables:
- `CROWDIN_PROJECT_ID` should contain the id of the Wire crowdin project. This can be found by logging in to crowdin, going to Settings > API & …
> [Chore] Add crowdin config

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
When we have just one client in the client list the edit button is shown
not set correctly to false `editList` when in the client list is empty 
NOTA BENE: `clients` represent all the client registered not being selfClient
```swift
self.clients = userClients.filter { !$0.isSelfClient() }
```
I'm highlighting this to you cause it confuse me a lot but then i discovered it :-) 
Set  `editList` to `false` when `clients.count == 0` (See NOTA BENE)
> [Fix]: Hide Edit Button When One User Client In List

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.LockView.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.swift
In an attempt to clean up the localized string a bit, I have renamed some strings used only in the app lock module. These strings were previously named to be part of the settings screen, even though they have nothing to do with the settings screen.
I also propose changing the way we write localized string keys to use camel case. I feel that they're easier to read and easier to type, but of course it's just as suggestion.
This PR also makes use of the new type safe localized string keys.
In order to preserve the existing translations, I've renamed the keys in all the localized files. These steps should be completed when the PR has been approved.
> [Chore] Rename localization keys for app lock module

- Wire-iOS/Sources/AppStateCalculator.swift
for more info about the issue see the [bug](https://wearezeta.atlassian.net/browse/SQCORE-490). 
in this particular case the transition were made cause the cause the current app state was `.authenticated(completedRegistration: true)` and the new state was `.authenticated(completedRegistration: false)`
as you can understand the value of `completedRegistration` is not important to the UI transition state, so for avoid this kind of issue I have defined the `equality operators` on the `AppState enum`.
> [Fix]: SQCORE-490 Preserve Last AppState

- Cartfile
- Cartfile.resolved
Minor bump for Down to include:
[[Feature] Add option to render only valid links](https://github.com/wireapp/Down/pull/20)
[[Fix] Crash when parsing empty block quote](https://github.com/wireapp/Down/pull/19)
> [Chore] Bump Down

- Wire-iOS Tests/Calling/SelfVideoPreviewViewTests.swift
- Wire-iOS Tests/Calling/VideoGridViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/SelfVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
- avs-versions
Video capture stop when the user changes the presentation mode from **all video streams** to **active speakers**.
note that this happens only if the user is not qualified for the active speakers mode.
Since the user doesn't qualify for the active speakers mode, the `SelfVideoPreviewView` is removed from `VideoGridViewController`'s view cache, which causes the capturer to be stopped. 
Pruning the view cache is good for the remote video views, but not critical for the self preview. 
Keeping the instance also improves user experience, because the view doesn't have to be recreated each time the user enables the video.
The `VideoConfiguration` passed to `VideoGridViewController` contains a list of `VideoStream` to be displayed. In the use case where the self user's `VideoStream` is not in the …
> [Fix] video capture stops on presentation mode change

- Wire-iOS/Sources/UserInterface/Screen Curtain/ScreenCurtain.RootViewController.swift
The native os ui components (status bar, keyboard, etc) are rotated when the phone is rotated.
The `ScreenCurtain.RootViewController`, which sits in a secondary window, did not have any rotation behavior specified. This regression was caused because I forgot to copy over that logic when converting the `NotificationWindow` to the `ScreenCurtain`.
Specify the rotation behavior to match the top most view controller in the main window, as was defined in the `NotificationRootViewController`.
> [Fix] Rotation issues on iPhone

- Wire-iOS/Sources/UserInterface/CustomAppLock/Setup/PasscodeSetupViewController.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQSERVICES-292
After creating a custom passcode from the app lock screen, the user is presented with the blurred shield view and can not navigate anywhere else.
The `AppLockModule` is the delegate of `PasscodeSetupViewController`, however I forgot to actually set the delegate value. I also noticed we don't invoke the delegate method after storing the passcode.
Set the delegate and call its method.
> [Fix] App stuck after creating custom passcode

- Wire-iOS Tests/App Lock/Mocks/AppLockModule.MockApplicationStateProvider.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModulePresenterTests.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModuleViewTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/UIApplication/ApplicationStateProvider.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Interactor.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQSERVICES-294
On iOS 14, if the encryption at rest is enabled, when the app is minimized, then the native device authentication (faceID, touchID or passcode) UI is presented, even though Wire is not visible.
When EAR is enabled, when the app becomes inactive (moves to the background) the user session is locked. This triggers a change to the Wire app state, and we transitioned to the `locked` state and load the `AppLockModule`. When the view is loaded, we initiate the authentication flow, which results in asking for user authentication.
This only appears on iOS 14, and is probably due to a change that `viewDidLoad` and other lifecycle methods may be invoked even when the app is in the background.
While it makes sense to inform the presenter …
> [Fix] Device authentication requested when app is minimized

- Wire-iOS.xcodeproj/project.pbxproj
- setup.sh
fix the issue that can not install debug build on iPhone 12.
> Xcode 12: test with iPhone device

- Wire-iOS/Sources/AppRootRouter.swift
https://wearezeta.atlassian.net/browse/SQCORE-510
The app crashes on showing the control centre while user is on Login screen.
The app loses focus when the control centre shows. This event triggered `applicationWillResignActive()` of `ScreenCurtain`. We are trying to access the user session at a time when it does not exist yet. This is because` screenCurtain.delegate `points to a different user session that exists on Wire.
In the `unauthenticated` state, set `screenCurtain.delegate = nil` and prevent using the wrong user session.
> [Fix] The app crashes on Login screen

- .github/workflows/swiftlint.yml
Add a Github action to run SwiftLint and report violations as comments. See: https://github.com/marketplace/actions/github-action-for-swiftlint
> [Chore] Add SwiftLint Github action

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
https://wearezeta.atlassian.net/browse/SQSERVICES-63
Conversation search field is transparent and conversation list is visible through the field in share extension.
Set the background color for the searchBar.
> [Fix] SearchBar background in share extension

- Wire-iOS Tests/ArticleViewTests.swift
refactor `testArticleViewWithPicture` to create SUT for every width to prevent unstable result on Xcode 12.4.
> xcode 12: refactor testArticleViewWithPicture

- .swiftlint.yml
- Wire-iOS Tests/ConversationCell/MarkDownSnapshotTests.swift
- Wire-iOS Tests/ConversationCell/MultiParagraphSnapshotTests.swift
- Wire-iOS Tests/ConversationCell/TextMessageMentionsTests.swift
- Wire-iOS Tests/ConversationList/ConversationListCell/ConversationListCellTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationMessageSectionControllerTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationTextMessageTests.swift
- Wire-iOS Tests/ConversationReplyCellTests.swift
- Wire-iOS Tests/HandleChangeStateTests.swift
- Wire-iOS Tests/InputBar/InputBarTests.swift
- Wire-iOS Tests/ShareViewControllerTests.swift
- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/WebLinkTextView.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationNotificationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
- Wire-iOS/Sources/UserInterface/CustomAppLock/Unlock/UnlockViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+SplitViewControllerDelegate.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController.swift
This PR introduces the [line length](https://realm.github.io/SwiftLint/line_length.html) lint rule. This is a configurable rule and by default reports lines with length between 120 and 200 characters as warnings, and lines longer than 200 characters as errors.
If we use this default configuration, then more than 2000 violations are reported. In order to deal with this in manageable chucks, I propose we set very high limits to reduce the number of violations to a reasonable size, fix those, then repeat the process repeatedly, each time lowering the limits just a little. We can continue this until we find the appropriate limits.
In some cases we don't want to split a long line into separate lines, such as we need a very long string for testing. I've dealt with these by using disable …
> [Chore] Lint line length above 250 characters

- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationIconBasedCell.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.swift
There are many crashes related to the `SelfUser` have been reported through `App Center`.
There is currently no way to reproduce it. But according to the logs, the possible reason for these crashes is that 
`SelfUser. provider` is `nil`. 
```
class var current: UserType & ZMEditableUser {
guard let provider = provider else { fatalError("Self user provider not set") }
return provider.selfUser
}
```
However, we set the provider when the user transits to the `authenticated` state. 
Since this crash can't be reproduced at the moment, and there's no part of code that triggers this crash, the solution is to check if `selfUser` exists and provider is set.
**Jira tickets with App Center links:**
https://wearezeta.atlassian.net/browse/SQSERVICES-296 …
> [Fix] Crashes with selfUser

- avs-versions
> [Chore] bump avs to 7.0.1

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
When a user taps on a conversation, the wrong conversation opens.
Seems like the the "standard" reloadData() for the collectionView (conversation list) conflicts with incremental reloading of the conversation list.
Always use an incremental reload of the collectionView when we need to update the list of conversations.
https://wearezeta.atlassian.net/browse/SQSERVICES-308
> [Fix] Tapping cell show wrong conversation

- Wire-iOS/Sources/AppRootRouter.swift
We have been experiencing several crashes lately when the trying to access the `SelfUser.current`, typically from the conversation list or in the conversation content.
`SelfUser.current` intentionally crashes when `SelfUser.provider == nil`. The self user provider is configured during the app state transition:
- The provider is set when `applicationWillTransition(to: .authenticated)` is called, and
- The provider is reset when `applicationDidTransition(to: appState)`, where `appState != .authenticated`.
The problem however is that we can repeatedly call these methods in any order, for example:
```swift
// The self user isn't set yet, so SelfUser.current will crash.
applicationWillTransition(to: .migrating)
// This will set the provider, SelfUser.current won't crash. …
```
> [Fix] Overlapping app state transitions

- Wire-iOS/Sources/AppRootRouter.swift
Application gets stuck on the migration screen after restoring a backup.
When the application transitions away from the `.unauthenticated` state we release the `AuthenticationCoordinator`, which is responsible for signalling when the login flow is completed. After https://github.com/wireapp/wire-ios-data-model/pull/1144 we started to attempt a migration every time we load the database. We still need to register a new client after restoring a backup so we don't immediately  transition to the `.authenticated` state and later when the client is registered we don't the state changed because `AuthenticationCoordinator` is gone.
The flow now looks like this:
- Restoring backup
- Migrating
- Registering client & perform slow sync
- Authenticated
Don't release the `AuthenticationCoordinator` when …
> [Fix] Stuck on migration screen after restoring backup

- Wire-iOS Tests/UserRightTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Settings/UserRight.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQSERVICES-177
SCIM users can edit the email field in the settings, but this is not allowed and the backend will reject the request.
Incorrect condition in `UserRights`, namely we were allowing SCIM users to edit the email field if they were not using SSO to login. But SCIM users should never be able to change their email from within Wire.
Change the condition to be dependent only on whether the self user is a SCIM user or not.
> [Fix] SCIM users can email field

- Wire-iOS/Sources/AppRootRouter.swift
1. User A logs in to Wire App User A taps on self profile 
2. User A taps on Add Account 
3. User A sees suggested accounts on top of keyboard
4.  User A taps on suggested account 
5. User A enters passcode/biometrics
App crashes
When the app returns the password picker it triggers `AppRootRouter.applicationDidBecomeActive()` and calls `teamMetadataRefresher.triggerRefreshIfNeeded()`, which end up accessing the `SelfUser.provider` which is not `nil` as expected in this scenario. This causes the app to crash when force unwrapping the `managedObjectContext` when it tries to retrieve the self user.
The `SelfUser.provider` is not nil because when the user taps "Add account" we log the user out with an error, which causes the app to take the first if branch: …
> [Fix] Crash after picking credentials from keychain when adding second account

- Wire-iOS/Sources/AppRootRouter.swift
Analytics usage is opt-in for non team members, and opt-out for team members.
When a team member logs into a device for the first time, the analytics usage opted out.
The code that enables the default opt in for team members was returning early because there didn't yet exist an instance of the analytics provider, which would only be created once the user was opted in.
Don't rely on the (not yet existing) analytics provider to get the self user, but rather `SelfUser.provider`.
There are no tests for setting up analytics yet, but it is something I am addressing in a separate refactoring branch.
> [Fix] Team user should have analytics enabled by default

- Wire-iOS/Sources/UserInterface/Conversation Options/CellConfiguration+ConversationOptions.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/CellConfiguration.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewModel.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/Cells/IconToggleSubtitleCell.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Details/ProfileDetailsContentController.swift
https://wearezeta.atlassian.net/browse/SQSERVICES-367
There's a crash when user disables `Allow guests and Services` on **iPad**.
On iPad, `UIAlertController` must be presented in a popover and the popover's source view (the view which the popover points to) must be set.
Set the source view for the `UIAlertController`. This fix required some additional changes that shouldn't affect the current behavior.
> [Fix] Crash when disabling Allow guests and Services

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Sources/AppStateCalculator.swift
If the user is logged out while in `.unauthenticated` state, the app can get stuck if this happens twice with the same error.
We only transition between app states if the new state is different from the previous state. The error associated with the `.unauthenticated` state is part of the equality check and we expect to reload unauthenticated view controller if we move to the `.unauthenticated` state associated with an error.  This only works for the first error but if the same error happens a second time we could potentially get stuck since the app state will determined to not have changed.
Change to error comparison from an object to a reference equality check . We could also check that if error is not `nil` and in that case always consider the app state to have changed.
> [Fix] Stuck on login if same logout error happens twice

- Wire-iOS Tests/Calling/CallHapticsControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/Array+CallParticipant.swift
This PR disables the join and leave haptics for group calls
- Updated `CallHapticsController` logic
- Added an `Array+CallParticipant` helper
- Updated and renamed some tests for `CallHapticsControllerTests`
> [Feature] disable join & leave haptics for group calls

- azure-pipelines.yml
- fastlane/Fastfile
Since this repo is public, CODECOV_TOKEN should be unnecessary when running codecov and it can be removed
###TODO
> remove CODECOV_TOKEN from fastlane

- Wire-iOS Tests/DeviceManagement/ProfileViewControllerTests.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
https://wearezeta.atlassian.net/browse/SQSERVICES-385
A connection request view that was opened via a deep link doesn't have a close button.
Before showing the `close button`, we check how many controllers in the navigation controller. If there's more than one view controller, it means there's a `back button` and a `close button` is not needed. 
In our case we have 2 view controllers:
- search user VC (contains a spinner)
- profile VC (contains a connection request UI)
But the `search user VC` should be replaced with the `profile VC` when it is loaded.
For some unknown reason, when `viewDidLoad` method is called, the `search user VC` still exists and it means the there're two view controllers in the stack. And the navigation items are configured in the `viewDidLoad` method.
Move the …
> [Fix] The close button is not visible on the connection request view

- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
**given** an ongoing 1:1 call and the call UI is minimised 
**when** the call is ended from the remote side
**then** the call UI is not dismissed and is irresponsive
The `ActiveCallRouter` has a method `dismissActiveCall(animated:completion:)`
The `completion` block is called after dismissing the active call.
However, if the active call is minimised, there is nothing to dismiss and the completion block won't be executed.
Call the completion block even if the active call is minimised.
> [Fix] call UI not dismissing after call ends

- avs-versions
> [Chore] bump avs to 7.1.1

- Wire-iOS Tests/Calling/ActiveCallRouterTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
The degradation alert is not showing up after the call 
In `ActiveCallRouter`, the post call action is executed directly if the active call is shown. It should be the opposite.
Execute post call action directly only when the active call is not shown, otherwise, save the action for after the call.
> [Fix] Call router post call action

- Wire-iOS Tests/Routers/URLActionRouterTests.swift
- Wire-iOS/Sources/AppRootRouter.swift
- Wire-iOS/Sources/AppStateCalculator.swift
- Wire-iOS/Sources/URLActionRouter.swift
When opening a deep link to switch backend the alert would be shown again after switching to your second account.
The `URLActionRouter` stores the link in a `url` property for later processing when the application has reached a valid app state. For the backend switch case though it was processing the deep link immediately and storing it in the `url` property for later processing which gets triggered when the app enters  the `.authenticated` state after switching accounts.
Remove the `url` property and show or delay showing alerts in a similar way as we do for app navigation.
> [Fix] Switch backend alert shown twice when switching accounts

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
**JIRA:** https://wearezeta.atlassian.net/browse/SQCORE-705
When the self user is removed from a conversation, an empty system message appears, when it should say "You were removed".
A switch over an enum was hitting the default branch which resulted in `nil` being returned instead of an attributed string. The `removed(ZMParticipantsRemovedReason)` has two seemingly possible values: `none` and `legalHoldPolicyConflict`. While the compiler doesn't complain with an error if only these two cases are handled, it does warn that not all cases might be handled (???). I think it might be have something to do with `ZMParticipantsRemovedReason` being an objective c enum... maybe the Swift compiler is getting confused.
Simply replace the pattern `.removed(reason: .none)` with `.removed` for now to …
> [Fix] Empty system message when removed from a conversation

- Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
There is a double warning notification when connecting to new user while being under LH. The issue is not reproducible every time.
The issue is not reproducible every time. The BE error response observer has been placed in the init () method of `SearchResultsViewController`. For some unknown reason, sometimes there are 2 instances of `SearchResultsViewController` and, as a result, there are 2 observers that display an alert message.
Move the observer to the viewWillAppear() method.
https://wearezeta.atlassian.net/browse/SQSERVICES-485
> [Fix] Double warning notification

- avs-versions
This reverts commit f41fb5ccb8ca2f04ec16a5a35c2f12f1c58b748a.
We need to stay on 6.1.x until the selective video endpoint is integrated
> Revert "[Chore] bump avs (#5122)"

- Wire-iOS Tests/Calling/CallGridViewControllerSnapshotTests.swift
- Wire-iOS Tests/Calling/Mocks/MockCallGridHintNotificationLabel.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridEvent.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridHintNotificationLabel.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/Stream/Stream+Video.swift
In the calling grid, we use hint labels to notify the user about the actions available to them. The current hints are:
- `Double tap on a tile for fullscreen` - showed when the calling grid first appears
- `Double tap to go back, pinch to zoom` - showed when a user maximises a tile
- `Pinch to zoom` - showed when there's a screenshare in 1:1 calls
The calling grid now allows for non-video tiles, for which pinch-to-zoom is disabled. 
So, for non-video tiles, I changed the hint `Double tap to go back, pinch to zoom` into `Double tap to go back`
Maximising a non-video tile - when it's the only one in the grid - shows the `Double tap to go back` hint, but has no other effect since the tile already appears fullscreen. Thus I disabled maximisation in this case.
> [Feature] Update hint notification behaviour for tiles without video

- .github/workflows/crowdin.yml
Synchronizing localized strings to and from Crowdin is a bit of a hassle.
Pushing localization sources and pulling new translations is currently a manual process. It is achieved using the Crowdin CLI tool, but this needs to be installed locally and the user needs to have a crowdin account to set up a personal access token. 
The Crowdin Github action can do all of this for us automatically. It is set up to run when a new commit is made to `develop`, which will upload and source strings to Crowdin. It will also automatically download new translations to the specified branch and open a pull request.
See for more info: https://support.crowdin.com/github-crowdin-action/
> [Chore] Add Crowdin GitHub action

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
When the self user joins a conversation as a guest, a system message is shown stating "You joined". The "you" part is inserted into the localized string and may another user's name, e.g. "John joined". 
One localized string is used for both the first and third persons, but languages that have conjugation require separate translations for these cases, e.g in German "Sie sind beigetreten" and "John ist beigetreten".
Add a second  localizable string to allow translators to disambiguate these different scenarios.
> [Fix] Ambiguous translation for string

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/UIEdgeInsets+directionAware.swift
- WireCommonComponents/AccessoryTextField.swift
~~App crashed on device when start after using XCFramework.~~ Warning is produces when using non extension allowed method in share extension.
From the log, some method is not allow on app extension.
clean up `APPLICATION_EXTENSION_API_ONLY` in project and follow the flag in `.xcconfig`.
Refactor the code and do not using `UIApplication` in `common component`.
Using `effectiveUserInterfaceLayoutDirection` for checking text direction.
> Fix: application extension not work after using XCFramework

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
- Wire-iOS/Sources/Authentication/Helpers/CountryCode/CountryCodeTableViewController.swift
replace `dimsBackgroundDuringPresentation` which is dropped in iOS 12 with `obscuresBackgroundDuringPresentation`
> fix: replace deprecated methods

- Wire-iOS Tests/Calling/CallGridViewControllerSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
When hanging up a large conference call from the last page of the call grid, the app crashes
Upon hanging up the call, the call configuration is updated and propagated to `CallGridViewController`.
Consequently, `requestVideoStreamsIfNeeded(forPage:Int)` is called. This method slices the `dataSource` array containing all streams by using the range of indexes of the elements presumed to be in the given page.
The range of indexes is calculated this way:
```
let startIndex = page * gridView.maxItemsPerPage
var endIndex = startIndex + gridView.maxItemsPerPage
endIndex = min(endIndex, dataSource.count)
```
Using `min(endIndex, dataSource.count)` ensures `endIndex` won't be out of `dataSource` bounds.
However, there is a risk for `startIndex` to be out of `dataSource`'s bounds and/or for …
> [Fix] Crash when leaving large call

- Wire-iOS Tests/ConversationMessageActionControllerTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationAudioMessageCellTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationFileMessageCellTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationImageMessageTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationVideoMessageCellTests.swift
- Wire-iOS Tests/Mocks/MockMessage.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
If the file sharing feature is disabled, we should hide the `download`, `save` and `share` buttons on the message action toolbar.
> [Feature] Hide download, save and share buttons

- Wire-iOS Tests/Calling/CallInfoConfigurationTests.swift
- Wire-iOS Tests/Calling/CallInfoRootViewControllerSnapshotTests.swift
- Wire-iOS Tests/Calling/CallInfoRootViewControllerTests.swift
- Wire-iOS Tests/Calling/CallInfoTestFixture.swift
- Wire-iOS Tests/Calling/VoiceChannelStreamArrangmentTests.swift
- Wire-iOS Tests/Mocks/MockCallInfoViewControllerInput.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallingConfiguration.swift
This PR introduces a feature configuration mechanism in the calling code in order to disable key conferencing features that won't be included in the upcoming release.
Disabled / Enabled features:
- [Disabled] - audio tiles
- [Disabled] - pagination
- [Enabled] - swipe down to dismiss call
- [Enabled] - color schemed audio calls (light / dark)
- [Disabled] - toggling the overlay in an audio call
- [Updated] - stream limit in calling grid
- Created a `CallingConfiguration` struct
- Enabled / disabled features according to the `CallingConfiguration`
- The flags added in `CallingConfiguration` will likely be retired once the large conference calls features has been released
- Snapshot tests and unit tests were not updated to reflect the chosen configuration in order to avoid doing the work …
> [Chore] disable large conference call features

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
(in **internal** builds)
When in a conference call with a large number of participants (50+), the iOS app is very slow:
- Pagination is slow
- Audio only comes after a few minutes
- The call drops
In the logs, we can find a lot of unnecessary information being dropped each time the call configuration changes. It's suspected to be the cause of the issues listed above
Remove the unnecessary logs
> [Fix] Remove excessive logging

- Wire-iOS Tests/CallStatusViewTests.swift
- Wire-iOS Tests/Calling/CallInfoTestFixture.swift
- Wire-iOS Tests/Calling/CallStatusViewInputTypeTests.swift
- Wire-iOS Tests/Mocks/MockCallInfoViewControllerInput.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusViewInputType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
The CBR label is not shown when CBR is enforced (in build configuration)
The visibility of the CBR label depends on wether or not CBR was enabled by the user in the settings. 
When CBR is enforced, the CBR settings are not available.
Showing the CBR label should take into account wether or not CBR is enforced in the build configuration
> [Fix] show bitrate label when CBR is enforced

- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
On iOS 15, `UIButton` has a new property `subtitleLabel` with conflicts with our `IconLabelButton.subtitleLabel`
rename to `subtitleTransformLabel`
> rename IconLabelButton.subtitleLabel to subtitleTransformLabel

- Wire-iOS Tests/ConversationInputBarViewController/ConversationInputBarViewController+DropInteractionTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/DragInteractionRestrictionTextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+DragAndDrop.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
There is **drag & drop** feature for iPhones in iOS 15 and this is an issue for **file sharing and copy / paste** restrictions for BK build.
1. Prevent file dropping if SecurityFlags.clipboard.isEnabled is false.
2. Disable the drag interaction if SecurityFlags.clipboard.isEnabled is false.
https://wearezeta.atlassian.net/browse/SQSERVICES-755
The playground build for **iOS 15** that has a restriction for drag&drop feature: **3.87 (992928)**
> [Fix] Add restrictions to drag & drop files depends on SecurityFlags

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Resources/Settings.bundle/Root.plist
- Wire-iOS/Sources/AppDelegate.swift
- Wire-iOS/Sources/Components/Settings.swift
Support enabling federation support from the command line and from the external settings app. This is useful when running automation tests or when debugging the app.
> [Feature] Support enabling federation support from the command line

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+DragAndDrop.swift
- Wire-iOS/Sources/UserInterface/Helpers/PerformClipboardAction.swift
If the file sharing feature is disabled, we should restrict the pasting of images.
Previously, the clipboard resriction was covered by `SecurityFlags.clipboard`, and now we need to split it between file handling and text.
Check the status of the file sharing feature before performing any actions on the clipboard.
> [Fix] Implement shouldAllowPerformAction method for MarkdownTextView

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/Grid/GridView.swift
Given a call with an odd number of participants, in landscape orientation, the layout is broken.
In the implementation of `UICollectionViewDelegateFlowLayout`,  the logic for dynamic calculation of the item sizes is flawed. 
It **wrongly** assumes that the layout will be done this way:
From here, the size of the last item is calculated to fit the assumed remaining space. 
**e.g:** for landscape, the 5th tile would be calculated to be twice the height of the other items
**However**, since the actual layout in landscape looks like this:
the size calculated for the last item is wrong, and as a result, it messes up the collection view's layout.
Update the size calculation logic so that the last tile remains the same size as the others in landscape
> [Fix] Grid layout for horizontal layout direction

- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+DragAndDrop.swift
We can drag and drop an image from the browser if the file sharing feature is disabled.
Image copied from browser can be both `NSString` and `UIImage` at the same time and the file sharing feature allows user to copy text.
And a helper method and check if the copied object is a string and not an image.
> [Fix] Drag and drop image from browser

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
in the calling grid, the paging indicator is hidden by the notch on devices like iPhone X, 11, 12...
constraints don't use safe area anchors
use safe trailing anchor for constraints
> [Fix] Page indicator is hidden by notch

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
devices with `compact` horizontal size class (e.g: iPhone 7) have a wrong grid view layout when rotating to landscape
when the device turns to landscape orientation, we should update the grid view axis to `.horizontal`
however, in the code, we only do so for phones with a `regular` horizontal size class
update grid view axis to `.horizontal` for both regular and compact horizontal size classes
> [Fix] Grid axis doesn't update when rotating to landscape for some devices

- Wire-iOS/Sources/AppDelegate.swift
- WireCommonComponents/AutomationHelper.swift
Follow up on https://github.com/wireapp/wire-ios/pull/5263
Enabling federation from the command line doesn't with Appium
Appium doesn't override users defaults when with arguments being passed.
Parse command line command from process info arguments.
> [Fix] Command line argument not working with Appium 

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/Grid/GridView.swift
After rotating the device, the position in the scrollview of the calling grid changes. It should stay on the same page instead.
When the device orientation changes, the layout is updated.
Consequently, the content offset isn't pointing to the same cell as before the rotation.
Before the rotation, save the index path of the item at the content offset position.
Then, in `collectionView(_ collectionView: UICollectionView, targetContentOffsetForProposedContentOffset proposedContentOffset: CGPoint)` use the saved index path to calculate and return the correct content offset
> [Fix] Grid view offset on rotation

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/Grid/GridView.swift
1. Join a call with multiple pages
2. Go to landscape
3. Go back to portrait
4. Scroll to different page
after some time, the page resets to the page that the grid was on after changing orientation
the page doesn't reset
`collectionView(_ collectionView: UICollectionView, targetContentOffsetForProposedContentOffset proposedContentOffset: CGPoint)`  is called when the grid is updated, thus setting the grid's offset to the offset of `firstVisibleIndexPath` which was saved upon rotating the device
Instead of using the first visible indexPath, rely on the current page
> [Fix] Grid resets to different page during UI updates

- Wire-iOS/Sources/Helpers/URL+Wire.swift
"Learn more" link on the empty search result screen leads to a 404 page.
The link was linking to a not yet existing support page.
Link to https://support.wire.com/hc/en-us/articles/360001157305-What-are-usernames- for now and update it again later when the new support page is created.
> [Fix] Learn more link was broken on the empty search result screen

- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.swift
When the iOS app runs Mac OS, conversation list view is not show 
The app runs on portrait mode
When the app is running on macOS, always use landscape mode
> Fix: always use landscape mode UI layout on macOS

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
Application was sometimes crashing when opening a push notification with app lock enabled.
`ZClientViewController` was captured by retain cycle so state transitions were being forwarded to UI components which had been torn down and specifically the SelfUser was no longer available, which caused a `precondition()` to be triggered.
Remove the retain cycle by making `self` weak in a newly introduced observer.
Introduced by https://github.com/wireapp/wire-ios/pull/5254
> [Fix] Avoid crash when app lock is enabled

- Wire-iOS Tests/Calling/CallParticipantViewTests.swift
`CallParticipantView` doesn't support orientation changes anymore, so we should remove the tests.
> [Chore] remove deprecated orientation tests

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/Error+Localization.swift
Remove handling of the connection limit reached error case to align with the behaviour on other platforms. This error case was introduced in https://github.com/wireapp/wire-ios/pull/5298
> Fix: don't handle  error to align with other platforms

- Wire-iOS/Sources/UserInterface/MarkdownBarView.swift
After Cartography is removed, Markdown view's stackview disappeared
it has 0 height.
set `translatesAutoresizingMaskIntoConstraints` to face to prevent generating autosizing constraints.
> fix: Markdown view's stackview has 0 height

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Unity shortcut hints cases in Title cases.
> fix: title cases in shortcut hints

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Fix typo of `keyboardshortcut.conversationDetail`
> fix: typo in keyboardshortcut.conversationDetail  

- Wire-iOS/Sources/UserInterface/UserProfile/Devices/ProfileClientViewController.swift
remove cartography from `ProfileClientViewController` and clean up legacy code. Snapshot test is covered in `ProfileClientViewControllerTests`
clean up unnecessary `fileprivate` to `private`
> fix: remove cartography from ProfileClientViewController

- Wire-iOS Share Extension/UnlockViewController.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
remove cartography from `IncomingConnectionView`
> Fix: remove cartography from incoming connection view

- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
Remove Cartography from `Tabbar`
> Fix: remove cartography from Tabbar and activate constraints in one batch

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/FileTransferView.swift
Remove cartography from `FileTransferView`. Snapshot tests is covered in `Wire_iOS_Tests.CollectionsViewControllerTests testFilesSectionWhenDeleted`
> Remove Cartography from FileTransferView

- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.LockView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionCellHeader.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionHeaderView.swift
- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchResultFooter.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ObfuscationView.swift
- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
- Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
Mark unused `init?(coder aDecoder: NSCoder)` as unavailable
> add unavailable to unused init coder

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
User is not able to share/forward the message from one conversation to another one.
There was a check if `activeMessageDestructionTimeoutValue == nil` we do not forward the message. It happened by accident during refactoring.
We should be able to forward NonEphemeral messages, and the message's `activeMessageDestructionTimeoutValue` should depend on the sender's settings, not the recipient's.
> [Fix] Share/forward the message

- Wire-iOS/Sources/Components/Buttons/IconButton.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/ImageToolbarView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
Image viewer has a double height toolbar
`buttonOuterContainer` height constraint is link to inner container
`buttonOuterContainer` should always has a constant height
> fix: Image viewer has a double height toolbar

- Wire-iOS/Sources/UserInterface/Collections/NoResultsView.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/SectionCollectionViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SeparatorCollectionViewCell.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SeparatorTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Components/Views/UserImageView/BadgeUserImageView.swift
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorView.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/GroupConversationCell.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/InviteTeamMemberCell.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Contacts/ContactsSectionController.swift
Removing  `= nil` from many cases around the project because it is redundant.
> SwiftLint: Fix warnings regarding redundant_nil_coalescing rule

- .github/workflows/semantic-commit-lint.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-769" title="SQPIT-769" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-769</a>  Add semantic linting of PR titles to relevant client repository
</td></table>
<br />
----
----
We want to ensure that PR titles should follow semantic commit rules
Add the semantic commit linter workflow from the Wire's .github repo
N/A
----
----
----
1. E.g. `feature(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.
> ci: Add semantic commit linting of Pull Request titles SQPIT-769

- Wire-iOS/Sources/Components/Settings+Logging.swift
----
----
The "Patches" log tag wasn't enabled in the testflight build.
It was enabled in the wrong place (environment var)
Enable it in the right place.
Nothing to test
----
----
----
> chore: enable "Patches" log tag in settings SQSERVICES-1031

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-775" title="SQPIT-775" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-775</a>  [bug] Fix iOS 15.1 transparent navi bar
</td></table>
<br />
Fix the transparent navi bar issue on iOS 15.1
> fix: Search screen has a transparent navi bar on iOS 15.1 SQPIT-775

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ConversationContentViewControllerDelegate.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ShowContentDelegate.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-19" title="IC-19" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />IC-19</a>  Fix transparent navbar
</td></table>
<br />
----
----
Navbar is transparent on the user profile screen in some cases.
Set background color.
This approach is very brittle. We should find a way to solve this without editing every single place where we present a screen.
_Attachments like images, videos, etc. (drag and drop in the text box)_
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis …
> fix: Navbar is transparent in user profile screen IC-19

- Wire-iOS/Sources/Analytics/Analytics.swift
- Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
----
----
In this PR I transition the screenShare event to work with the new mechanism. In addition to that I fixed an issue regarding a failing test from the previous PR's regarding refactoring analytics. We were calling the `tagEvent` method from the previous implementation before the refactoring. Now we're calling the correct (updated) `tagEvent` method and the failing test has been fixed.
Remaining stuff to be done is to transition the `EndCall` event to work with the new mechanism and then clean things up by removing old code etc.
----
> refactor: ScreenShare event to work with the new analytics mechanism

- Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
- Wire-iOS/Sources/Analytics/AnalyticsConsoleProvider.swift
- Wire-iOS/Sources/Analytics/Countly/CountlyUserInterface.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.swift
----
----
This is the last big refactor for a major analytics event to make it work with the new analytics mechanism. @johnxnguyen I will leave some comments for you.
----
> refactor: `CallEnded` event to work with the new analytics event

- Wire-iOS.xcodeproj/project.pbxproj
----
----
By default, Xcode can't find any packages installed by homebrew on Apple Silicon Macs, since they're now installed to a different location that isn't on the default `$PATH (/opt/homebrew/bin/`, rather than `/usr/local/bin`).
Workaround: explicitly add this location to `$PATH` before attempting to run swiftlint.
----
> chore: SwiftLint add support for Apple Silicon brew directory

- Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
- Wire-iOS/Sources/Permissions/ShareContactsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
- Wire-iOS/Sources/UserInterface/CustomAppLock/Unlock/UnlockViewController.swift
----
----
In this PR I fix SwiftLint warnings related to this rule:
**Self in Property Initialization Violation**: `self` refers to the unapplied `NSObject.self()` method, which is likely not expected. Make the variable `lazy` to be able to refer to the current instance or use `ClassName.self`. `(self_in_property_initialization)`
----
> chore: fix self_in_property_initialization SwiftLint Warning

- .swiftlint.yml
- Wire-iOS Tests/AVAsset/AVURLAsset+conversionTests.swift
- Wire-iOS Tests/AccessoryTextField/AccessoryTextFieldValidationTests.swift
- Wire-iOS Tests/CombinationTest.swift
- Wire-iOS/Sources/UserInterface/Overlay/CallTopOverlayController.swift
----
----
Started removing rules from the list. It's going to be a long process. For a start I fix warnings and errors for the rules below:
- **Closure Parameter Position Violation**: Closure parameters should be on the same line as opening brace. `(closure_parameter_position)`
- **Compiler Protocol Init Violation**: The initializers declared in compiler protocol ExpressibleByArrayLiteral shouldn't be called directly. `(compiler_protocol_init)`
- **Reduce Boolean Violation**: Use `allSatisfy` instead `(reduce_boolean)`
----
> fix: SwiftLint warnings and errors for multiple rules (`reduce_boolean`, `compiler_protocol_init`, `closure_parameter_position`)

- .swiftlint.yml
- Wire-iOS Tests/DateFormatterTests.swift
- Wire-iOS Tests/Settings/SettingsPropertyTests.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/Components/ShareViewController/ShareViewController.swift
- Wire-iOS/Sources/Helpers/AttributedStringOperators.swift
- Wire-iOS/Sources/Helpers/NSAttributedString+Highlight.swift
- Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionLinkCell.swift
- Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/RotationAwareNavigationController.swift
- Wire-iOS/Sources/UserInterface/Components/MessagePreviewView.swift
- Wire-iOS/Sources/UserInterface/Components/RoundedView/ContinuousMaskLayer.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SearchResultLabel.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/LikeButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxDataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ProgressView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ZMConversationMessage+AudioMessage.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ZMConversationMessage+File.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/SimpleTextFieldValidator.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffect.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioEffectsPickerViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetLibrary.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
----
----
With this PR I fix SwiftLint Warnings for the rule below:
- **Statement Position Violation**: Else and catch should be on the same line, one space after the previous declaration. `(statement_position)`
Since the changed files are 60 I decided to split this change into 2 PRs. The 2nd PR is going to be opened as soon we merge this one.
----
> chore: Fix SwiftLint warnings for statement position Part 1

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EphemeralKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/RecordingDotView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ReplyComposingView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAvatarView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+Notifications.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+SafeArea.swift
- Wire-iOS/Sources/UserInterface/Location/NSUserDefaults+Location.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController+NewDeviceAlert.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController+SettingsChangeAlert.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsButtonCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ConfirmEmailViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/FingerprintTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Wire-iOS/Sources/UserInterface/SkeletonViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/EmptySearchResultsView.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/Services/SearchServicesSectionController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
----
----
Wanted to break this PR in two separate ones so it's easier for review. Since #5466 is now merged, it's time to open a new PR and fix the rest of the warnings produced by that rule.
- Statement Position Violation: Else and catch should be on the same line, one space after the previous declaration. (statement_position)
----
> fix: SwiftLint warnings for statement position Part 2

- Wire-iOS Tests/ConversationMessageCell/ConversationTextMessageTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-799" title="SQPIT-799" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-799</a>  fix: flaky test on wire-ios
</td></table>
<br />
----
----
Restore `testSoundCloudMediaPreviewAttachment` with fail expected to make sure sound cloud preview is covered in test.
> fix: restore testSoundCloudMediaPreviewAttachment with fail expected SQPIT-799

- Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
- Wire-iOS/Sources/Components/CompanyLoginFlowOpener.swift
- Wire-iOS/Sources/Components/CustomSpacingStackView.swift
- Wire-iOS/Sources/Components/TokenField/TokenField.swift
- Wire-iOS/Sources/Helpers/UIScreen+SafeArea.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/CallQualityController/CallQualityViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/SimpleTextField.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+SafeArea.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
- WireCommonComponents/AccessoryTextField.swift
Since the project is support iOS 12+, the code specific for iOS 11 or lower becomes dead code
Remove code for iOS 11 or below and remove markers for `#available(iOS 11, *)` which is always true.
> chore: remove iOS 11 or earlier dead code

- Wire-iOS/Wire-Info.plist
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-847" title="SQPIT-847" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQPIT-847</a>  Bund app: check why EXTERNAL_FILE_PICKER_ACTION_ENABLED/SHARE_EXTENSION_ENABLED are ignored
</td></table>
<br />
after https://github.com/wireapp/wire-ios/pull/5210, `FILE_GIF_ACTION_ENABLED`, `SAVE_MESSAGE_ENABLED`, `EXTERNAL_FILE_PICKER_ACTION_ENABLED`, `OPEN_FILE_PREVIEW_ENABLED`, `SHARE_EXTENSION_ENABLED` flags no longer read from the source code. Remove them from the .plist.
> fix: remove deprecated flags SQPIT-847

- Wire-iOS Tests/MentionsHandlerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-858" title="SQPIT-858" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQPIT-858</a>  Fix: wire-ios test target built failed with Xcode 12.4
</td></table>
<br />
After https://github.com/wireapp/wire-ios/pull/5524 is merged, test target build failed with Xcode 12.4
Unknown, but the framework search path should be updated for test target
Update Framework search path for test target
> fix: test target build failed with Xcode 12.4 SQPIT-858

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1138" title="SQSERVICES-1138" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQSERVICES-1138</a>  [iOS] Display user link in self user profile
</td></table>
<br />
----
----
Add new strings for this feature: https://wearezeta.atlassian.net/browse/SQSERVICES-1138
----
----
----
> chore: Add new strings SQSERVICES-1138

- Wire-iOS Tests/Calling/CallInfoRootViewControllerTests.swift
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCALL-186" title="SQCALL-186" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQCALL-186</a>  [iOS] Inform the user they joined the call in muted state
</td></table>
<br />
----
----
This feature has several issues that need to be addressed before it can be released (see reports in the ticket)
Therefore we will revert it for now
----
----
----
> chore: revert joined muted indication SQCALL-186

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-100" title="FS-100" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-100</a>  [iOS] Show classified banner in calls
</td></table>
<br />
----
----
Update the classification banner in call status screen when the conversation participants changed.
> feat: update classifications banner in call when participants changed FS-100

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-467" title="FS-467" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-467</a>  iOS: I see "Not classified" label in the conversation on switching the value of Guest toggle to OFF 
</td></table>
<br />
----
----
Update the classification banner in the conversation screen when the allow guest toggle changed.
> feat: update classification banner in conversation when allow guest toggle changed FS-467

- Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Calling.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCALL-506" title="SQCALL-506" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQCALL-506</a>  [iOS] User is joined as Unmuted on rejoining a group conversation
</td></table>
<br />
----
----
Re-joining conference calls would result in the user joining **not muted** instead of **muted**.
After leaving a call, AVS prepares for any new call by setting the mute state to its default **unmuted** state. If the client needs to join muted, it has to set the muted state itself before joining the call.
Explicitly set the muted state to **muted** when joining a conference call from the `join` button …
> fix: join ongoing conference calls as muted - SQCALL-506

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- WireCommonComponents/AutomationHelper.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCALL-508" title="SQCALL-508" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQCALL-508</a>  iOS: Add a launch argument to display the calling overlay 
</td></table>
<br />
----
----
Added a launch argument to keep the calling overlay visible for QA automation.
----
----
----
> chore: add launch argument to keep overlay visible SQCALL-508

- Wire-iOS Tests/Bundle/URL+WireTests.swift
- Wire-iOS/Sources/Helpers/URL+Wire.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1292" title="SQSERVICES-1292" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQSERVICES-1292</a>  [iOS] Link to ToC is broken in the public account signup flow
</td></table>
<br />
----
----
Links for `Terms of use` and `Privacy Policy` have been changed.
Fix links. 
----
----
----
> Fix: Broken links SQSERVICES-1292

- Wire Notification Service Extension/NotificationService.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1310" title="SQSERVICES-1310" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQSERVICES-1310</a>  Support multiple accounts
</td></table>
<br />
----
----
Get the account ID from the push payload and create a notification session with that ID.
----
----
----
> feat: Support multiple accounts SQSERVICES-1310

- Wire-iOS Tests/AppStateCalculatorTests.swift
- Wire-iOS/Sources/AppStateCalculator.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/DebugActions.swift
----
----
If you're already logged into the app, then the app get's blacklisted due to no api version being available, then it's possible to get to the conversation list by simply opening the app.
When a user is already logged in and the app comes to the foreground, the session manager will inform its delegate that the active session changed. The delegate is responsible for transitioning to different app states (such as the blacklist state and the authenticated state).
But when the app comes to the foreground, we attempt to resolve the api version. In the case that none could be resolved, the session manager will inform its delegate to transition to the blacklist state, as expected. But because we're already logged in, the session manager will …
> fix: it's possible to bypass blacklist FS-519

- Wire-iOS.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-35" title="IC-35" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-35</a>  share extension is missing
</td></table>
<br />
----
----
The share extension is missing, it can't be found when in any share sheet modals.
The share extension wasn't embedded in the app. Not sure how it got removed 🤷🏻‍♂️
Embed the share extension in the app.
----
----
----
> fix: share extension is missing IC-35

- Wire-iOS/Sources/UserInterface/Conversation Options/GuestLinkInfoCell.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1439" title="SQSERVICES-1439" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQSERVICES-1439</a>  [iOS] Update copy when other team has guest links disabled and I look into guest link options
</td></table>
<br />
----
----
With this PR we fix the layout issue of guest link copy.  We've added a bit of padding so the copy isn't so close to the edge of the screen.
|   BEFORE |  AFTER |
|---|---|
| ![image-20220407-101555](https://user-images.githubusercontent.com/10944108/162203886-d33b1d06-fc5e-44eb-8336-a23cb479c8d7.png) | <img width="555" alt="Screenshot 2022-04-07 at 14 46 44" …
> fix: Fix the layout issue of guest link copy SQSERVICES-1439

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/URL+Wire.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1389" title="SQSERVICES-1389" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQSERVICES-1389</a>  [iOS] Broken link to German legal page
</td></table>
<br />
----
----
With this PR we aim to fix the issue with the broken German legal page. But that problem also lead us to think how to treat URL's for different languages. Currently on the Wire website we support German and English. 
So when the Wire iOS app is in German we should redirect users to the German version of the website when it comes to "About", "Legal" and many other pages. 
The initial solution was to do something …
> fix: Broken link to german legal page SQSERVICES-1389

- .github/workflows/crowdin.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-43" title="IC-43" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-43</a>  Crowdin Github Action is broken
</td></table>
<br />
----
----
The Crowdin Github Action is failing. See https://github.com/crowdin/github-action/issues/114
Bump the Crowdin Github Action to 1.4.8.
----
----
----
> chore: Crowdin Github Action is failing IC-43

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
----
----
With this PR we fix the transparent navigation bar when we try to create a group conversation from the Profile View Controller.
| BEFORE  |  AFTER  |
|---|---|
| ![Screenshot 2022-04-21 at 16 21 23](https://user-images.githubusercontent.com/10944108/164480306-b92b8e77-ccef-42df-bd3f-de192cbc0588.png)  | ![Screenshot 2022-04-21 at 16 29 03](https://user-images.githubusercontent.com/10944108/164480560-ec5dc275-a3bc-4a77-9157-74faf3e3a154.png)  |
----
> fix: Transparent Navigation Bar when creating a Group Conversation from the Profile View Controller

- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsContentViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-44" title="IC-44" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-44</a>  The colour of navigation bar is transparent when profile view controller presented as a popover or a modal
</td></table>
<br />
----
----
With this PR we fix the color of the navigation bar when  profile view controller presented as a popover or a modal depending on the context. 
|BEFORE | AFTER |
|---|---|
|<img width="586" alt="Screenshot 2022-04-25 at 10 01 32" src="https://user-images.githubusercontent.com/10944108/165052897-012409ff-322b-4a3e-86b4-e2cda3be7e1a.png"> | <img width="586" alt="Screenshot …
> fix: The color of navigation bar when profile view controller presented as a popover or a modal IC-44

- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
----
----
With this PR we fix the nav bar color for country picker
| BEFORE  | AFTER |
|---|---|
| ![Screenshot 2022-04-27 at 16 59 33](https://user-images.githubusercontent.com/10944108/165549532-8894ddb8-d1ae-4dca-b1e6-7aba2f504c46.png) | ![Screenshot 2022-04-27 at 17 00 59](https://user-images.githubusercontent.com/10944108/165549637-7f359400-765c-4ac7-8ec5-e7f4f2896926.png) |
----
> fix: Nav bar color for country picker

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCORE-1300" title="SQCORE-1300" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQCORE-1300</a>  [iOS] Trim whitespace in username field
</td></table>
<br />
----
----
It's possible to add  whitespace around the name text field in settings.
Trim whitespace in the text field
----
----
----
> chore: trim whitespace in input field SQCORE-1300

- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+Folders.swift
----
----
With this PR, we fix the color of the navigation bar of the FolderPickerViewController.
| BEFORE  | AFTER  |
|---|---|
| <img width="548" alt="Screenshot 2022-05-20 at 10 46 17" src="https://user-images.githubusercontent.com/10944108/169493542-3cac8e26-a276-4816-94f3-d17d70717129.png">  | <img width="548" alt="Screenshot 2022-05-20 at 10 56 34" src="https://user-images.githubusercontent.com/10944108/169493561-dfe95541-c102-4098-a9d4-92d8c2025906.png">  |
----
> fix: The color of the navigation bar of the FolderPickerViewController

- Wire-iOS Tests/AppStateCalculatorTests.swift
- Wire-iOS/Sources/Helpers/ColorScheme.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-92" title="ACC-92" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />ACC-92</a>  [iOS] Folders Screen: Dynamic Type Support (Partially implemented)
</td></table>
<br />
----
In this PR I have implemented dynamic type correctly to make sure that the tableView heading's font is scalable.
| iPhone 8 - English  | iPhone 8 - German  |  iPhone SE - English | iPhone SE - German  |
|---|---|---|---|
| <img width="548" alt="Screenshot 2022-05-12 at 08 21 49" src="https://user-images.githubusercontent.com/50630878/171859380-bc7d20de-0846-49c0-9478-0ddad6297ed4.gif">  | <img width="548" alt="Screenshot 2022-05-12 at 08 26 …
> feat: folders screen - dynamic type support ACC-92

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperToolsView.swift
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperToolsViewModel.swift
- Wire-iOS/Sources/WireApplication.swift
----
----
With recent work on federation and API versioning, it's increasingly difficult to diagnose why the app may not be behaving as you expect. For example, you might not be able to log in with your credentials, but you're sure they're correct. Sometimes the app is connected to the wrong backend, but it's hard to identify that. Wouldn't it be great to find out quickly what backend you're connected to? Wouldn't it be great to quickly access other useful info, such as the current API version, whether federation is enabled, the ids of the self user, what your push token is,  etc?
We already have a developer options menu in the account settings, but this not accessible until the user has logged in. Also, it doesn't have a lot of this info that …
> feat: new developer tools screen

- Wire-iOS Tests/App Lock/Tests/AppLockModuleViewTests.swift
- Wire-iOS Tests/ConversationList/Container/ConversationListViewControllerTests.swift
- Wire-iOS Tests/ShareContactsViewControllerSnapshotTests.swift
- Wire-iOS Tests/ShareViewControllerTests.swift
- Wire-iOS/Sources/Permissions/PermissionDeniedViewController.swift
- Wire-iOS/Sources/Permissions/ShareContactsViewController.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.LockView.swift
- Wire-iOS/Sources/UserInterface/Availability/AvailabilityStringBuilder.swift
- Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/UserNameTakeOverViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- WireCommonComponents/FontScheme.swift
- WireCommonComponents/FontSpec.swift
This reverts commit 60d358e4f45a816efa66617fabc29bb85a2cb1de.
----
----
This introduced a lot of issues with dynamic type throughout the app and we would like to revert it for now.
----
> chore: revert "feat: Non-Linear font scaling (#5677)"

- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1624" title="SQSERVICES-1624" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQSERVICES-1624</a>  [iOS] Unable to open attachment files (pdf)
</td></table>
<br />
----
----
Fixed issue when user is unable to open file  for the second time. 
I removed condition that checks if file was already downloaded before opening. It won't cause downloading single file multiple times because before downloading files data we're checking if it's already stored on the device.
> fix: unable to open attachment file second time [SQSERVICES-1624]

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/TopPeopleCell.swift
----
----
Drop pin method and use anchors API instead IC - 69
----
> chore: Drop pin method and use anchors API instead IC - 69

- Wire Notification Service Extension/NotificationService.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperFlags/DeveloperFlagsView.swift
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperFlags/DeveloperFlagsViewModel.swift
- WireCommonComponents/DeveloperFlag.swift
----
----
We still have issues with the NSE not displaying notifications for periods of time. It's hard to know where the failure is happening because 1) notifications are just difficult to debug without a debugger, 2) the NSE is a separate process and our logging tools don't work in it, 3) it not easy to reproduce the issue.
Add two developer flags:
1. `nseDebugEntryPoint`, if on, will make the NSE display the contents of the push it receives at its entry point immediately and then return. This is useful to check whether the problem is if the NSE is receiving the push at all (eg. due to bad network) or if it's to do with our processing of the push.2. 
2. `nseDebugging`, if on, will display notifications with debug messages in all the failure …
> chore: improve nse debugging

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
----
----
With this PR we fix the issue in Start Conversation Screen where the colors would change based on light and dark mode.
----
> fix: Start Conversation Screen: Fix color for the User Cell

- Wire-iOS Tests/Calling/CallParticipantsListViewControllerTests.swift
- Wire-iOS Tests/CheckmarkCellTests.swift
- Wire-iOS Tests/ContactsCellSnapshotTests.swift
- Wire-iOS Tests/ConversationCreationControllerSnapshotTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationMessageSenderSnapshotTests.swift
- Wire-iOS Tests/CustomAppLock/AppLockChangeWarningViewControllerTests.swift
- Wire-iOS Tests/CustomAppLock/WipeDatabaseViewControllerTests.swift
- Wire-iOS Tests/GroupConversationCellTests.swift
- Wire-iOS Tests/LegalHoldDetailsViewControllerSnapshotTests.swift
- Wire-iOS Tests/SwiftSnapshotTesting/XCTestCase+SnapshotTesting.swift
- Wire-iOS Tests/UserCellTests.swift
- Wire-iOS Tests/UserSearchResultsViewControllerTests.swift
----
----
Since our base OS is iOS 13 we don't need those checks anymore. 
----
> chore: remove @available(iOS 13, *) checks

- Wire-iOS/Sources/AppDelegate.swift
- Wire-iOS/Sources/LaunchSequenceOperation.swift
- WireCommonComponents/AutomationHelper.swift
- WireCommonComponents/DeveloperFlag.swift
----
----
QA would like to be able to set the preferred api version via command line argument rather than through the app via automation.
Add the option to set the command line argument `preferred-api-version` with a numerical string value which will set the preferred api version of the app.
Additionally, I've added a safety measure to clear any debug / dev state when the app is in release mode, just to make sure that no custom behavior is run in release mode due to persisted data set in debug modes.
----
----
----
> chore: add automation helper to set preferred api version

- Wire-iOS/Sources/MLS/CoreCrypto.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-703" title="FS-703" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-703</a>  [iOS] Automatically Commit PendingProposals
</td></table>
<br />
----
----
Calling `wire_setCallbacks` always fails
It attempts to cast from  `WireDataModel.CoreCryptoCallbacks` to `WireCoreCrypto.CoreCryptoCallbacks` which always fails since they are different types.
Introduce a wrapper around WireDataModel.CoreCryptoCallbacks.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis …
> fix: cast always fails when setting core crypto callbacks FS-703

- Wire-iOS/Sources/LaunchSequenceOperation.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- WireCommonComponents/AutomationHelper.swift
----
----
QA couldn't set the preferred api version with the existing argument. They also want to be able to toggle the message protocol option when creating a group.
I think the helper wasn't being run when we needed it to be.
- Explicitly set the preferred api version in the api version launch operation.
- Add an option to control the message protocol toggle
----
----
----
> chore(mls): fix QA automation helper

- Wire-iOS/Sources/Helpers/MediaShareRestrictionManager.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1654" title="SQSERVICES-1654" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQSERVICES-1654</a>  [ios] Bund: Create iOS column 1 clients that block the user from using spellcheck, translation tools and lookup from iOS
</td></table>
<br />
----
----
As a part of the restriction file sharing for Bund, we should also disable iOS suggestions and message forward action (the ability to forward a message to other Wire conversations).
----
----
----
1. E.g. `feat(conversation-list): …
> fix: Disable iOS suggestions and message forward action SQSERVICES-1654

- Wire-iOS/Resources/Base.lproj/InfoPlist.strings
- Wire-iOS/Resources/ar.lproj/InfoPlist.strings
- Wire-iOS/Resources/da.lproj/InfoPlist.strings
- Wire-iOS/Resources/de.lproj/InfoPlist.strings
- Wire-iOS/Resources/es.lproj/InfoPlist.strings
- Wire-iOS/Resources/et.lproj/InfoPlist.strings
- Wire-iOS/Resources/fi.lproj/InfoPlist.strings
- Wire-iOS/Resources/fr.lproj/InfoPlist.strings
- Wire-iOS/Resources/it.lproj/InfoPlist.strings
- Wire-iOS/Resources/ja.lproj/InfoPlist.strings
- Wire-iOS/Resources/lt.lproj/InfoPlist.strings
- Wire-iOS/Resources/nl.lproj/InfoPlist.strings
- Wire-iOS/Resources/pl.lproj/InfoPlist.strings
- Wire-iOS/Resources/pt-BR.lproj/InfoPlist.strings
- Wire-iOS/Resources/ru.lproj/InfoPlist.strings
- Wire-iOS/Resources/sl.lproj/InfoPlist.strings
- Wire-iOS/Resources/tr.lproj/InfoPlist.strings
- Wire-iOS/Resources/uk.lproj/InfoPlist.strings
- Wire-iOS/Resources/zh-Hans.lproj/InfoPlist.strings
- Wire-iOS/Resources/zh-Hant.lproj/InfoPlist.strings
----
----
The photo library access permission alert does not explain to the user for what reason we need access.
Change the copy to include an example why we need access to the photo library.
----
----
----
> fix: photo library permission copy does not have an example

- Wire Notification Service Extension/NotificationService.swift
- WireCommonComponents/DeveloperFlag.swift
----
----
We suspect that people still suffering from notification issues is because their app is in a bad state where iOS is no longer delivering notifications. To test this hypothesis, we're adding a flag to intentionally break the notification service. If the flag is on, we will not do anything in the service, which hopefully after receiving and ignoring enough pushes, the app will no longer show any notifications.
----
----
----
> chore: add flag to break notifications

- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/MessageProtocolSectionController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-880" title="FS-880" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-880</a>  [IOS] Protocol and Cyphersuite indication in the Group properties
</td></table>
<br />
----
----
If I tap on the message protocol cell (in group details), the app crashes.
The `MessageProtocolSectionController` doesn't override a method from super, that is expected to be overridden.
Override the method with an empty implementation.
Tested manually.
----
----
----
1. E.g. `feat(conversation-list): Sort …
> fix(mls): crash when tapping message protocol cell FS-880

- Wire Notification Service Extension/Simple/Helpers/EventDecodingProtocol.swift
- Wire Notification Service Extension/Simple/Helpers/EventMessageExtractor.swift
- Wire Notification Service Extension/Simple/Job.swift
- Wire Notification Service Extension/Simple/NotificationServiceError.swift
- Wire Notification Service Extension/Simple/SimpleNotificationService.swift
- Wire-iOS Tests/Notification Service Extension/SimpleNotificationServiceExtension/JobTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1700" title="SQSERVICES-1700" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />SQSERVICES-1700</a>  Refactor NotificationService for possible reuse
</td></table>
<br />
This pull requests implements Phase 2 and 3 from the [new notification extension plan](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/647725130/Notification+Service+Extension+2.0).
> feat: simple nse step2 cleanup, tests SQSERVICES-1700

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
----
----
With this PR we fix the issue that popped up where the icons will disappear if the title conversation is a long one.
----
> fix: buttons disappearing in ConversationView Navigation bar because of the length of the title

- Wire-iOS/Sources/Helpers/SemanticColors.swift
----
----
With this PR we replace `Asset.gray90` with `Asset.gray100` for the border color of the Audio, Video and Search Buttons in conversation View.
----
> fix: Border color for `Audio`, `Video` and `Search` buttons in `ConversationView` (Dark Mode)

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
<table>
<td>
</td></table>
<br />
> fix: callSelfParticipantView bugs- ACC-143

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Accessibility.strings
- Wire-iOS/Sources/UserInterface/Collections/CollectionAudioCell.swift
----
----
With this PR we fix two typos in `Accessibility.strings`
----
> fix: Typos in Accessibility.strings

- Wire-iOS Tests/MessageReplyPreviewViewTests.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Wire-Info.plist
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1321" title="FS-1321" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-1321</a>  [iOS] Create Bund build with CallKit force disabled
</td></table>
<br />
----
----
- Add an option to force disable CallKit via a build time flag. The default is CallKit is not disabled.
- If disabled, then the setting in user options is hidden, and the session manager is configure appropriately to disable CallKit.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the …
> feat: add option force disable CallKit via build time flag FS-1321

- Wire-iOS/Sources/UserInterface/MarkdownBarView.swift
----
----
With this PR we fix the spacing issue between the markdown buttons in Conversation View. The spacing was way too big and occurred on devices such as the iPad, and phones like the iPhone Pro Max etc.
----
> fix: Spacing issue between markdown buttons in Conversation View ACC - 333

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
----
----
With this PR we update the string for `participants.services.remove_integration.button` from `Remove integration` to `Remove service`
----
> chore: Update string for `participants.services.remove_integration.button`

- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
We need to set it to white on light and dark mode
----
----
With this PR we fix the background color of the canvas to be white in both light and dark mode.
----
> fix: Background color of Canvas - ACC - 306

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-355" title="ACC-355" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-355</a>  [iOS] Fix the highlight outline
</td></table>
<br />
> fix: frame on active speaker acc-355

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewControllerInput.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-356" title="ACC-356" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-356</a>  [iOS] Fix: other user profile pic still shows when the camera is ON
</td></table>
<br />
> fix: profile pic visible when camera on ACC-356

- Wire-iOS Tests/Calling/CallGridViewControllerSnapshotTests.swift
- Wire-iOS Tests/Calling/CallInfoRootViewControllerSnapshotTests.swift
- Wire-iOS Tests/Calling/CallInfoRootViewControllerTests.swift
- Wire-iOS Tests/Calling/CallParticipantsListViewControllerTests.swift
- Wire-iOS Tests/IconLabelButtonTests.swift
- Wire-iOS Tests/UserCellTests.swift
- Wire-iOS/Sources/AppDelegate.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionIconType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/RoundedPageIndicator.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsListView/CallParticipantsListView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallGridConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
- WireCommonComponents/AutomationHelper.swift
- WireCommonComponents/DeveloperFlag.swift
<table>
<td>
</td></table>
<br />
----
----
We have a developer flag that we use to test the new and old calling overlay. But automation tests cannot change this flag.
Add a flag to the QA automation helper that can be used inside tests.
@Marcin-Ratajczak we should use` DeveloperFlag.isUpdatedCallingUI`
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in …
> chore: Add 'updatedCallingUI' key to the QA automation helper ACC-143

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-361" title="ACC-361" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-361</a>  [iOS] Fix "pre calling UI" in the horizontal mode
</td></table>
<br />
> fix: incoming call UI horizontal ACC-361

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-362" title="ACC-362" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-362</a>  [iOS] Fix button colors on the "pre calling UI"
</td></table>
<br />
----
> fix: colors of calling actions buttons on mode change ACC-362

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/SelfCallParticipantView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-359" title="ACC-359" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-359</a>  [iOS] Fix: "the video gets stuck"
</td></table>
<br />
fix bug that freezes selfParticipant video when you start audio call and then enable, disable and enable again camera
> fix: freezed video ACC-359

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-390" title="ACC-390" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-390</a>  [iOS] Conversation title on the top is little cut off on iPhone 14 pro due to dynamic island
</td></table>
<br />
> fix: call title cut on iPhone 14 ACC-390

- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
- Wire-iOS/Sources/Analytics/Events/ZMConversation+Analytics.swift
- Wire-iOS/Sources/AppRootRouter.swift
- Wire-iOS/Sources/AuthenticatedRouter.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1344" title="FS-1344" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1344</a>  [iOS] [Bund Col1] App crash upon starting call
</td></table>
<br />
----
----
Given CallKit is disabled and I receive an incoming call while the app is the background, when I bring the app to the foreground, the app will sometimes crash.
There seem to be a couple different crashes:
- Trying to access the self user when it is not yet available (in analytic events).
- Trying to constraint a call top overlay to an unrelated view.
The underlying cause of the top overlay crash is because:
- we try to present it …
> fix: crashes when opening app to answer a call FS-1344

- Wire-iOS/Sources/AppRootRouter.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1411" title="FS-1411" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1411</a>  [iOS] Col1 RC 3.108(226): Moving app to background while in a call makes user unable to open calloverlay
</td></table>
<br />
… FS-1411
----
----
Given there is an ongoing call, when I the app is put to the background and brought back to the foreground, then the call UI is not visible.
In my last PR, I [deleted this line](https://github.com/wireapp/wire-ios/pull/6047/files#r1062564858). It's clear now that we need to present the call ui again after coming from the background, since it may have been torn …
> fix: active call overlay is not presented when coming from background FS-1411

- Wire Notification Service Extension/LegacyNotificationService.swift
- Wire Notification Service Extension/NotificationService.swift
- Wire-iOS/Sources/AppDelegate.swift
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperToolsViewModel.swift
- Wire-iOS/Sources/Managers/DatadogWrapper.swift
- WireCommonComponents/DeveloperFlag.swift
----
----
Remove the developer flag to enabled DataDog so that it is always enabled (for internal builds only). This PR also contains some formatting improvements.
----
----
----
> chore: remove datadog flag

- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationStepController.swift
- Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift
----
----
With this PR we fix a keyboard trap that we had during the sign-up flow, where the user couldn't dismiss the keyboard in any way. With the new implementation, the user can dismiss the keyboard by tapping anywhere on the screen
----
> fix: User cannot resend code or change Email while creating a new personal wire account - ACC - 346

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Authentication/AuthenticationFlowStep.swift
- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/Authentication/Event Handlers/AuthenticationCoordinatorAction.swift
- Wire-iOS/Sources/Authentication/Event Handlers/AuthenticationEventResponderChain.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Device Configuration/DeviceConfigurationEventHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Post-Login/Success/AuthenticationSuccessEventHandler.swift
----
----
After https://github.com/wireapp/wire-ios-sync-engine/commit/6b1675bb6cba6d4407e4c024bf9524ddbd16938a we no longer ask for FaceID permissions during the login flow.
Previously we were migrating the DB to encryption at rest (this was unnecessary and causing issues so I removed the migration step), which then resulted In a locked DB. The user then needed to authenticate to unlock the DB, which causes the permission for FaceID to be requested. Since we skip the migration phase now, we don't need to unlock the DB and consequently no FaceID permission is needed during the login flow. 
- Add a step to the login flow to configure the device. 
- In this step, require local authentication (triggering biometric permission requests) if EAR is …
> fix: setup EAR permissions in login flow

- Wire Notification Service Extension/NotificationService.swift
- Wire-iOS.xcodeproj/project.pbxproj
----
----
Datadog when enabled in config crashes on device.
Datadog is *not* included in build phase embed frameworks.`DATADOG_IMPORT=1` should be defined in xcconfig so conditional script can remove the framework or not
* Add `DATADOG_IMPORT=1` to xcconfig in addition to `OTHER_PREPROCESSOR_FLAGS = DATADOG_IMPORT`
* Do add Datadog to embed frameworks build phase
Build app with:
```
DATADOG_IMPORT=1
OTHER_PREPROCESSOR_FLAGS = DATADOG_IMPORT
```
----
----
----
> fix: datadog crash on device

- Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTabBar.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-414" title="ACC-414" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />ACC-414</a>  [iOS] iPad: Tab bar doesn't update colors when switching from Light to Dark mode
</td></table>
<br />
----
----
Wrong colors in dark mode for tab bar.
We need use `super.traitCollection` for TabBar.
----
----
----
> fix: traitCollection for tab bar ACC-414

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.swift
----
----
That issue is bugging me for a while. So when we bring the app from the background to the foreground and we're in the conversation view. Then the border color of the search icon is wrong. With this PR we fix that issue. 
Here's a video that explains that issue. 
https://user-images.githubusercontent.com/10944108/212669330-39b4ae33-b771-4c20-98c5-56a041e75edb.mp4
----
> fix: Border Color of Search Icon in Conversation View when bringing the app from the background to foreground

- Wire-iOS/Sources/Helpers/UIBarButtonItem+StyleKit.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupPasswordViewController.swift
----
----
With this PR we update the font size of the NavigationBarItems in BackupPasswordViewController. 
----
> fix: Update font size for navigation bar items in `BackupPasswordViewController`

- Scripts/datadog-conditional-framework.sh
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperToolsViewModel.swift
- Wire-iOS/Sources/Managers/DatadogWrapper.swift
- fastlane/Fastfile
- fastlane/Pluginfile
----
----
The Datadog crash reporting integration has compilation issues or  (CrashReporter) causes a popup to show up on iOS16.
Revert for now the feature.
----
----
> revert: datadog crashreporting

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1502" title="FS-1502" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1502</a>  [iOS] Calling: on non-UI KIT calls, the calling UI has different sizes of buttons
</td></table>
<br />
> fix: incoming call landscape layout FS-1502

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/UIDevice+Orientation.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1501" title="FS-1501" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1501</a>  [iOS] Calling: not matching avatar is shown when receiving non-UI Kit call with different display name
</td></table>
<br />
> fix: calling UI layout issues FS-1501

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1501" title="FS-1501" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1501</a>  [iOS] Calling: not matching avatar is shown when receiving non-UI Kit call with different display name
</td></table>
<br />
> fix: change image size in incoming call FS-1501
