- README.md
- setup.sh
Update README with steps to update local pods repo if necessary.
Remove CocoaPods version check from setup script as it is installed via bundler.
> Update README with steps to update local pods repo

- Wire-iOS.xcodeproj/project.pbxproj
* Remove the development team identifier
> Remove development team from Xcode project

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/Components/Settings.h
- Wire-iOS/Sources/Components/Settings.m
- Wire-iOS/Sources/UserInterface/Camera/CameraController.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/ConfirmAssetViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/ConfirmAssetViewController.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/ImagePickerConfirmationController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Helpers/UIView+Zeta.m
- Wire-iOS/WireBridgingHeader.h
- Picture confirmation
- Remember last used camera
- Inset between photos
- 2 Rows for camera roll
- Fixed bug with huge keyboard
- Put back video button
- Edit video if it is too long
- Download iCloud assets
> Camera keyboard revisit

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/DeviceProximityListener.swift
* Fixes audio message playback not switching to earpiece when held vertically at the ear.
* Only activate the proximity / motion listener when a message is played, deactivate it when the playback stops.
> Fix audio message playback not using earpiece when held vertically

- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileSelfPictureViewController.m
- Considered useless to sketch on your own profile pic
> Remove sketch for self picture

- Wire-iOS/Sources/Analytics/AnalyticsTracker.m
- Wire-iOS/Sources/Analytics/Events/Analytics+ProfileEvents.h
- Wire-iOS/Sources/Analytics/Events/Analytics+ProfileEvents.m
- Wire-iOS/Sources/Analytics/Events/AnalyticsGroupConversationEvent.h
- Wire-iOS/Sources/Analytics/Events/AnalyticsGroupConversationEvent.m
- Wire-iOS/Sources/Analytics/Sketchpad/AnalyticsTracker+Sketchpad.m
- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileSelfViewController.m
* Second part of [6964](https://wearezeta.atlassian.net/browse/ZIOS-6964)
* Remove more unused or redundant analytic calls
> Remove unused and outdated analytics events

- Wire-iOS/Sources/UserInterface/Components/Views/SwipeMenuCollectionCell.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
> Peek & Pop support for conversation list

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationPreviewViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
- Wire-iOS/WireBridgingHeader.h
* Add top and bottom insets to the preview view controller shown when 3D touching on a conversation in the conversation list
> Add inset to view controller shown on conversation name peek

- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileSelfViewController.m
* Add developer option for QA to force upload the address book (good to test tracking)
> Add developer option to force upload address book

- Wire-iOS/Sources/Analytics/Permissions/AnalyticsTracker+AddressBookPermissions.swift
> Fix typo in analytics event name

- Wire-iOS/Sources/Managers/AddressBookHelper.m
- WireExtensionComponents/Utilities/AutomationHelper.swift
Enable address book upload on simulator if forced by command line
Additionally, refactored the `AddressBookHelper` class.
> Enable address book upload on simulator if forced by command line

- Wire-iOS Tests/InputBar/InputBarTests.swift
* This test crashes when run on a clean simulator
> Disable second crashing test

- .travis.yml
* Add rule to build release branches to `.travis.yml`
> Add release branch exception to .travis.yml

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
* The editing view had the wrong width on tablets.
> Fix edit view width on iPad

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
* https://github.com/wireapp/wire-ios/pull/108 now against the correct branch `release/2.14`
> Fix editing view width on ipad

- Wire-iOS Tests/Soundcloud/SoundcloudServiceTests.m
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/Soundcloud/SoundcloudService+Testing.h
- Wire-iOS/Sources/Components/Soundcloud/SoundcloudService.m
Relates to issue fixed in https://github.com/wireapp/wire-ios/pull/126
> Test to verify correct behavior with inconsistent Soundcloud reply

- .gitignore
- Podfile.lock
As suggested by https://github.com/wireapp/wire-ios/issues/118
> Track Podfile.lock

- Wire-iOS/Sources/UserInterface/Conversation/ReactionsList/ReactionsListViewController.swift
* Change location and icon type of the dismiss button in the `ReactionsListViewController`
> Move dismiss button to the right and change icon to `X` in "liked by" view controller

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/FileMessageCellState.swift
- Before actions where happening as a result of clicking the whole cell
- Now action should go from button
> Fixed action to download the received file

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- The logic for showing number of people who liked vs their names was broken
- PR adds logic to detect when people who like names owerflow
> Fixed likers names rendering

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m
Deleting a video message was causing a crash
Deleted cells in the UITableView update were configured even after they were deleted (accessing a now deleted ManagedObject, which causes a crash) because they were reconfigured inside the `beginUpdates` / `endUpdates` section, before the cell is actually removed from the visible cells.
Pass a list of deleted index paths to the method that refreshes the cells, and do not reconfigure those that were deleted
> Fix crash on deleting video message

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Like.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIView+SlideInState.swift
> Timestamp change animation for reactions

- Podfile
- Podfile.lock
- PR upstream https://github.com/mysterioustrousers/MTAnimation/pull/28
> Update MTAnimation to fix the animation completion crash

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Analytics/Events/Analytics+ConversationEvents+Swift.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+ConversationEvents.h
- Wire-iOS/Sources/Analytics/Events/Analytics+ConversationEvents.m
- Wire-iOS/Sources/Analytics/Events/Analytics+ConversationEvents.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
- Wire-iOS/Sources/Analytics/Events/ZMConversation+Analytics.swift
- Wire-iOS/Sources/Analytics/Events/ZMMessage+Analytics.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Like.swift
> Track like actions

- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Added localization for new features (reaction, delivery receipts)
- Removed unused UI copy strings (Crowdin removed them according to https://github.com/wireapp/wire-ios/pull/141)
- Cleaned localizable file comments and unified file structure
> pr-BR localization cleanup

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ZMConversationMessageWindow+Formatting.m
- Delivered disabled until the majority would send the receipts
> Remove delivered state

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
* Make the sketch and fullscreen buttons accessible in `ImageCell`.
* Mark the `imageViewContainer` as image.
> Set sketch and fullscreen button as accessibility elements when image cell is selected

- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Removed unused German text strings
- Added Brazilian Portuguese & German localization for new features: reaction, delivery
> German localization for release 2.15

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/es.lproj/InfoPlist.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.stringsdict
- Wire-iOS/Resources/ru.lproj/InfoPlist.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.stringsdict
- Wire-iOS/Resources/uk.lproj/InfoPlist.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.stringsdict
- Adding support for Ukrainian, Spanish and Russian localization
- Adding localized strings from Crowdin for new languages
> Adding Ukrainian, Spanish and Russian localization

- Wire-iOS/Sources/Helpers/UIApplication+Permissions.m
The UI seems broken if user did not allowed the camera permissions in camera keyboard: the camera alert is overlapped by the keyboard.
We do not show those dialogues at the same time. The alert is shown first, then the camera keyboard is coming into focus.
> Do not show alert together with camera keyboard

- Wire-iOS/Sources/Helpers/NSURL+WireURLs.m
* https://github.com/wireapp/wire-ios/pull/230 against `develop`
> Add new password reset url

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientTableViewCell.swift
- WireExtensionComponents/Utilities/Date+Format.swift
* Fix optional activation date string in clients list
> Fix optional activation date

- Wire-iOS Tests/ReactionsListViewControllerTests.swift
- Wire-iOS Tests/Settings/SettingsPropertyTests.swift
- Wire-iOS Tests/TextMessageCellTests.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
- Wire-iOS/Sources/UserInterface/Registration/AddEmailPasswordViewController.h
- Wire-iOS/Sources/UserInterface/Registration/AddEmailPasswordViewController.m
- Wire-iOS/Sources/UserInterface/Registration/AddPhoneNumberViewController.h
- Wire-iOS/Sources/UserInterface/Registration/AddPhoneNumberViewController.m
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertySelectValueCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyTextValueCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsPropertyToggleCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsNavigationController.swift
- Show version in last row
- Name validation
- Small copy changes
> Updates for settings review

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Wire-iOS/Sources/UserInterface/Settings/ProfileSelfPictureViewController.m
- Wire-iOS/Sources/UserInterface/Settings/SettingsStyleNavigationController.swift
- Fix full screen image overflowing
- Fix overlap of keyboard and phone field on iPad
- Update style of device controller
> Settings revisit 3

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/ConversationInputBarViewController+Emoji.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_activities.plist
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_objects.plist
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_people.plist
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiRessources/emoji_travel.plist
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/Emojis.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EmojiSectionViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/RecentlyUsedEmojis.swift
* Adds a recently used emoji section (limited to 15 emoji), the emoji are stored in the application support directory
* Fix section controller selection bugs
* Fixes a couple of emoji in the plists
> Add recently used emoji section

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EmojiSectionViewController.swift
* Limit emoji section control to a max width 
* Adjust hit area padding of the section buttons
* Add long press option to the delete button to quickly delete multiple characters
> Fix hitArea, iPad layout and add fast deletion on long press

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
* Adds the new paper-plane send button
> Add new send button design

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> Restore title case in Settings

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/TypingIndicatorView.swift
- Run expansion and fade in animation in parallel
- Start the pen animation after it has appeared completely
- Pen always starts animating from left to right
> Tweak is typing animation

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
* The send button icon color was dimmed in the highlighted state which it shouldn't be.
> Adjust send button color in highlighted state

- Wire-iOS/Entitlements-Dev.entitlements
APNS for development build were not working
> Fix using production environment for APNS in debug

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Resources/Magic/style.plist
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphyConfirmationViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
- align navigation bar buttons
- add margins between buttons and giphy preview
- add no-results label
- use correct font for the title
> Giphy design fixes

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphyConfirmationViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Disable rotation on iphone
- Show more columns on iPad
- Fix confirm button constraints
- Fix placeholder typo
- Fix statusbar not being visible on iPad
- Fix layout after rotation
> More giphy fixes

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EphemeralKeyboardViewController.swift
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
* Adds the new indicator design showing the ephemeral destruction interval instead of the hourglass in case the conversation is ephemeral.
> Add new ephemeral destruction time indicator

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/FingerprintTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
This PR fixes the personal fingerprint screen shown from the user device screen.
The screen also respect light / dark  mode.
> Fix transparent device information screen

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/da.lproj/InfoPlist.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.stringsdict
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/InfoPlist.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.stringsdict
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Added new languages: Danish, French
> Added localisation for release 2.20

- Wire-iOS/Sources/Analytics/AnalyticsFileTransferObserver.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
- Wire-iOS/Sources/Analytics/FileTransfer/AnalyticsTracker+FileTransfer.h
- Wire-iOS/Sources/Analytics/FileTransfer/AnalyticsTracker+FileTransfer.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Audio.swift
* Add `is_ephemeral` tracking attribute and `ephemeral_time` attribute in case the message is ephemeral.
> Add tracking attributes for ephemeral messages

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.h
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListCell.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController.m
* Update conversation list media playback view on media player changes.
* Stop the audio track player if its source message has been deleted.
> Update conversation list media playback view on media player changes

- WireExtensionComponents/Utilities/AutomationHelper.swift
[#7524](https://wearezeta.atlassian.net/browse/ZIOS-7524): This was requested by QA to work around am automation bug, if the `wire_arguments.txt` file is present in the `/tmp` directory of the simulator the launch arguments will be read from that file instead of the process.
> Add option to read launch arguments from a file instead of from command line

- Wire-iOS/Sources/UserInterface/CanvasViewController.swift
- You can now toggle between draw/edit mode by tapping the draw button
- When in edit mode no button is seleced
> Change how mode selection works in sketch

- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Some new strings are missing in some languages, using English placeholders until they get translated
> Added localisation for release 2.21

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarButtonState.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
* Add flag to hide ephemeral sending UI in group conversations
> Add switch to disable sending ephemeral messaging in groups

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/ar.lproj/InfoPlist.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.stringsdict
- Added support for Arabic language
- Imported already localised strings from Crowdin
> Added Arabic localization

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/zh-Hans.lproj/InfoPlist.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.stringsdict
- Added support for Simplified Chinese language
- Imported already localised strings from Crowdin
> Adding support for Simplified Chinese language

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/ConversationInputBarViewController+Emoji.swift
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
The changes requested during the design review.
> Ephemeral redesign: design review

- Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
Yellow accent color is hard to combine with other colors as foreground / background.
> Removed yellow color from accent selector

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/RecentlyUsedEmojis.swift
We used to try to set do not backup flag before the folder was created.
> Last used Emoji: Create directory; then set the flag

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.m
Yellow accent color can still be picked randomly during the registration.
> Do not pick yellow accent automatically

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
* The `MessageToolBoxView` was not using the `updatedAt` `Date` but the `serverTimestamp` to construct the date string for edited messages.
> Fix edited messages showing wrong date

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/sl.lproj/InfoPlist.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.stringsdict
- Added support for Slovenian language
- Imported already localised strings from Crowdin
> Added Slovenian localization

- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/InfoPlist.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Some new strings are missing in some languages, using English placeholders until they get translated
> Added localisation for release 2.23

- Wire-iOS Tests/IconSystemCellTests.m
- Wire-iOS Tests/ParticipantDeviceCellTests.m
- Wire-iOS Tests/ZMSnapshotTestCase+Swift.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/LocationMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/TextMessageCell+Internal.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/WireBridgingHeader.h
Fixes for displaying different forwarded content.
> Forward design review

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.h
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.m
When opened the camera keyboard, clicking on camera roll icon requires audio permissions #390 
Receiving audio call requires video permissions.
> Fix permission dialogues

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Use of CallKit raise privacy concerns, therefore adding an option to disable it.
> Add switch to disable CallKit

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Attaching files does not work in the integrated browser that we show.
> Open contact support in Safari

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
On iPad: the forward menu is collapsed by keyboard
Forwarding is ephemeral on ephemeral conversations
Audio metadata is not forwarded
Search includes conversations where user cannot post
> Fix known forwarding issues

- Wire-iOS/Sources/UserInterface/Components/Controllers/ActionSheetController/ActionSheetController.m
- Wire-iOS/Sources/UserInterface/Conversation/ActionSheetController+Conversation.h
- Wire-iOS/Sources/UserInterface/Conversation/ActionSheetController+Conversation.m
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
* There was an inconsistency in the casing of the title between the action sheets for group and 1-one-1 conversations.
> User new title casing for group conversation action sheets

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.stringsdict
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.stringsdict
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.stringsdict
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.stringsdict
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.stringsdict
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.stringsdict
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.stringsdict
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.stringsdict
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.stringsdict
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.stringsdict
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.stringsdict
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.stringsdict
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.stringsdict
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.stringsdict
- Some new strings are missing in some languages, using English placeholders until they get translated
> Added localisation for release 2.24

- Wire-iOS/Sources/Analytics/Events/Analytics+Usernames.swift
- Wire-iOS/Sources/Analytics/Events/AnalyticsConnectionRequestEvent.m
- Wire-iOS/Sources/UserInterface/ContactsUI/ContactsViewController.m
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationList+Handles.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/ChangeHandleViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
* Add more tracking calls for usernames.
> Add more tracking for usernames

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/InviteContacts/InviteContactsViewController.m
Before with one-way autoconnect it was not possible to have person that is in your address book and on wire. Now it is possible, and we need to handle this case.
> Connect to people address book

- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/WireBridgingHeader.h
* The context menu for a conversation was not being presented from the archive since the presentation of the view controllers was changed to not rely on child view controller containment.
> Fix conversation content menu not being presented from archive

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/SplitViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/WireBridgingHeader.h
As we decided in the past to develop in smaller chunks and give the teammates possibility to review the changes faster, I split the UI changes for collections in smaller PRs.
This PR includes collections button to conversation top bar, also I moved the `ConversationViewController` category into separate file. Temporarily the collections icon uses search glyph.
> Added collections button to navigation bar

- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
> Replace dash with middle dot in search result cell

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> Update references to system Contacts app

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/et.lproj/InfoPlist.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.stringsdict
- Added support for Estonian localisation
- Imported existing translations from Crowdin
Aitäh, @margusholland
> Adding Estonian localisation

- Wire-iOS Tests/ConversationTitleViewTests.m
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Collections/CollectionsHeaderView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationDetailsTransitioningDelegate.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationDetailsTransitioningDelegate.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationTitleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/WireBridgingHeader.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
- Added "Library" icon and updated stylekit
- Added section headers and made them interactive
- Added ability to show only certain section in the controller
> Collections: Grouping and opening content

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/Settings.h
- Wire-iOS/Sources/Components/Settings.m
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/UserInterface/Collections/AssetCollectionHolder.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionViewLeftAlignedFlowLayout.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Switch to toggle between using the collections or not (off by default)
- Switch to select collections implementation ( @basine )
- Fix for cells accessibility id's being hidden
> Added collections toggles and fixed video accessibility

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.stringsdict
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.stringsdict
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.stringsdict
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.stringsdict
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Some new strings are missing in some languages, using English placeholders until they get translated
> Added localisation for release 2.27

- Wire-iOS/Resources/Sounds/audio-notifications/MediaManagerConfig.plist
- Wire-iOS/Resources/Sounds/audio-notifications/ios.json
- Wire-iOS/Resources/Sounds/audio-notifications/ios.xml
https://wearezeta.atlassian.net/browse/ZIOS-7823
> Allow outgoing ringtone to play during a call

- Wire-iOS/Sources/Analytics/AnalyticsConsoleProvider.swift
This PR print analytic console logging as JSON dict.
> print analytics log as json

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/TwoLineTitleView.swift
We supposed to show both title of conversation and title of the screen in navigation title item.
> Correct title for collections view

- Wire-iOS/Resources/Settings.bundle/Root.plist
- Wire-iOS/Sources/Analytics/Analytics+iOS.m
- Wire-iOS/Sources/Analytics/AnalyticsConsoleProvider.swift
This PR allows console logging analytics with settings switch.
> Fix small bug + enabling console log

- Wire-iOS/Sources/Analytics/AnalyticsConsoleProvider.swift
This PR consolidate attributes handling to prevent crashes.
> Attribute solidification

- Wire-iOS/Resources/Base.lproj/Localizable.strings
@infotexture @olivereitalu @Yorgos-V please review
> Reverting collections name change

- Podfile
- Podfile.lock
Updating localytics to 4.2.0. See [changelog](https://docs.localytics.com/dev/sdk-changelog.html#developers-sdk-changelog-ios).
> Bump components

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
Added a UISearchController to filter through the conversation list
> Share extension: added ability to search in conversation list

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.h
- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.m
- Wire-iOS/Sources/UserInterface/Collections/CollectionAudioCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionCellHeader.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionFileCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionHeaderView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionLinkCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionVideoCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionViewLeftAlignedFlowLayout.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/VideoMessageView.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIColor+WAZExtensions.m
- WireExtensionComponents/Utilities/ColorScheme.h
- WireExtensionComponents/Utilities/ColorScheme.m
The existing design of the collection view seems to be not that clear to the users.
The new design reveals the connection between the elements using the insets and groups. Also sections now have the icons.
Additionally the new term, name with accent color, is added. The name accent color is generated from the user accent color with the certain opacity. The opacity is defined in the table and is different per color. Opacity also different for the light/dark color schemes.
Screenshot:
> Update for new collections design

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Collections/CollectionHeaderView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionLinkCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Removed "Collections" title from header
- 4 image/video cells in the row on iPhone 6
- Changed section icons color
- Updated the margins between the sender and link name
> Changes for design review

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Collections/CollectionCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsSectionSet.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+PullToDismiss.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/SavableImage.swift
- Allow saving of images and copying
- Auto-open downloaded files/assets
- Correct dismissal of full screen image view
- Put videos after images
- Correct collections view insets
> Collections design review 3

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Collections/CollectionHeaderView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionLinkCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/TwoLineTitleView.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+PullToDismiss.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MessageAction.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
- WireExtensionComponents/Utilities/ColorScheme.h
- WireExtensionComponents/Utilities/ColorScheme.m
There was a menu items missing for the full screen view, I added forward and reveal in conversation.
Also some design changes here and there.
> Added message forwarding from image view

- Wire-iOS Share Extension/ShareViewController.swift
Removing placeholder text from share extension - it looked wrong. In a following PR, I will add an icon for when we are uploading a file and there is no text
> Remove placeholder text from share extension

- Wire-iOS Share Extension/ConversationSelectionViewController.swift
- Wire-iOS Share Extension/ShareViewController.swift
Share extension is now not transparent as it fixes several minor UI issues (especially on dark background)
> Share extension: fixes for UI issues

- Wire-iOS Share Extension/ShareViewController.swift
- Wire-iOS.xcodeproj/project.pbxproj
* Lower the share extension's deployment target to 8.
* Use iOS 8 compatible API.
> Lower the share extension deployment target

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
Next step would be to use the same controller in the conversation.
> Allow browsing collection of images by swiping

- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/FileTransferView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MessageAction.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
- WireExtensionComponents/Utilities/ColorScheme.m
- Fixed name accent color for violet color
- Added actions toolbar to swiping images controller. Now you can save/forward/copy/reveal image from the toolbar.
- Unified message actions handling.
> Collections images update

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Do not show collection buttons for pending incoming or outgoing connections
> Do not show collection icon for pending connections

- Wire-iOS Share Extension/Base.lproj/Localizable.strings
- Wire-iOS Share Extension/ConversationSelectionViewController.swift
- Wire-iOS Share Extension/NotSignedInViewController.swift
* A couple of Strings still weren't localized in the share extension (cc @jenskasemets ).
> Add missing localizations

- Wire-iOS/Sources/Analytics/Events/Analytics+Collection.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Fixed localytics events identifiers
- Added action buttons identifiers for image view
> Collection identifiers fixes

- Cartfile
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/Helpers/CGFloat+Hairline.swift
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/FeedbackOverlayView.swift
When viewing an image in collection there is a button to copy it to clipboard. As it's not obvious from the icon what it does, this PR adds a text overlay on top of toolbar with text that is shown for a bit and fades out.
> Collections: added visual feedback when image is copied to clipboard

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Collections/CollectionAudioCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionFileCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionVideoCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ZMConversationMessage+File.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
- It was possible to forward the file that is not downloaded. This caused the crash.
> Forbid forwarding the files that are not downloaded

- Wire-iOS Share Extension/PostContent.swift
* This change got lost in a merge
> Fix iCloud files sending from share extension (again)

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift
This will make conversation degradation testing faster, making QA life easier
> Add debug button in internal build to delete clients

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDevicesViewController.m
* Refresh the `ProfileDevicesViewController`'s client list in `viewWillAppear`
> Refresh clients list in viewWillAppear:

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> Rename “Forward” command to “Share”

- Wire-iOS Share Extension/Error+Logging.swift
- Wire-iOS Share Extension/NSItemProvider+Fetching.swift
- Wire-iOS Share Extension/PostContent.swift
- Wire-iOS Share Extension/SendController.swift
- Wire-iOS Share Extension/UnsentSendable.swift
- Wire-iOS.xcodeproj/project.pbxproj
* Add fixes for comments made in https://github.com/wireapp/wire-ios/pull/594
> Add comments from PR review

- Wire-iOS/Sources/Analytics/AnalyticsVoiceChannelTracker.m
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.h
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.m
- Wire-iOS/Sources/AppController.m
- Wire-iOS/Sources/Components/Settings+Calling.swift
- Wire-iOS/Sources/Components/Settings.h
- Wire-iOS/Sources/Components/Settings.m
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/Managers/ProximityMonitorManager.m
- Wire-iOS/Sources/Managers/SoundEventListener.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MissedCallCell.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelController.m
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Add tracking attributes mentioned in:
https://wearezeta.atlassian.net/browse/ZIOS-7814
> Add new calling tracking attributes and update for changed API

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Implemented `UITableViewDataSourcePrefetching` for conversation. Not sure if it would make the scrolling faster, the PR is more to try it and check the visual difference in the performance.
> Prefetch messages with the new iOS 10 API

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/ImageCache.m
- Wire-iOS/Sources/Helpers/syncengine/Message.h
- Wire-iOS/Sources/Helpers/syncengine/Message.m
- Wire-iOS/Sources/Helpers/syncengine/ZMConversationMessage+Properties.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Implemented the prefetching of the collections contents and thumbnails pre-rendering for images.
> Allow prefetching for collections contents

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/TypingIndicatorView.swift
https://wearezeta.atlassian.net/browse/ZIOS-7405
> Fix typing indicator animation stopping after opening user profile

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelController.m
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.h
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m
- avs-versions
The voice channel transition wasn't animating the blur effect when appearing and the dismiss transition wasn't animating at all.
> Fix voice channel transition

- Wire-iOS/Sources/UserInterface/Settings/ChangeEmailViewController.swift
To make life easier when testing
> Added accessibility identifier to change email text field

- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.m
https://wearezeta.atlassian.net/browse/ZIOS-7932
> Add non bucketed call duration attribute

- Wire-iOS/Sources/Analytics/AnalyticsVoiceChannelTracker.m
- Wire-iOS/Sources/Analytics/Clusterizers/TimeIntervalClusterizer.h
- Wire-iOS/Sources/Analytics/Clusterizers/TimeIntervalClusterizer.m
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.h
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.m
Adds tracking for call setup time.
> Track call setup time

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m
https://wearezeta.atlassian.net/browse/ZIOS-8022
> Use new API for turning off video when entering background

- Wire-iOS/Sources/Components/Settings.m
We want to have internal users try out calling 3 so will make it the default protocol for now.
> Enable calling 3 by default

- Wire-iOS/Sources/UserInterface/Overlay/AppLockView.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Fixed layout on iPad
- Dismiss keyboard if needed
> Disable app lock if passcode is removed

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Check if image is present in collection, it might be not there because it's not yet uploaded
> Do not crash on not yet loaded images

- Wire-iOS/Sources/Managers/SoundEventListener.m
- Don't play sounds when participants join/leave (AVS handles this)
- Pick leave sound based on the call-end-reason
> Clean up sound played during a call

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangePhoneViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ConfirmPhoneViewController.swift
Minor tweaks and copy changes after design review
> Phone changing: fixes after design review

- Wire-iOS/Sources/Helpers/NSAttributedString+Highlight.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/Message+Formatting.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Flash cell
- Highlight query in message text
> Highlight search results

- Wire-iOS/Sources/AppController.m
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- ZMUserSession.shared can be nil, we seen the crash like that
> Fix potential crash in app lock

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/InviteButtonController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsNavigationController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/InviteActionSheet/UIActivityViewController+Invite.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/InviteActionSheet/UIActivityViewController+Invite.m
- Wire-iOS/WireBridgingHeader.h
- WireExtensionComponents/Views/OverflowSeparatorView.swift
* Adds a sticky invite button to the bottom of the top level settings view.
> Add invite button to bottom of top level settings screen

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m
If the `VoiceChannelOverlay` was opened and then there was no notification for the call state change, then the timer would never start.
> Start timer on VoiceChannelOverlay even if there is no call state change

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Analytics/Events/Analytics+Collection.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+LocalSearch.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
* Add local search analytics tracking.
> Add local search tracking

- Wire-iOS/Sources/UserInterface/StartUI/Common/UIViewController+WR_Invite.m
* The warning was not valid anymore.
> Remove showing warning about 2 week validity of invites

- Wire-iOS/Sources/UserInterface/Collections/NoResultsView.swift
- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.m
- Wire-iOS/Sources/UserInterface/Components/KeyboardFrameObserver.m
- Wire-iOS/Sources/UserInterface/Components/Views/TextSearchInputView.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
- Updated icons in search UI
- Fixed black status bar on black theme
- Hide placeholder when the input is selected		
- Fixed accessiblity labels not visible		
- Fix for random black window bug
> Search UI improvements

- Wire-iOS/Sources/UserInterface/Components/Transitions/VerticalTransition.h
- Wire-iOS/Sources/UserInterface/Components/Transitions/VerticalTransition.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationDetailsTransitioningDelegate.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationDetailsTransitioningDelegate.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Really looks better when the nav and input bars are hidden.
> Hide flickering elements on fullscreen transition in conversation view

- Wire-iOS/Sources/Analytics/AnalyticsBase.m
- Wire-iOS/Sources/Analytics/AnalyticsConsoleProvider.swift
- Wire-iOS/Sources/Analytics/AnalyticsLocalyticsProvider.m
- Wire-iOS/Sources/Analytics/AnalyticsProvider.h
- More changes are coming to `wire-ios-sync-engine` and to `wire-ios-mocktransport`, but they are not blocking this PR.
> Removed tracking identifier

- Wire-iOS/Sources/Analytics/Events/Analytics+LocalSearch.swift
- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchResultsView.swift
- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/TextSearchInputView.swift
* Add a loading spinner to the search.
* Track search duration.
* Disable autocorrection for the search query input field.
> Add search loading spinner

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- This is the easiest fix so far.
> Post correct image on sketch after paste

- Wire-iOS/Sources/UserInterface/Collections/AssetCollectionWrapper.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/TextSearchInputView.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Fix for wrong layout after reopening of collection
- Fix for wrong keyboard color on dark theme
- Fix for collection not refetching new items
> Collection + text search fixes

- Wire-iOS/Resources/Base.lproj/Localizable.strings
http://brand.wire.com/text/writing-style/#politeness
> Remove “Please” from unlock copy per style guidelines

- Wire-iOS/Sources/UserInterface/Collections/TextSearch/TextSearchViewController.swift
* Do not show no results until results have been received
> Do not show no results until results have been received

- Wire-iOS/Sources/UserInterface/Conversation/ArchivedListViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ArchivedListViewModel.swift
- Temporary measure to limit the crash rate
- Should not break any functionality
> Do not animate the archive update

- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
* Only fallback to underlying user if current one does not have a handle.
> Only fallback to underlying user if current one does not have a handle

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Update lock copy to clarify the grace period of it.
> Update app lock copy and setting

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
Inspired by @anatoli26
Thanks @Yorgos-V and @markesaaremets 
https://github.com/wireapp/wire-ios/issues/756
> Unread status dot to the back button

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
* Only make links in tweet tappable in link previews.
> Only make links in tweet tappable in link previews

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PinchZoom.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PinchZoom.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Adds support to look on the images in detail.
> Pinch to zoom in conversation

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
* Single image view controller was dismissed when copying an image.
> Do not dismiss view controller when copying from single image view

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter+ConversationImages.swift
> Restored double tap to like for images in conversation

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PinchZoom.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Fixed crash
- Added the dimming view
- Possible to move the image
> Improve pinch zoom animation

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/FingerprintTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Also somewhat modernized the early swift code
> Added accesibility identifiers to the device detail screen

- Wire-iOS/Sources/Components/Youtube/MediaPreviewViewController.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserBarView.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserBarView.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.m
* Fix top alignment in BrowserViewController when shown with statusbar.
> Fix top alignment in BrowserViewController when shown with statusbar

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/PingCell.m
- Looks better with current user names design
> Natural case ping

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+PullToDismiss.m
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.h
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PinchZoom.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter+ConversationImages.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
- Issue happened mostly because of the changes for styling the controllers before showing them. This changed the loading sequence of the views of the controllers.
- Other issue happened because of the screenshot view was shared between several fullscreen image views.
- Also removed some sketchy force unwraps.
> Fixed pull to dismiss

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Added 2 buttons: sketch and sketch with emoji
> Allow sketching on image from single image view

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift
- Also removed unnecessary `translatesAutoresizingMaskIntoConstraints` :hurtrealbad:
> Add missing accessibility IDs

- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/TopPeopleCell.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/TopPeopleLine/CollectionViewContainerCell.m
* Add accessibility identifiers and labels to top people start UI section.
> Add accessibility identifiers to top people

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell+Like.swift
- Method is called from ObjC, the parameter can be nil.
> Fixed potential crash with liked message

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
… localized resources by http://bob-ci-iosx.local:8081/job/download_crowdin_ios/190/
> Localization for release 2.32

- Wire-iOS/Resources/Base.lproj/Localizable.strings
We didn't have any translations for this, maybe @infotexture could take a look at this?
> Another call in progress: added base translation

- avs-versions
> Revert "Update avs-versions"

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter.h
- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
- Apparently it was always there.
> Fixed retain cycle in conversation content view controller

- Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
- The gesture recognizer is enabled now
> Allow swipe to dismiss collections

- Wire-iOS/Sources/UserInterface/Components/Controllers/ActionSheetController/ActionSheetContainerView.m
- Wire-iOS/Sources/UserInterface/Settings/SettingsNavigationController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsStyleNavigationController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileClientViewController.swift
- Positioning of the elements
- Fonts fixed
> Fixed remaining nav bar visual issues

- Wire-iOS/Sources/AppController.m
- Wire-iOS/Sources/Managers/ColorSchemeController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/Message+Formatting.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/Message+Formatting.m
- Fixed to work realtime without app kill
> Fix for dynamic type and dark theme setting

- Scripts/embedBuildInfo
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Settings/VersionInfoViewController.m
- Also removed the leftovers from the buildcontrol
> Display correct avs component version

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/AppController.m
- Wire-iOS/Sources/UserInterface/Components/Views/TestView.swift
- Allows to show arbitrary view fullscreen.
- Could be useful when you develop the view that is hard to show otherwise and for iOS development beginners @markesaaremets .
> Small UI testing framework for beginners

- Wire-iOS Tests/ConversationAvatarViewTests.swift
- Wire-iOS Tests/RandomGeneratorFromDataTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Components/Views/ConversationAvatarView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.h
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
- Unsafe data pointers also unsafe in Swift: it does not check the memory bounds, therefore the rubbish data was added to the random output.
- Also renamed `ConversationAvatarView` and moved to common controls.
> Fixed stable random, added tests

- Wire-iOS/Sources/UserInterface/ConversationList/Space.swift
- Wire-iOS/Sources/UserInterface/ConversationList/SpaceSelectorView.swift
- "Family" space.
- Selection logic, tap when all spaces are selected on selected one dims others.
> Added 3rd space and selection logic

- Wire-iOS Tests/ConversationStatusLineTests.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
- Show "You left / You removed status".
- Do not loose the status when intermediate system messages are present.
> Fixes for status string

- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangePhoneViewController.swift
- WireExtensionComponents/Utilities/ExtensionSettings.swift
* Fix a couple of remaining Xcode 8.3 warnings..
> Fix a couple of remaining warnings

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
* Fix the 3D-Touch selection animation rect.
> Fix 3d touch peek animation selection rect

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.h
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
> Fixed list dynamic type observation

- Wire-iOS Tests/ConversationStatusTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
- WireExtensionComponents/Utilities/IteratorProtocol+Histogram.swift
> Fixed unread rename (and others) bumping badge count

- Wire-iOS Tests/ConversationStatusLineTests.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
> "Started a conversation" status

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppController.m
- WireExtensionComponents/Utilities/DeveloperMenuState+Debugging.swift
- WireExtensionComponents/Utilities/DeveloperMenuState.h
- WireExtensionComponents/Utilities/DeveloperMenuState.m
We want to force internal users to enable the right logs for debug reports
> Enable some logs by default when on internal

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+TopBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel+Spaces.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/Model/ConversationListViewModel.m
- Wire-iOS/Sources/UserInterface/ConversationList/Space.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Unify shared `SettingsPropertyFactory` 🤕
> Add option to set the space name

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+TopBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- WireExtensionComponents/Views/OverflowSeparatorView.swift
- Consequence of the spaces introduction.
- Also some renaming / refactoring included.
> Correctly animate conversation list top line when spaces disabled

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/CallCells.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationRenamedCell.swift
- WireExtensionComponents/Utilities/AttributedStringOperators.swift
- Changed the way the cell is localized for cases:
- You vs someone called.
- You vs someone renamed the conversation.
> You called vs someone called in German (and others)

- Wire-iOS/Sources/UserInterface/MessageComposeViewController.swift
* Fix message text view insets.
> Fix message text view insets

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Conversation/ConversationListBottomBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ComposeEntryViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/DraftListViewController.swift
- Wire-iOS/Sources/UserInterface/DraftMessageCell.swift
- Wire-iOS/Sources/UserInterface/MessageComposeViewController.swift
- Wire-iOS/Sources/UserInterface/UIAlertController+DraftDeletion.swift
* Adds the first changes requested by design.
* The custom view controller transition for the 2 buttons grew quite big but is very easy to fine tune that way. However we can think of using Cartography constraint groups instead of having arrays for the different states.
> Drafts design review

- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Added accessibility labels
- Added open self image change from click
- Fixed badge visual
- Fixed showing full name
> Self profile review

- Wire-iOS/Sources/UserInterface/ConversationList/ComposeEntryViewController.swift
* Add  more type information to the `createConstrains` method (saves us two seconds).
> Add type information

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
* Enable drafts UI for all builds.
> Enable drafts UI for all builds

- Wire-iOS/Sources/UserInterface/MessageComposeViewController.swift
* It shouldn't be possible to send whitespace only message drafts.
> Strip leading whitespace from draft messages

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/DraftListViewController.swift
- Wire-iOS/Sources/UserInterface/MessageComposeViewController.swift
* Small drafts UI and copy changes.
> Change fonts, update copy and always dismiss compose view after deletion

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
* This reverts commit 92ed09a2226d3ed492afe705843f0b97110796a0.
> Revert "Enable drafts UI for all builds (#967)"

- Wire-iOS/Sources/Developer/DebugAlert.swift
- Wire-iOS/Sources/Developer/DeveloperOptionsController.swift
- Fixes issue with sending the logs on iPad.
> Present the debug alert on top of the topmost controller

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Resources/Settings.bundle/Root.plist
- Wire-iOS/Resources/Settings.bundle/en.lproj/Root.strings
- Removed the edge environment since it's not supported any more.
> Retire edge backend

- Wire-iOS/Sources/AppController.m
- Wire-iOS/Sources/Managers/FileBackupExcluder.swift
* Exclude Library directory in shared container from backup.
> Exclude Library directory in shared container from backup

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
* Animate tooltip away before showing compose / start UI screens.
> Animate tooltip away before showing compose / start UI screens

- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- It was possible to delete the not completely sent image from the full screen view toolbar.
- This can mess up the SE logic.
> Forbid deletion of unsent image

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/DraftsRootViewController.swift
- WireExtensionComponents/Controllers/ShareViewController+Views.swift
* Pin `ShareViewController ` send bar to keyboard.
* Adjust return key type.
> Pin share view controller send bar to keyboard

- WireExtensionComponents/Controllers/ShareViewController+Views.swift
* Move ShareViewController send button to the right.
> Move ShareViewController send button to the right

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPhoneFlowViewController.m
- In case it is already shown.
> Do not re-show add email screen

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/DraftSendInputAccessoryView.swift
- Wire-iOS/Sources/UserInterface/DraftsRootViewController.swift
- Wire-iOS/Sources/UserInterface/MessageComposeViewController.swift
- WireExtensionComponents/Controllers/ShareViewController.swift
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
* Add new back button with number of stored drafts (excluding the current one).
* Fix tooltip being shown on each start.
* Inject `showPreview` flag into `ShareViewController`.
> Drafts adjustments and fixes

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.m
- Looking better on crowded screen.
> Increase conversation list cells height to 64 points

- Wire-iOS/Sources/UserInterface/ConversationList/Space.swift
- Wire-iOS/Sources/UserInterface/ConversationList/SpaceSelectorView.swift
- Mocking the designed teams behaviour.
> Make fake teams exclusively selected

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
In iOS 8 creating the OpenGL context while the app is in the background will result in a crash:
https://wearezeta.atlassian.net/browse/ZIOS-8565
This PR works around that by delaying the creation until the application becomes active.
> Don't create video views while in the app is not active

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
https://wearezeta.atlassian.net/browse/ZIOS-8598
> Fix video preview showing up in audio calls

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
Creating video preview view will implicitly ask for video permissions.
https://wearezeta.atlassian.net/browse/ZIOS-8599
> Don't create video preview view unless it's a video call

- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
> Use new sketch colors

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.swift
- Wire-iOS/Sources/UserInterface/Participants/ParticipantsListCell.h
- Wire-iOS/Sources/UserInterface/Participants/ParticipantsListCell.m
- Wire-iOS/Sources/UserInterface/Participants/ParticipantsViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
- Check permissions for adding participants.
- Check permissions for removing participants.
- Added guest label for participants list.
> Add checking permissions, add guest label

- Wire-iOS/Sources/Analytics/Events/Analytics+SearchEvents.h
- Wire-iOS/Sources/Analytics/Events/Analytics+SearchEvents.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
tracking for team search is excluded from the pilot.
> Restore old analytics tracking

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/TeamView.swift
- Wire-iOS/Sources/UserInterface/Participants/ParticipantsListCell.m
- Label is localized.
- Action is clarified.
- One element instead of the set of elements visible for accessibility.
> Added proper accessibility labels

- Wire-iOS/Sources/UserInterface/Components/Views/ConversationAvatarView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
- Hiding the unnecessary views is significantly more performant than removing / adding due to autolayout.
- `regularStyle` and `emphasisStyle` to use cached values.
> Improved performance on conversation list avatars

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/TeamView.swift
- Indicate current state and action performed better.
> Updated teams accessibility to indicate the state

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.h
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.h
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Select correct team when trying to open conversation.
> Auto-select team when opening conversation

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/ConversationList/NewDevicesDot.swift
- Wire-iOS/Sources/UserInterface/ConversationList/TeamView.swift
- Also observe the accent color changes for the selection.
> Use layers for new message dot rendering

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ParticipantsPopover.m
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Participants/ParticipantsViewController.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchSectionHeaderView.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchSectionHeaderView.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/UsersInContacts/UsersInContactsSection.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/UsersInContacts/UsersInContactsSection.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.h
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.h
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/Views/UserNameDetailView.swift
- WireExtensionComponents/Utilities/ColorScheme.h
- WireExtensionComponents/Utilities/ColorScheme.m
https://wearezeta.atlassian.net/browse/ZIOS-8583
> Add AddParticipantsViewController which support adding team members to conversations

- Wire-iOS/Sources/Helpers/syncengine/ZMUser+Additions.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
Unconnected team members should behave the same way as connected team members.
> Show correct controls & device list for team members

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCell/ParticipantsCellViewModel.swift
German cases for creating conversations / adding / removing members where gramatically wrong.
> fix cases in conversation system message

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
https://wearezeta.atlassian.net/browse/ZIOS-8661
> Add extra case for when everyone has been added to conversation

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
Remove redundancy between section title & option
> Add separate string for analytics option

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- WireExtensionComponents/Utilities/ColorScheme.m
Tweaked padding, colors and added clear button to search field
> StartUI: design tweaks

- Podfile
- Podfile.lock
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/Analytics/AnalyticsBase.m
- Wire-iOS/Sources/Analytics/Events/AnalyticsEvent.m
Maybe one day we can fully move to Carthage...
> Removed unused dependencies

- avs-versions
Fixes ringing_from_me dosnt stop when the call is cancelled.
> Bump avs to 3.5.32

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
- Handle label is moved above the user image.
> Show team name in self profile

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Components/Views/RoundedBadge.swift
- Wire-iOS/Sources/UserInterface/Participants/ParticipantsListCell.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
The team members section should contain the contacts of user, labeled as guests.
> Joined contacts and team members in start UI

- Wire-iOS/Sources/UserInterface/Components/Views/RoundedBadge.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
- circle.yml
- Updated looks of guest label.
- Updated self profile layout.
> Teams beta design review

- Wire-iOS/Sources/AppDelegate+ErrorTracking.swift
* Only track context type, error code and domain.
> Only track context type, error code and domain

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
Add join call button to conversation navigation bar if there is an ongoing call:
> Add join call button to conversation navigation bar if there is an ongoing call

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
In some situation it’s not possible to find which conversations are causing the badge count to be non-zero, even if they all look read. This option in the debug menu will allow to identify which one is the offending conversation. Hopefully this will allow us to understand the pattern of this issue.
> Add debug button to identify unread conversations

- Wire-iOS/Sources/Components/AudioPlayer/AudioPlaylistViewController.m
- Wire-iOS/Sources/Components/AudioPlayer/AudioTrackViewController.m
- Wire-iOS/Sources/Components/Youtube/MediaPreviewViewController.m
- Wire-iOS/Sources/UserInterface/Components/MediaPreview/MediaPreviewView.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/LinkAttachmentPresenter.h
* Fix long press on old-style media attachments.
> Fix long press on old-style media attachments

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
* Small join button layout adjustments.
> Adjust join call button layout

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Change conversation background colour to grey (see screenshot)
> design fix: turn conversation background grey

- Wire-iOS/Sources/UserInterface/Registration/RegistrationEmailFlowViewController.m
If registration fails we should go back to the registration form so you can edit your details and try again.
https://wearezeta.atlassian.net/browse/ZIOS-8821
> Go back to registration form if registration fails

- Wire-iOS/Sources/AppController.m
After we re-organized the new CD-free registration some calling-related issues started to happen.
1. No CallKit overlay for incoming call.
2. No in-app UI for the call.
3. Client is crashing when we try to initiate the call.
The issues where happening due to the inconsistency in the order of the operations: we first need to set use call kit flag before initializing the SE first time. Also the notification window controller was not yet created when we asked it to load the calling and other logged in UI -- see RootViewController.m:155 (in this case Swift would save us).
> 3-in-1: Fixed calling crash, fixed call overlays not appearing

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/CollectionViewSectionAggregator.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/CollectionViewSectionAggregator.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- WireExtensionComponents/Utilities/ColorScheme.m
• Search field on the Add People screen: since the field has a white opacity, it is not visible on the white mode. 
• Search field bottom margins when you scroll on the Start UI list.
> Design fixes/add people screen

- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
- Devices badge white on the Profile screen
> design fixes/devices badge

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
- top separatornot showing on start UI
> Design Fix/ StartUI

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
* Adjust join button visuals (for @markesaaremets).
> Adjust join button visuals

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
> Fix team member and contacts section title

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/UIAlertController+DraftDeletion.swift
- space between title label and search bar in StartUI increased
> Design tweaks

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Components/Settings.h
- Wire-iOS/Sources/Components/Settings.m
- Wire-iOS/Sources/Components/Settings/SettingsProperty.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.m
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- link preview setting to disable previews for links you send
> add option to turn off generating link previews

- avs-versions
Fix for https://wearezeta.atlassian.net/browse/ZIOS-8788
> Bump AVS to 3.5.40. 

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- move 'by popular demand' section to bottom in the 'options' setting group
> design fix: settings

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Get back to original buttons layout for 2.41
> Temporary remove create team button

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Reverts wireapp/wire-ios#1175
Also moves devices section into the settings.
> Add back the create team button

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/AppStateController.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- New AppRootViewController updated to host itself in the window correctly.
> Fix shifted UI

- Wire-iOS/Sources/AppStateController.swift
- Initially the app is in the inactive state, so the UI is not getting loaded.
> Observe applicationDidFinishLaunching to update state

- Wire-iOS/Sources/Helpers/syncengine/SessionManager+Shared.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
> Allow max 3 accounts

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+TopBar.swift
- User image was off from the left inset.
> Fix the layout of the current account button

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Remove question mark from title & align copy with previous implementation.
> Revise logout confirmation copy

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/AccountView.swift
- Wire-iOS/Sources/UserInterface/SkeletonViewController.swift
NOTE: this currently showing the picture of the account you were switching from, I'll fix this in a separate PR since we need to change the SE API.
> Show a skeleton of the app when while switching accounts

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/Settings/AppLock.swift
- Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory.swift
- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
Fixing the potential app lock issue.
> App lock: use keychain directly

- Wire-iOS/Sources/UserInterface/SelfProfile/AccountView.swift
The old picture was still showing after change
> Updating avatar view profile picture after change

- Wire-iOS Tests/VoiceChannelOverlayTests.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Components/Settings.m
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlayController.m
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- It is not working properly with the current AVS.
> Temporarily disable CBR

- Wire-iOS/Sources/UserInterface/StartUI/Common/ProfilePresenter.m
https://wearezeta.atlassian.net/browse/ZIOS-9018
> Dismiss start UI before navigating to conversation

- Wire-iOS/Sources/UserInterface/ConnectRequests/ConnectRequestsViewController.m
Write the else case for if (self.connectionRequests.count != 0) in ConversationListViewModel.m
> [bugfix]  iOSZIOS-9012 Connection request screen disappears & reveals empty table view

- Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Calling.swift
- Wire-iOS/Sources/UserInterface/ContactsUI/ZMAddressBookContact+LocalInvitation.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationIgnoredDeviceCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationNewDeviceCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MissingMessagesCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+Handles.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.h
- Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorView.swift
It was trying to access ZMClientViewController which was not there yet. Added nullability annotations for it and update the code in all places.
> Fix: audio message tests crashing

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelParticipantCell.swift
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelParticipantsController.swift
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift
- Negative call duration
- Group call participant list not shown
> Fixes for calling regressions

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/InviteContacts/InviteContactsViewController.m
fix ConversationListViewController alpha = 0 issue.
check self.presentedViewController != nil before dismiss.
> [bugfix]ZIOS-9051-Opening-conversation-from-Contacts-UI-lead-to-an-empty-screen(Xcode9)

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
audio recorder stop recording when system interruption began
> bugfix: add observer for .AVAudioSessionInterruption and stop recording if intertuption began

- Wire-iOS/Sources/Managers/SoundEventListener.swift
Receiving a call in the background shows the media controls while playing the ringtone
Don't play sounds while in the background. Ringtone will be played via the configured sound for the push notification / Callkit
> Only allow sounds to be played while app is active

- Podfile
- Podfile.lock
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
> Revert "Fix/zios 9069 xcode9 fix issues with  method called on background thread messages"

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
> Revert "Disable analytics switch"

- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelViewController.swift
https://wearezeta.atlassian.net/browse/ZIOS-6095
> Call duration timer wasn't started for an already ongoing call

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
Tested with iPhone 6 (iOS 11), iPhone 6 (iOS 10) and iPhone X.
> Fixed layout issues with lateral margins on Search Results

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
Issue related to https://github.com/wireapp/wire-ios/pull/1371
> Fixed margins to the bottom button in Add Participants view controller

- Wire-iOS/Sources/UserInterface/Registration/RegistrationRootViewController.m
Previously we were only showing the X if the selected account was authenticated.
https://wearezeta.atlassian.net/browse/ZIOS-9115
> Show X on login screen if you have any authenticated account

- Wire-iOS/Resources/Base.lproj/InfoPlist.strings
- Wire-iOS/Wire-Info.plist
Also one of the permissions text string was not present in the file.
> Added permission for writing to photo library

- Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+iOS.h
- Wire-iOS/Sources/Helpers/syncengine/ZMUserSession+iOS.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- 50 MB in team, 25 MB for the regular user
> Increase the file size limit in teams

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
> Forbid adding phone number in team

- Wire-iOS/Resources/Base.lproj/InfoPlist.strings
- Wire-iOS/Wire-Info.plist
> Allow requesting the Face ID permissions

- Wire-iOS/Sources/Analytics/TrackingManager.swift
- WireExtensionComponents/Utilities/ExtensionSettings.swift
- Cleaned up some optionals and let vs var
> Cleanup the code for Mixpanel integration

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
> Display mixpanel distinct id for debug builds

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
This setting was temporarily disabled until some technical issues with CBR was solved.
> Enable CBR setting again

- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
The close button is hard to click from the first attempt.
Increase the size and the tap area of the button.
> Improved the touch area of close button in full screen image view

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/CharacterInputField.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Helpers/CAAnimation+Cursor.swift
Instead of copy-pasting the cursor blinking animation, we have now the reusable code for it.
> Unified the cursor animation code

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/Analytics/AnalyticsTracker.m
- Wire-iOS/Sources/Analytics/Events/Analytics+Settings.swift
- Wire-iOS/Sources/Analytics/Registration/AnalyticsTracker+Registration.h
- Wire-iOS/Sources/Analytics/Registration/AnalyticsTracker+Registration.m
- Wire-iOS/Sources/Analytics/Registration/AnalyticsTracker+Registration.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationEmailFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationPhoneFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
New events are tracking the appearance of the landing screen and the actions that can be taken on it.
> Added tracking for the landing screen

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+TOS.swift
Simple alert that checks if user would like to use the service and agree to the TOS. It's based on `UIAlertController`.
> Added TOS alert

- avs-versions
> Update AVS to 3.8.26.

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
Align text field to center when keyboard dismissed.
Minimum height constraints for labels and textfields.
Labels and textfields are misplaced or iPhone 4s and iPad. The UI gadgets align bottom when keyboard dismissed.
Add minimum height constraints for labels and textfields. 
WIP for iPad in split over mode.
> Layout team create flow screen for iPad and small screen iPhone

- Wire-iOS Tests/AccessoryTextField/AccessoryTextFieldValidationTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
imp. traitCollectionDidChange to update textfield's width constraint when size class changes
> Handle the case iPad switching between fullscreen mode and split over mode

- Wire-iOS/Sources/Helpers/NSURL+WireURLs.h
- Wire-iOS/Sources/Helpers/NSURL+WireURLs.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/SetTeamNameStepDescription.swift
- Extracted the URL to the appropriate location.
- Added the locale parameter.
> Use dedicated URL for teams features

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+TOS.swift
- TOS dialogue is presented as an alert message.
- TOS are viewed in safari view controller.
> Request TOS integration

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
The tracking code is already implemented, this PR is only wiring it up.
> Integrated the tracking calls in team creation

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift
set iconButton's adjustsImageWhenDisabled, the arrow is white when the button is disabled.
> fix icon disabled color

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
We were using random accent color and it sometimes doesn't look too good.
Use a different method for picking random color that audits the color to be acceptable.
> Avoid unacceptable accent colors

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift
The last merge overwrite a change for icon size. This PR fixes that.
> redo iconButton icon size update

- .github/issue_template.md
The .gittemplate did have a error.
The checkbox did have wrong markdown syntax. This is fixed now.
The syntax was `[ ] -`. This is not correct.
The syntax should be `* [ ]`.
> Fix the checkbox in the issue template

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/AccessoryTextField.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
Remove unnecessary constraints for confirm button.
> fix broken constraints

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ScreenDescriptions/SetEmailStepDescription.swift
Add the "Enter your work email address." for enter email screen's subtitle.
> add email screen subtitle

- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
remove the repeated  topSpacer, bottomSpacer.
> remove duplicated topSpacer, bottomSpacer in the addsubview list

- Wire-iOS Share Extension/lt.lproj/Localizable.strings
- Wire-iOS Share Extension/zh-Hant.lproj/Localizable.strings
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/lt.lproj/InfoPlist.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.stringsdict
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/InfoPlist.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.stringsdict
Adding Traditional Chinese and Lithuanian localization
> Add zh-Hant and lt translations

- Wire-iOS Share Extension/it.lproj/Localizable.strings
- Wire-iOS Share Extension/tr.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/InfoPlist.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.stringsdict
New localized strings for the languages. Missing status localization for German langauge.
> Localization for Wire iOS 3.4 (WIP)

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamInviteTextFieldFooterView.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Team Invites/TeamMemberInviteViewController.swift
* Show error in case there is no internet connection.
> Show error in case there is no internet connection

- Wire-iOS/Sources/Developer/DebugAlert.swift
As we allow sending logs without being logged in now we can no longer assume a self user will be present.
> Remove force unwrapping of selfUser

- Wire-iOS/Sources/Helpers/NSURL+WireURLs.h
- Wire-iOS/Sources/Helpers/NSURL+WireURLs.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/UIAlertController+TOS.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
* Use correct TOS link for team accounts.
> Use correct TOS link for team accounts

- Wire-iOS/Sources/Developer/DebugAlert.swift
* Disallow presenting a debug alert while another one is already shown.
> Do not stack debug alerts

- Wire-iOS Share Extension/es.lproj/Localizable.strings
- Wire-iOS Share Extension/lt.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/InfoPlist.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.stringsdict
Update localization from Crowdin
> Update localization from Crowdin

- Wire-iOS/Sources/Managers/SoundEventListener.swift
* Change feedback style from medium to light for messages except pings.
> Change feedback style from medium to light for messages except pings

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
> Services: Fixed background color of the top bar in the startUI

- Wire-iOS/Sources/Components/ShareViewController/ShareDestinationCell.swift
- Wire-iOS/Sources/Components/ShareViewController/ShareServiceViewController.swift
- Wire-iOS/Sources/Components/ShareViewController/ShareViewController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceView.swift
- Removed the unnecessary check-marks from share controller.
- Fixed bot detailed description view.
> Bots design review leftovers

- Wire-iOS/Sources/Components/ShareViewController/ShareServiceViewController.swift
- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.m
Those IDs are necessary for the automation. Missing IDs are for the following screens:
1. Service detail page.
2. Add service screen.
3. Participants list.
> Added missing accessibility IDs

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
* Add service events to enabled tracking events in 28f69f4.
* Declutter ServiceViewController adding services logic a bit in 0406839.
> Add service events to enabled tracking events

- Cartfile
- Cartfile.resolved
- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphyConfirmationViewController.swift
- Wire-iOS/Sources/UserInterface/Components/UINavigationBarContainer.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCellBurstTimestampView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/AudioMessageView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/IconSystemCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationRootViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordKeyboardViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecordViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/Emoji/EmojiSectionViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
- Wire-iOS/Sources/UserInterface/Location/LocationSendViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/VoiceChannelOverlay.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationStepController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingButton.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorView.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileHeaderView.swift
- WireExtensionComponents/Views/TabBar/TabBar.swift
Cartography 3 offers quite some nice updates, most and foremost is the possibility of creating constraints not only between views but also with layout guides. This allows constrainting to safe areas of view controllers.
> Cartography 3

- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/ViewDescriptions/BackButtonDescription.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/InviteTeamMemberCell.swift
Identifiers as agreed with QA. Some existing labels where not visible, so magic with UIAccessibility was necessary.
Also added accessibility labels for actual accessibility.
> Accessibility labels / IDs for conversation name and start UI

- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.h
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/ServicesSection.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/SectionControllers/UsersInContacts/UsersInContactsSection.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.h
- WireExtensionComponents/Icons/Autogenerated/WireStyleKit.m
- WireExtensionComponents/Icons/ZetaIconTypes.h
* Fix conversation being created when cancelling
* Add disclosure indicator to service conversations
* Fix selected people not becoming tokens in the search field
> Fix conversation being created when cancelling

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.h
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.h
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
* Show new linear conversation flow from profile details screen.
> Show new linear conversation flow from profile details screen

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/SimpleTextField.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+SafeArea.swift
- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/InviteTeamMemberCell.swift
Fixed all sorts of inset/font/color issues. Also fixed logic for enabling the NEXT button.
> Visual fixes for linear create conversation flow

- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
iPad support: on iPad the linear conversation creation flow should be presented as the form sheet. Dismiss should happen with the X button.
> Update linear conversation creation flow for iPad

- Wire-iOS/Sources/UserInterface/StartUI/Common/Cells/SearchResultCell.m
- Subtitle for non-connected user should include the handle now.
- Accessibility label for guest.
- Colors on dark mode for the checkmark.
> SearchResultCell: Fixed several issues

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+LinearGroupCreation.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
New events added:
1. User opens linear conversation flow.
2. Finished selecting the name.
3. Conversation is created.
> Added tracking for the linear conversation creation flow

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewModel.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
* Trimm whitespace from conversation name.
* Fix skip/done button font weight in `AddParticipantsController`.
> Trimm whitespace from conversation name

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Availability/AvailabilityTitleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
- WireExtensionComponents/Utilities/ColorScheme.h
- WireExtensionComponents/Utilities/ColorScheme.m
- Fixed navigation bar color in the name selection screen.
- Fixed title color in the select participants screen.
- Fixed accessibility label in Availability.
- Fixed the bar color in participants screen.
- Fixed separator color.
> Linear conv creation flow: fixed color of bars

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
Added Accessibility ID to DestructionCountdownView for automation test purposes.
> ZIOS-9512: Added Accessibility ID to DestructionCountdownView

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
* Fix top people not opening the associated 1-1 conversation anymore.
> Fix top people not opening conversation 

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarSendController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Files.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
* Add haptic feedback to all message types.
> Add haptic feedback to all message types

- Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
The font in the navigation bar is too small.
> Increased font in the settings navigation bar

- Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
* Fix default status bar style for clear background navigation controller.
> Fix default status bar style for clear background navigation controller

- WireExtensionComponents/Icons/ZetaIconTypes.h
> ZIOS-9648: Changed settings account icon

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Per https://github.com/wireapp/wire-desktop/issues/1278
> Adjust confirmation copy for clearing history

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/UILabel+Convenience.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ToggleView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+StartUI.m
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController.h
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
* Add allow guests toggle to group creation flow.
> Add allow guests toggle to group creation flow

- Wire-iOS/Sources/UserInterface/Components/Views/GuestIndicator.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ToggleSubtitleCell.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/UINavigationController+CloseButton.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsGuestOptionsCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsParticipantCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
Add accessibility identifiers for new screens
> Add accessibility identifiers for new screens

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/Services/ServiceDetailViewController.swift
* Fix rotation issues in new participants section (disable landscape).
> Fix rotation issues in new participants section

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsRenameCell.swift
Use keyboard appearance matching the selected color theme
> Use keyboard appearance matching color theme

- .circleci/config.yml
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
We have not tracked test coverage on UI project for some reasons that are now forgotten.
The changes needed to enable it are inside shared resources branch. This PR will not be merged, but is needed to test if everything works as expected on CI.
> Enable test coverage

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation Options/CellConfiguration.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewModel.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ToggleSubtitleCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/ActionSheetController+Conversation.h
- Wire-iOS/Sources/UserInterface/Conversation/ActionSheetController+Conversation.m
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/AlertResultConfiguration.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/UIAlertController+RemoveAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsFooterView.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+removeUserConfirmationUI.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileFooterView.m
* Use standard components for remove participant sheet.
* Add accessibility identifiers.
> Add accessibility identifiers, adjust remove participant confirmation sheet

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/GroupDetailsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/GuestOptionsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/RenameGroupSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/SectionCollectionViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ServicesSectionController.swift
Split up the GroupDetailsViewController into multiple files
> Split up the GroupDetailsViewController into multiple files

- Wire-iOS/Sources/UserInterface/Helpers/UIVIewController+Navigation.swift
- Wire-iOS/Sources/UserInterface/UserProfile/Views/ProfileFooterView.m
Add accessiblity label for back button and improve naming of profile buttons identifiers
> Automation fixes

- Wire-iOS Tests/ConversationStatusLineTests.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
* Show `XYZ joined` as status when wireless user joins.
> Show `XYZ joined` as status when wireless user joins

- Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsParticipantCell.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ServicesSectionController.swift
Adjust automation identifiers as requested
> Adjust automation identifiers as requested

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/GuestsBarController.swift
- Updated the animation.
- Show per default the bar when user opens the conversation.
> Update guests bar animation, show per default

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.m
- Wire-iOS/Sources/Analytics/Events/Analytics+ConversationEvents.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+Guests.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+LinearGroupCreation.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/Conversation+OptionsConfiguration.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
When users have enabled tracking we would like to gather information for product improvement purposes
> Added tracking for guests in conversations

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/InitialSyncObserver.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/GuestOptionsSectionController.swift
* Disable guest options cell until initial sync completed.
> Disable guest options cell until initial sync completed

- Wire-iOS/Sources/UserInterface/Helpers/UIViewController+SafeArea.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/NagScreen/AddEmailStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/EmailVerificationStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NameStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/PhoneVerificationStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/ProfilePictureStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController.m
Added iPhone X safe area margins to view controllers in the registration flow.
> Added safe area margins in signup screens

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/DatabaseStatisticsController.swift
We need to know more about the size of the database and various other statistics.
Added another screen in developer options that show some numbers about the local database:
> Added developer option to see statistics about local database

- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/Analytics/Events/Analytics+Guests.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewModel.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/StartUIViewController+SearchResults.swift
* Add tracking for guest room link actions.
> Add tracking for guest room link actions

- Wire-iOS Tests/WirelessExpirationTimeFormatterTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/Helpers/syncengine/ZMUser+ExpirationTimeFormatting.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
* Add expiration label to wireless users profile screen.
>  Add expiration label to wireless users profile screen

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/TintCorrectedActivityController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.m
* Fix share controller tint.
* Remove empty screen for group details.
> Fix share controller tint, remove empty screen for group details

- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.m
Profile screen should follow the current color scheme.
> Fix color of the status bar on the profile screen

- Wire-iOS/Sources/UserInterface/Components/Views/UserCell.swift
* Use correct use image avatar size for `UserCell`.
> Fix user cell avatar size

- Wire-iOS/Sources/UserInterface/Conversation/Create/ToggleView.swift
The toggle in the group creation flow was white in dark mode
Colors are hard coded
Implement the Themeable protocol for the `ToggleView`
> Make ToggleView themeable

- Wire-iOS/Wire-Info.plist
The iTunes connect suggested us adding the following keys to speed up the submit process.
> Apple export compliance code

- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+Delete.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
* Don't show delete and leave option for one-to-one conversations.
> Don't show delete and leave option for one-to-one conversations

- Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
- Wire-iOS/Sources/UserInterface/Sketchpad/CanvasViewController.swift
- Wire-iOS/Sources/UserInterface/Sketchpad/SketchToolbar.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsView.swift
Two issues were reported about iPhone X support:
- The sketch toolbar didn't extend to the bottom of the screen
- The button to add participants to the conversation covered the list
- The sketch toolbar extends to the bottom of the screen
- The button to add participants floats above the screen on iPhone X, and the collection view goes to the bottom of the screen.
> ZIOS-9769: Fix visual bugs on iPhone X

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/Analytics/AnalyticsMixpanelProvider.swift
- Wire-iOS/Sources/Analytics/Registration/AnalyticsTracker+Registration.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/Flow/TeamCreationFlowController.swift
> Added tracking of the added_team_name property

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Registration/NavigationController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/CountryCode/CountryCodeBaseTableViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/EmailFormViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/PhoneNumberViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationEmailFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationPhoneFlowViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationTextField.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/EmailSignInViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/PhoneSignInViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/SignInViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/EmailStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/PhoneNumberStepViewController.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/PhoneNumberStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/PhoneVerificationStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/TermsOfUseStepViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingButton.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
- WireExtensionComponents/Views/TabBar/TabBar.swift
- WireExtensionComponents/Views/TabBar/TabBarController.swift
Logging into the app cannot be performed with VoiceOver. 
We ensure that accessibility labels and traits are set and localized correctly. We also make sure that all data is accessible and understandable for users of assistive technologies (images, transitions)...
> ZIOS-8754: Support VoiceOver in login flow

- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+Delete.swift
* Fix inverted delete and leave options logic.
> Fix inverted delete and leave options logic

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/UIAlertController+NewSelfClients.m
> **You have connected 2 devices to your Wire account**
> Simulator
> 5 minutes ago, Simulator
> just now
>
> If you didn’t do this, remove those devices and reset your password.
> **Your account was used on:**
>
> Simulator
> 5 minutes ago
> 
> Simulator
> just now
>
> If you don’t recognize the devices above, remove them and reset your password.
> ZIOS-7529: Update new device modal copy

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Helpers/UIView+Constraints.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Basic screen that gives the possibility to save the back up for the user.
> Back up UI

- Wire-iOS/Sources/UserInterface/Registration/NavigationController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Removed the chevron from the "New team or account" button in Settings
- Increased size and fixed highlight color of cancel button on the landing page
> ZIOS-9808: Fix landing page visual bugs

- Cartfile
- Wire-iOS.xcodeproj/project.pbxproj
* Remove ZipArchive dependency (moved to sync-engine).
> Remove ZipArchive dependency (moved to sync-engine)

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NoHistoryViewController.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NoHistoryViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/NoHistoryViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupViewController.swift
- WireExtensionComponents/Views/CheckAnimationView.swift
- WireExtensionComponents/Views/Loading/UIViewController+LoadingView.h
- WireExtensionComponents/Views/Loading/UIViewController+LoadingView.m
- Do not show alert when not necessary.
- Erase leftover backups.
> Added checkmark view, other fixes

- Wire-iOS/Resources/Classy/stylesheet.cas
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileDetailsViewController.m
- Use content background color in user profile view (+ white header)
- Remove fade animation when changing the tab
> ZIOS-9812: Update design of profile view

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/AuthenticationType.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
* Adjust unlock copy depending on device capabilities.
> Adjust unlock copy depending on device capabilities

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/AssetLibrary.swift
Previously, when taking a screenshot, or deleting a picture when the app was in split view with Photos.app, the changes would not appear on the camera keyboard.
The users were theoretically still able to pick deleted images, and could not pick the screenshot.
We make the `AssetLibrary` listen to changes from the photo library, and call the `assetLibraryDidChange(_:)` delegate method to reload the collection view in the camera picker.
> ZIOS-9423: Observe library changes in camera keyboard

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Requested by the automation not to show the push disabled alert.
> Do not show the push alert if guided by the automation

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/Steps/UIAlertController+RestorePassword.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupPasswordViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupViewController.swift
* Fix backup password controller appearance and presentation.
> Fix backup password controller appearance and presentation

- Wire-iOS Share Extension/fr.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/InfoPlist.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Updated "de|it|ja|pt-BR|es-ES|ru|uk|tr|nl|da|fr|zh-CN|sl|ar|et|fi|pl|zh-TW|lt" localized resources
> Updated translations

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController+Delete.swift
* Tweak conversation options style, order and copy 
* Don't show "Delete and Leave" option if self is not a member of the group.
> Tweak conversation options style

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/TintCorrectedActivityController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationPreviewViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/MessagePresenter.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Previews/LocationPreviewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/TintColorCorrectedViewController.swift
* Extract tint color correction logic.
* Fix preview view controller tint colors.
> Extract tint color correction logic

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Collections/ConversationImagesViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageDeletion.swift
* Fix delete preview item color and copy.
* Fix message deletion confirmation options color.
> Fix delete preview item color and copy

- Wire-iOS/Sources/UserInterface/Conversation/Content/Previews/LocationPreviewController.swift
* Use updated copy for location preview controller.
> Use updated copy for location preview controller

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Overlay/ActiveVoiceChannelViewController.swift
This PR adds another view controller which binds the calling components with the voice channel.
Many things are still missing or not working as intended.
working:
not working
> Working calling UI

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
Added accessibility identifier to the call dismissal button inside the new voice overlay UI.
> Added accessibility identifier to call dismissal button

- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
Status title and subtitle didn't have accessibility identifiers that were there in the old version
> Added accessibility identifiers to calling UI

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Components/Controllers/SectionCollectionViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SectionFooter.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/RenameGroupSectionController.swift
* Add section footer to rename section containing info about group video call limits.
* Add footer to conversation creation flow.
> Add section footer to rename section

- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController.m
Fixed conversation list bottom margin on iPhone X.
> ZIOS-10012: Fixed conversation list bottom margin on iPhone X

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/ThumbnailCornerPinningBehavior.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SectionFooter.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
* Use similar font size as in settings for description footers.
* Tweak floating thumbnail dynamics + size.
> Use similar font size as in settings for description footers

- Wire-iOS Tests/CallInfoConfigurationTests.swift
- Wire-iOS Tests/CallInfoTestFixture.swift
- Wire-iOS Tests/Mocks/MockCallInfoViewControllerInput.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
* Disable idle timer while video calling.
> Disable idle timer while video calling

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsController.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsGenerator.swift
* Add initial call haptic feedback implementation.
> Add initial call haptic feedback implementation

- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsController.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsGenerator.swift
* Adjust impact feedback style, set participants in call haptics controller.
> Adjust impact feedback style

- Wire-iOS Tests/CallHapticsControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsController.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallHapticsGenerator.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/Calling+Logs.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/UIAlertController+OngoingCall.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridView.swift
* Add tests for CallHapticsController.
* Ensure the title in ongoing call action sheet is not bold.
> Add tests for CallHapticsController

- Podfile.lock
- Wire-iOS.xcodeproj/project.pbxproj
Do `gem install cocoapods` in order to update your cocoapods to the most recent one (1.5.3).
> Boostrap with CocoaPods 1.5.3

- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/RenameGroupSectionController.swift
* Calculate footer size correctly to accomodate for dynamic type.
> Calculate footer size correctly to accomodate for dynamic type

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Components/CustomSpacingStackView.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/UINavigationController+CloseButton.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/ProfileView.swift
- Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
The user image view was not visible any more for the automation or accessibility.
Variety of fixes for the self profile screen.
> Fix: automation and accessibility fixes for self profile

- Wire-iOS/Sources/Helpers/syncengine/SessionManager+Shared.swift
- Wire-iOS/Sources/Managers/AddressBookHelper.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+ImagePicker.swift
- Fixed the accessibility ID of the call status view.
- Fixed usage of TARGET_OS_SIMULATOR in Swift.
> Some fixes for automation

- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.h
- Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
Reduce the warnings found by wire-bot
> clean up ZClientViewController.h

- Wire-iOS Tests/CallInfoConfigurationTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/Haptic Feedback/CallParticipantTimestamps.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/Calling+Logs.swift
* Sort call participants list according to participants join call timestamp.
> Sort call participants list according to participants join timestamp

- Wire-iOS Tests/CallViewControllerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
Block is implicitly retaining self. [weak self] to the rescue!
> Fixed CallViewContorller leaks

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
* Use system modal transition to present conversation details.
> Use system modal transition to present conversation details

- Wire-iOS Tests/EphemeralTimeoutFormatterTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/EphemeralTimeoutFormatter.swift
Update EphemeralTimeoutFormatter to support day unit.
> Update remain time display formatter to support days

- Wire-iOS Tests/SavableImageTests.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionImageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/SavableImage.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+SaveImage.swift
* Adjust SavableImage to work with animated GIFs.
> Adjust SavableImage to work with animated GIFs

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Change the text of decline button from "Decline" to "No, thanks".
> Fix: Update decline button text

- Wire-iOS Tests/ConversationInputBarViewControllerTests.swift
- Wire-iOS Tests/GroupDetailsTimeoutOptionsCellTests.swift
- Wire-iOS Tests/Mocks/MockMessage.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/EphemeralKeyboardViewController.swift
Fix the compiler errors after bump components
> Fix: the compiler error after bumping components

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationTimeoutOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
* Present alert controller on timer update request error.
> Present alert controller on timer update request error

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBar.swift
* The textfield size did not update correctly when pasting a large amount of text.
> Adjust input bar constraints

- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationTimeoutOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
User don't have to stay on the timer selection screen after the timer was selected.
> Go back to the conversation details after conv timer selected

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Change was not considered, since the new flag was not checked.
> Set conversation timer: respond to conversation timer update

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/InfoPlist.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Localization 3.16

- Wire-iOS/Sources/Analytics/Events/Analytics+MediaActionEvents.swift
Added the flag to the contributed event.
> Track the synced ephemeral messages

- Wire-iOS Tests/EphemeralTimeoutFormatterTests.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/EphemeralTimeoutFormatter.swift
-  replace month unit with week unit
-  clamp display time > 1 year
-  update tests
> Fix: update time formatter for remain time display

- Wire-iOS/Resources/Base.lproj/Localizable.strings
We have increased group size limit and it should be reflected in the user-facing text.
> Updated translation for group size

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
The group can contain up to 256 participants now. The copy must reflect that change.
> Increased the group size copy

- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBarController.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
* Enable swiping between tab bar view controllers.
> Enable swiping between tab bar view controllers

- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
The toggle is visible for the automation as object without ID, this is happening because the accessibility is flattening the cell to be the toggle. This means that we need to add the id to the cell, too.
> Add accessibility ID to the cell: device verified

- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBarController.swift
* Fix tab-bar controller background color.
> Fix tab-bar controller background color

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
* Assert when registering a negative ephemeral timeout value.
> Assert when registering a negative ephemeral timeout value

- Wire-iOS/Sources/UserInterface/Components/TabBar/Tab.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBarController.swift
* Attempt to fix `TabBar` crash.
* Animate `TabBar` selection indicator line when swiping.
> Attempt to fix TabBar crash, animate tabbar selection line

- Wire-iOS/Sources/UserInterface/ConversationList/ZMConversation+Status.swift
* Show ongoing call indicator for accepted 1-1 calls again.
> Show ongoing call indicator for accepted 1-1 calls again

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Updated "de|it|ja|pt-BR|es-ES|ru|uk|tr|nl|da|fr|zh-CN|sl|ar|et|fi|pl|zh-TW|lt " localized resources

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewController.swift
* Fix the participant details list cells width on iPad.
> Fix the participant details list cells width on iPad

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Align with (planned) implementation on other platforms.
> Change conversation option section title (#2348)

- Wire-iOS/Sources/Managers/SoundEventListener.swift
There are several different call-related system messages:
1. When user participated in the call we append "performedCall" system message with the call duration.
2. When user missed the call we append "missedCall" system message.
For the system message "performedCall" it's not necessary to play the new message sound, since the user is aware of the fact that the call was performed.
Also for "performedCall" we are not altering the conversation state subtitle (this is already working as expected).
> Do not play the system notification sound when ending the call

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
- Wire-iOS/Sources/UserInterface/Company Login/UIAlertController+CompanyLogin.swift
- Wire-iOS/Sources/UserInterface/Registration/SharedIdentity/TimeoutIdentitySessionRequester.swift
* Update SSO copy in multiple places.
* Update SSO error to use new company login naming.
* Show an alert when there is no internet connection when trying to login using SSO.
> Update company login flow copy

- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationRootViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/EmailSignInViewController.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/EmailSignInViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/SignInViewController.h
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/SignInViewController.m
* Move company login button next to forgot password button.
> Move company login button next to forgot password button

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewModel.swift
The participants screen does not update when participants are removed from the conversation.
The view model held a static set of users.
Make the view model observe conversation participant changes and update the internal data accordingly.
> Update participant list when conversation participants change

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Copy change for the conversation overflow alerts.
> Change copy

- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBarController.swift
* Fix tabbar selection glitch.
> Fix tabbar selection glitch

- Wire-iOS Tests/CoreDataSnapshotTestCase.swift
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/RegistrationViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationTeam/LandingViewController.swift
* Show status bar in landing view controller.
> Show status bar in landing view controller

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
* When recording a long audio message the screen might turn off. We now disable the application idle timer during audio message recording.
> Disable application idle timer during audio message recording

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/UIMenuItem+MessageActions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/AudioMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransferCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MessageAction.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
* Add download menu item to file based message cells.
> Add download menu item to file based message cells

- Wire-iOS/Sources/UserInterface/Conversation/GuestBar/ZMConversation+GuestBarState.swift
* Don't show guest banner if there is only 1 other user with is a service.
> Don't show guest banner if there is only 1 other user with is a service

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/VideoMessageCell.swift
* Fix dowload menu item not appearing for video messages.
> Fix dowload menu item not appearing for video messages

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ImageMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
* Fix crash when showing menu for text and image messages.
> Fix crash when showing menu for text and image messages

- ConversationCell+Menu.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
* Convert conversation menu logic to Swift.
> Convert conversation menu logic to Swift

- Wire-iOS/Sources/Components/AudioPlayer/AudioPlaylistViewController.m
- Wire-iOS/Sources/Components/AudioPlayer/AudioTrackViewController.m
- Wire-iOS/Sources/Helpers/UIApplication+Permissions.m
- Wire-iOS/Sources/Permissions/PermissionDeniedViewController.m
- Wire-iOS/Sources/UserInterface/Registration/RegistrationPersonal/SignIn/EmailSignInViewController.m
There were still some deprecated url method calls that I missed last time.
> Fix deprecated method calls

- Wire-iOS/Sources/Developer/DebugAlert.swift
Update the recipient email for sent logs to `calling-ios@wire.com`
> Update log recipient email [skip ci]

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Camera.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Remove the warning reported by wire-bot for a missing method.
> Fix: warning of ConversationInputBarViewController+Files.m#L292: undeclared selector 

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Update translations for the 3.20 release.
> Updated "de|it|ja|pt-BR|es-ES|ru|uk|tr|nl|da|fr|zh-CN|sl|ar|et|fi|pl|zh-TW|lt" localized resources

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Updated localizations

- Wire-iOS Tests/Mocks/MockMessage.swift
- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/Mentions/MentionsTextAttachment.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
* Update for changes made to the Mentions object.
> Update for changes made to the Mentions object

- WireExtensionComponents/Utilities/AutomationHelper.swift
This reverts a PR #2605 as we found a way to access log files from device itself.
> Revert automation workaround for accessing device logs

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.h
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/TextMessageCell.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewControllerDelegate.h
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Helpers/UITextView+Range.swift
Allows opening mentions, on iPad and iPhone.
> Opening Mentions

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
- Wire-iOS/Sources/UserInterface/Conversation/Mentions/MentionsSearchResultsViewController.swift
This is initial version of input field and connection to suggestions popup.
> Connect input field to suggestions popup

- Wire-iOS/Sources/UserInterface/Components/Views/MarkdownTextView.swift
When a mention was copied from the input bar it copy the invisible text attachment
Convert  any selected mentions to plain text when copied.
> Convert mentions to plain text when copied

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+UITextViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
Input field now respects half-entered mentions and shows the suggestions box when possible.
Also connected the input bar button to trigger the mentioning flow.
> Fix input field behaviour when adding mentions

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
When moving cursor to a position where there is valid mention text we should re-open the suggestions popup.
> Opening suggestions flow when changing cursor position

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler+TextView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/NSAttributedString+Space.swift
When adding a mention we should always make sure there is a space after it.
> Adding space after inserting mention

- Wire-iOS Tests/MentionsHandlerTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/MentionsHandler.swift
There were no tests, tried to add them for most of the implementation that is not tied to text view.
> Added tests for Mentions handler

- Wire-iOS/Sources/UserInterface/Conversation/Mentions/UserSearchResultsViewController.swift
Color should be the same in dark and light mode.
> Corrected background color for mentions suggestions list

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+DataUsagePermissions.swift
New copy is added. Fixed typo.
> Updated tracking consent copy

- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
Desired, in order to see the conversation context.
> Show conversation name in actions menu

- Wire-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Wire-iOS/Sources/UserInterface/Conversation/Mentions/UserSearchResultsViewController.swift
Fixed background color of the collection view that is inside of the mentions search view
> ZIOS-10709: fixed mentions collection view background color

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
Lazily loaded variable `audioRecorder` was accessed in `deinit`. It was working before, but with the new runtime version this is causing the cryptic crash. 
Looking on it logically, the purpose of the lazy var is to save the object creation time, if the creation is not necessary. When we are accessing the object in `deinit` every time we are still going to load it, which defeats the purpose of lazy.
> Don't access lazy var in deinit

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationCellActionController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+PeekPop.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController.m
Added support for the menu actions.
> UIMenu actions for cells

- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Reply.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ReplyComposingView.swift
Action to jump back to the message being replied to.
> Reply composer: added action to go back to the message

- Wire-iOS/Sources/UserInterface/Availability/AvailabilityStringBuilder.swift
- Wire-iOS/Sources/UserInterface/Components/MessagePreviewView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ReplyComposingView.swift
Observe the message being replied to, wether the message:
- Was edited: update the view.
- Was deleted: cancel the reply process.
> Fixed composer observation, added edited icon

- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Actions.swift
- Wire-iOS/Sources/UserInterface/Components/MessagePreviewView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/MessageContent/ImageMessageContentView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Reply.swift
- Fixed issue with the thumbnail for the panorama image.
- Fixed issue when starting the second reply while replying.
> Reply composer fixes

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/BurstTimestampTableViewCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
Timer is necessary here to update the burst timestamp.
> Update burst timestamp on timer

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/Views/UITableView+Scrolling.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Scrolling.m
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationMessageWindowTableViewAdapter+DataSource.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController.m
In case we see the message from the current user appearing in the message window, the table view is scrolling to the very end of the conversation.
> Jump to the conversation end when sending the message

- avs-versions
> Revert "Bump AVS to 4.8."

- Wire-iOS/Sources/Components/TokenField/TokenField.h
- Wire-iOS/Sources/Components/TokenField/TokenField.m
- Wire-iOS/Sources/Vendor/SCSiriWaveformView.h
- WireExtensionComponents/Views/Loading/ProgressSpinner.h
Clean up Interface builder related code since they are no longer needed.
> Fix: Clean up Interface builder related code

- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsViewController.swift
Background color of the bar on the dark theme should not be 100% black.
> Message details: set bar background color

- Wire-iOS/Sources/Components/AudioPlayer/AudioTrackView.m
> ZIOS-11001: Added accessibility ID for Soundcloud button inside AudioTrackView

- Wire-iOS/Sources/UserInterface/Conversation/Message Details/MessageDetailsDataSource.swift
When the details of a user (name, handle, verification shield, ...) changes while they are displayed in the message details, the changes were not displayed.
Reload the cells in the message details data source when the user changes.
> ZIOS-11012: Reload message details when a user changes

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Mentions.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
Design wanted to add a haptic feedback when the sender taps on a user in the mention selection screen.
> ZIOS-10751: Add haptic feedback when confirming a mention

- Wire-iOS/Sources/Authentication/RegistrationTeam/Team Invites/TeamInviteTextFieldFooterView.swift
- Wire-iOS/Sources/Helpers/URL+Wire.swift
- Wire-iOS/Sources/UserInterface/BlacklistViewController.swift
> move URLs to URL+Wire

- Scripts/compare-translations.py
- Scripts/process-translations.sh
- setup.sh
When building the app we want to add a possibility to override some translations that would be stored in the configuration repo.
Tweaked the `setup.sh` by adding a script by @marcoconti83 to validate that modified translations makes sense.
> Added setup step to post process translations

- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchGroupSelector.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
In start UI screen, disable service tab for partner role.
> Feature:  I don't want to be able to add/remove services

- Wire-iOS/Sources/Authentication/RegistrationTeam/UIAlertController+Newsletter.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ConversationListViewController+DataUsagePermissions.swift
Disable newsletter and data usage alerts when `DATA_COLLECTION_DISABLED` is present
> Support disabling alerts by feature flag

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationTextMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/MessageToolboxView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ObfuscationView.swift
Add accessibilityLabel for obfuscated text and ObfuscationView. Fix the issue that the label may have two lines if the date text is long.
> Accessibility Id for obfuscated elements 

- Wire-iOS/Sources/Authentication/Helpers/CountryCode/CountryCodeTableViewController.m
Maybe not need to set tableview contentinset to fix this issue.
> Maybe better solution: 'Search bar overlaps first item inside country code selection'  (#3165)

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/AudioRecorder.swift
Added the possibility to stop the audio message recording from the control center. Since the Stop button is available only with live streams (
https://stackoverflow.com/questions/38021378/how-to-use-stop-button-in-ios-control-center-instead-of-pause-button-with-swift), I've used the Pause button.
After tapping on Pause, the recording is closed and can be sent from the app.
> ZIOS-10356: Control center UI for recording audio message

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Permissions/PermissionDeniedViewController+Extension.swift
- Wire-iOS/Sources/Permissions/PermissionDeniedViewController+Internal.h
- Wire-iOS/Sources/Permissions/PermissionDeniedViewController.m
- Wire-iOS/WireBridgingHeader.h
Remove `PureLayout` form `PermissionDeniedViewController`. The snapshot test is included in `testForPremissionDeniedViewController`.
> PureLayout remove - PermissionDeniedViewController

- Wire-iOS/Sources/UserInterface/Conversation/PlaceholderConversationView.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Try to enable dark mode on iPad.
- Remove the limitation in the settings
- Update the background color of the placeholder for the right conversation
> Support dark mode on iPad

- avs-versions
_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._
_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues. (Optional)_
_Briefly describe the solutions you have implemented for the issues explained above._
_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here. (Optional)_
_Specify here any other facts that you think are important for this issue. (Optional)_
_Attachments like images, videos, etc. (Optional)_
> Bump to avs 5.0.11

- Wire-iOS/Sources/Components/ShareViewController/ShareDestinationCell.swift
Add accessibility ID's in ShareDestinationCell's icons for automation purposes.
> Fix: Add accessibility ID's in forward message screen

- Wire-iOS/Resources/Base.lproj/InfoPlist.strings
- Wire-iOS/Wire-Info.plist
Update copy when asking for contacts access permission
> Update copy when asking for contacts access permission

- Wire-iOS/Resources/fr.lproj/InfoPlist.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
> Update french localization

- Wire-iOS Tests/URL+WireTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- WireCommonComponents/Bundle+Backend.swift
Added tests for static URL loaded from the configuration bundle.
> ZIOS-11427: Add test for json file content

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallQualityController/CallQualityController.swift
Fixed copy in the app for public logs support (copy is not final).
> ZIOS-11506: Public logs UI support

- Wire-iOS/Sources/UserInterface/UserProfile/Devices/UserClientCell.swift
Add a more detailed identifier for the device class icon
> Add a more detailed identifier for the device class icon

- Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationReauthenticateInputHandler.swift
Fix the issue that when the session is expired and login with the phone number not working issue.
> Fix: Unable to login when logged out from phone only account

- Wire-iOS Share Extension/zh-Hant.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/InfoPlist.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/InfoPlist.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.stringsdict
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/InfoPlist.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/InfoPlist.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Updated localisation

- Wire-iOS/Sources/UserInterface/Settings/SettingsTechnicalReportViewController.swift
Changed copy to the email content in order to reflect changes from https://github.com/wireapp/wire-ios/pull/3487
> Fix: Changed debug email content copy

- Wire-iOS/Resources/Configuration/Version.xcconfig
> bump version

- Scripts/download-assets.sh
- fastlane/Fastfile
Allow setting config repo URL and branch options when running`download-assets.sh`
Update `fastfile` to support passing new parameter to `download-assets.sh` via `setup.sh`
> fastfile & download-assets.sh: config repo url and branch options

- Wire-iOS/Sources/Authentication/Interface/Helpers/UIAlertController+TOS.swift
- Wire-iOS/Sources/Components/CompanyLoginFlowOpener.swift
- Wire-iOS/Sources/UserInterface/Camera/CameraController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/BrowserViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController+SetupView.swift
- Wire-iOS/Sources/UserInterface/Components/KeyboardAvoidingViewController+Constraint.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+CreateViews.swift
- Wire-iOS/Sources/UserInterface/Location/MapKit+Helper.swift
Fix warnings regarding deprecations.
> fix: deprecated warnings

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/UIAlertController+ConnectionRequest.swift
Add delete group action item if needed and display a confirm alert before deleting.
> Feature: deleting a conversation

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Menu action which will trigger additional dialogues should end with …
Update copy.
> Fix: Add … to delete group menu item

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Update copy when deleting a conversation
> Update copy when deleting a conversation

- Wire-iOS Share Extension/ru.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/InfoPlist.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Latest localization from crowding
> [chore] Pull in latest localization from crowdin

- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController+Internal.h
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.m
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/Model/ConversationListViewModel.swift
Tap the section header to toggle section collapse.
> Feature: add support for collapsing folders

- Wire-iOS Tests/ConversationList/SectionHeader/ConversationListHeaderViewSnapshotTests.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListContentController.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
Do not display section header for `contactRequests` section
> Feature: Pending Incoming Request has it's own folder in Grouped view instead of being on top

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ViewModel/ConversationListViewModel.swift
Add `favorites` case to ConversationListViewModel.Section.Kind
> Feature: Update view model to display favorites

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationActionController.swift
Add remove from folder action.
Tests will come in a follow up PR. (see https://github.com/wireapp/wire-ios/pull/3707)
> Feature: add remove from folder action

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.stringsdict
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Pull latest localisation from crowdin
> Chore: update localisation

- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
Pull in lastest localization from Crowdin.
> Chore: update localization

- Cartfile
- Cartfile.resolved
bump DifferenceKit to the latest release.
> bump DifferenceKit

- WireCommonComponents/AVAsset+VideoConvert.m
Increase the video quality to `.highQuality` since `.mediumQuality` is too compressed.
> Encode videos we send in higher quality

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
Provide more info when crashed for accessing invalid index path.
> Add log for app crash when accessing out of bound conversation cell

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> [Fix] Copy typo

- fastlane/Fastfile
Prepare for app center support
> add appcenter lanes

- Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
Restored logic responsible for selecting key window
> Fix keyboard not dismissing 

- azure-pipelines.yml
> bump Azure's Xcode version

- fastlane/Fastfile
Remove retired hockey app fastlanes.
> remove hockey app fastlanes

- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewController.swift
Self user is displayed as first item in the list.
Sort the list of participants.
> Fix: self user should be alphabetically sorted

- avs-versions
> Update AVS to 5.4.2.

- Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
- Wire-iOS/Sources/Analytics/Events/ZMConversation+Analytics.swift
- Wire-iOS/Sources/Helpers/syncengine/Conversation+Participants.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Additions.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMConversation+Calling.swift
- Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
- Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
- Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView+Update.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationAction.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/ConversationActions/ConversationCallController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupParticipantsDetail/GroupParticipantsDetailViewController.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
- replace activeParticipants with localParticipants;
- remove adding the self user;
> Fix: remove adding the self user

- Wire-iOS Tests/ConversationDetail/GroupDetailsViewControllerSnapshotTests.swift
- Wire-iOS/Sources/Helpers/UserType+ZMUser.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
Create helpers to access a role of a particiant in a conversation.
> create role helpers

- Wire-iOS/Resources/Base.lproj/Localizable.strings
Updating the copy describing the group admin status.
> [Chore] Update group admin copy

- avs-versions
> Update AVS to 5.4.

- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
Add two new debug actions for:
- Crashing the app
- Triggering a slow sync
> [Feature] Add internal debug actions

- Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
Changing the test queue to the main queue
> [Fix] Failed tests due to timeout on expectation

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/ShareViewController/ShareViewController.swift
- Wire-iOS/Sources/Components/TokenField/TokenField.h
- Wire-iOS/Sources/Components/TokenField/TokenField.m
- Wire-iOS/Sources/Components/TokenField/TokenFieldDelegate.swift
- Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
convert TokenFieldDelegate to Swift
> convert TokenFieldDelegate

- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
Hide phone login tab if we're on custom backend
> [Fix] hide phone login if custom backend

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/InfoPlist.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Pulled latest localizations from Crowdin.
> [Chore] updated localizations

- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
- Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+Navigation.swift
- Wire-iOS/Sources/Authentication/Event Handlers/AuthenticationCoordinatorAction.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Flow Start/AuthenticationStartCompanyLoginLinkEventHandler.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationReauthenticateInputHandler.swift
- Wire-iOS/Sources/UserInterface/Company Login/CompanyLoginController.swift
Start the SSO flow automatically upon user clicking on `Login with SSO` button.
- Fetch SSO Settings from BE
- Fallback on manual SSO flow if no SSO code 
Note: Did some refactoring to make the flow more understandable
> [Feature] Automatic SSO flow 

- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphyConfirmationViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
Fixes Giphy screens status bar style is dark in dark color scheme mode issue.
> Fix: Giphy screens status bar style

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> [Fix] Enterprise link localization

- Wire-iOS/Sources/Components/ShareViewController/ShareViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+Forward.swift
Fix the issue similar to #4118 for Share screen.
> fix: After share screen is dismissed, status bar is white on white

- Wire-iOS Tests/LinkOpeningOption/BrowserOpeningOptionTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/BrowserOpening.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/LinkOpener.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/MapOpening.swift
- Wire-iOS/Sources/UserInterface/Settings/LinkOpening/TweetOpening.swift
Refactored duplicate implementation of `storedPreference` with associatedtype in `LinkOpeningOption`
> Refactored LinkOpeningOption storedPreference with associatedtype

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Components/Buttons/ButtonWithLargerHitArea.h
- Wire-iOS/Sources/Components/Buttons/ButtonWithLargerHitArea.swift
- Wire-iOS/Sources/Components/Buttons/IconButton.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsView.swift
- Wire-iOS/Sources/UserInterface/Components/Views/PopUpIconButton.swift
- Wire-iOS/Sources/UserInterface/Components/Views/TextSearchInputView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/FileTransfer/FileTransferView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Ephemeral.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarButtonsView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/InputBarSecondaryButtonsView.swift
- Wire-iOS/Sources/UserInterface/Location/LocationSelectionViewController.swift
- Wire-iOS/Sources/UserInterface/MarkdownBarView.swift
- Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
Convert `ButtonWithLargerHitArea` and make it internal.
> Convert ButtonWithLargerHitArea

- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/ConversationMessageSectionController.swift
Connect button action to the touch action of button cell
> Feature: Connect button action to button cell

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
> feature: localize button state

- Wire-iOS Tests/Button/SpinnerButtonTests.swift
- Wire-iOS Tests/ConversationCell/CompositeMessageCellTests.swift
- Wire-iOS/Sources/Components/Buttons/SpinnerButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
Show spinner when the button in button cell is pressed.
Dismiss spinner when the button state changes.
> Show spinner when button is pressed

- Wire-iOS/Sources/Components/Buttons/Button.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Poll/ConversationButtonMessageCell.swift
prevent unnecessary state update.
reset button state only if config is changed.
> Fix: prevent unnecessary state update

- Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
Convert `Ping`, `Send`, `Giphy` categories to Swift.
> Convert ConversationInputBarViewController catogories

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+KeyCommand.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+Private.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+SendButton.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.h
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.m
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
Convert keyboard shortcut and UI helper methods to Swift.
> Convert ConversationInputBarViewController helpers

- Wire-iOS.xcodeproj/project.pbxproj
- WireCommonComponents/AutomationHelper.swift
- WireCommonComponents/CGFloat+Hairline.swift
- WireCommonComponents/CircularProgressView.swift
- WireCommonComponents/ExtensionSettings.swift
- WireCommonComponents/FileMetaDataGenerator.swift
- WireCommonComponents/FilePreviewGenerator.swift
- WireCommonComponents/Icons/UIImage+StyleKit.swift
- WireCommonComponents/SharedConstants.swift
- WireCommonComponents/UIColor+AccentColor.swift
Clean up objc project settings and signatures in Common component target.
> Clean up objc in common component

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Helpers/URL+Wire.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallAction.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallBrowserViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoRootViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallQualityIndicatorViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/NetworkCondition+Helper.swift
This PR is still Work In progress.
When an user is in a situation of "broken leg" scenario the client should show a banner that informs the user about the call state.
> [Feature] Call Indicator

- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationTableViewDataSource.swift
App crash at the line `if fetchController.fetchRequest.fetchOffset > 0`
`fetchController` has optional type and it may be nil
Use optional unwrap instead.
> Fix: app crash at fetchController.fetchRequest.fetchOffset > 0

- Wire-iOS/Sources/Components/TokenField/TokenField.swift
- Wire-iOS/Sources/Components/TokenField/TokenizedTextView.swift
- Wire-iOS/Sources/UserInterface/Collections/CollectionsSectionSet.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
Fix new warnings after building with Xcode 11.
> fix: fix warnings introduced in Xcode 11

- Wire-iOS/Entitlements-Dev.entitlements
- Wire-iOS/Entitlements-Prod.entitlements
Add unrestricted VOiP entitlement
> [Chore] Add unrestricted VOiP entitlement

- WireCommonComponents/AVAsset+VideoConvert.swift
Undo refactoring for now to prevent test fail.
> Fix: failed testThatVideoIsConvertedToUploadFormat

- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
> Update localization for v3.59

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Resources/ar.lproj/Localizable.strings
- Wire-iOS/Resources/da.lproj/Localizable.strings
- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/es.lproj/Localizable.strings
- Wire-iOS/Resources/et.lproj/Localizable.strings
- Wire-iOS/Resources/fi.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/it.lproj/Localizable.strings
- Wire-iOS/Resources/ja.lproj/Localizable.strings
- Wire-iOS/Resources/lt.lproj/Localizable.strings
- Wire-iOS/Resources/nl.lproj/Localizable.strings
- Wire-iOS/Resources/pl.lproj/Localizable.strings
- Wire-iOS/Resources/pt-BR.lproj/Localizable.strings
- Wire-iOS/Resources/ru.lproj/Localizable.strings
- Wire-iOS/Resources/sl.lproj/Localizable.strings
- Wire-iOS/Resources/tr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hant.lproj/Localizable.strings
Cherry-pick locatization update
> cherry pick string update

- avs-versions
> [Chore] Bump AVS to 5.6.15

- Wire-iOS/Sources/UserInterface/Conversation/InputBar/CameraKeyboard/CameraKeyboardViewController.swift
Fix the broken layout due to remove auto created constraints.
> Fix: broken camera keyboard layout

- Wire-iOS Tests/ArticleViewTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Components/MediaPreviewView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationLinkAttachmentCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Content/Text/ConversationLinkPreviewArticleCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/ArticleView.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/LinkViewDelegate.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ContextMenuDelegate.swift
ENable context preview menu for `MediaPreviewView`.
Refactor `ArticleViewDelegate` to `LinkViewDelegate` as a source of providing info to create a openable link preview view.
> Context preview menu for MediaPreviewView

- Wire-iOS/Sources/Authentication/Interface/Views/PhoneNumberInputView.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangeEmailViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ChangePhoneViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/Views/AccessoryTextFieldCell.swift
Toggle Keyboard when editing email/phone number.
> Fix: Keyboard does not automatically pop up anymore on phone / email page in settings

- Wire-iOS Tests/Calling/VoiceChannelVideoStreamArrangmentTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
Sort the video participants by name, with the exception that the first video tile is always the self video preview (if available).
**JIRA:** https://wearezeta.atlassian.net/browse/ZIOS-13480
> [Feature] Sort video participants

- avs-versions
Bump to latest AVS 6.0.x version.
> [Chore] Bump AVS to 6.0.47

- avs-versions
> [Chore] Bump AVS to 6.2.7

- Wire-iOS Share Extension/TargetConversationCell.swift
- Wire-iOS Share Extension/UnsentGifImageSendable.swift
- Wire-iOS Share Extension/UnsentSendable.swift
- Wire-iOS Share Extension/Wire-iOS Share Extension.entitlements
- Wire-iOS/Entitlements-Prod.entitlements
- Wire-iOS/Resources/Configuration/Version.xcconfig
- Wire-iOS/Sources/Authentication/AuthenticationFlowStep.swift
- Wire-iOS/Sources/Authentication/AuthenticationInterfaceBuilder.swift
- Wire-iOS/Sources/Authentication/Backup/BackupRestoreController.swift
- Wire-iOS/Sources/Authentication/Backup/UIAlertController+ImportWarning.swift
- Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
- Wire-iOS/Sources/Authentication/TeamCreationState.swift
- Wire-iOS/Sources/Components/ShareViewController/UIViewController+PopoverFrame.swift
- avs-versions
Added entitlements to fix warnings.
> chore: Release/3.63

- avs-versions
> [Chore] Bump AVS to 6.2.10

- Wire-iOS Tests/Calling/VoiceChannelVideoStreamArrangmentTests.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/VideoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/Stream.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
https://wearezeta.atlassian.net/browse/ZIOS-13481
- Scale video to fill available space by default
- Scale screenshare video to fit available space to preserve aspect
> [Feature] Specify default fill mode for video tiles

- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
Show the reminder message for custom applock in setting screen
> show custom subtitle when app lock is enabled

- Wire-iOS/Sources/Helpers/UIAlertController+Permissions.swift
- Wire-iOS/Sources/Helpers/UIApplication+Permissions.swift
- Refactor the permissions alert for a cleaner implementation
- Make alerts dismiss button consistent using `Later` instead of `OK`
> [Refactor] permissions alerts

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/GridCell.swift
https://wearezeta.atlassian.net/browse/ZIOS-13627
- Add accessibility identifier to `GridCell`
> [Chore] add accessibility identifier to GridCell

- avs-versions
> [Chore] bump avs to 6.2.20

- avs-versions
> [Chore] bump avs to 6.2.22

- Wire-iOS/Sources/AppRootViewController.swift
- Wire-iOS/Sources/Components/Settings.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Wire-Info.plist
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13684
> [Feature]: Feature Flag CBR Enabled

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/Components/Settings.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
- Wire-iOS/Wire-Info.plist
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13682
> [Feature]: Feature Flag Enable Link Preview

- Wire-iOS/Sources/AppRootViewController+URLActionDelegate.swift
- Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
- Wire-iOS/Sources/Helpers/Bundle+SecurityFlags.swift
- Wire-iOS/Wire-Info.plist
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13685
> [Feature]: Feature Flag Custom Backend

- avs-versions
> [Chore] bump avs to 6.2.28

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/SelfVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
- avs-versions
https://wearezeta.atlassian.net/browse/ZIOS-13708
- Set `BaseVideoPreviewView` background color to `graphite`
- Set `AVSVideoView` and `AVSVideoPreviewView` background color to `clear`
> [Fix] video tile background color

- Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
Disable using stored passcode when creating passcode
> do not allow auto fill when creating passcode

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
- Handle orientation changes in video thumbnail
> [Feature] Video thumbnail orientation

- Wire-iOS/Resources/de.lproj/Localizable.strings
- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/zh-Hans.lproj/Localizable.strings
New localisation strings for version 3.65
> [Feature]: New Localization String v3.65

- avs-versions
> [Chore] Bump AVS to 6.4.12

- Wire-iOS/Resources/fr.lproj/Localizable.strings
- Wire-iOS/Resources/uk.lproj/Localizable.strings
Update localization from crowdin
> [Chore] Update localization

- avs-versions
> [Chore] Bump avs 6.4.14

- Wire-iOS/Resources/de.lproj/Localizable.strings
Localization for 3.70 release candidate
> [Chore]: Localization for 3.70 release candidate

- Wire-iOS/Resources/Configuration/Version.xcconfig
> [Chore]: Bump for 3.70

- Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
- Wire-iOS Tests/Analytics/AnalyticsTests.swift
- Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
- Wire-iOS/Sources/Analytics/AnalyticsProviderFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/DebugActions.swift
Merge Release 3.70 into Develop Branch
> [Chore]: Merge Release 3.70 into Develop Branch

- Wire-iOS/Sources/UserInterface/Calling/Thumbnail/PinnableThumbnailViewController.swift
- Set the accessibility identifier of the thumbnail to the container's subview
> [Chore] Update thumbnail accessibility ID

- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/BaseVideoPreviewView.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoPreviewView.swift
Added an accessibility identifier providing:
- A unique identifier for the view based on the client id
- A way to differentiate between maximised / minimised state
> [Chore] accessibility identifiers for video preview

- Wire-iOS/Resources/Configuration/Version.xcconfig
> [Chore] bump version to 3.72

- Wire-iOS/Sources/UserInterface/Components/Views/IconImageView/PulsingIconImageView.swift
Update the pulsing icon animation in order to be consistent between platforms
> [Chore] update pulsing icon animation

- Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Unlock/UnlockViewController.swift
QA requested some accessibility identifiers for the unlock screen.
> [Chore] Add accessibility identifiers

- Wire-iOS/Sources/UserInterface/UserProfile/Devices/UserClientListViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
- Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewControllerViewModel.swift
Remove `bareUser` and `fullUser` to allow injecting `MockUserType` for testing
> remove ZMUser from ProfileViewController and children classes

- avs-versions
> [Chore] bump avs to 6.6.17

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Internal feature flag for the active speakers tab, defining if video grid presentation mode can be toggled or not.
> [Chore] active speakers feature flag

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Increase the call overlay timeout from 4 to 8 seconds
> [Chore] increase call overlay timeout

- avs-versions
> [Chore] bump avs to 6.7.16

- Wire-iOS/Resources/Configuration/Version.xcconfig
> [Chore]: Bump for 3.77

- Wire-iOS/Sources/Helpers/AttributedStringOperators.swift
- Wire-iOS/Sources/UserInterface/Calling/Permissions/CallPermissionsConfiguration.swift
- Wire-iOS/Sources/UserInterface/Helpers/OrientationDelta.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptor.swift
Fix [operator whitespace](https://realm.github.io/SwiftLint/operator_whitespace.html) lint rule violations.
> [Chore] Fix operator whitespace violations

- Wire-iOS/Sources/UserInterface/Components/NetworkStatus/NetworkStatusViewController.swift
If network state update is enqueued when the app enters the background the UI would not update.
We throttle network state updates so the UI view animation is applied after app has transition into the background at which point the animation is no longer applied.
Re-apply the current network state when the app enter foreground.
> [Fix] Network indicator getting out of sync after returning from background

- Wire-iOS Tests/App Lock/Mocks/AppLockModule.MockApplicationStateProvider.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModulePresenterTests.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModuleViewTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/AppRootRouter.swift
- Wire-iOS/Sources/Helpers/UIApplication/ApplicationStateProvider.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Interactor.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
- Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.swift
Cause there were a small conflict I have created the PR for merging the release 3.77 into develop
> [Chore]: Merge release 3.77 into Develop

- avs-versions
> [Chore] Bump avs to 7.0.0

- Wire-iOS Tests/ArticleViewTests.swift
- Wire-iOS Tests/ConversationList/ConversationListCell/ConversationStatusLineTests.swift
- Wire-iOS Tests/ConversationMessageCell/ConversationVideoMessageCellTests.swift
- Wire-iOS Tests/MessageReplyPreviewViewTests.swift
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
> [Chore] disable flaky tests

- .swiftlint.yml
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Authentication/Backup/BackupRestoreController.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Registration/RegistrationActivationExistingAccountPolicyHandler.swift
- Wire-iOS/Sources/Authentication/Interface/Helpers/UIAlertController+Newsletter.swift
- Wire-iOS/Sources/Components/Settings+Logging.swift
- Wire-iOS/Sources/Helpers/FontScheme.swift
- Wire-iOS/Sources/UserInterface/Components/Controllers/FullscreenImageViewController.swift
- Wire-iOS/Sources/UserInterface/Components/Views/SwipeMenuCollectionCell.swift
- Wire-iOS/Sources/UserInterface/Conversation Options/ConversationNotificationOptionsViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarButtonState.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController+KeyCommand.swift
- Wire-iOS/Sources/UserInterface/CustomAppLock/Setup/PasscodeError.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
- Wire-iOS/Sources/UserInterface/GroupDetails/Sections/ParticipantsSectionController.swift
- Wire-iOS/Sources/UserInterface/Helpers/UIImage+Decoding.swift
- Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsTableViewController.swift
- WireCommonComponents/SettingsPropertyName.swift
Fix some line length violations.
> [Chore] Lint line lengths

- avs-versions
> [Chore] bump avs to 7.0.8

- avs-versions
> [Chore] bump avs to 7.1.4

- avs-versions
> [Chore] bump avs to 7.1.6

- Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModulePresenterTests.swift
- Wire-iOS Tests/App Lock/Tests/AppLockModuleViewTests.swift
BSI needs a documentation that contains security-relevant test cases which are mapped to security functions (SF) and interfaces (TSFI). Additionally we need to deliver a document for them which contains all test cases containing purpose, procedure, expected result and actual result.
This PR annotates unit/integration test cases with a comment in front of each test case function. This helps to automatically gather these test cases and create a document out of it.
There are additional pull requests in wire-ios and wire-ios-data-models like this.
See https://github.com/wireapp/bsi-mapping/ for the scripts that do the parsing and creation of the documents.
> [Chore] Annotate test cases for BSI

- avs-versions
> [Chore] bump avs to 7.2.3

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
This PR adds the localizable strings that will be used for the join conversation feature.
> [Chore] Add strings for join conversation feature

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/RoundedPageIndicator.swift
Accessibility identifiers for automation
Needs merge after: https://github.com/wireapp/wire-ios/pull/5129
> [Chore] Update accessibility identifiers for calling grid

- Wire-iOS/Resources/Base.lproj/Localizable.strings
> fix: localization type **External**s

- Wire-iOS Share Extension/Base.lproj/Localizable.strings
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
This PR contains strings that should be translated before the next code freeze and they are related to the upcoming `file sharing feature`.
> [Feature] Add strings for file sharing

- Wire-iOS Share Extension/Base.lproj/Localizable.strings
We need to update copy for Share extension
https://zpl.io/25jx1xo
> [Chore] Update alert message for Share extension

- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallingConfiguration.swift
enable large conference calls features to have them in internal builds
> [Chore] enable large conference calls features

- avs-versions
> [Chore] bump avs 7.2.90

- avs-versions
> [Chore] bump avs to 7.2.95

- Wire-iOS/Sources/AppRootRouter.swift
Enable the internal `usePackagingFeatureConfige` flag, which enables the conference restriction feature flag.
> [Chore] Enable conference restriction feature flag

- Wire-iOS Tests/CallStatusViewTests.swift
- Wire-iOS Tests/Calling/CallInfoTestFixture.swift
- Wire-iOS Tests/Calling/CallStatusViewInputTypeTests.swift
- Wire-iOS Tests/Mocks/MockCallInfoViewControllerInput.swift
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusViewInputType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
This is a cherry-pick of this commit https://github.com/wireapp/wire-ios/pull/5235 which got lost on `release/3.87` and never made it to `develop`
It's already been reviewed and approved.
> [Fix] show bitrate label when CBR is enforced (#5235)

- WireCommonComponents/FileMetaDataGenerator.swift
`func audioSamplesFromAsset(_ asset: AVAsset, maxSamples: UInt64) -> [Float]?` take long time to build
(~800ms on M1 Mac)
long code and type-checking take long time
Set the types for variables to save the type check.
move logic outside the loop to safe running time
refactor the method as a extension of AVAsset to prevent global method and make it file private.
> fix: audioSamplesFromAsset slow building time

- Wire-iOS/Sources/UserInterface/Components/Controllers/ConfirmAssetViewController/ConfirmAssetViewController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/ConversationContentViewController+MessageAction.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
Fix the issue that Canvas view has a transparent navi bar
> Fix: Canvas view has transparent navi bar

- Wire-iOS Tests/ThreeDotsLoadingViewTests.swift
- Wire-iOS/Sources/UserInterface/Components/ThreeDotsLoadingView.swift
- Wire-iOS/Sources/UserInterface/Conversation/InputBar/TypingIndicatorView.swift
Convert Cartography `distribute` functions
> Fix: remove cartography part 6 - distribute

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/AppRootRouter.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-985" title="SQSERVICES-985" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQSERVICES-985</a>  [iOS] Copy changes: self-deleting enabled
</td></table>
<br />
----
----
Change the copy for self-deleting messages 
----
----
----
> chore: Update copy for self-deleting messages SQSERVICES-985

- Wire-iOS/Sources/UserInterface/Conversation/GuestBar/GuestsBarController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-72" title="FS-72" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10803&avatarType=issuetype" />FS-72</a>  [iOS] Distinguish "federated users are present" from guests
</td></table>
<br />
----
----
Federation banner has no text after adding a federated user.
The banner view is updated before the view is loaded and it has a condition to ignore updates before the view is loaded.
Store state if the view is not loaded and apply it after the view is loaded.
- create a group
- don't add any federated participant - only users from same backend
- go inside the group details
- add federated users
- look for the banner - banner …
> fix: federation banner having no text after adding a federated user FS-72

- Wire-iOS.xcodeproj/project.pbxproj
----
----
Clean up removed Cartography framework from the project
> fix: clean up Cartography framework SQPIY-772

- Wire-iOS/Resources/Configuration/Version.xcconfig
----
----
For the latest **3.94 hotfix**, we had a release branch, but we could not merge it back directly to the develop branch. I created a [PR](https://github.com/wireapp/wire-ios/pull/5459) with changes from the release branch, but forgot to update the `WIRE_SHORT_VERSION`. This is a PR is for updating the app version.
----
----
----
> chore: Update the app version

- avs-versions
----
----
bump avs to `8.0.9`
----
----
----
> chore: bump avs to 8.0.9

- avs-versions
----
----
bump avs version to 8.0.13
----
----
----
> chore: bump avs version to 8.0.13

- avs-versions
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCALL-532" title="SQCALL-532" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQCALL-532</a>  [iOS] bump avs version to `8.1.8`
</td></table>
<br />
----
----
bump avs
----
----
----
> chore: bump avs to 8.1.8 SQCALL-532

- Wire-iOS.xcodeproj/project.pbxproj
- WireCommonComponents/Stylable.swift
----
----
With this PR we introduce a Stylable Protocol for the work we're planning to do regarding colors, contrast and build certain components. 
----
> feat: Introduce Stylable Protocol

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Conversation/Create/Cells/ConversationCreateEncryptionTypeCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/Cells/ConversationEncryptionTypeCell.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
- Wire-iOS/Sources/UserInterface/Conversation/Create/Sections/ConversationEncryptionTypeSectionController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-539" title="FS-539" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-539</a>  [iOS] Add UI option for MLS in create conversation
</td></table>
<br />
----
----
- When creating new Groups, User can select Proteus or MLS as a protocol for the new group.
- For selection of protocol when user taps the cell a list of available protocols is show and user can select from it.
1    |    2
:--:|:--:
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title …
> feat(mls): add ui option for mls in create conversation FS-539

- .swiftlint.yml
- Wire-iOS Share Extension/AccountSelectionViewController.swift
- Wire-iOS Share Extension/ConversationSelectionViewController.swift
- Wire-iOS Share Extension/CrashReporter.swift
- Wire-iOS Share Extension/Error+Logging.swift
- Wire-iOS Share Extension/ExtensionBackupExcluder.swift
- Wire-iOS Share Extension/NSExtensionContext+Attachments.swift
- Wire-iOS Share Extension/NSItemProvider+Fetching.swift
- Wire-iOS Share Extension/NotSignedInViewController.swift
- Wire-iOS Share Extension/SLComposeServiceViewController+Preview.swift
- Wire-iOS Share Extension/SendController.swift
- Wire-iOS Share Extension/SendingProgressViewController.swift
- Wire-iOS Share Extension/ShareExtensionViewController.swift
- Wire-iOS Share Extension/UIButton+SetIcon.swift
- Wire-iOS Share Extension/UnlockViewController.swift
- Wire-iOS Share Extension/UnsentGifImageSendable.swift
- Wire-iOS Share Extension/UnsentSendable.swift
- WireCommonComponents/Icons/Autogenerated/WireStyleKit.swift
----
----
With this PR we introduce SwiftLint to Share Extension and we take care of any warnings and errors.
----
> chore: Introduce SwiftLint to Share Extension

- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
----
----
Enable the mls log tag so we can see mls logs.
----
----
----
> chore(mls): enable mls log tag

- Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
- Wire-iOS/Sources/Authentication/Event Handlers/AuthenticationCoordinatorAction.swift
- Wire-iOS/Sources/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1731" title="SQSERVICES-1731" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQSERVICES-1731</a>  [iOS] Remove unsplash
</td></table>
<br />
> feat: remove unsplash-SQSERVICES-1731

- Wire-iOS/Sources/Helpers/Logging.swift
- Wire-iOS/Sources/MLS/CoreCrypto+Setup.swift
- WireCoreCrypto/WireCoreCrypto.xcodeproj/project.pbxproj
----
----
Update core crypto to 0.5.2.
----
----
----
> chore(mls): update core crypto to 0.5.2

- Wire Notification Service Extension/Simple/Job.swift
- Wire Notification Service Extension/Simple/NotificationServiceError.swift
- Wire Notification Service Extension/Simple/SimpleNotificationService.swift
- Wire-iOS Tests/Notification Service Extension/SimpleNotificationServiceExtension/JobTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
> add coreData caching, clean up, fix test

- avs-versions
----
----
Bump AVS to 8.2.16
----
----
----
> chore: bump avs to 8.2.16

- Wire Notification Service Extension/LegacyNotificationService.swift
- Wire Notification Service Extension/Simple/Helpers/CallEventHandler.swift
- Wire Notification Service Extension/Simple/Helpers/NotificationContentProvider.swift
- Wire Notification Service Extension/Simple/Job.swift
- Wire Notification Service Extension/Simple/NotificationServiceError.swift
- Wire Notification Service Extension/Simple/SimpleNotificationService.swift
- Wire-iOS Tests/Notification Service Extension/LegacyNotificationServiceTest.swift
- Wire-iOS Tests/Notification Service Extension/SimpleNotificationServiceExtension/JobTests.swift
- Wire-iOS.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1700" title="SQSERVICES-1700" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />SQSERVICES-1700</a>  Refactor NotificationService for possible reuse
</td></table>
<br />
This pull requests implements Phase 4 from the [new notification extension plan](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/647725130/Notification+Service+Extension+2.0).
----
> feat: add call events handling - SQSERVICES-1700

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Accessibility.strings
- Wire-iOS/Sources/Helpers/SemanticColors.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionIconType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
- Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsListView/CallParticipantsListView.swift
----
----
New colors for buttons and bottom sheet on the calling UI.
----
----
----
> feat: Update colors for new calling UI

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Helpers/SemanticColors.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionIconType.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallInfoConfiguration.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/NSLayoutConstraint+Helper.swift
<table>
<td>
</td></table>
<br />
> feat: add top bar to Call View - ACC-143

- Wire-iOS/Sources/Helpers/SemanticColors.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/SelfCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/NSLayoutConstraint+Helper.swift
<table>
<td>
</td></table>
<br />
> feat: update CallParticipantDetailsView- ACC-143

- Wire-iOS/Generated/Colors+Generated.swift
- Wire-iOS/Generated/Strings+Generated.swift
----
----
After updating the the latest version of SwiftGen, it has added some changes to the generated files. This PR simply commits those new changes.
----
----
----
> chore: update generated SwiftGen files

- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationStepController.swift
----
----
With this PR we fix the position of the footerView in the login and sign up flow. Now it takes into account the safe area.
----
> fix: Position of the FooterView in Login/Sign up flow

- Wire-iOS Tests/Calling/CallGridViewControllerSnapshotTests.swift
- Wire-iOS Tests/Calling/CallInfoRootViewControllerSnapshotTests.swift
- Wire-iOS Tests/Calling/CallInfoRootViewControllerTests.swift
- Wire-iOS Tests/Calling/CallParticipantsListViewControllerTests.swift
- Wire-iOS Tests/IconLabelButtonTests.swift
- Wire-iOS Tests/UserCellTests.swift
- Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallParticipantsListView/CallParticipantsListView.swift
<table>
<td>
</td></table>
<br />
> fix: Fix failing tests ACC-143

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Accessibility.strings
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/AccessibilityActionView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
<table>
<td>
</td></table>
<br />
> feat: add scroll action to voiceOver on callingUI ACC-143

- Wire-iOS/Sources/Helpers/SemanticColors.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/RoundedPageIndicator.swift
<table>
<td>
</td></table>
<br />
----
> fix: Calling UI visual fixes ACC-143

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-358" title="ACC-358" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-358</a>  [iOS] Fix the space between "Double tap on a tile..." and the conversation name (user name)
</td></table>
<br />
----
----
> fix: hints label placement ACC-358

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-360" title="ACC-360" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-360</a>  [iOS] Fix issues on the "pre calling UI"
</td></table>
<br />
> fix: incoming call ui ACC-360

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/Grid/GridView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-366" title="ACC-366" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-366</a>  [iOS] Fix: Voice over for page control
</td></table>
<br />
> feat: add voiceover for page control ACC-366

- Wire-iOS/Sources/Helpers/SemanticColors.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
<table>
<td>
</td></table>
<br />
ACC-380 ACC-379 ACC-377
Add black overlay with changing alpha when bottom sheet s scrolled up
Make corner radius smaller for call grid cells
Disable user interaction for call grid when bottom sheet is scrolled up
> feat: design changes for calling UI ACC-143

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Accessibility.strings
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/Authentication/Interface/Descriptions/ViewDescriptions/TextFieldDescription.swift
- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
- Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationStepController.swift
- Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
- Wire-iOS/Sources/UserInterface/Components/TabBar/TabBar.swift
- Wire-iOS/Sources/UserInterface/ConnectRequests/OutgoingConnectionBottomBar.swift
- Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
- Wire-iOS/Sources/UserInterface/Settings/BackupPasswordViewController.swift
- Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-144" title="ACC-144" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />ACC-144</a>  Meaningful Sequence (1.3.2)
</td></table>
<br />
----
----
Apply voice over changes for login, connection, system message screens.
----
----
----
> feat: Voice over fixes for login ACC-144

- Wire-iOS/Sources/Helpers/ColorScheme.swift
- Wire-iOS/Sources/Helpers/SemanticColors.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
<table>
<td>
</td></table>
<br />
> Fixes  test and review ACC-143

- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/Grid/GridView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
> Fix: Calling UI review fixes

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/BaseCallParticipantView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
----
--
Fix: ACC-421, ACC-422, ACC-423, ACC-424, ACC-361
--
ACC-421 Participants Cell layout is incorrect
ACC-422 Page indicator is not attached to  right side
ACC-423 User name and call status visible twice when someone you call someone
ACC-424 Participants list covered by notch
ACC-361 [iOS] Fix "pre calling UI" in the horizontal mode
> fix: Bug fixes calling UI

- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridEvent.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewControllerInput.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallGridConfiguration.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-360" title="ACC-360" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-360</a>  [iOS] Fix issues on the "pre calling UI"
</td></table>
<br />
----
> fix: Fullscreen hint fix ACC-360

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Resources/Base.lproj/Localizable.strings
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
<table>
<td>
</td></table>
<br />
----
> fix: add hang up button accessibility identifier ACC-143

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-429" title="ACC-429" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />ACC-429</a>  iOS: CBR label doesn't show in the start of a CBR call 
</td></table>
<br />
----
> fix: refresh cbr vbr label ACC-429

- Scripts/datadog-conditional-framework.sh
- Wire-iOS.xcodeproj/project.pbxproj
- Wire-iOS/Sources/Developer/DeveloperTools/DeveloperToolsViewModel.swift
- Wire-iOS/Sources/Managers/DatadogWrapper.swift
- fastlane/Fastfile
- fastlane/Pluginfile
----
----
Can't build the app for device.
Compiler complains that "CrashReporter" is missing.
Add "CrashReporter" framework.
----
----
----
> fix: crash reporting

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-360" title="ACC-360" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-360</a>  [iOS] Fix issues on the "pre calling UI"
</td></table>
<br />
----
> fix: incoming call buttons layout ACC-360

- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACC-360" title="ACC-360" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />ACC-360</a>  [iOS] Fix issues on the "pre calling UI"
</td></table>
<br />
> fix: incoming call layout ACC-360

- Wire-iOS/Generated/Strings+Generated.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
- Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
- Wire-iOS/Sources/UserInterface/Calling/Helper/UIDevice+Orientation.swift
> fix: incoming call avatar layout

- fastlane/Fastfile
----
----
Use AppStore connect auth key to upload ipa.
----
----
----
> feat: use appstore connect api
